### ISSUE TITLE
Reverse poco generation ignores some tables

### ISSUE THREAD

**Issue by ScottYates** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#1]
So I have isolated what I think is a bug.

Using these tables, the template will generate code for the table named CEWD_EIF_Test, but ignore all the others.

I have included the sql server script to create the database and tables, there is no data in any of them, and no indexes.  I have also included my app.config and TheMissing.tt.  This should allow for easy replication.

I am using SqlServer 2008r2 64bit, and Visual Studio 2013.

![image](https://cloud.githubusercontent.com/assets/1346947/13333587/58d97f0e-dbcd-11e5-8e1f-6f21f7e14404.png)

[missingdbtest.zip](https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/files/147244/missingdbtest.zip)

**Comment by sjh37** [comment]
Entity Framework will only work with tables that have a primary key.
Only CEWD_EIF_Test has a primary key defined.

What the generator does which is helpful is, for any table which does not have a primary key, it sets all the NOT NULL columns to be primary keys. However, in your case, all the columns are NULL for all your other tables.

Add primary keys to all your other tables, in a similar way to how you've done it for CEWD_EIF_Test.

**Comment by ScottYates** [comment]
Ok, understood.  Thank you.  Was that in the documentation somewhere and I just missed it?

**Comment by sjh37** [comment]
Very little documentation for the generator (working on a Pluralsight course for it), however that is a requirement of Entity Framework.

http://stackoverflow.com/questions/3996782/entity-framework-table-without-primary-key

**Comment by ScottYates** [comment]
If it is possible in the code, maybe a warning message might be issued on tables that were not included?  

Obviously this is not an error on your part at all.  In my case (and I suspect others) it just causes a lot of investigation that could be avoided with a warning message.

I would look into making the changes myself, but my version of Visual Studio is 2013 and will not allow me to work on the current code base.

Thank you for your quick response and the work you have done on this!  It is extremely useful.

**Comment by sjh37** [comment]
That's actually a good idea :-)
Thanks.

**Comment by ScottYates** [comment]
Woot!

**Comment by sjh37** [comment]
That is now implemented, and will be in the next release.

**Comment by sjh37** [comment]
See this [changeset](https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/commit/8e5a3ed6c3f615d7bd47f6d4ec4c9022cbc464cb)

**Comment by ghost** [comment]
Excellent!  That looks like a good compromise!  Thank you.
