### ISSUE TITLE
Poco Interfaces

### ISSUE THREAD

**Issue by anyolejoe** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#100]
Many thanks for a super-useful utility, which we've used to ditch our edmx files fairly easily.

One thing that would be even more helpful for us would be the ability to generate interfaces for the Pocos, as they get used for Com Interop and we're having to manually generate these, which can be quite time-consuming on a large database.

Do you think an Elements.PocoInterface item might get added into a future version, or perhaps there is an alternative solution we've not found yet?

**Comment by sjh37** [comment]
What functions would you declare in the interfaces? or are you talking about a blank interface.

**Comment by ljfolino** [comment]
To add onto this. Here is the scenario I have and am looking for guidance.  I can add the interface manually if I need to to each class, but thought I would look around here first.  I want to use EF Query Filter.  This is a separate project, but to implement a soft delete filter I need to have the classes implement an interface.  We will call it IDeleted.  Ultimately it would be nice to be able to have some basic logic like if Table has column named Deleted implement interface.  This would allow for a lot of different scenarios.  The most basic scenarios would be to add an interface to all generated classes, or a filter of based on name.  This would allow scenarios where you could inherit a IUser class used in Owin and what not.

**Comment by sjh37** [comment]
That can be done in the `WritePocoBaseClasses` callback.

For example:

``` cs
// Writes optional base classes
Func<Table, string> WritePocoBaseClasses = t =>
{
    if (t.Columns.Any(c => c.NameHumanCase.Equals("Deleted", StringComparison.InvariantCultureIgnoreCase)))
        return ": IDeleted";
    return "";
};
```
