### ISSUE TITLE
TransactionalBehavior.DoNotEnsureTransaction in Database.ExecuteSqlCommand()

### ISSUE THREAD

**Issue by segyepark** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#101]
I would suggest adding **System.Data.Entity.TransactionalBehavior.DoNotEnsureTransaction** as the first parameter of Database.ExecuteSqlCommand() in EntityFramework.Reverse.POCO.Generator/EF.Reverse.POCO.ttinclude at 379 line (or adding it as an option in Database.tt).

The default value of System.Data.Entity.TransactionalBehavior is **EnsureTransaction**: If no transaction is present then a new transaction will be used for the operation.
Database.ExecuteSqlCommand() is considered to execute transaction involved queries so you will see **explicit** BEGIN TRANSACTION & COMMIT/ROLLBACK in SQL Profiler. But the problem is that there are many cases that do not need to have an explicit transaction, such as queries only for returning OUTPUT parameters after SELECT actions or even DML queries with no explicit transaction required since they are just one SQL statement or inconsistency is acceptable. Leaving the default option EnsureTransaction makes a lot of explicit transactions so it causes performance issues with a lot of undesirable locks.

Simply adding TransactionalBehavior.DoNotEnsureTransaction as suggested in the first line solves the issue.
**TransactionalBehavior.DoNotEnsureTransaction: If an existing transaction is present then use it, otherwise execute the command or query without a transaction.**

_Reference: https://msdn.microsoft.com/en-us/library/system.data.entity.transactionalbehavior(v=vs.113).aspx_

**Comment by sjh37** [comment]
Thanks. This will be in the next release.
