### ISSUE TITLE
Table per Type Code Generation

### ISSUE THREAD

**Issue by jsmarsch** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#102]
I bet this has been asked, but my google-fu is failing me.  Is there a way to have the Reverse POCO generator create classes that match the Table per Type pattern described here: http://weblogs.asp.net/manavi/inheritance-mapping-strategies-with-entity-framework-code-first-ctp5-part-2-table-per-type-tpt

**Comment by Kasper888** [comment]
TPT(table per type) is an inheritance mapping and inheritance is a one to one relation where the base table has a Primary key and the Concrete table's Primary key is a forigen key to the base's Primary key, but not all one to one relations are inheritance, so it cannot be automatically generated/predicated you have to configure it manaully; I've already did in the following example:
-- We have 3 Tables: Person(PK_ID identity) the base table and Student(PKFK_ID forigen to Person PK_ID), Teacher(PKFK_ID forigen to Person PK_ID) concrete tables.
in the db.tt file do the following:
1. add this in the UpdateCoulmn function:
```c#
// Remove ID column from Concrete classes as it will be inherited from a base class
if (column.IsPrimaryKey && column.IsForeignKey)
{  
    if (table.Name == "Teacher" || table.Name == "Student")
        column.Hidden = true;
}
```
2. add this in the WritePocoBaseClasses function:
```c#
// Writes base classes
if (t.ClassName == "Student" || t.ClassName == "Teacher")
    return " : Person";
```
3. add this in the ForeignKeyFilter:
```c#
//Remove navigation property to the base class as it already inherit
if (fk.PkTableName == "Person")
{
    if (fk.FkTableName == "Student" || fk.FkTableName == "Teacher")
        return null;
}
```

**Comment by sjh37** [comment]
Thanks Kasper.

**Comment by sjh37** [comment]
let me know if this does not answer your questions.
