### ISSUE TITLE
Error Can't upgrade to EFR POCO 2.24.0

### ISSUE THREAD

**Issue by airomero** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#103]
Hi, i can´t upgrade to v2.24.0. I get errors upgrading from VS or downloading the installer from the VS Gallery. This is the log:

29/8/2016 9:11:52 a. m. - Microsoft VSIX Installer
29/8/2016 9:11:52 a. m. - -------------------------------------------
29/8/2016 9:11:52 a. m. - Initializing Install...
29/8/2016 9:11:52 a. m. - Extension Details...
29/8/2016 9:11:52 a. m. -   Identifier         : EntityFramework_Reverse_POCO_Generator..d542a934-8bd6-4136-b490-5f0049d62033
29/8/2016 9:11:52 a. m. -   Name               : EntityFramework Reverse POCO Generator
29/8/2016 9:11:52 a. m. -   Author             : Simon Hughes
29/8/2016 9:11:52 a. m. -   Version            : 2.24.0
29/8/2016 9:11:52 a. m. -   Description        : Reverse engineers an existing database and generates EntityFramework Code First POCO classes, Configuration mappings and DbContext.
29/8/2016 9:11:52 a. m. -   Locale             : en-US
29/8/2016 9:11:52 a. m. -   MoreInfoURL        : https://efreversepoco.codeplex.com/
29/8/2016 9:11:52 a. m. -   InstalledByMSI     : False
29/8/2016 9:11:52 a. m. -   SupportedFrameworkVersionRange : [4.5,)
29/8/2016 9:11:52 a. m. - 
29/8/2016 9:11:52 a. m. -   SignatureState     : Unsigned
29/8/2016 9:11:52 a. m. -   Supported Products : 
29/8/2016 9:11:52 a. m. -       Microsoft.VisualStudio.Pro
29/8/2016 9:11:52 a. m. -           Version : [11.0,)
29/8/2016 9:11:52 a. m. -       Microsoft.VisualStudio.Premium
29/8/2016 9:11:52 a. m. -           Version : [11.0,)
29/8/2016 9:11:52 a. m. -       Microsoft.VisualStudio.Ultimate
29/8/2016 9:11:52 a. m. -           Version : [11.0,)
29/8/2016 9:11:52 a. m. -       Microsoft.VisualStudio.VSWinExpress
29/8/2016 9:11:52 a. m. -           Version : [11.0,)
29/8/2016 9:11:52 a. m. -       Microsoft.VisualStudio.VPDExpress
29/8/2016 9:11:52 a. m. -           Version : [11.0,)
29/8/2016 9:11:52 a. m. -       Microsoft.VisualStudio.VWDExpress
29/8/2016 9:11:52 a. m. -           Version : [11.0,)
29/8/2016 9:11:52 a. m. - 
29/8/2016 9:11:52 a. m. -   References         : 
29/8/2016 9:11:52 a. m. - Signature Details...
29/8/2016 9:11:52 a. m. -   Extension is not signed.
29/8/2016 9:11:52 a. m. - 
29/8/2016 9:11:54 a. m. - The extension will be upgraded from version 2.21.1.
29/8/2016 9:11:56 a. m. - The following target products have been selected...
29/8/2016 9:11:56 a. m. -   Microsoft Visual Studio Enterprise 2015
29/8/2016 9:11:56 a. m. - 
29/8/2016 9:11:56 a. m. - Beginning to install extension to Microsoft Visual Studio Enterprise 2015...
29/8/2016 9:11:56 a. m. - Upgrading 'EntityFramework Reverse POCO Generator', version 2.21.1 to version 2.24.0.
29/8/2016 9:11:57 a. m. - Install Error : System.NullReferenceException: Referencia a objeto no establecida como instancia de un objeto.
   en Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.RemoveExtensionAutoUpdateSetting(String extensionIdentifier)
   en Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.UninstallInternal(IInstalledExtension extension, Boolean forceDelete)
   en Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.CommitInstalledAndUninstalledExtensions(IEnumerable`1 installedExtensions, IEnumerable`1 uninstalledExtensions, IEnumerable`1 packComponentChanges)
   en Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.BeginInstall(IInstallableExtension installableExtension, Boolean perMachine, AsyncOperation asyncOp, Boolean enforceCertificateCheckForUpgrade)
   en Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallWorker(IInstallableExtension extension, Boolean perMachine, AsyncOperation asyncOp, Boolean enforceCertificateCheckForUpgrade)
29/8/2016 9:11:57 a. m. - Reverting uninstall of version 2.21.1 of the extension.

Any help?
Thanks!!

**Comment by sjh37** [comment]
Visual Studio is not very good at tidying up after itself.
Uninstall the generator extension.
Close Visual Studio.
Open a command prompt and type:

```
cd C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions
dir efrpoco.zip /s
```

This will list all the folders you need to delete.

Once that is done, reinstall the generator.

**Comment by airomero** [comment]
It worked!! Thanks
