### ISSUE TITLE
Remove configuration from main file.

### ISSUE THREAD

**Issue by ljfolino** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#104]
Would it be possible to refactor the reverse poco generator a little more?  The scenario is that I like to have my entities,configurations, and context in different namespaces.  IE I have the context in the main project level and the Entities in a sub folder and Configurations in a sub folder.  Would it be possible to break out the connection string and project level configuration.  Currently I edited to be something like this:

```
<#@ include file="$(ProjectDir)/Main.tt" #>
<#@ template language="C#" debug="true" #>
<#
ElementsToGenerate = Elements.Context | Elements.UnitOfWork;

// Generate output
if (tables.Count > 0 || storedProcs.Count > 0)
{
#>
<#@ include file="EF.Reverse.POCO.ttinclude" #>
<#@ import namespace="System.Xml.Schema" #>
<# } #>
```

**Comment by sjh37** [comment]
This is an advanced technique and you are obviously an experienced dev and most won't need this. Let me think about it, and have a play.

**Comment by sjh37** [comment]
Similar to #389
