### ISSUE TITLE
Naming issues

### ISSUE THREAD

**Issue by blyry** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#11]
_Currently working on these -- will add more pull requests_
- Given the view inv_ItemProfit and the stored procedure inv_ItemProfits the generated property names conflict -- there's duplicate checking but I think it happens pre-pluralization.
- Table names aren't properly scrubbed -- a '-' in a table name flows through to generated classes and properties

**Comment by sjh37** [comment]
I fixed the '-' in table names and was released in 2.21.0.
Create a pull request whenever you are ready for the first point.
