### ISSUE TITLE
SchemaIgnoreName

### ISSUE THREAD

**Issue by mkenyon2** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#112]
It would be great if we could have a value where you could list a schema or schemas that you want ignored. For instance, if using Identity, those tables could be a separate schema in the database, and used by a customized DbContext used only for those tables. The generator would then skip those specified schemas.

**Comment by dyardy** [comment]
There is an option in the tt file to exclude schemas using regex.  Options also include ability to select specific schemas.  Take a look in tt file.

**Comment by sjh37** [comment]
@mkenyon2 Already supported. Take a look at your tt file. Thanks @dyardy
