### ISSUE TITLE
Missing EF DbContext constructor

### ISSUE THREAD

**Issue by ErikEJ** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#12]
I am missing this, which is need for wrapping multiple calls to savechanges in a SqlTransaction as per: https://msdn.microsoft.com/en-us/data/dn456843.aspx 

```
   public MyContext(DbConnection connection, bool contextOwnsConnection)
        : base(connection, contextOwnsConnection)
    {
        InitializePartial();
    }
```

**Comment by sjh37** [comment]
This will be in the next release. For now, please pull the latest code.

**Comment by ErikEJ** [comment]
Fantastic! Thanks

**Comment by sjh37** [comment]
Released in v2.19.0

**Comment by NaomiN** [comment]
May be a comment needed that if we're using our own DbContextBase class it is now required to have all constructors implemented. Took us some time to figure this error out.

**Comment by sjh37** [comment]
Thanks @NaomiN, I have made a comment in the [release notes](https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/releases/tag/v2.19.0).
