### ISSUE TITLE
Support DataAnnotations

### ISSUE THREAD

**Issue by airomero** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#121]
Hi, i think it'd be great to have support for dataannotations. For example if the table field does not allow null, then the generated property should be generated with the [Required] attribute. Or if the table field is a varchar(25) the generated field should have a [MaxLength] of 25 property. What do you think? I feel it would make people happy and with less pain when it comes to customize the generated entities.

**Comment by sjh37** [comment]
I am almost there with it. Might be another week to complete.

**Comment by airomero** [comment]
I almost cry!! Really?! Great!!!
May i make a sugestion?? For example, the `[Required]` attribute get generated, great. But what if i want to change the default error message? It'd be great if, for a given built in dataannotations you could specify the error message. If you could do it, for example the output of the `[Required]` attribute in all generated classes could be:
`[Required(ErrorMessage = "My filed {0} is ultra required ;)")]`
And also it could help in the localization of error messages without resx files (if you only want to translate the messages to a single languaje).

**Comment by ghost** [comment]
I wonder (and have atm) if this should be used for XmlElementAttribute or XmlRootAttribute etc. Technically, this DataAnnotations seems to be only for MVC/ASP components. I do not need that per se. E.g. `[Display(Name="")]` is of no use to me but the other attributes might although `[MaxLength(n)]` and        `[StringLength(n)]` where `n` always seems the same might be useful but no idea why and how this would have differing numbers and why 1 out of 2 isn't superfluous.

**Comment by sjh37** [comment]
Set `UseDataAnnotationsSchema = true;` will cause the schema data annotations to be output.
