### ISSUE TITLE
Nullable guid default value

### ISSUE THREAD

**Issue by rhammonds** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#122]
The tool creates a bug for default constraints for nullable fields that are set to null.  

It sets the field in the poco constructor to System.Guid.parse("ULL")

The bug appears to be in this code:
// Remove unicode prefix
if (IsUnicode && Default.StartsWith("N") )
          Default = Default.Substring(1, Default.Length - 1);

I fixed by changing the "if" to:
if (IsUnicode && Default.StartsWith("N") && Default !="NULL")

**Comment by ErikEJ** [comment]
Should the starts with check not simply check for N' instead?

**Comment by rhammonds** [comment]
I see the code is removing the Unicode identifier.  Here is a sample constraint that has the issue: ALTER TABLE [dbo].[Equipment] ADD  CONSTRAINT [DF_Equipment_VendorID]  DEFAULT (NULL) FOR [VendorID]

The tool is pulling in the default value as "NULL".

When the logic is applied it drops the leading "N" and sets it to "ULL"

The result is the poco constructor looks similar to this:

```
    public Equipment()
    {
        VendorID = System.Guid.Parse("ULL");
    }
```

**Comment by sjh37** [comment]
Thanks. This will be in the next release.
