### ISSUE TITLE
Change the name of a poco class, but not the DbSetName?

### ISSUE THREAD

**Issue by jsmarsch** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#125]
Is there a way to change the class name of a table without affecting member name that will be generated for it? 

Example:
We want to generate poco's with a suffix of "Entity", like this:
`public class CustomerEntity {...}`

But when DbSet's and collections are generated, we would like to leave off the suffix:
`public DbSet<CustomerEntity> Customers {}  // instead of CustomerEntities`

and in navigation properties:
`public IList<CustomerEntity> Customers {}  // instead of CustomerEntities`

We are using the TableRename delegate to add the "Entity" suffix now, but I don't see a way to control only the class name or only the human readable name.  Is that an option?  Great tool, by the way.

**Comment by sjh37** [comment]
Have a play around with the ForeignKeyName function delegate in your <database settings>.tt file.

Something like

``` c#
ForeignKeyName = (tableName, foreignKeyName, attempt) =>
{
    switch (attempt)
    {
        case 1:
            return tableName.Replace("Entities", "");
...
```

**Comment by jsmarsch** [comment]
Thanks -- that took care of a lot of it, but it didn't change the name of the dbsets.

So, in the DbContext definition, I still have:
`public DbSet<CustomerEntity> CustomersEntities { get; set; }`

But I want

`public DbSet<CustomerEntity> Customers { get; set; }`

Is there a way to do that?

**Comment by sjh37** [comment]
The DbSet is written out with

``` c#
public System.Data.Entity.DbSet<<#=tbl.NameHumanCase#>> <#=Inflector.MakePlural(tbl.NameHumanCase)#>
```

So Modify the Inflector.MakePlural to strip out what you need.
