### ISSUE TITLE
Allow disabling the use of CodeGeneratedAttribute

### ISSUE THREAD

**Issue by ghost** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#126]
In `Core.ttinclude` we find

``` cs
string CodeGeneratedAttribute = "[System.CodeDom.Compiler.GeneratedCode(\"EF.Reverse.POCO.Generator\", \"2.24.0.0\")]";
```

Besides the fact that hard-coding your version number really isn't very maintenance friendly, on a personal level, I really find the option to disable it lacking. Would be preferred those annotations are wrapped in a conditional which makes use of `null` or so as flag possible.

Currently, setting `CodeGeneratedAttribute` to empty string or null will break either during transformation (in the case of null) or in the generated code (due to annotation leaving a empty line between the last attribute and the class definition (accessor/name/type etc).

Would mind doing a PR or something, not sure how/if you are open to this so I rather 'discuss' it here before I do anything to see if it is desirable or not.

**Comment by sjh37** [comment]
This has been mentioned a few times.
I should technically add the generated code attribute to each property too if the class is marked as partial.

However, a few people have asked that this be made optional, and a boolean setting would be nice in the main tt settings file.

A pull request would be greatfuly received. I am still in the middle of doing data annotations.
Thanks.

**Comment by ghost** [comment]
#139

There you go - I hope sufficient to cover for the demand, additionally one can now also override the attribute should they wish, default remains original attribute text/value and enabled/on/true.

**Comment by sjh37** [comment]
Thanks, this is now implemented and will be in the next release as soon as data annotations is completed.

**Comment by ghost** [comment]
:+1:
