### ISSUE TITLE
UseCamelCase = true

### ISSUE THREAD

**Issue by ghost** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#127]
In the `Database.tt` file there is a setting:

``` cs
UseCamelCase = true;    // This will rename the tables & fields to use CamelCase. If false table & field names will be left alone.
```

I fail to see how this will ever work in _renaming tables & fields_.  What is a field? I presume it is meant as synonym for "column" since there is the mention of a "table". Now I play dumb for a bit, but please amuse me. How can one rename tables and columns in SQL Server? I am guessing, you intended to mean the "C# code (classes) representation of those database concepts". But even then, I fail to see class names generated with camelCase (and not CamelCase imho) nor do property names get generated in camelCase. Also annotations which show HumanName (or something like that) all show PascalCase formats.

Either it doesn't work, or the meaning is ambiguous or I just really don't get what effect I should observe.

**Comment by ghost** [comment]
Ok taking a closer look to the Core file, I see that in some internal T4/SQL stuff this is used. Since I don't have any C# fields in my classes (only properties are generated) this might be the reason I don't see any effect on the switch. The variable is used in a few places, it could also be it is building some internal lists of tables, columns, keys etc and those are the ones it is applied to. It wouldn't make sense to camelCase neither the actual SQL tables or the resulting C# Classes, which all basically dictate PascalCase mandatory or at least, by convention.

It still leaves me to puzzle how this is relevant though. Personally, my desired outcome would be more along the lines of:

SQL table: _WildAnimal_ (we don't use plural table names due to easier composition of names e.g. WildAnimalReservation)

``` cs
[XmlRoot(ElementName="wildAnimal", ...]
public class WildAnimal { ... }
```

Anyway I guess mine is not everyone's use case and as such, this might had just been resolved by a little clarification as to what it is supposed to do until I found [this puppy here](https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/blob/e7543abb403843e2cb2a85b3143dc9658ce8df4d/EntityFramework.Reverse.POCO.Generator/EF.Reverse.POCO.Core.ttinclude#L2855) which indicates with `useCamelCase ? Inflector.ToTitleCase(singular)` that this is a bug/error of flipped boolean? If UseCamelCase is True, convert it to TitleCase? That doesn't seem right.

**Comment by ghost** [comment]
A classical case of ambiguous use of terms. Hence why I never use anything else besides PascalCase and camelCase because it is not helpful to have 2 distinctly different forms under the same name. Anyone who ever thought that would be fun to deviate from the earlier established use be cursed, regardless who came first. This can be closed.

**Comment by sjh37** [comment]
I should rename the boolean flag to UsePascalCase.

Database with columns such as `field_person_id', 'engineer-name' would get generated as follows:

with UseCamelCase = true;

``` c#
... FieldPersonId {get; set;}
... EngineerName {get; set;}
```

with UseCamelCase = false;

``` c#
... field_person_id {get; set;}
... engineer-name {get; set;}
```

**Comment by sjh37** [comment]
Done. I've been meaning to rename that field for ages. This will be in the next release.
