### ISSUE TITLE
StaticPartial needs to be wrapped in a conditional or breaks template

### ISSUE THREAD

**Issue by ghost** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#128]
[EF.Reverse.POCO.ttinclude#L232](https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/blob/5a7e3e21d78a2be3bb6dd5e53fdc1bbd03961aef/EntityFramework.Reverse.POCO.Generator/EF.Reverse.POCO.ttinclude#L232)

This needs a conditional wrapper in order to not fail when someone has `MakeClassesPartial = false;` (default in the `Database.tt` file is false, meaning it breaks currently on first use).

**Comment by sjh37** [comment]
Thanks for pointing this out.
This was pulled in from #118

**Comment by sjh37** [comment]
Done. This will be in the next release.
Thanks.
