### ISSUE TITLE
Enable switch to force generation of Many to Many entities

### ISSUE THREAD

**Issue by ErikEJ** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#13]
I would be nice to make this code change an option:

```
      public void IdentifyMappingTables(List<ForeignKey> fkList, bool useCamelCase, string collectionType, bool checkForFkNameClashes, bool includeComments, bool isSqlCE)
        {
            foreach(var tbl in this.Where(x => x.HasForeignKey))
            {
                //tbl.IdentifyMappingTable(fkList, this, useCamelCase, collectionType, checkForFkNameClashes, includeComments, isSqlCE);
            }
        }
```

Use case: I use the generated EF model for table synchronization between server and client database, so I need a object per table...

**Comment by sjh37** [comment]
That has already been added.
See the new flag in your database.tt file:

`````` c#
UseMappingTables = true; // If true, mapping will be used and no mapping tables will be generated. If false, all tables will be generated.```
``````

**Comment by ErikEJ** [comment]
Amazing!

**Comment by NaomiN** [comment]
Hi,

I need further customizations here! Please see a new issue. Our use case: we had used UseMappingTables = true; setting in our tt file. Now one of the tables which was mapping needs an extra column. I did add that column to ExcludeColumnFilter, but unfortunately it didn't affect that method. I don't want to modify the Core files myself if that could be avoided. So, one of the possible solutions is to have a new custom property to be able to specify extra mapping tables. If you can think of a better solution, it would be nice.

Thanks a lot in advance and this is quite an important issue for us. I tried to add a partial class with these properties myself and it allowed to build the project without errors, but I would also need to add a partial for configuration file and that's too much to implement (and while we do have Partials in the Models we don't yet have Partials in the Data project and I don't want to start a precedent). I tried setting IsMapping property in the UpdateColumn method but it made no effect. So, I need to find a solution.
