### ISSUE TITLE
[BUG] - 'SET FMTONLY' confusing

### ISSUE THREAD

**Issue by huyttq** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#131]
The line [2320](https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/blob/master/EntityFramework.Reverse.POCO.Generator/EF.Reverse.POCO.Core.ttinclude#L2320) in EF.Reverse.POCO.Core.ttinclude looks very confusing. It is set ON finally but OFF is the thing we should use for generating return model if a stored procedure uses temp tables

**Comment by sjh37** [comment]
Have a read of https://devio.wordpress.com/2013/01/15/the-amazing-fmtonly-trick/ to see if this helps.
Another interesting read http://www.sqlservercentral.com/Forums/Topic969503-338-1.aspx

With regard to FMTONLY ON/OFF, OFF/OFF, nonsense, this is the way Microsoft do it when their tools reverse engineer a SQL Server database. Strange, but works reliably.

**Comment by sjh37** [comment]
Please let me know if you still think this is a bug after reading the above articles.

**Comment by sjh37** [comment]
Closing this for now.
