### ISSUE TITLE
Errors in adding item to project with EF 6

### ISSUE THREAD

**Issue by weedkiller** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#133]
I added this in a web project ASP MVC, and I got these errors. I am looking for some guidance on how to modify the template please to create both DTO, VM's using the table names and and table columns

I added the string to web config

```
<connectionStrings>
  <add name="Runners"
       providerName="System.Data.SqlClient"
       connectionString="Data Source=(local);Initial Catalog=Runners; Integrated Security=True; />
</connectionStrings>
```

```
Severity    Code    Description Project File    Line    Suppression State
Error       Running transformation: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.TextTemplatingA70D83EAFEF0DB3B03C4E4E8C39C78FF0DAC14F7CF9F5850452786CF83C63AB5FFB6E2B0E5FDB06C24FF0DDB62B58A54D276E3A40073F7438989401C2633E8DB.GeneratedTextTransformation.IsSqlCeConnection(DbProviderFactory factory) in D:\DTO_Assets\EF.Reverse.POCO.Core.ttinclude:line 505
   at Microsoft.VisualStudio.TextTemplatingA70D83EAFEF0DB3B03C4E4E8C39C78FF0DAC14F7CF9F5850452786CF83C63AB5FFB6E2B0E5FDB06C24FF0DDB62B58A54D276E3A40073F7438989401C2633E8DB.GeneratedTextTransformation.TransformText() in D:\DTO_Assets\Database_Runners.tt:line 327   

D:\DTO_Assets\EF.Reverse.POCO.Core.ttinclude    505 

```

**Comment by sjh37** [comment]
Sounds like the GetDbProviderFactory() is returning NULL.

In your database.tt file did you set `ConnectionStringName = "Runners";` ?

**Comment by weedkiller** [comment]
Thanks, I totally mucked it up while trying to customize. 

Yes you were right 👍 one of the interfaces I turned on was not working. But going back to the defaults it works. I need help/guidance please to customize some of the output - **for e.g. for each POCO class generated, I also want to custom generate additional code/another output class file** with the same code for e.g. POCO `user.cs`

Besides the POCO, how can I also get this output to `UserDTO.cs` 

 I got a little further, and then stuck when I changed this `fileManager.StartNewFile(tbl.NameHumanCase + ConfigurationClassName + FileExtension)` to `fileManager.StartNewFile(tbl.NameHumanCase + ConfigurationClassName + "dt" + FileExtension)` - how do I get it to write the file below?

```
[AutoMapper(typeof(user))]
public class UsersDto : IObservable
{
    public string uName { get; set; }
    public string uLast { get; set; }
    public string uEmail { get; set; }
}
```

**Comment by sjh37** [comment]
The simple way to create Dto's is to create another folder, say Models, and into that folder add in the reverse generator again. This time set the entities to generate only the poco classes as:

``` c#
ElementsToGenerate = Elements.Poco;
```

Next is to append Dto to the poco name, you can do this with:

``` c#
TableRename = (name, schema) =>
{
    return name + "Dto";
};
```

To add the attribute `[AutoMapper(typeof(user))]` you would use

``` c#
Action<Table> WritePocoClassAttributes = t =>
{
    WriteLine("    [AutoMapper(typeof(" + Replace(t.NameHumanCase, "Dto", "") + "))]);
};
```
