### ISSUE TITLE
Table named Media beign renamed to Medium always

### ISSUE THREAD

**Issue by vectorderivative** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#14]
The title says it all. Even tho I added a renaming rule as
`TableRename = (name, schema) => 
    {
        if (name == "media") 
        {
            name = "Media";
        }
}`

**Comment by vectorderivative** [comment]
I fixed it by adding
`new CustomPluralizationEntry("Medium", "Media")`

That's weird because the table its named Media. Adding a `new CustomPluralizationEntry("Media", "Media")` didn't work.

**Comment by sjh37** [comment]
Pluralization is case sensitive
try 

``` c#
new CustomPluralizationEntry("medium", "media")
```

**Comment by sjh37** [comment]
It's case sensitive, because if there was a table named get_engineers, it pluralises just the last part of the name. So the pluralisation entry for get_engineers should be

``` c#
new CustomPluralizationEntry("engineer", "engineers")
```
