### ISSUE TITLE
Support 1:0..1 relationships

### ISSUE THREAD

**Issue by kayle** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#144]
I want to override a few relationships in my db that default to 1:* to actually be 1:0..1

Is the best approach to add a hook into CalcRelationship to check for manual overrides? I believe I'd also need a new Relationship enum value.

**Comment by sjh37** [comment]
Hi Kayle,
Yes it is.
I don't think you need a new enum value as null should suffice as 1:0. If there is a value there then its 1:1.
Unless the EF configuration code generated is different in someway, then yes you would need a new enum value.
