### ISSUE TITLE
Poco Interfaces Part 2

### ISSUE THREAD

**Issue by anyolejoe** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#146]
Hello again,

Sorry for my super-slow response, which meant the last thread on this got shut down - I got side-tracked there for a while.

Anyhow, what would be really helpful would be to have a new type on the ElementsToGenerate property (e.g. Elements.PocoInterface) that could be used to output an interface version of the poco class. This could hook up to the WritePocoBaseClasses, WritePocoColumn delegates, so we could customise the output, so we can ensure the data types are valid for com interoperability etc.

That would be a great addition for our purposes, as it's a big manual chore otherwise.

Many thanks.

**Comment by sjh37** [comment]
Can you not use:

``` c#
Func<Table, string> WritePocoBaseClasses = t =>
{
    //if (t.ClassName == "User")
    //    return ": IdentityUser<int, CustomUserLogin, CustomUserRole, CustomUserClaim>";
    return "";
};
```

**Comment by anyolejoe** [comment]
We can use that to assign the interface to the Poco Class, but I'm not sure how we could use that to generate the matching interface itself. It's these that we need so that an old vba legacy application can use the classes we're passing out of the methods in our data layer etc.

**Comment by sjh37** [comment]
Ok, understand now.
As these are POCO classes, the interface will be empty, right? There are no functions that can be declared as the POCO is simply a collection properties.
What functions do you want in the interface(s), and will they vary from POCO to POCO ?

**Comment by anyolejoe** [comment]
It's just the properties we'd be after, so the following poco class -

```
public class MiddleClass
{
    public string PoliteComment {get; set;}
    public int NumberOfCars { get; set; }
}
```

would output this interface -

```
public interface IMiddleClass
{
    string PoliteComment { get; set; }
    int NumberOfCars { get; set; }
}
```

I would hook up the interface to the Poco in the WritePocoBaseClasses delegate. In addition, I would include a check in the WritePocoColumn so that as the interface's column is generated we ensure that things like nullable and generic variables are substituted with a com interoperable equivalent. We could then manually add these com interop equivalent properties into a partial class and would get appropriate compile time errors to ensure this was done.

The result would be that when we passed the object into our legacy app, we would get a strongly typed object rather than a anonymous object.

**Comment by sjh37** [comment]
What I would do then is to add the EF reverse generator again, and call it, say, Interfaces.tt.
Then get it to **only** generate POCO's, and specify

``` c#
TableRename = (name, schema) =>
{
    return "I" + name;
};
```

That will generate all your interfaces with the properties you need.

Then in your main.tt file, make use of 

``` c#
Func<Table, string> WritePocoBaseClasses = t =>
{
    return ": I" + t.NameHumanCase;
};
```

That will generate the real poco's, inherited from the previously generated interfaces.

**Comment by anyolejoe** [comment]
Great - thanks for that, but how would I remove the public modifiers from the properties?

**Comment by sjh37** [comment]
try

``` c#
UpdateColumn = (Column column, Table table) =>
{
    column.Entity = column.Entity.Replace("public ", "");
}
```

**Comment by anyolejoe** [comment]
That's looking good - if I can do something similar to replace the "class" declaration to an "interface" declaration too and then I should be home and hosed!

**Comment by sjh37** [comment]
Create a copy of `EF.Reverse.POCO.ttinclude`, and call it `EF.Interfaces.ttinclude`

Modify interfaces.tt to read the new `EF.Interfaces.ttinclude`  file instead.
Modify `EF.Interfaces.ttinclude` approx line 76

from

``` c#
public <# if(MakeClassesPartial) { #>partial <# } #>class <#=tbl.NameHumanCase#><#=WritePocoBaseClasses != null ? WritePocoBaseClasses(tbl) : "" #>
```

to

``` c#
public <# if(MakeClassesPartial) { #>partial <# } #>interface <#=tbl.NameHumanCase#><#=WritePocoBaseClasses != null ? WritePocoBaseClasses(tbl) : "" #>
```

**Comment by anyolejoe** [comment]
You're a legend - many thanks for that and think we've got a route through to Com Interop heaven now.

**Comment by sjh37** [comment]
Cool. Glad I could help.
Nothing worse than having to write mind numbing code.

**Comment by Eric-Hanson** [comment]
Did this enhancement get added or do we still add the hack to create poco interfaces?

**Comment by sjh37** [comment]
Hi Eric, This did not get added. If others think its of value, I can add it. I'll re-open this case so it goes on the todo list.

**Comment by Eric-Hanson** [comment]
It may be an edge case and the instructions above are not difficult. I'm considering adding interfaces related to our potential use of [AutoMapper ](http://automapper.org/) to feed our converters.

**Comment by aeslinger0** [comment]
It would also be handy to allow the DBContext interface to be generated separately as well. Many times, a solution structure has a project dedicated to just Contracts/Models and are intended to not have any references to other projects. This is where I generate the POCOs - separate from the DbContext in a Data project. It would be great to be able to generate the `IDbContext` in the Contracts/Models project as well so if we wanted to write, for example, extension methods that use `IDbContext`, we could do so without adding a reference to the data project.

**Comment by sjh37** [comment]
I will close and re-create this issue as the above relates to v2 and not v3, which uses {{moustache}} templates.

**Comment by stevensrf11** [comment]
Is there a way to modify the tt script in version 3.8.4 so that each poco entity class is derived from a custom interface
