### ISSUE TITLE
Option to exclude reverse navigation properties

### ISSUE THREAD

**Issue by roblugt** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#147]
Firstly thank you for creating such a useful project!

We will often include POCO classes in our entity model that represent static data.  These will typically be read-only from the application's perspective and will be involved in one-to-many relationships with the line-of-business entities.  E.g. a library application may have a `Book` entity with a FK relationship to a `BookType`.  The `BookType` will typically not be changed by the application and may just include meta-data that aids in the processing of the `Book`.

At present, if we don't filter out the _ForeignKey_, the POCO generator will generate reverse navigation properties for these entities, but this is not always desirable.  When the Entity Framework performs its navigation fix-up processing, the generated reverse navigation properties are modified which not only takes time but also forces the object into the `EntityChangeTracker`, which means these objects cannot be shared between `DbContexts`.  See [StackOverflow](http://stackoverflow.com/questions/40548991/entity-framework-how-to-cache-and-share-read-only-objects) for a related question.

Would you consider looking at a Pull Request to add the option to exclude selected Foreign Keys from reverse navigation?

**Comment by sjh37** [comment]
Yes I would :-)

**Comment by roblugt** [comment]
Thanks. I've created a pull request titled "Optionally exclude reverse navigation properties".  This is my first PR on GitHub so please let me know if you need anything else.

Many thanks
Rob

**Comment by sjh37** [comment]
Many thanks Rob. The pull request was spot on.
Notes for pull requests on this or other projects:
1. Always keep the changes to a minimum, so the author can see exactly what's changed in regard to the pull request. I.e. no whitespace tidy up, tabs to spaces, etc.
2. Don't be tempted to do a few different changes in one pull request. Have one pull request for one bug fix / enhancement.

:-)

This pull request will be in the next release after I've completed data annotations.

**Comment by ErikEJ** [comment]
ADD Contriburion guidelines?

**Comment by sjh37** [comment]
@ErikEJ [Wrote this guidline](https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/wiki/How-to-get-your-pull-request-accepted)

**Comment by roblugt** [comment]
Great, many thanks.

**Comment by ErikEJ** [comment]
@sjh37 Maybe add a Contributing section to the readme.md with link to the new page ?
