### ISSUE TITLE
Tool not generating classes if key is absent

### ISSUE THREAD

**Issue by sameer-kumar** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#148]
I'm trying to use the tool against the SQL 2012 database where table objects don't have any primary key defined but it fails. At this moment I can't change the design of my DB and add keys.

How can I proceed?

Thanks for your help!

**Comment by sjh37** [comment]
EF cannot work with any table without a primary key. So this generator helps you out. It sets all the columns which are NOT NULL to be a primary key.
So if you have a table with no primary key, and all columns are NULLable, then that table cannot be included. All the other tables (which have NOT NULLable columns will be included).
