### ISSUE TITLE
Visual Studio 2017 Compatibility

### ISSUE THREAD

**Issue by vzczc** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#150]
When testing Visual Studio 2017 RC I found that this does not work there, do you have any plans to fix this?

**Comment by sjh37** [comment]
I haven't installed 2017 RC yet. I'll install as soon as it out of RC and see how it fairs then.

**Comment by AndyCadley** [comment]
So far, I've not had any issues using the templates that are in an existing project, it's just that the extension itself won't show up in VS2017. So you can workaround it by adding the items manually or with VS2015.

**Comment by mattmercurio** [comment]
I've used the framework in many projects but in a new VS2017 project nothing happens upon save of the TT file. It does show the connection used in the generated file but no luck on any entities etc. Has anyone started fresh in VS2017? I'm using v2.29.0

**Comment by sjh37** [comment]
Hi @mattmercurio 
I've just tested this, brand new console application, installed-package entityframework, added a connection string to the app.config, added generator. all worked.
Changed connection string in app.config to point to a different database, resaved generator, worked perfectly.
As its generating a C# file for you as its displaying the connection string used, I suspect the connection string is either not correct, or the sql server service is not running.

**Comment by mattmercurio** [comment]
Added providerName="System.Data.SqlClient" to my connection string and it worked.

**Comment by ErikEJ** [comment]
Could you share the output when no provider name was specified (it what was in database.cs) ? - maybe we can improve with an  error message to help you get unblocked

**Comment by mattmercurio** [comment]
**Without provider** it stops after the Connection String string used is displayed.

**With provider** it generates properly, displays the SQL version info and then continues to gen the namespace etc.

// Database Edition       : Developer Edition (64-bit)
// Database Engine Edition: Enterprise

**Comment by ErikEJ** [comment]
@sjh37 

How about adding something like:

            if (!string.IsNullOrEmpty(ProviderName))
            {
                try
                {
                    return DbProviderFactories.GetFactory(ProviderName);
                }
                catch (Exception x)
                {
                    string error = x.Message.Replace("\r\n", "\n").Replace("\n", " ");
                    Warning(string.Format("Failed to load provider \"{0}\" - {1}", ProviderName, error));
                    WriteLine("");
                    WriteLine("// ------------------------------------------------------------------------------------------------");
                    WriteLine("// Failed to load provider \"{0}\" - {1}", ProviderName, error);
                    WriteLine("// ------------------------------------------------------------------------------------------------");
                    WriteLine("");
                }
            }
			else
			{
                Warning("Failed to find providerName in the connection string");
                WriteLine("");
                WriteLine("// ------------------------------------------------------------------------------------------------");
                WriteLine("//  Failed to find providerName in the connection string");
                WriteLine("// ------------------------------------------------------------------------------------------------");
                WriteLine("");				
			}

**Comment by sjh37** [comment]
I've added that, and its working nicely. Thanks @ErikEJ

**Comment by ErikEJ** [comment]
Great, makes OOB experience even better!

**Comment by sjh37** [comment]
Released
