### ISSUE TITLE
Using custom function in TableRename

### ISSUE THREAD

**Issue by Eric-Hanson** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#152]
I'm attempting to use a custom function in the TableRename customization and encountering an error "Compiling transformation: The name '{namespace top level}' does not exist in the current context. The error remains even after adding the namespace in the AdditionalNamespaces collection.

Here is the code from class "Db" where TableNameRenameDictionary is a dictionary<string, string>:
``
public static string DataTableName(string actualSqlTableName) {
        return TableNameRenameDictionary[actualSqlTableName] ?? actualSqlTableName;
}
``
...
In Database.tt file:
``
TableRename = (name, schema) => {
  return {namespace}.Db.DataTableName(name);
}
``

What changes do you recommend? Is this feature supported?

**Comment by sjh37** [comment]
Add your DataTableName function anywhere after line 26 in EF.Reverse.POCO.Core.ttinclude

![image](https://cloud.githubusercontent.com/assets/4190514/20753803/0dc7c246-b700-11e6-934c-3e361e54a95b.png)


Then in your database.tt file
```c#
TableRename = (name, schema) => DataTableName(name);
```

**Comment by Eric-Hanson** [comment]
Thank you. That works well.
