### ISSUE TITLE
lack of dbo.sysdiagrams forces additional migration

### ISSUE THREAD

**Issue by TadeuszSobol** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#153]
Where is switched off dbo.sysdiagrams table.
Lack of dbo.sysdiagrams forces additional migration removing it - but it is unacceptable for us due to removing live documentation about data base.

**Comment by Chris3773** [comment]
This is what I added to TableFilter to remove dbo.sysdiagram from the pocos. However it looks like this not needed anymore after version v2.25.0.

```
if(t.Schema.Equals("dbo", StringComparison.InvariantCultureIgnoreCase) && t.NameHumanCase.Equals("sysdiagram", StringComparison.InvariantCultureIgnoreCase))
            return false;
```

**Comment by sjh37** [comment]
It's switched off in the SQL query.
See https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/commit/27f8780cd71439c1ccaa87e20e784674ebcff078
