### ISSUE TITLE
If table have 2 foreign keys, the are ugly renamed by using table name and ordinary numbers

### ISSUE THREAD

**Issue by TadeuszSobol** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#154]
For example, columns Thesis_id and RelatedThesis_id are renamed to ThesisId and ThesisId1 etc.
And all indexes and foreign keys from v.2.24 are recreated in first migration (in such schema) in version 2.25

**Comment by sjh37** [comment]
If the SQL columns Thesis_id and RelatedThesis_id are C# named ThesisId and ThesisId1 in v2.24, what column names have they been given 2.25. I'd like to see the difference.

**Comment by TadeuszSobol** [comment]
No, in 2.24 database Thesis_id is renamed to C# ThesisId and database RelatedThesis_id is renamed to RelatedThesisId.
I investigate that in 2.24 (and earlier) it could happen because of our changes in ForeignKeyName algorithm (to save source-destination relation name and foreign key column name), ie:

```c#
ForeignKeyName = (tableName, foreignKeyName, attempt) =>
{
    switch (attempt)
    {
     case 1:
         var fk = foreignKeyName;
         if (fk.EndsWith("Id"))
             fk = foreignKeyName.Substring(0, foreignKeyName.Length - 2);
         if (fk == tableName)
         {
             return fk;
         }
         if (tableName.EndsWith("s"))
         {
             return tableName;
         }
         return fk + "_" + tableName;

     case 2:
         fk = foreignKeyName.Substring(0, foreignKeyName.Length - 2);
         if (fk == tableName)
         {
             return fk;
         }
         if (tableName.EndsWith("s"))
         {
             return tableName;
         }
         return fk + "_" + tableName;

     case 3:
         return foreignKeyName + "_" + tableName;

     case 4:
         return foreignKeyName + "_" + tableName;

     case 5:
         return tableName;
     default:
         return tableName;
    }
};
```

**Comment by sjh37** [comment]
It sounds like if you want to update to v2.25, put the `ForeignKeyName` function back to how you had it before, and all should be ok. Alternatively, keep the modified 2.24 version you have.

**Comment by sjh37** [comment]
I am still unsure what you want me to do, or what you are asking for.

**Comment by TadeuszSobol** [comment]
Please, do not replace original database column names by database table name in annotations.  It is working well for DataAnnotation=false and in previous versions.
However, when DataAnnotation=true it seems the ForeignKeyName algorithm is omitted during generating names in annotations.
If it is true, please correct it.

**Comment by sjh37** [comment]
I will check

**Comment by sjh37** [comment]
I have checked and its working ok.
What I did:

```c#
ForeignKeyName = (tableName, foreignKeyName, attempt) =>
{
    switch (attempt)
    {
        case 1:
            if (tableName == "Employee")
                return "SomeDude";
            return tableName;
...
```

This generated:
```c#
public class Employee
{
    ...
    public virtual Employee SomeDude { get; set; } // FK_Employees_Employees
    ...
}
```

Turning on data annotations gave this:
```c#
public class Employee
{
    ...
    [ForeignKey("ReportsTo")]
    public virtual Employee SomeDude { get; set; } // FK_Employees_Employees
    ....
}
```

As you can see, in both scenarios the foreign key was renamed to "SomeDude".

Am I missing something else?

**Comment by TadeuszSobol** [comment]
I think I found the reason of ugly renames.
When I use in .TT file UseDataAnnotationsSchema=false everything works OK, including Microsoft migration tool: it generate empty migration file – as expected (because no changes), so it is OK too.
However, when I use UseDataAnnotationsSchema=true (and UseDataAnnotations = true), for the same database, the Microsoft migration tool (add-migration) creates huge migration file containing strange unnecessary changes like:
many  DropForeignKey(…)  and many  DropIndex(…),
not required  RenameColumn(table: "dbo.RelatedA", name: "**RelatedThesisA_id**", newName: "**ThesisA_Id**");  - _it is wrong because ThesisA_id already exists_ .
And for tables with 2 or more Foreign Keys the migration tool  generates:
CreateIndex("dbo.RelatedA", "ThesisA_Id");
CreateIndex("dbo.RelatedA", "**ThesisA_Id1**");  - _should be RelatedThesisA_id without rename_
And so on.

But in your file it looks fine (as you wrote):
```c#
[Column(@"ThesisA_id", Order = 2, TypeName = "int")]
[Index(@"IX_ThesisA_id", 1, IsUnique = false, IsClustered = false)]
[Required]
[Display(Name = "Thesis a ID")]
public int ThesisAId { get; set; } // ThesisA_id

[Column(@"RelatedThesisA_id", Order = 3, TypeName = "int")]
[Index(@"IX_RelatedThesisA_id", 1, IsUnique = false, IsClustered = false)]
[Required]
[Display(Name = "Related thesis a ID")]
public int RelatedThesisAId { get; set; } // RelatedThesisA_id
```
Therefore, it seems Microsoft Migration Tool wrongly generates  migration .cs file but only if Data Annotation Schema is used and many FKs are in same database table – as show above.
Maybe it is possible to help Microsoft correctly understand annotations or maybe in next version of MS Migration Tool for EF Core it will be working but anyway we have to support older applications by many years using EF6 tools.

**Comment by sjh37** [comment]
Thanks  Tadeusz,

Ok. Not sure why migrations would generate a change when the result is the same.
In your case, I would keep use data annotations = false;
I will close this case as I have no influence on migrations (I don't work for Microsoft), only what this tool can generate.

Simon.
