### ISSUE TITLE
MyDbContextStaticPartial does not exist in the current context	

### ISSUE THREAD

**Issue by arbh89** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#155]
Hi, i have updated my template to version 2.25.0.0 and i am using the property MakeClassesPartial = true but i am getting an error MyDbContextStaticPartial does not exist in the current context in DbContext class.

![image](https://cloud.githubusercontent.com/assets/6992258/20713829/69f20640-b60f-11e6-93d8-dbbef1324d7a.png)

**Comment by sjh37** [comment]
That is because you have to create that function in your partial class. How else are you going to initialise static variables within your static constructor? It's a mandatory requirement.

If the generated db context is called `MyDbContext`, then you need something like:

```c#
public partial class MyDbContext
{
    private static void MyDbContextStaticPartial()
    {
        // Put any static initialisation in here
    }
}
```
