### ISSUE TITLE
How can poco classes inherit from generic Entity class?

### ISSUE THREAD

**Issue by Eric-Hanson** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#156]
Configuration options make it easy for the context to inherit from another class.

How hard is it to configure the generator to inherit from a generic Entity class?

My standard entities are usually wrapped in a generic class derived from an interface as follows:
`public class PocoClass : Entity<PocoClass> { ... }`

**Comment by Eric-Hanson** [comment]
Figured it out, look for property WritePocoBaseClasses.

Here is my code:
```
    // Writes optional base classes
    Func<Table, string> WritePocoBaseClasses = t =>
    {
        return " : Entity<" + t.NameHumanCase + ">";
    };
```

**Comment by papyr** [comment]
@Eric-Hanson can I ask where did you plug this in, I am trying to do something similar to also generate a DTO class back to back after the POCO class
