### ISSUE TITLE
Guidance on template upgrade

### ISSUE THREAD

**Issue by ErikEJ** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#157]
What do you propose is the best apporach for this? Would be nice to have a suggested approach (on the wii for eample)

**Comment by sjh37** [comment]
I show how to update in the Pluralsight course.
I know I need to create some documentation and guides, which I can do that now I've Data Annotations out of the way.

**Comment by j4adev** [comment]
I was interested in this as well.  I ended up creating a temp project adding a new "EF Reverse POCO Code First Generator" to the project.  Doing a winmerge between the temp projects YourDbContextName.tt file and the existing one.  Carefully put the old bits into the new temp version or translated them to the new format.  Then copy the new .tt file and the two EF.ReversePOCO.*.ttinclude files from the temp project into the existing project.  This seems to have worked out so far.

**Comment by TimSirmovics** [comment]
I copy the contents of .tt file into Notepad++, then delete all 3 files from the project and add the new one. I then scan over the old .tt and update settings in the new .tt as neccesary. Not the best method but generally I change the same settings (I have about 50 of these files over different projects) so it works ok.

**Comment by sjh37** [comment]
I personally delete *.ttinclude, leaving my original .tt settings file, then re-add the generator using database1.tt. I then use Araxis Merge to compare the original .tt settings file with database1.tt, and pull in anything new into the original .tt file. I then delete database1.tt

**Comment by RichardCha** [comment]
> I copy the contents of .tt file into Notepad++, then delete all 3 files from the project and add the new one. I then scan over the old .tt and update settings in the new .tt as neccesary. Not the best method but generally I change the same settings (I have about 50 of these files over different projects) so it works ok.

Yes, I have to do like what you said above. I have about 10 of these xx.tt files. It is heavy maintenance work every time new version released.

I am looking forward to having an easy way to solve this problem.

**Comment by sjh37** [comment]
I've written a document on [upgrading v2 to v3](https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/wiki/Upgrading-from-v2-to-v3).

However, from upgrading v3 to v3, I still use the method I mentioned [above](https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/issues/157#issuecomment-434990039).
