### ISSUE TITLE
Support for UseDataAnnotations and IncludeCodeGeneratedAttribute?

### ISSUE THREAD

**Issue by Eric-Hanson** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#158]
Searching this site for Data Annotation support and adding "Sealed" attribute to poco classes, I discovered properties UseDataAnnotations and IncludeCodeGeneratedAttribute. 

They are not supported in my current version of the EntityFramework-Reverse-POCO-Code-First-Generator v2.24.0. Are these features supported in version v2.25.0?

**Comment by sjh37** [comment]
These are new features released in v2.25

**Comment by Eric-Hanson** [comment]
Thank you, I will request the updated version.
