### ISSUE TITLE
Hot to do not remove already existing dbo.sysdiagrams in database

### ISSUE THREAD

**Issue by TadeuszSobol** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#159]
We have many Database Diagrams in many databases (stored in dbo.sysdiagrams table). We do not want to be forced to remove they by each of migrations after installing v2.25, so we revert to 2.24 - because our dbo.sysdiagrams are required kind of our live database structure documentation and we are not authorized to remove they.
So, how to stop excluding dbo.sysdiagrams table from generated context **or such configuration switch should be added**

**Comment by sjh37** [comment]
If you are using migrations, then why are you still reverse engineering the database?
