### ISSUE TITLE
Enhanced use of comments

### ISSUE THREAD

**Issue by ErikEJ** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#16]
Instead of this:

```
    public System.Guid RidKey { get; set; } // RIDKey (Primary key)
```

Is it possible to generate this: ???

```
    /// <summary>
    /// RIDKey (Primary key)
    /// </summary>
    public System.Guid RidKey { get; set; }
```

Justification: Added value for consumers of generated DbContext, allowing them to easily identify for example primary and foreign keys via Intellisense:

![efpoco2](https://cloud.githubusercontent.com/assets/4169187/13878848/5b4671fe-ed14-11e5-8fb8-8720feb15aa3.png)

**Comment by ErikEJ** [comment]
In case I make a pr for this, how do you imagine the option for this? Make a new Enum like for the extended property comments? Or add an enum value like: ExtendedPropertyCommentsStyle.InSummaryBlockWithStandardComments ?

**Comment by ErikEJ** [comment]
Ping!

**Comment by sjh37** [comment]
Sorry Erik,

Can you change IncludeComments from a bool to be an Enum.
Rename ExtendedPropertyCommentsStyle to be CommentsStyle, so we only have one enum for both.

So the tt now looks like

``` c#
IncludeComments = CommentsStyle.InSummaryBlock;; // Adds comments to the generated code
IncludeExtendedPropertyComments = CommentsStyle.InSummaryBlock; // Adds extended properties as comments to the generated code
```

**Comment by ErikEJ** [comment]
Are you propsoing the above as default values in the .tt?

**Comment by sjh37** [comment]
Thinking about it, the IncludeComments should default to "end of line".
and the extended properties to "in summary block"
