### ISSUE TITLE
How to reuse the POCO generator variables, and create a seperate class

### ISSUE THREAD

**Issue by papyr** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#162]
Hi, I really like this tool, its been very helpful 👍  but when scripting the Db tables to the POCO objects , I don't know **how to add a new file name, and reuse the table variable to create another file.**?

My file has many modifications I need, if you can help me with this small sample.. I can do the rest. 
Can you please tell me how can I modify the POCO to _1)_ create another class, _reuse_ the variables from the db table names, _2)_ how can I create put it in a separate file for these class with table**Book**CheckOut.cs

[TableName("TbBooks")]
public class **Book** : ICheckedInOut
{
    public const int Max**NameLength** = **16**;
    public const int Max**MaxSurnameLength** = **16**;
   ...
   ...
[Required]
[MaxLength(Max**NameLength**)]
public virtual string **Name** { get; set; }
}

Thanks

**Comment by sergy79** [comment]
Hi, after reading the comments, I was unable to get it working myself, I was also trying to figure out how to reuse the table/attribute names so I could create another file and save as a separate file

**Comment by sjh37** [comment]
Turn on partials in the database.tt and add to your partial class any extra functionality you need. However, these are entities and not business objects, so perhaps it would be better to pass the plain poco entity to business logic to be processed rather than adding the functionality to the poco.
 Also take a look at #156 and #146

**Comment by papyr** [comment]
Ok, I see a Func wire up and a partial from your comments

Created copy like so
`Create a copy of EF.Reverse.POCO.ttinclude, and call it EF.DTO.ttinclude`


Made another copy so
```
Modify DTO.tt to read the new EF.DTO.ttinclude file instead.
Modify EF.DTO.ttinclude approx line 76
```

Left this in place
`public <# if(MakeClassesPartial) { #>partial <# } #>class <#=tbl.NameHumanCase#><#=WritePocoBaseClasses != null ? WritePocoBaseClasses(tbl) : "" #>`

sorry for being slow here :) I am not getting how to get the custom inserts to reuse the same tablename and variables.  It looks like the main class is written when its close, and the variables are now lost - is that correct.

_Can you give me a snippet to show to reuse the code functions or segments to write the table and attributes/columns to a separate file called BookDTO.cs_

I found line# 289 of the [database.tt file](https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/blob/master/EntityFramework.Reverse.POCO.Generator/Database.tt) _where I found the code for table and column generator_ do I modify this code here?

**Comment by papyr** [comment]
I signed up and was watching your course on pluralsight to learn - however there is not section on reusing the table/entity to generate a new class, can you tell me how to do this please

![image](https://cloud.githubusercontent.com/assets/12733414/20999760/e2eb43dc-bce4-11e6-9c91-0210fa84d4d1.png)

**Comment by sjh37** [comment]
I don't show how to change the generator to output something completely different. A DTO usually  does not map to an EF table poco because it can be a select statement from a few tables, and perhaps only a few columns from each. 

If I understand what you want, you want to generate Dto's which map 1 to 1 the EF poco's. And also add a base class to the Dto? I know others have done this, and info is on one of the closed github issues. I only have my android tablet with me this week so can't really help. Creating Dto's is something I manually do myself. However i usually only need to create 5 to 10 to match a resulting select statement for a view model.

**Comment by papyr** [comment]
Simon thats correct, if you could include a sample on to that, gen up a separate class with DTO's that it would help me out, once I understand that, I can build on it.

**Comment by sjh37** [comment]
@papyr That is outside the remit of this generator. I'm not a tutorial service. There are many Pluralsight courses to help you learn about getting data from the database and mapping it to DTO's.

AutoMapper is the NuGet plugin to map your POCO's to your DTO's.

Alternatively select the object directly

```c#
return await _db.SomeTable
        .AsNoTracking()
        .Where(x => x.Id == someId)
        .Select(row => new EngineersAtSite
        {
            Id = row.Id,
            Name = row.Item.Forename + " " + row.Item.Surname,
            EngineerId = row.Item.EngineerId ?? 0
        })
        .ToListAsync();
```

**Comment by papyr** [comment]
I was saying 90% of the tool already generates the code - why not give it an option to let other use/extend it for other classes like DAL classes.

**Comment by sjh37** [comment]
What I would do is to add the generator again into a separate DAL folder, or a separate project.
Specify that only the POCO's are to be generated. `ElementsToGenerate = Elements.Poco;`

If you wanted to append DAL to the end of the Poco class name, update your settings tt file
```c#
// Writes optional base classes
Func<Table, string> WritePocoBaseClasses = t =>
{
    return "DTO";
};
```

**Comment by papyr** [comment]
Thanks
