### ISSUE TITLE
Entity Framework errors with DataAnnotation enabled and particular table configurations

### ISSUE THREAD

**Issue by StefanoP73** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#163]
Hi, I have two problem with my DB and the new v2.25 with DataAnnotation enabled...

I created 2 different tables (TableA, TableB) with the following cases:

1. TableA with a **double PrimaryKey** and **enabled only DataAnnotation**
    I can view in the poco class 2 propeties with **[Key]** Data Annotation,
    During the execution I get the following error:
    

> Unable to determine composite primary key ordering for type 'ConsoleApplication1.Models.TestA'. Use the ColumnAttribute (see http://go.microsoft.com/fwlink/?LinkId=386388) or the HasKey method (see http://go.microsoft.com/fwlink/?LinkId=386387) to specify an order for composite primary keys.

If I enable UseDataAnnotationsSchema the error is gone.

2. TableA and TableB with a **single PrimaryKey** and with a **1 to 1 relationship** "`FK_TableB_TableA`", **DataAnnotation and UseDataAnnotationsSchema both enabled**
   I can view in the poco class the PrimaryKey and the ForeignKey in the TableB for the "`public virtual TableA`"
   during execution I get the following error:
   

> Unable to determine the principal end of an association between the types 'ConsoleApplication1.Models.TableB' and 'ConsoleApplication1.Models.TableA'. The principal end of this association must be explicitly configured using either the relationship fluent API or data annotations.

I can resolve the first problem adding `Order` numbering of DataAnnotation `System.ComponentModel.DataAnnotations.Schema.Column` to the PrimaryKey, like already does UseDataAnnotationsSchema, so I enabled it
But I fell in the second error and the only way I found to resolve it is adding to POCO Configuration "`public TableBConfiguration(string schema)`" the Foreignkey:
`HasRequired(a => a.TableA).WithOptional(b => b.TableB).WillCascadeOnDelete(false); // FK_TableB_TableA`
Like the TT create with UseDataAnnotationsSchema disabled

I hope to be clear
If in the meatime I find a solution I'll post it here :)

Thank you for all your beautifull work

**Comment by sjh37** [comment]
Thanks Stefano. Still early days for data annotations. With the great help from the community I will get all the bugs ironed out.

**Comment by JensLeible** [comment]
I solved it by adding the ForeignKey data annotation to the foreign key property, passing the name of the navigation property, in addition to the  ForeignKey data annotation on the navigation property which is already there. I did this manually in the generated file and did not try to fix the generation yet.

**Comment by sjh37** [comment]
This has been fixed via #321 , and will be in the next release. If this does not fix your exact issue, please let me know and I will re-open this case.

**Comment by clarghi** [comment]
Hi,
I have updated to 2.33.0 version, but the error is the same:
"Unable to determine the principal end of an association between the types 'ConsoleApplication1.Models.TableB' and 'ConsoleApplication1.Models.TableA'. The principal end of this association must be explicitly configured using either the relationship fluent API or data annotations."
