### ISSUE TITLE
How can I customize stored proc generation to provide async calls?

### ISSUE THREAD

**Issue by fmorriso** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#164]
I'd like to "experiment" and see if I can get this tool to generate async versions of the calls to stored procecures.

Where would I do that?

P.S. Is this on anybody's TODO list as a future enhancement ?

**Comment by sjh37** [comment]
It would be in the .tt include files. One is for processing and the other is to write the output into C# files.
