### ISSUE TITLE
"StoredProcedureFilter" lambda functionality similar to "TableFilter = (Table t) =>"

### ISSUE THREAD

**Issue by ShakyaJones** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#168]
This will allow (for example) the ability to include only stored procs that belong to a particular database schema using:
StoredProcedureFilter = (StoredProcedure p) => 
{
  if p.Schema.Equals("ormProcs", StringComparison.InvariantCultureIgnoreCase)
    return true;
  else return false;
}
Note that using SchemaFilterInclude would not cover this need because it would apply the same rules to tables as stored procs. For example it would not include any tables from the dbo schema if including only the "ormProcs" schema. There may be only stored procs, no tables, in the ormProcs schema.

**Comment by sjh37** [comment]
Pull the latest changes.

**Comment by sjh37** [comment]
Released in v2.26
