### ISSUE TITLE
CodeGeneratedAttribute is missing from the generated configuration classes

### ISSUE THREAD

**Issue by andygjp** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#17]
Hi,

I automatically add any hand crafted configuration (any configuration without the CodeGeneratedAttribute) when I initialise my context, but to make this work I have to manually edit the EF.Reverse.POCO.ttinclude file every time I upgrade. Please can this be added to the EF.Reverse.POCO.ttinclude for consistence, as the POCOs have this attribute, and because I always forget to edit the file :stuck_out_tongue:.

Cheers,
Andy

**Comment by sjh37** [comment]
Thanks, I'll take a look at your pull request.

**Comment by sjh37** [comment]
I've pulled. So will be in next release. Many Thanks.
