### ISSUE TITLE
Remove redundant wiki page

### ISSUE THREAD

**Issue by ErikEJ** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#172]
This page seems redundant: https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/wiki/AdventureWorks-2012-and-2014-databases

**Comment by sjh37** [comment]
I have updated the page to explain why this page is here. I want to keep it around as it shows people how to install a version of EF that supports the use of HIERARCHYID type.

**Comment by ErikEJ** [comment]
But most of that info is duplicated here: https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/wiki/HierarchyId

**Comment by sjh37** [comment]
Gah, missed it. Cannot see the wood for the trees. Thanks Eric.
Page removed.
