### ISSUE TITLE
Guidance on Dbcontext compare

### ISSUE THREAD

**Issue by ljfolino** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#177]
I have an old EDMX DBContext and would like to migrate to using Reverse POCO Generator.  Do you know of any good tools to compare two DBContext Schemas together and diff them or a good way to go about doing this. The issue comes down to multiple FKs pointing to the same table IE Company table.

**Comment by sjh37** [comment]
From the database side, red gate have a product called sql compare.
http://www.red-gate.com/products/sql-development/sql-compare/
