### ISSUE TITLE
Issue with stored procedure return model if c# keywords are used for column names 

### ISSUE THREAD

**Issue by ErikEJ** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#178]
(Constructed) Example:

    CREATE PROCEDURE TestProc
    AS
    SELECT 0 AS int

Return model:

     public class dbo_TestProcReturnModel
     {
        public System.Int32? int { get; set; }
  }

Results in: Invalid token int ...

**Comment by sjh37** [comment]
I'll take a look, but if I remember correctly, if I rename the field so say "someInt" no data will ever be returned to it as the return model column names must match exactly the return parameters.

**Comment by ErikEJ** [comment]
So the only real option is to fix it in the sproc?

**Comment by sjh37** [comment]
I'm afraid so.
I'll read some more to see if we can re-map the returned data, but I don't think we can.

**Comment by sjh37** [comment]
If you are not allowed to alter the sproc, then you can write another sproc which calls it, and returns the data as another name.

**Comment by PTancek** [comment]
Is there perhaps a fix for this is the newer versions?

**Comment by sjh37** [comment]
Hi @PTancek 
No, the stored proc return parameters cannot be renamed within entity framework. Unfortunately stored procedure return models must match exactly the return column names returned, and therefore cannot be renamed. If they were renamed, Entity Framework would not map the column data back.

The two ways to fix this are:

- Change the stored procedure to return different column names, or
- If you cannot alter the original stored procedure, then create a new stored procedure which calls the original stored procedure and return the columns as different names. In your code, only call the new stored procedure. You can filter out the original stored procedure so it's excluded and therefore is not callable in the EF db context.

Related cases: #227 and #650
