### ISSUE TITLE
[SQLCE] Log string truncation issue

### ISSUE THREAD

**Issue by ErikEJ** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#179]
From: https://www.blogger.com/comment.g?blogID=5238131531249720750&postID=4880639492129960646 

I've a SQL Server Compact database. I did a reverse POCO after following article: 

https://github.com/ErikEJ/SqlCeToolbox/wiki/EntityFramework-Reverse-POCO-Code-First-Generator.

But I'm getting exception: System.NotSupportedException
Message: "Binary column with MaxLength greater than 8000 is not supported."

It's recommended not to change file generated by reverse POCO. What should I do to overcome this limitation?

**Comment by ErikEJ** [comment]
Please provide code to generate this error and a description of the table causing the error

**Comment by sjh37** [comment]
Just had the same question asked over on PluralSight. 
https://app.pluralsight.com/library/courses/code-first-entity-framework-legacy-databases/discussion
I've pointed them at this case.

**Comment by ErikEJ** [comment]
I suspect it may be an issue with the calling code not setting the SqlCeParameters correctly: https://github.com/ErikEJ/EntityFramework.SqlServerCompact/blob/master/src/Provider40/Storage/Internal/SqlCeMaxLengthMapping.cs#L57

**Comment by sjh37** [comment]
I have a function which returns the SqlDbType to use:

```c#
private static string GetSqlDbType(string sqlType, int scale, int precision)
{
    string sysType = "VarChar";
    switch(sqlType)
    {
        case "binary":
            sysType = "Binary";
            break;

        case "image":
            sysType = "Image";
            break;
        ...
}
```

Should the code at https://github.com/ErikEJ/EntityFramework.SqlServerCompact/blob/master/src/Provider40/Storage/Internal/SqlCeMaxLengthMapping.cs#L57 be:

```c#
if (parameter.DbType == System.Data.DbType.Binary ||
    parameter.DbType == System.Data.DbType.Image)
```

**Comment by ErikEJ** [comment]
No, I only use DbType.Image in the Typemapper: https://github.com/ErikEJ/EntityFramework.SqlServerCompact/blob/master/src/Provider40/Storage/Internal/SqlCeTypeMapper.cs 

I need repro code from the folks reporting the error in order to help....

**Comment by ErikEJ** [comment]
Found the bug! (In EF Reverse POCO)

Generated configuration:

            Property(x => x.Description).HasColumnName(@"Description").IsOptional().HasColumnType("ntext").IsMaxLength();
            Property(x => x.Picture).HasColumnName(@"Picture").IsOptional().HasColumnType("image").HasMaxLength(1073741823);

Working configuration  (for image and ntext columns  with SQLCE):

            Property(x => x.Description).HasColumnName(@"Description").IsOptional().HasColumnType("ntext").HasMaxLength(null);
            Property(x => x.Picture).HasColumnName(@"Picture").IsOptional().HasColumnType("image").HasMaxLength(null);

So **HasMaxLength(null)** should be used here.... Not sure about the implications for SQL Server....
This also works (not generatein any MaxLength at all) , and might be easier to implement:

            Property(x => x.Description).HasColumnName(@"Description").IsOptional().HasColumnType("ntext");
            Property(x => x.Picture).HasColumnName(@"Picture").IsOptional().HasColumnType("image");

**Comment by sjh37** [comment]
Great. I shall get a fix out today.

**Comment by sjh37** [comment]
Should I only restrict this to "image", or image, ntext, and binary types ?

**Comment by sjh37** [comment]
In fact, instead I could do this
```c#
if (isSqlCe && MaxLength > 4000)
```

Then perform the restriction, rather than checking the types. What do you think? @ErikEJ

**Comment by ErikEJ** [comment]
The last proposal looks good, I had something similar in mind.

What do you mean by "perform the resctriction" though - I assume have this check, and if it is true, set MaxLength to null ?

**Comment by sjh37** [comment]
Code now released. Let me know if this fixes things.

**Comment by ErikEJ** [comment]
Great, I will give it a try!

**Comment by Anil86** [comment]
@ErikEJ @sjh37 yes,  
     `Property(x => x.Picture).HasColumnName(@"Picture").IsOptional().HasColumnType("image").HasMaxLength(1073741823);`
 was causing the issue.


Oringinal POCO property:

        public byte[] Icon16 { get; set; } // Icon16 (length: 1073741823)
        public byte[] Icon32 { get; set; } // Icon32 (length: 1073741823)

Configuration:

            Property(x => x.Icon16).HasColumnName(@"Icon16").HasColumnType("image").IsOptional().HasMaxLength(1073741823);
            Property(x => x.Icon32).HasColumnName(@"Icon32").HasColumnType("image").IsOptional().HasMaxLength(1073741823);


Fix:

            Property(x => x.Icon16).HasColumnName(@"Icon16").HasColumnType("image").IsOptional();//.HasMaxLength(1073741823);
            Property(x => x.Icon32).HasColumnName(@"Icon32").HasColumnType("image").IsOptional();//.HasMaxLength(1073741823);

**Comment by ErikEJ** [comment]
@Anil86 Could you try with HasMaxLength(null) (which is the implemented solution) ?

**Comment by Anil86** [comment]
@ErikEJ Works 👍

**Comment by ErikEJ** [comment]
Thanks for confirming!

**Comment by ErikEJ** [comment]
@sjh37 Also tested with both image and ntext columns, this Config works:

      Property(x => x.Description).HasColumnName(@"Description").HasColumnType("ntext").IsOptional().IsMaxLength();
      Property(x => x.Picture).HasColumnName(@"Picture").HasColumnType("image").IsOptional().HasMaxLength(null);

**Comment by Listenreich** [comment]
@ErikEJ I'm using EF 6.1.3 with SQL CE 3.5. I still get an validation error (The field 'Picture' must be a string or array type with a maximum length of '4000'), if I insert data bigger than 4000 bytes, even with the following code 
`Property(x => x.Picture).HasColumnName(@"Picture").HasColumnType("image").IsOptional().HasMaxLength(null);` in my configuration settings. Should this fix work for the version 6.1.3?

**Comment by sjh37** [comment]
@Listenreich It has nothing to do with EF 6.1.3, but rather the reverse poco version the fix was released for, which was 2.27.0 onwards.

What version of the reverse poco are you using?

**Comment by Listenreich** [comment]
@sjh37 I'm using the version v2.30.0.

**Comment by Listenreich** [comment]
@sjh37 i made a demo project for the problem which i can provide you if this helps.

**Comment by sjh37** [comment]
Yes please

**Comment by ErikEJ** [comment]
Closing as no repro receeived
