### ISSUE TITLE
Source of wiki page

### ISSUE THREAD

**Issue by ErikEJ** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#180]
Hi Simon, can you remember what was the source of this page?

https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/wiki/Speed-up-Reverse-generating-by-updating-statistic-on-sys-tables.

(Also the link appears to be broken, maybe due to the end "." ??)

**Comment by ErikEJ** [comment]
Found it here: https://github.com/aspnet/EntityFramework6/issues/4 (but it might be useful to link to it?)

**Comment by sjh37** [comment]
Will do. I'll also see if I can remove the '.' on the end.

**Comment by sjh37** [comment]
Link added. New url is now https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/wiki/Speed-up-Reverse-generating-by-updating-statistic-on-sys-tables

**Comment by sjh37** [comment]
To drop back the cardinality estimator, I've an option in the generator called:

```c#
// If SqlServer 2014 appears frozen / take a long time when this file is saved,
// try setting this to true (you will also need elevated privileges).
IncludeQueryTraceOn9481Flag = false;
```

You can set that to true, and it will append `OPTION (QUERYTRACEON 9481)` to the SQL queries.
This works for me, but I also have admin rights. I wonder if its worth considering `ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION=ON` instead?

**Comment by ErikEJ** [comment]
yes, that works for SQL 2016 and SQL Azure V12: https://msdn.microsoft.com/en-us/library/mt629158.aspx?f=255&MSPPError=-2147217396 - and does not require the same level of admin rights
