### ISSUE TITLE
Table per Type Code Generation - continued

### ISSUE THREAD

**Issue by siphillipson** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#181]
In issue #102 jsmarsch asked about table-per-type code generation, and Kasper888 provided a very useful reply which has enabled me to make some progress.

Using the approach suggested by Kasper888, my generated _derived_ classes have their Id properties removed (as they are inherited from the base class) and the navigation properties removed - both as expected.

However, when I run the generator, the derived classes aren't added to the DbContext, and each class contains the following comment:

`// The table '<table name>' is not usable by entity framework because it`
`// does not have a primary key. It is listed here for completeness.`

I would have expected that because the derived classes _do_ have a primary key - inherited from their base class - that the derived classes _would_ be usable by EF?  Am I possibly missing a step here?

Many thanks.

(The simple example tables that I'm using are in [this StackOverflow question](http://stackoverflow.com/questions/41472739/table-per-type-inheritance-with-the-entity-framework-reverse-poco-generator))

**Comment by siphillipson** [comment]
Just as a follow-up on my question:

My tables consist of a base table - `LogBase` - and a derived table, `ErrorLog`.

If I attempt to query the database using:

`var errorLogs = db.LogBases.OfType<ErrorLog>().ToList()`

the resulting error message contains the line `Invalid column name 'Discriminator'`

.. which seems to indicate that EF considers the inheritance mode to be the default [table-per-hierarchy](https://weblogs.asp.net/manavi/inheritance-mapping-strategies-with-entity-framework-code-first-ctp5-part-1-table-per-hierarchy-tph) rather than the intended table-per-type - so is there a way to tell EF that I'm intending to use TPT?

**Comment by sjh37** [comment]
There was a fix in #167 which is now live today (5th Jan) in version 2.27.0 which should fix this. Update to the latest version.
The bug was to do with not marking the table as having a primary key if the column was hidden.

**Comment by siphillipson** [comment]
Many thanks - this has sorted the issue for me.
