### ISSUE TITLE
that the access modifier of a specific column is "override"

### ISSUE THREAD

**Issue by piqm** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#185]
I want in my poco file, that the access modifier of a specific column is "override"

**Comment by sjh37** [comment]
You would do that in the WritePocoColumn() callback in your database.tt file.

Replace the "public" text in c.Entity with "public override" for the columns you need.

**Comment by sjh37** [comment]
I see you are doing it the other way,
https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/compare/master...cux:patch-2

Which is a good idea too.

**Comment by piqm** [comment]
Can you apply this change to the next version.?

**Comment by sjh37** [comment]
Add in some comments inside of `UpdateColumn = (Column column, Table table) =>` to show a little example.
Create a pull request when you are ready.

**Comment by sjh37** [comment]
Released in v2.28
