### ISSUE TITLE
Removing "-" from classes generated from table

### ISSUE THREAD

**Issue by jacobymatt** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#194]
Hi, I have a number of tables with hyphens in them and then dates (numbers) after the hyphen. The generator is creating their corresponding classes just like the table name which then causes build errors because of the hyphen-number combination. How do configure this to simply remove the hyphens from those objects?

**Comment by jacobymatt** [comment]
Apologies, i just got it to work correctly. This was the solution in the .tt file:

// Table renaming *********************************************************************************************************************
    
    TableRename = (name, schema) =>
    {        
        name = name.Replace("-", "");
}

**Comment by sjh37** [comment]
Glad you got it sorted

**Comment by hero3616** [comment]
I have the same dash/hyphen problem but only for the SP ReturnModels. How can I run same Replace("-", "") on ReturnModel class property names?

**Comment by hero3616** [comment]
Found it. In case anyone would need the same,
In Core.ttinclude (or EF.Reverse.POCO.v3.ttinclude in newer versions) file
public static readonly Func<DataColumn, string> WriteStoredProcReturnColumn
added
columnName = columnName.Replace("-", "");
