### ISSUE TITLE
Adding View to dbContext

### ISSUE THREAD

**Issue by dyardyGIT** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#195]
I have a view without a primary key.  I suspect this is the reason why the view is not being added to the generated dbContext.  How best can I include a view so that my generated dbContext has a reference to the view data?
thx

**Comment by sjh37** [comment]
Hi Dyardy,
You need at least one of the fields to be `NOT NULL`.

**Comment by dyardyGIT** [comment]
Thanks.  The solution for me was to refashion my view definition using RowId like the following

This will create a non-null RowId for each row in the result.

SELECT   ISNULL(ROW_NUMBER() OVER(ORDER BY P1), -1) AS RowID,   P1 AS Code, P3, P2
FROM            dbo.BigTable
WHERE P1 IS NOT NULL
