### ISSUE TITLE
Ran into trouble with old build server

### ISSUE THREAD

**Issue by RalphMack** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#196]
My team is using VS2015 in our daily development, targeting Framework 4.5.1 - 4.5.2 as soon as our servers are brought up to date (or at least a date :)). The build server, managed by the larger organization, is running an older TFS, and hence building against C#5 rather than C#6. Perhaps surprisingly, this hasn't burned us - until today. 

I recently updated my EF stuff to get rid of the old .edmx in preparation for migration to EF7 after .NET Standard 2.0 comes out and have finally started using this reverse POCO generator. I love it. It gives me lots of things I've been wanting and will make our development much easier to maintain. However, when we submitted for build, we got the following errors (sanitized slightly to avoid product identification):

'Xxxx.Infrastructure.Data.FakeXxxxToolsEntities.ChangeTracker.get' must declare a body because it is not marked abstract or extern. Automatically implemented properties must define both get and set accessors.
'Xxxx.Infrastructure.Data.FakeXxxxToolsEntities.Configuration.get' must declare a body because it is not marked abstract or extern. Automatically implemented properties must define both get and set accessors.
'Xxxx.Infrastructure.Data.FakeXxxxToolsEntities.Database.get' must declare a body because it is not marked abstract or extern. Automatically implemented properties must define both get and set accessors.

The root problem is that C#6 allows using a { get; } property whose value is set in the constructor, much like a readonly, but C#5 does not.

To work around it, I turned off the unit test generation piece, and the rest of everything built, but I was looking forward to working with that. It offers a potential solution for some problems that have vexed us for quite a while. Is there any way to get the POCO generator to generate C#5 compliant fakes?

**Comment by sjh37** [comment]
If I set my compiler to C#5 I get the following
```
Error	CS8026	
Feature 'readonly automatically implemented properties' is not available in C# 5.  
Please use language version 6 or greater.
```

**Comment by sjh37** [comment]
Hi Ralph, Pull the latest code from the repo, and make the same changes to your `EF.Reverse.POCO.ttinclude` file.
I had to fall back to how C# 5 did it, with backing fields. I kept the backing fields public so you can set them up with moq's, etc in your unit tests.

```c#
public System.Data.Entity.Infrastructure.DbChangeTracker _changeTracker;
public System.Data.Entity.Infrastructure.DbChangeTracker ChangeTracker { get { return _changeTracker; } }
public System.Data.Entity.Infrastructure.DbContextConfiguration _configuration;
public System.Data.Entity.Infrastructure.DbContextConfiguration Configuration { get { return _configuration; } }
public System.Data.Entity.Database _database;
public System.Data.Entity.Database Database { get { return _database; } }
```

This fix will be in the next release. Which will be next week.

Let me know if this solves your problem.

**Comment by RalphMack** [comment]
Wow! That was a phenomenally quick response and the issue was admittedly a "Doctor, it hurts when I do this" kind of thing (followed by a contortion vaguely reminiscent of a pretzel). Thank you for looking into this one at all!

**Comment by sjh37** [comment]
I'll close this as it will be in the next release.

**Comment by sjh37** [comment]
Released
