### ISSUE TITLE
Could you please pass extra StoredProcedure parameter to StoredProcedureRename

### ISSUE THREAD

**Issue by ichalyshev** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#198]
Func<string, string, StoredProcedure, string> StoredProcedureRename;

I have no idea how Inflector.ToTitleCase will rename my stored proc. I think it is more convenient to rename sp name by sql sp name (sp.Name like in StoredProcedureReturnModelRename).

**Comment by sjh37** [comment]
Done.
This will be in the next release.

**Comment by sjh37** [comment]
Released.
