### ISSUE TITLE
Could you make DbContextInterfaceName allow null?

### ISSUE THREAD

**Issue by ichalyshev** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#199]
I am not using DbContextInterfaceName. And want to not generate dependency in my dbContext, but geter

string DbContextInterfaceName {get {return _dbContextInterfaceName ?? ("I" + DbContextName);} 

will force to generate interface for db context.

Could you make DbContextInterfaceName allow null, and change the way how db context class is generated

`public <# if(MakeClassesPartial) { #>partial <# } #>class <#=DbContextName#> : <#=DbContextBaseClass#>, <#=DbContextInterfaceName#>`

f.e.

`    public <# if(MakeClassesPartial) { #>partial <# } #>class <#=DbContextName#> : <#=DbContextBaseClass#><# if(DbContextInterfaceName != null) { #>, <#=DbContextInterfaceName#> <# } #>`

**Comment by sjh37** [comment]
This was already completed as part of #189 and #190.
The code has not yet been released, but will be in the next version which will be this week

**Comment by ichalyshev** [comment]
Thanks a lot! Great project
