### ISSUE TITLE
possible missing schema in SP

### ISSUE THREAD

**Issue by Sako73** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#2]
I had a stored procedure in a non-default schema, and it was written without the schema prefixed in the EXEC statement.  I had to add "<#= sp.Schema>." to line 257 in the EF.Reverse.POCO.ttinclude to get it to import correctly.

Thanks.

**Comment by sjh37** [comment]
It should already be doing this. What version are you using ?

**Comment by Sako73** [comment]
v2.10.1 is the file header

**Comment by sjh37** [comment]
This bug was fixed in a later version. Upgrade the generator to the latest version.

**Comment by Sako73** [comment]
Thank you!
