### ISSUE TITLE
Warning when building a project

### ISSUE THREAD

**Issue by NaomiN** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#20]
We're getting this warning:

'ISiriusSqlContext.SaveChanges()' hides inherited member 'IContext.SaveChanges()'. Use the new keyword if hiding was intended.

---

We defined 

DbContextInterfaceBaseClasses = "IContext";    // Specify what the base classes are for your database context interface

and that interface has

 public interface IContext : IDisposable
    {
        IDbSet<T> Set<T>() where T : class;
        int SaveChanges();
and other methods
}

What needs to be changed to avoid the warning?

**Comment by sjh37** [comment]
You should not need to declare `int SaveChanges();` in your interface as that is already created in the `ISiriusSqlContext` interface class.

**Comment by NaomiN** [comment]
Is there any other way to solve it (I'll try commenting this out in our interface but it may happen with other methods and besides, what if this interface is used for other purposes being a base class)? 

BTW, commenting this line out indeed got rid of the warning.

**Comment by sjh37** [comment]
I can't wait to finish the Pluralsight course I'm working on as it describes this in detail. 
I'll let you know when it's available, but I'm guessing that it will be a month away.

**Comment by NaomiN** [comment]
Yes, I already advertised it today in our developer's daily meeting :) We'll be waiting it. Thanks again.

**Comment by NaomiN** [comment]
Did you add SaveChanges method recently? When I tried to push that local change to our server I got

RepositoryBaseWithList.cs (276): 'Siriusware.Data.ISiriusSqlContext' does not contain a definition for 'SaveChanges' and no extension method 'SaveChanges' accepting a first argument of type 'Siriusware.Data.ISiriusSqlContext' could be found (are you missing a using directive or an assembly reference?)
