### ISSUE TITLE
Support for .NET Core please

### ISSUE THREAD

**Issue by nrogoff** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#200]
Would be great to have .NET Core support for this excellent tool.

**Comment by ErikEJ** [comment]
Possible duplicate of https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/issues/5

**Comment by sjh37** [comment]
Yes, this is a duplicate of #5 so will close this issue.
