### ISSUE TITLE
Adding Second Database with Unit Testing DbContext fails

### ISSUE THREAD

**Issue by Eric-Hanson** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#202]
We're just starting with the Reverse POCO Code First Generator - it seems great. 

However, with multiple database.tt definitions, the second with `AddUnitTestingDbContext = true;` causes many errors such as:
  `CS0756 A partial method may not have multiple defining declarations`
  `CS0579 Duplicate 'System.CodeDom.Compiler.GeneratedCode' attribute` (repeated four times)
  `CS0101 The namespace '`{mycompany.dept.Data}`' already contains a definition for 'FakeDbAsyncEnumerable'`
  `CS0101 The namespace '`{mycompany.dept.Data}`' already contains a definition for 'FakeDbAsyncEnumerator'`
All 44 of the errors are on the alphabetically second database's related .cs file.

The error surprising since the project uses custom namespaces for each database. For example:
  `PocoNamespace = "`{mycompany.dept}`.Data.DataDb";`
  `ContextNamespace = "`{mycompany.dept}`.Data.DataDb";`
  `UnitOfWorkNamespace = "`{mycompany.dept}`.CS.Data.DataDb";`
  `PocoConfigurationNamespace = "`{mycompany.dept}`.CS.Data.DataDb";`
and 
  `PocoNamespace = "`{mycompany.dept}`.Data.MainDb";`
  `ContextNamespace = "`{mycompany.dept}`.Data.MainDb";`
  `UnitOfWorkNamespace = "`{mycompany.dept}`.CS.Data.MainDb";`
  `PocoConfigurationNamespace = "`{mycompany.dept}`.CS.Data.MainDb";`

Do you have any suggestions?

**Comment by sjh37** [comment]
Hi Eric,
Either:

1. Add the reverse generator again into a sub folder, and hence it automatically gets a different namespace, or
2. Set the Namespace to something different on the second tt file using
```c#
Namespace = "fred"; // Override the default namespace here
```

**Comment by sjh37** [comment]
Any problems, please let me know :-)

**Comment by Eric-Hanson** [comment]
Great solution. Thank you. Works much better in our model with different folders than in one folder with unique namespaces. 

One unrelated issue is the FakeDataContext not implementing a property defined in the base context interface. If I drop the property, other parts of code fail since they need the property defined in the interface to compile. Can I extend the fake context to implement a static response for such a bool property?

Thanks again, Eric

**Comment by sjh37** [comment]
Yes. Just create a pull request and I will take a look at it. Thanks for contributing.

**Comment by Eric-Hanson** [comment]
Was able to create a partial for the fake context class and extend with the needed property. I will not be adding a pull request. I simply added the following partial class and property:
`public partial class Fake{MyName}Context {
  public bool IsConnected => true;
}`
Thank you again for your assistance.
