### ISSUE TITLE
CS0103- The name 'MyDbContextStaticPartial' does not exist in the current context	

### ISSUE THREAD

**Issue by mwoffenden** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#205]
We are seeing this in our auto generated DBContext.  

`        static MyDbContext()
        {
            System.Data.Entity.Database.SetInitializer<MyDbContext>(null);
            MyDbContextStaticPartial(); // Create the following method in your partial class: private static void MyDbContextStaticPartial() { }
        }`

MyDbContextStaticPartial is not defined anywhere, so I can't compile.

If I add the empty method class as suggested by the comment, the issue goes away.  But of course the next time I generate POCO classes, the issue comes back.

What's the permanent fix for this?

**Comment by sjh37** [comment]
:-)
You need to create this somewhere else, in another file. That way the generator won't overwrite it next time.

**Comment by mwoffenden** [comment]
Ok, but it looks like a bug in the core code that we used "right out of the box".  This did not occur in the previous version (2.24.0).

**Comment by sjh37** [comment]
Yes, That is because this is new functionality, which allows you to perform actions within a static context constructor.

**Comment by AndyCadley** [comment]
Could the generator not automatically add:
```csharp
static partial void MyDbContextStaticPartial()
```
as it does for other partial methods? That way you wouldn't need to implement this if you didn't actually need it. Or am I missing something subtle?

**Comment by sjh37** [comment]
If it did, it would mean it would get overridden every time. Hence the need for you to add it yourself.
Alternatively, I could revert the code back and not allow people to perform initialisation in a static db context constructor.

**Comment by nilcat** [comment]
I stumbled on this when I tried to make the classes partial - perhaps there should be a switch for this as I now have a file with no code
