### ISSUE TITLE
TableValueFunction entries are not generated

### ISSUE THREAD

**Issue by davidsk** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#21]
This relates to v2.19.0.  The parameter is set to true in the .tt file and the EntityFramework.CodeFirstStoreFunctions package is installed but there are no tvf methods in my context

**Comment by sjh37** [comment]
Whoops, that should be false. 
Thanks for spotting this.

**Comment by davidsk** [comment]
I meant that I changed the value to true in order to generate the tvfs, but no tvf methods are generated...

**Comment by sjh37** [comment]
Yes, I just checked, and it was false, which is how the default should be.

**Comment by sjh37** [comment]
Did you:
install-package EntityFramework.CodeFirstStoreFunctions

**Comment by davidsk** [comment]
yup.

**Comment by sjh37** [comment]
ok, let me test it... 2 mins..

**Comment by sjh37** [comment]
do you have skype? It's working ok for me.
simon_hughes

**Comment by sjh37** [comment]
or join.me so we can screen share

**Comment by sjh37** [comment]
try https://join.me/958-015-753

**Comment by sjh37** [comment]
I have updated the comment in the tt file which means that for TVF you **also** need to set `IncludeStoredProcedures = true`

``` c#
IncludeTableValuedFunctions = false; // If true, you must set IncludeStoredProcedures = true, and install the "EntityFramework.CodeFirstStoreFunctions" Nuget Package.
```

This will be in the next release.
