### ISSUE TITLE
wrong casing in switch statement

### ISSUE THREAD

**Issue by ErikEJ** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#213]
Should this not (and the line below) be lower case?

https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/blob/master/EntityFramework.Reverse.POCO.Generator/EF.Reverse.POCO.Core.ttinclude#L1127

**Comment by sjh37** [comment]
Thanks Eric. No idea how nobody spotted that.
Many thanks!

**Comment by sjh37** [comment]
This will be in the next release.
