### ISSUE TITLE
Wizard to configure the template to seperate Entities from DbContext and Configuration

### ISSUE THREAD

**Issue by feldrim** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#214]
I'm copying my comment from VS Marketplace.

> First, we had to reconfigure the template because of the layered architecture. Entity classes had to be moved under our shared Contracts project. DbContext and Configuration files stayed under the DbStore project. It would be awesome if I could do it using a wizard.

**Comment by sjh37** [comment]
This is not a plug-in to visual studio, but rather a T4 template, and hence can't have a wizard UI to guide you through the process. It's simple enough to setup how you want it without a wizard.

This project is designed to have the ability to separate the contracts, context and config files to either be in separate folders, or in separate projects. Watch the pluralsight course to see how this is done.

However, I created a wizard to help with table filtering, which is available at https://efreversepocoui.codeplex.com/

**Comment by ErikEJ** [comment]
Simon, would it be possible for you to move the EF UI to github - I just tried creating a PR and failed due to hg not working with codeplex (any more??)

**Comment by sjh37** [comment]
@ErikEJ  Done:
https://github.com/sjh37/EntityFramework-Reverse-POCO-Generator-UI

**Comment by ErikEJ** [comment]
NICE! 👏

**Comment by ErikEJ** [comment]
Ooops, when git cloning and branching, something odd with line endings?

**Comment by ErikEJ** [comment]
I will just fix as first commit in my PR!

**Comment by sjh37** [comment]
Thanks :-)
