### ISSUE TITLE
Integer suffix added incorrectly

### ISSUE THREAD

**Issue by davidsk** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#22]
I have a table named t_Function.  The "t_" prefix is removed using the TableRename function but when the code is generated, the file and class are both named Function1.

At first I thought function was a reserved word but that doesn't seem to be the case.

**Comment by davidsk** [comment]
Got it - there's a view called v_OT_CORE_Function and the table renaming function returns "Function" for both, so there is a naming clash.  However, I have set the views NOT to be generated - I assumed that this would exclude views from naming considerations

**Comment by sjh37** [comment]
I thought I saw the problem, but it wasn't as it does already check the exclude filters before it renames.

**Comment by sjh37** [comment]
Can you try this for me.

at line 1670, it says

``` c#
tableName = tableRename(tableName, schema);
```

Can you add the following below that line:

``` c#
if(tableFilterExclude != null && tableFilterExclude.IsMatch(tableName))
    continue;
if (tableName.Contains('.'))    // EF does not allow tables to contain a period character
    continue;
```

**Comment by davidsk** [comment]
Added those lines but it's still adding the suffix.

For this particular case, ignoring views (for the purpose of determining whether a name is duplicated or not) would solve this.  I noticed that you are tracking whether the table is a view or not and thought you could test that against the IncludeViews value...but it isn't available.  Could the IncludeViews parameter be passed to the ReadSchema method?

**Comment by sjh37** [comment]
Yes, I think that is the correct solution, pass in the includeviews parameter. I'll do that...

**Comment by sjh37** [comment]
Thanks for your help and clarity.
All fixed. This will be in the next release.
See this [changeset](https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/commit/6dbe26d884b436d22f4a1a860aebcf8742dd70ab).
