### ISSUE TITLE
TableValuedFunctions return entities

### ISSUE THREAD

**Issue by abraham-chahla** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#220]
Hi Simon.

Could you implement this functionality: 
StoredProcedureReturnTypes.Add("SalesByYear", "SummaryOfSalesByYear"); 
but for Table-Valued-Functions?

Thank you in advance!

**Comment by sjh37** [comment]
No need. It works on TVF functions already.

I did a test with
```c#
StoredProcedureReturnTypes.Add("CsvToInt", "dummy_csv_rm");
```

and ended up with
```c#
// Table Valued Functions
System.Linq.IQueryable<dummy_csv_rm> CsvToInt(string array, string array2);
```

**Comment by abraham-chahla** [comment]
Thank you Simon! I will give this a try and let you know.
Thank you again for this!
