### ISSUE TITLE
Invalid XML Summary Block Comments Can Be Generated

### ISSUE THREAD

**Issue by StevenBonePgh** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#221]
With setting IncludeExtendedPropertyComments = CommentsStyle.InSummaryBlock and if an extended property contains an ampersand, less than, or greater than (&, <, or >) the XML Comment is generated without escaping the characters (as required).  If compiling with XML Comment Generation enabled, compiler warnings are emitted as a result.

One possible fix is:
```
// In file *.tt, Func<Column, string> WritePocoColumn
// change this:
WriteLine("        /// {0}", c.SummaryComments);
// to:
WriteLine("        /// {0}", System.Security.SecurityElement.Escape(c.SummaryComments));
```

The downside of this approach is that it over-aggressively escapes single and double quotes, which are legal in an element node value (such as the `<summary>` block).  When reading the comment in-line it looks weird because of this, but it is unescaped properly when IntelliSense renders it.

There are other ways to do this that you may select as different/better approaches to solve this: [Different Ways to Escape XML String in C#](http://weblogs.sqlteam.com/mladenp/archive/2008/10/21/Different-ways-how-to-escape-an-XML-string-in-C.aspx)  As such, I didn't wish to submit a pull request as to defer the solution to you.

**Comment by sjh37** [comment]
@StevenBonePgh How about stripping these characters instead of escaping them?

**Comment by Chris3773** [comment]
I don't think stripping the characters would be the best approach as it could change the meaning of the comment.

You could create a function to only escape (&, <, and >) or use a XML escaper and have the quotes  encoded in the source.  I don't see this as a big deal breaker as you would be using IntelliSense and the Doc generator more then you would be looking at the generated code.

**Comment by StevenBonePgh** [comment]
I agree with @Chris3773 and we should not strip them. Unless you are against the over-aggressive escapes for single and double quotes, I'd just implement my example with the quick and dirty `SecurityElement.Escape`.  Most people likely either use the build output with Sandcastle or via IntelliSense, so I doubt anyone would complain about it. If necessary, yeah, we could write a specialized escaper or create the summary node through XmlWriter (but then you need to deal with which encoding to use, etc.) but first I'd want to make sure proper comments are emitted.

**Comment by sjh37** [comment]
For now, unless anyone complains I think we should just go with the `SecurityElement.Escape` method. We can look at it again if there are further unforeseen problems.

**Comment by sjh37** [comment]
Thanks guys, This will be in the next release.
