### ISSUE TITLE
Problem using Entity Framework PowerTools

### ISSUE THREAD

**Issue by pablorivassanchez** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#222]
Hello,

I'm using EntityFramework Reverse Poco and when I try to use the Entity Framework PowerTools to View the entity data model from the db context I get the following error. Also happend the same when I try to generate Views.

I Attach the file.
![error](https://cloud.githubusercontent.com/assets/20487828/22972724/2ce346a2-f37b-11e6-9c5c-4f0cab597978.JPG)

**Comment by sjh37** [comment]
The code-first code generated is correct and accurate. There is obviously a bug in the power tools, which is nothing I can fix. Create a bug report for them at their site.

**Comment by ErikEJ** [comment]
@pablorivassanchez  Hi, I have tested this with "latest" PowerTools from here https://github.com/aspnet/EntityFramework6/pull/154 , and have no issues with a DbContext generated by this template. In order to be able to reproduce this, you have to share your code.

**Comment by pablorivassanchez** [comment]
Hello @ErikEJ and @sjh37 . Thank for your answers. The problem was that even I have the last powertools I didnt have the Entity Framework 6 Tools for Visual Studio 2012 & 2013. It seems that if you dont have that you can not use the powertools. Sorry for post that here but I searched by internet and I didnt find anything about that error.

**Comment by ErikEJ** [comment]
Good info, why are you still using VS 2012/2013?

**Comment by pablorivassanchez** [comment]
It's in my job. They only have license for VS 2013 Profesional.

**Comment by sjh37** [comment]
Then you will have to look at the code to understand the model.
Alternatively, use SQL Server to create a database diagram for you so you can see how your model all fits together.

**Comment by ErikEJ** [comment]
@pablorivassanchez OK, so after installing the EF 6 Tools in VS 2013, the PowerTools work as expected, is that correctly understood?

**Comment by pablorivassanchez** [comment]
Exactly after install EF 6 Tools that error dissapeared. Yeah we normaly have also database diagram but the problem is, the project has a legacy database and sometimes we have to force the foreign keys in the dbcontext by using fluent api so it's nice to see a picture of the relations.
