### ISSUE TITLE
Display attribute configuarble in the database?

### ISSUE THREAD

**Issue by airomero** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#223]
Hi, the Display attribute that is generated from the column name could be configured in the database, in the **Description** filed of the **Column Properties** in Sql Server. So if you enter the **Description** in the **Column Properties** it is used as the Display attribute. If you don´t enter it then it uses the display attribute as it does today (from the column name). I've already done it for my use. Do you see it valuable to introduce it?? It is specially usefull when you have columns with ugly names and teh generated Display attribute is ugly too.

**Comment by Chris3773** [comment]
The extended property MS_Description would not be suitable for most use cases to be used as the Display attribute. The Display attribute are used mostly for displaying as field labels and most uses for MS_Description are for describing the field.

One solution maybe to reading from a new extended property like `DisplayName` to be used as the Display attribute. There are no standards for extended properties so you would need to know the generator is looking for these properties. Then there is also the head arc of writing the sp_addextendedproperty code by hand.

**Comment by ErikEJ** [comment]
@Chris3773 An option could be to tell the generator what column metadata property to get the description from...

**Comment by airomero** [comment]
I thought that the Description property would be fine because it is always there (you don't have to define an extended property), I've never saw it being used, it is persisted in the database so it always regenerates and it is fast. I modified 10 lines of code and is working for me. 

If you don't use it then it takes the column name as always. I find it usefull when your columns have ugly names (my case) or when you work in languages other than english where you have gramatical rules that don`t apply to a column name in the database, but when you show a information to the user (validation, label, etc) you have to apply those gramatical rules. I just explain why i use this way and it works. But if you find it usefull at all then dismiss this "Issue" ;) 

I thought that maybe it'd be usefull to store the "pretty name" of the column in the column description and use it as the display name if it has a value.

**Comment by sjh37** [comment]
Many people have wanted to (mis)use the Description property for lots of different reasons, all of which would compete with each other. Therefore I am keeping it as documentation only.

If you want to rename a few columns, have you looked at using the `UpdateColumn` callback?
example:

```c#
UpdateColumn = (Column column, Table table) =>
{
    if (column.NameHumanCase == "SomeHorribleName")
        column.NameHumanCase = "ABetterName";
   ...
    return column;
};
```
