### ISSUE TITLE
Use with Mehdi's DbContextScope?

### ISSUE THREAD

**Issue by Eric-Hanson** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#225]
When using this EF Reverse POCO Code First Generator, is there any advantage to also implementing Mehdi El Gueddari's implementation of the [DbContextScope](https://github.com/mehdime/DbContextScope) pattern for managing context? Are the two even compatible?

**Comment by sjh37** [comment]
Hi Eric.

They should work nicely together.
However, I don't use it as I've always trusted the lifetime of database contexts to a tried and trusted **Inversion Of Control** container like AutoFac or CastleWindsor.

**Comment by Eric-Hanson** [comment]
Thank you for the IoC suggestions.
