### ISSUE TITLE
Question about FakeDbContext

### ISSUE THREAD

**Issue by pablorivassanchez** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#226]
Hello,

I have a little problem trying to using the FakeDbContext that is generated with the Template. I am doing some relations with DataAnnotation (forcing a foreign key), here is an example:

```c#
public class Program
{
public int ProgramId{get;set;}
public int? TypeId{get;set;}
[ForeignKey("TypeId")]
public Type ProgramType{get;set;}
}

public class Type
{
public int TypeId{get;set;}
public string Name{get;set;}
}
```

The relation is not in the real database (these are not the tables but are similars). When I'm doing the unit test like that:

```c#
using (var context = new FakeDbContext())
 {
                context.Type.Add(new Type() { TypeId= 1, Name= "Test" });
                context.Program.Add(new Program() { ProgramId= 125, TypeId= 1});
                var resultado = context.Program.Include(x=>x.ProgramType).ToList();         
}
```

I don't get the Type pulled into ProgramType. It is possible to make that work like that?

Thanks in advance.

**Comment by sjh37** [comment]
Hi.
Try turning data annotations off, and see if that works as expected.

**Comment by pablorivassanchez** [comment]
Hi,

I have both false:

UseDataAnnotations = false; // If true, will add data annotations to the poco classes.
    UseDataAnnotationsSchema = false; // UseDataAnnotations must also be true. If true, will add data annotations schema to the poco classes.

Maybe it is not possible to simulate the relation in the fake dbContext?

Thanks.

**Comment by sjh37** [comment]
It's basically linq to objects, so it should.

Try this style instead:
```c#
var t = new Type() { TypeId= 1, Name= "Test" };
context.Program.Add(new Program() { ProgramId= 125, ProgramType = t });
var resultado = context.Program.Include(x=>x.ProgramType).ToList();
```

**Comment by pablorivassanchez** [comment]
Yeah this way works but I wanted to know if it's possible to make it works without asign the object to the property so the dbcontext make the relation for me.

**Comment by sjh37** [comment]
I don't know. That's down to Entity Framework itself. Ask over on the EF support pages.
From the code generated point of view, everything is as it should be, and exactly what you would of created by hand had you done it manually.

I'll close this case as its something out of my control, and down to EF itself.
I hope you find an answer Pablo, and if you do, please post it here and I could make a wiki out of it.
If its something that the generator can help with, then please let me know.
