### ISSUE TITLE
Bad Code generated when SP Parameters start with a number

### ISSUE THREAD

**Issue by mcurrycl** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#227]
I have a number of Stored Procedures that I have inherited where the return field names start with a number:

30DayBal, 60DayBal, etc

When the tool generates my Stored Procedures, it creates invalid C# code by starting the properties with a number, also:

        public System.Decimal? 30DayBal { get; set; }
        public System.Decimal? 60DayBal { get; set; }
        public System.Decimal? 90DayBal { get; set; }

Can this be worked around somehow?

Thanks for a great tool.

**Comment by sjh37** [comment]
Unfortunately stored procedure return models must match exactly the return column names returned, and therefore cannot be renamed. If they were renamed, Entity Framework would not map the column data back. Quite annoying.

Anyway, the workaround for this is to wrap this stored procedure by another stored procedure which calls it, and returns the column names with a different name, and exclude the stored procedure which returns invalid column names.
