### ISSUE TITLE
Multiple Columns as Foreign Key/Navigation Properties to a Single Person Table?

### ISSUE THREAD

**Issue by Eric-Hanson** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#228]
Where I have a single table joining on three Foreign Key columns to a single People table. Our related queries often use includes to bring in the related rows. These navigation properties create exceptions "Invalid column name" listing column name '{table name}_{column name}'.

Is this supported by version 2.28.0 or the current version?

Reviewing previous posts, I noticed your comment "If you want to keep two mapping tables.. remove ... use them as plain tables, and simply use joins in your LinqToSql by setting: UseMappingTables = false;"

Setting UseMappingTables to false looks like it will require significant work. Are there any alternatives to specify the properties or make this situation work correctly?

**Comment by sjh37** [comment]
Hi @Eric-Hanson It should work right out of the box. I use includes all the time.

Can you list the table which has the problems both in terms of SQL Creation, and the EF configuration class for it so I can check it has been generated correctly and matches what is in SQL Server.

**Comment by Eric-Hanson** [comment]
Asking permission to share, I'll have to get back with you.

**Comment by Eric-Hanson** [comment]
Requested upgrade to version 2.29.0 to verify it is not corrected and simplifying where I can in our configuration.

**Comment by fjrodriguezcom** [comment]
I think I have the same problem. I have a table Parent with some fields and two fields of them are ChildId and ChildFinalId pointing to table Child. When I try to save a Parent entity, I get two errors The column name 'Child_ChildId' is not valid . The column name 'Child_ChildId1' is not valid.
I can go ahead if I comment reverse navigation properties from Child to Parent. There is a weird ChildFinal property pointing to Parent entities, and the other have a Parent_ChildId name.

**Comment by sjh37** [comment]
@fjrodriguezcom Thanks for this. I'd like to replicate the problem.
Can you list the table which has the problems both in terms of SQL Creation, and the EF configuration class for it so I can check it has been generated correctly and matches what is in SQL Server.

**Comment by Eric-Hanson** [comment]
@sjh37 Found removing custom inherited context and interface base classes corrected the issue.

**Comment by sjh37** [comment]
Thanks for letting me know
