### ISSUE TITLE
GenerateSeparateFiles=true generates empty context class.

### ISSUE THREAD

**Issue by schungx** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#23]
When setting `GenerateSeparateFiles` to `true` in order to generate one class per file, the main context class generated will be empty.

Setting `GenerateSeparateFiles` to `false` makes it work right, but all the classes are merged into one file.

**Comment by sjh37** [comment]
I'm pretty sure there is nothing I can do about this. This file is the starting point for the generator before it can specify the next file to use.
I've not invested any real time in looking at it.
Let me know if you manage it, and create a pull request.

**Comment by schungx** [comment]
Well, it is OK that the file is empty.  But should there at least be a file that contains the database context?

Right now, the code doesn't compile because the context class is missing...

**Comment by sjh37** [comment]
The context will be there somewhere, It depends on how you named it.

**Comment by schungx** [comment]
Well, I'm quite certain that once `GenerateSeparateFiles` is set to `true`, the only files created are the entity class files, the entity mapping files (they're in pairs), and the context file.  The context file has an empty context with the correct name.  There is no context code anywhere.

If `GenerateSeparateFiles` is set to `false`, then the context code is inserted correctly.

**Comment by andygjp** [comment]
Does the name of your tt file match the name of the DbContextName?

Occasionally I found the context wasn't created, but after I changed the name of my tt file it hasn't happened since.

My tt file is called KbGen.tt and the DbContextName is set to Kb. When I generate the context I get a KbGen.cs file which, for all intents and purposes, is empty and a Kb.cs (the context code file).

**Comment by schungx** [comment]
@andygjp, That's IT!!!  You are God!

You are absolutely right.  I have the name of the `tt` file the same as my context, so the two files collide, causing the context file not to be generated.

Once I renamed the `tt` file to something else, the context file is generated correctly.

@sjh37, This probably should be mentioned in the docs... This can get very frustrated to trouble-shoot!

Thanks again!

**Comment by andygjp** [comment]
:smile:

**Comment by sjh37** [comment]
Thanks Andy

**Comment by j4adev** [comment]
I fell into this trap as well.  Maybe it's worth adding a comment in the tt file that the tt filename and the context name need to be different when using the generate separate files feature.

Thanks for a great tool!

**Comment by sjh37** [comment]
Released.
