### ISSUE TITLE
Table value functions are not being generated

### ISSUE THREAD

**Issue by Chris3773** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#230]
With version v2.29.0 table value functions are not being generated.

Looks like the change added with `ed86628 ` is removing valid table value functions. A return column that is a NVARCHAR is returning as `DataType.IsClass = true` which is removing the function.

**Comment by sjh37** [comment]
Thanks Chris.
Fixed. See the code change above.
This will be in the next release.

**Comment by sjh37** [comment]
Released
