### ISSUE TITLE
Issue with stored procedures

### ISSUE THREAD

**Issue by siddzie** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#233]
This is a very useful tool and I use it in my project everyday. But I am encountering a very strange issue with SPs. I am unable to generate files for SPs belonging to user defined schema and also not all SPs are generating files for dbo schema.

For example: I have a SP named [ProjectManagement].[uspExportProjectAudit]. THe generator is unable to create files for it. Not even when I compile it in dbo schema.

Here is the excerpt of the tt file:
```c#
IncludeStoredProcedures = true;
....
SchemaFilterExclude = new Regex("Staging|Assessment");
	SchemaFilterInclude = null;
	TableFilterExclude = null;
	TableFilterInclude = null;
	ColumnFilterExclude = null;
....
StoredProcedureFilter = (StoredProcedure sp) =>
	{
		// Example: Exclude any stored procedure in dbo schema with "order" in its name.
		//if(sp.Schema.Equals("dbo", StringComparison.InvariantCultureIgnoreCase) && sp.NameHumanCase.ToLowerInvariant().Contains("order"))
		//    return false;
		if(sp.Schema.Equals("dbo", StringComparison.InvariantCultureIgnoreCase))
		{
			return false;
		} 
		return true;
	};
```
Is there any special rule for SPs? What am I missing?

**Comment by sjh37** [comment]
Do any of the return columns have a space in it? If so, it cannot be used.

Your code:
```c#
  if(sp.Schema.Equals("dbo", StringComparison.InvariantCultureIgnoreCase))
  {
      return false;
  } 
```
will exclude all stored procedures in the "dbo" schema.

However, it should create a mapping for [ProjectManagement].[uspExportProjectAudit] stored procedure. One thing though, you cannot map to a stored procedure which has a return column with a space in it.

**Comment by siddzie** [comment]
Yes the return columns had space in it and that also explains why when I try to generate files for all SPs in dbo schema, it doesn't generate all. 

Thanks a lot Simon!
