### ISSUE TITLE
Cannot generate base class for Stored Procedure Return Model POCO class

### ISSUE THREAD

**Issue by siddzie** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#234]
Hi,

Reverse POCO tool seemingly unable to generate POCO class for Stored Procedure Return Model with a inheritance from Base Domain Class.

I have following Code in the t4 template to generate the POCO files with inheritance.

	Func<Table, string> WritePocoBaseClasses = t =>
	{
		//if (t.ClassName == "User")
		//    return ": IdentityUser<int, CustomUserLogin, CustomUserRole, CustomUserClaim>";
		return " : Data.BaseDomainModel";
	};

It cannot generate the file with inheritance for SP return model, however it works for tables.

Please provide some guidance.

**Comment by sjh37** [comment]
No callback has been created for stored procedure return models. To add a base class, in `EF.Reverse.POCO.Generator` line 1139, change
```c#
    public <# if(MakeClassesPartial) { #>partial <# } #>class <#= spReturnClassName #>
```
to
```c#
    public <# if(MakeClassesPartial) { #>partial <# } #>class <#= spReturnClassName #> : Data.BaseDomainModel
```

**Comment by siddzie** [comment]
Thanks a lot Simon! It generates the file as desired.
