### ISSUE TITLE
Add [Required] Attribute to Non-Nullable Navigation Properties

### ISSUE THREAD

**Issue by cody1024d** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#236]
It seems that the [Required] Attribute is being added on normal columns that are non-nullable.  Is it possible in some way to add the same attribute to Navigation Properties (who's foreign keys are non-nullable)?

Here's an example:

```c#
public class Note {
    [Required]
    public int PersonId { get; set; }

.......

    [ForeignKey("PersonId")] public virtual Person Person { get; set; }
}
``` 

Also, I have tried updating the WritePocoColumn function, but this isn't getting called for Navigation Properties it seems, and ends up in duplicated [Required] attributes on the other properties.

**Comment by sjh37** [comment]
Done. This will be in the next release.

**Comment by cody1024d** [comment]
@sjh37 Man you're quick.  Kudos to you.  Also, I'm sure you've heard this a bunch already, but your work on this, and this project in general is a lifesaver.

**Comment by sjh37** [comment]
That reminds me, got to get a release out today.

**Comment by cody1024d** [comment]
Hahaha perfect!  I'll be on the lookout for it

**Comment by sjh37** [comment]
Released

**Comment by cody1024d** [comment]
@sjh37 Just so you know, when I upgraded, and put this into practice, other users of this TT file will have to be aware of a "gotcha" with EF.  Basically, if you query for a Note object (as above), and never touch the Person property, then, because of lazy loading, that property is essentially null, and the save will be rejected.  Here is some additional resources on this:

http://stackoverflow.com/questions/6038541/ef-validation-failing-on-update-when-using-lazy-loaded-required-properties

I think in the end, this probably needs to be a configuration option, because if people upgrade, and re-generate their entities, it could cause bugs in their projects.

I wasn't aware of this behavior when I made this initial enhacnement request.  I still think it is useful, though (as it will help fail model validation when trying to post new objects, and creating sub objects, and all).

**Comment by sjh37** [comment]
Reading that article makes me think I should revert this back to not adding in the `[Required]` attribute on foreign keys.

**Comment by sjh37** [comment]
I have reverted the code change. Even making it optional could be problematic due to lazy loading. So best to leave off.

**Comment by cody1024d** [comment]
@sjh37 I feel as though with proper documentation, making it optional (and off by default) would solve the problem?  In my specific use case, not being able to set the Navigation Property to Required, will create a TON of boiler plate code in my use-case.  (Specifically a poorly architected, legacy DB)

**Comment by sjh37** [comment]
Ok, how about I make a callback so its customisable if you want it on/off, plus on which tables.

**Comment by cody1024d** [comment]
I don't mind that at all!  :)  Thanks @sjh37!

**Comment by cody1024d** [comment]
@sjh37 Any update on this?  Is this something you'd want help on?

**Comment by sjh37** [comment]
@cody1024d Would you be able to spend time and create a pull request for this? I'm maxed out all this week and next. Deadlines...

**Comment by cody1024d** [comment]
@sjh37 Yeah, I definitely can.  I plan on using this at my 9-5, so it's a high priority to me.  I've got some other stuff to work on right now, but will dig into this in the coming days to get it done

**Comment by sjh37** [comment]
Thanks

**Comment by cody1024d** [comment]
@sjh37 Ok, PR made for the change.  Let me know your thoughts!

**Comment by sjh37** [comment]
@cody1024d Previously I had
```c#
dataAnnotation = string.Format("[ForeignKey(\"{0}\"){1}] ",
   string.Join(", ", fkCols.Select(x => x.col.NameHumanCase).Distinct().ToArray()),
   fkCols.Any(x => x.col.IsNullable) ? string.Empty : ", Required"
);
```

Your last line is
```c#
foreignKey.IncludeRequiredAttribute ? ", Required" : string.Empty
```

So the variable IncludeRequiredAttribute needs setting somewhere, and people need a clue on where to use it and what it does.

You could use the callback `ForeignKeyFilter` to set `IncludeRequiredAttribute` although that function is about filtering, and doesn't have access to `fkCols.Any(x => x.col.IsNullable)`. How about a new call back, passing in foreignKey, fkCols, pkCols, and call it `ForeignKeyProcessing` ?

**Comment by cody1024d** [comment]
Yeah, that's fair.  I'll make those changes!  On that note, this is my first time editing a TT file (I'm actually predominantly a mobile dev lol), is there a way to test this new code generation logic?  Are there any test-entities and stuff included in this solution?

**Comment by sjh37** [comment]
Completed, this will be in the next release.

**Comment by cody1024d** [comment]
Thanks @sjh37.  I had a semi-completed solution, but comparing mine to yours will be a cool learning experience.

**Comment by cody1024d** [comment]
@sjh37 Any chance for a release soon?  Sometime next week would be super helpful

**Comment by sjh37** [comment]
I'll see what I can do 👍

**Comment by cody1024d** [comment]
@sjh37  I don't mean to pester, but any update on a release?  I guess I could just clone the project and pull in the ttinclude files, and update the tt files in a pinch?

**Comment by sjh37** [comment]
my bad. I'll get it done asap.

**Comment by sjh37** [comment]
Done. Will be available in less than 15 mins.

**Comment by cody1024d** [comment]
Right on!  Thanks @sjh37
