### ISSUE TITLE
Bug "Parameter names must be unique in the parameter collection" (Fix included)

### ISSUE THREAD

**Issue by aeslinger0** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#237]
If you join the same Sql Function more than once, you'll get an error message that includes this text:  "Parameter names must be unique in the parameter collection"

I was able to fix this by appending a guid to the parameter name. The consumer of the generated method will still see the nice parameter name.

For version 2.29.0, modify `EF.Reverse.POCO.Core.ttinclude` line 3539 to be:

> sb.AppendLine(string.Format("            var {0}Param = new System.Data.Entity.Core.Objects.ObjectParameter(\"{1}\" **+ guid**, typeof({2})) {{ Value = {3} }};",

Then in `EF.Reverse.POCO.ttinclude`, modify line 482 to be:

> return ((System.Data.Entity.Infrastructure.IObjectContextAdapter)this).ObjectContext.CreateQuery<<#=spReturnClassName#>>("[<#=DbContextName#>].[<#=sp.Name#>](<#= WriteStoredProcFunctionSqlAtParams(sp) #>**" + guid + "**)", <#= WriteTableValuedFunctionSqlParameterAnonymousArray(sp) #>);

and finally, in that same file, add this after line 480:

> var guid = Guid.NewGuid().ToString("N");

**Comment by sjh37** [comment]
Many thanks. This will be in the next release.

**Comment by sjh37** [comment]
Sorry, I had to revert this change. I got problems when testing it as the parameter names did not match exactly the parameter names of the stored proc / function.

**Comment by sjh37** [comment]
I've marked this as can't fix for now, as I can't see how to fix it. How did you get this to work correctly?

**Comment by aeslinger0** [comment]
@sjh37, this is the code that is generated for me after my change and I haven't had any problems since. Is this what you have? I'm running this against SQL 2008 R2.

```
[System.Data.Entity.DbFunction("DbContext", "SearchAssets")]
[CodeFirstStoreFunctions.DbFunctionDetails(DatabaseSchema = "dbo")]
public IQueryable<dbo_SearchAssetsReturnModel> dbo_SearchAssets(string assetKeyword)
{
    var guid = Guid.NewGuid().ToString("N");
    var assetKeywordParam = new System.Data.Entity.Core.Objects.ObjectParameter("assetKeyword" + guid, typeof(string)) { Value = assetKeyword };

    return ((System.Data.Entity.Infrastructure.IObjectContextAdapter)this).ObjectContext.CreateQuery<dbo_SearchAssetsReturnModel>("[DbContext].[SearchAssets](@assetKeyword" + guid + ")", assetKeywordParam);
}
```
