### ISSUE TITLE
Stored Procedures not generated as async

### ISSUE THREAD

**Issue by jeremysimmons** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#238]
Stored Procedure methods are not generated with async, and no config option present.

```
Database.ExecuteSqlCommand(System.Data.Entity.TransactionalBehavior.DoNotEnsureTransaction, "EXEC @procResult = [dbo].[ProcedureName] @Param1, @Param2, @Param3 OUTPUT", value1, value2, value3, procResultParam);
```

wanting 
the signature 
`public Task<int> ExecuteSqlCommandAsync(TransactionalBehavior transactionalBehavior, string sql, params object[] parameters)`

**Comment by jeremysimmons** [comment]
I fail... 
Async cannot be created due to having out parameters, or is relying on the procedure result

**Comment by sjh37** [comment]
:-)

**Comment by jeremysimmons** [comment]
@sjh37 ~~I'm not 100% sure why this is the case though. Why would the async prohibit retrieving the OUT parameter?~~ http://stackoverflow.com/a/18716968/26877 
I'm not a fan of using Tuple<T1, T2, TN>. I would be a fan of a type that contains the output parameters along with the return value. Has this been discussed before? Are you open to a pull-request?

**Comment by sjh37** [comment]
I'm ALWAYS open to a pull request!

**Comment by saysmaster** [comment]
All stored procedures return something. Async generation has been effectively disabled with this glitch. I remember poco generator generating async store procedure calls in earlier versions. What happened?

**Comment by sjh37** [comment]
@saysmaster Async stored procedures are generated.

For example, here is one SP from the Northwind db. It shows both non-async and async methods being generated:
```c#
public List<CustOrderHistReturnModel> CustOrderHist(string customerId)
{
    int procResult;
    return CustOrderHist(customerId, out procResult);
}

public List<CustOrderHistReturnModel> CustOrderHist(string customerId, out int procResult)
{
    var customerIdParam = new SqlParameter { ParameterName = "@CustomerID", SqlDbType = SqlDbType.NChar, Direction = ParameterDirection.Input, Value = customerId, Size = 5 };
    if (customerIdParam.Value == null)
        customerIdParam.Value = DBNull.Value;

    var procResultParam = new SqlParameter { ParameterName = "@procResult", SqlDbType = SqlDbType.Int, Direction = ParameterDirection.Output };
    var procResultData = Database.SqlQuery<CustOrderHistReturnModel>("EXEC @procResult = [dbo].[CustOrderHist] @CustomerID", customerIdParam, procResultParam).ToList();
    procResult = (int) procResultParam.Value;
    return procResultData;
}

public async Task<List<CustOrderHistReturnModel>> CustOrderHistAsync(string customerId)
{
    var customerIdParam = new SqlParameter { ParameterName = "@CustomerID", SqlDbType = SqlDbType.NChar, Direction = ParameterDirection.Input, Value = customerId, Size = 5 };
    if (customerIdParam.Value == null)
        customerIdParam.Value = DBNull.Value;

    var procResultData = await Database.SqlQuery<CustOrderHistReturnModel>("EXEC [dbo].[CustOrderHist] @CustomerID", customerIdParam).ToListAsync();
    return procResultData;
}
```

**Comment by saysmaster** [comment]
Ah ok, I see. So maybe this is the difference between this case and mine:

This stored procedure from Northwind, as I can see [here](https://gist.github.com/keeyanajones/7eed8886a8cf294d05f61d7b256fc71a) returns a result set.

My stored procedures that do not get their async methods created, they return nothing. They execute a batch update on a table and that's all. No result set or returns. Maybe I am missing something but I don't think there is anything that prohibits async method creation in that case, and the outputted message (unable to create async method because of out variables etc) is a bit misleading. There are no out variables at all in the method signature.

**Comment by sjh37** [comment]
@saysmaster You can always try and let the generator create those Async calls for you.
Search for, and make adjustments to the boolean result:
```c#
sp.StoredProcHasOutParams() || sp.ReturnModels.Count == 0
```

This results in a boolean flag `AsyncFunctionCannotBeCreated` being set which is used in the templates.
```c#
{{#if AsyncFunctionCannotBeCreated}}
    // {{FunctionName}}Async() cannot be created due to having out parameters, or is relying on the procedure result ({{ReturnType}}){{#newline}}
{{#else}}
    Task<{{ReturnType}}> {{FunctionName}}Async({{WriteStoredProcFunctionParamsFalse}});{{#newline}}
{{/if}}
```
