### ISSUE TITLE
Setting to disable lazy-loading

### ISSUE THREAD

**Issue by phofman** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#239]
It would be really nice to have a way of disabling generation of "virtual" keyword next to navigation properties. Yes/No switch would be sufficient.

That would essentially disable lazy-loading and stop causing problems if the generated entities are also serialized and stored outside the database. Serializers mostly go though all properties and when entity is detached from context, it will en up with an exception.

I know, that lazy-loading could be disabled via `dbContext.Configuration.LazyLoadingEnabled = false;` but then having properties as virtual only misleads other devs.

**Comment by sjh37** [comment]
Thanks so much. I have merged this and will be in the next release.
