### ISSUE TITLE
Timestamp Column / RowVersion Column

### ISSUE THREAD

**Issue by fferlini** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#24]
There is an issue using generator with SqlServer Compact 4.0 and RowVersion Column
With SQL Server Standard Timestamp column type is "TimeStamp" ad is mapped to "byte[]", on SQLCompact 4.0 the type is "RowVersion" and the column is mapped to "string"

To solve the problem, i've changed the following statements on EF.Reverse.POCO.Core.ttinclude file:
col.IsRowVersion = col.IsStoreGenerated && !col.IsNullable && ( typename == "timestamp" );

to

col.IsRowVersion = col.IsStoreGenerated && !col.IsNullable && ( typename == "timestamp" || typename == "rowversion" );

and added;

```
case "rowversion":
                    sysType = "RowVersion";
                    break;
```

and added:
case "rowversion":
                        sysType = "byte[]";
                        break;

**Comment by sjh37** [comment]
I've just pulled in ErikEJ code changes around this.See if that helps. 
Regards,Simon Hughes

-------- Original message --------
