### ISSUE TITLE
SQL varbinary(max) generates to "varbinary" which migrates to varbinary(4000), SB "varbinary(max)"

### ISSUE THREAD

**Issue by PETERHUP** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#241]
In SQL I have a field 
`[SourceDocument] [varbinary](max) NULL,`

which should generate to:

`Property(x => x.SourceDocument).HasColumnName(@"SourceDocument").HasColumnType("varbinary(max)").IsOptional();`

but is currently generating to:

`Property(x => x.SourceDocument).HasColumnName(@"SourceDocument").HasColumnType("varbinary").IsOptional();`

When I then do a migration update-database it creates a field of varbinary(4000)

**Comment by rposener** [comment]
+1 - pretty major issue (silently fails and loses data)!

**Comment by ErikEJ** [comment]
@rposener You write: (silently fails and loses data)! - only when using migrations, or?

**Comment by rposener** [comment]
Actually we use the generator for DB-first to Code-first Context.  You'd set an entity with  say a file of 12K size in a varbinary and it would truncate it at 4,000 bytes.

**Comment by ErikEJ** [comment]
@rposener  Really? @sjh37  Has this always been an issue?

**Comment by sjh37** [comment]
@ErikEJ Nobody has ever mentioned this issue before. If you want to store binary files, people use a varchar(256) to put a path in to where the file is located on the hard drive.
However, what @rposener has found is that if you do store large binary data (> 4000) bytes in SQL Server you have to declare the type as varbinary(max) instead of varbinary.

**Comment by PETERHUP** [comment]
@sjh37 I use MSSQL as a backend and setup a filestream to securely store external documents and use a varbinary(max) to do so.  I think this makes it more secure since you can only access the files through MSSQL security.  It also does not effect the max database size of 10 for the express edition which is also nice.

**Comment by sjh37** [comment]
This will be in the next release. So will close this issue.
