### ISSUE TITLE
Compiling transformation: Cannot convert type 'Microsoft.VisualStudio.TextTemplating......GeneratedTextTransformation.PropertyAndComments' to 'string

### ISSUE THREAD

**Issue by mwoffenden** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#242]
We just upgraded to the latest version and getting this error:

Error		Compiling transformation: Cannot convert type 'Microsoft.VisualStudio.TextTemplating3AF4D39A98E9E05C90C4ACD01346AED58C422C9E9AD20BFBDE404ADF97A1B516D5D3CFA8C28E5A1814F01B4DA88425459786F7764EF5DD51A28FA522253F3436.GeneratedTextTransformation.PropertyAndComments' to 'string'	

The error line is in EF.Reverse.POCO.ttinclude, near line 1001

`foreach(string s in tbl.ReverseNavigationProperty.OrderBy(x => x))`

We're using VS2017.  Need some help, thanks!

**Comment by sjh37** [comment]
The class PropertyAndComments is as follows:
```c#
public class PropertyAndComments
{
    public string Definition;
    public string Comments;
}
```

The foreach is as follows:
```c#
foreach(var s in tbl.ReverseNavigationProperty.OrderBy(x => x.Definition))
```
Which is correct.

Your code is missing the `x.Definition` inside the OrderBy
```c#
foreach(var s in tbl.ReverseNavigationProperty.OrderBy(x => x))
```

Can you check it is there in the EF.Reverse.POCO.ttinclude file.

**Comment by mwoffenden** [comment]
My mistake.  I forgot to copy the new EF.Reverse.POCO.ttinclude file into place.

Working great now.  Thanks for quick reply!
