### ISSUE TITLE
Is it possible to specify a FK class in code?

### ISSUE THREAD

**Issue by rlightner** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#244]
I have a table that contains a Row called WidgetId. I would like to make that a FK via code to the Widget table.

**Comment by rlightner** [comment]
Anyone?

**Comment by sjh37** [comment]
Sorry, this can't be done via the settings in the generator.
The FK should be added as soon as possible to your database to prevent invalid data being added.
