### ISSUE TITLE
Complex types still registered for TVFs with renamed return types

### ISSUE THREAD

**Issue by ackginger** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#245]
When adding modelBuilder.ComplexType<> for TVFs it does not filter on StoredProcedureReturnTypes collection, so includes types which are not then required or created.

Suggest changing where clause to:
`<#      foreach (StoredProcedure sp in storedProcs.Where(s => s.IsTVF && !StoredProcedureReturnTypes.ContainsKey(s.NameHumanCase) && !StoredProcedureReturnTypes.ContainsKey(s.Name))){#>`

**Comment by sjh37** [comment]
Thanks. This will be in the next release.
