### ISSUE TITLE
Excluding columns from specific tables only

### ISSUE THREAD

**Issue by LearnArchitecture** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#248]
First of all thank you very much for this project.

I am planning to use this tool to generate internal and external projects for our product, I watched almost half of your course on PS for this tool so far, but I had a quick question.

I know we can exclude columns from all tables, e.g.  you removed "Added" from all tables in your PS tut, but can we do it for certain tables ? e.g. exclude "Added" from Table1 and Table3 but add it to Table2.

Please let me know if this makes sense. Also any resource I could use to learn how you developed this tool so that I could contribute to it too :)

Many thanks

**Comment by sjh37** [comment]
Yes you can. You just need to mark the column as Hidden and it will be excluded.

In `UpdateColumn` you can specify which columns you want for certain tables. For example, for the UserAccount table, I only want to keep 3 columns: Id, UserId, UserId

```c#
// Minimize 'user_account' columns to minimum
if (table.NameHumanCase.Equals("UserAccount", StringComparison.InvariantCultureIgnoreCase))
{
    column.Hidden = !column.NameHumanCase.Equals("Id", StringComparison.InvariantCultureIgnoreCase) &&
                    !column.NameHumanCase.Equals("UserId", StringComparison.InvariantCultureIgnoreCase) &&
                    !column.NameHumanCase.Equals("UserIdentifier", StringComparison.InvariantCultureIgnoreCase);
}

// Minimize 'site' columns to minimum
if (table.NameHumanCase.Equals("Site", StringComparison.InvariantCultureIgnoreCase))
{
    column.Hidden = !column.NameHumanCase.Equals("Id", StringComparison.InvariantCultureIgnoreCase) &&
                    !column.NameHumanCase.Equals("Name", StringComparison.InvariantCultureIgnoreCase);
}

```
