### ISSUE TITLE
Can we use this to generate ASP.NET Web API web services ?

### ISSUE THREAD

**Issue by LearnArchitecture** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#249]
Can we use this tool to generate a service layer which is using ASP.NET Web API ? 

Many Thanks

**Comment by sjh37** [comment]
Not quite. It does the main job for you.
I use this tool to reverse engineer our company database, filtered to just the tables I need for my Web API. All I write is the authentication bit, and the LINQ query layer to return the data. Oh, and the unit tests of course which use the generated FakeDbContext so I can test the LINQ query layer :-)
