### ISSUE TITLE
TableRename Function

### ISSUE THREAD

**Issue by Chris3773** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#252]
To allow more control of renaming tables change the input of the TableRename function to the Table object from only schema and name.

An use case where this would come in handy would be if you want to prefix all views.

**Comment by sjh37** [comment]
Hard to do at this point as the Table object is not fully constructed.

1. Set the Name, Schema, and IsView Table properties.
1. Use the callback TableRename.
1. Check for renamed table for exclusion. Some tables are renamed by appended 'xxx', these can then be excluded by the table filter if 'xxx' is in the name.
1. We can then set ClassName and NameHumanCase in the Table object once we have the renamed name.

The only 3 things we have at the start are Name, Schema and IsView.
What I will do, is to include the boolean flag for IsView to the callback

**Comment by sjh37** [comment]
This will be in the next release.

**Comment by sjh37** [comment]
released
