### ISSUE TITLE
Drop WCF support

### ISSUE THREAD

**Issue by phofman** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#255]
What about removing anything related to WCF from the current generator as it produces unintuitive code and generates R# warnings about wrong placement of attributes.

Once *AddWcfDataAttributes* is enabled, then additional attribute is generated before anything of `WritePocoColumn()` call. If comments are put in summary block, they are generated via mentioned method, so the *DataMember* attribute is placed before that comment. As the result the WCF attribute and all custom annotations are separated via comment block.

WCF-related attributes can be generated via *WritePocoClassAttributes()* and *WritePocoColumn()* without any harm with identical final result.

**Comment by sjh37** [comment]
Its probably about time I dropped that tbh.

**Comment by sjh37** [comment]
If you have time, would you be able to create a pull request?

**Comment by phofman** [comment]
OK, I will create one

**Comment by sjh37** [comment]
Done. This will be in the next release.

**Comment by sjh37** [comment]
Released.
