### ISSUE TITLE
Table plurals ending with 'ies' do have weird results

### ISSUE THREAD

**Issue by Bitfiddler** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#257]
If you have a table called 'TRADE_SUMMARIES' and you run the poco generator, an entity called:
"TradeSummaRy" is created.

Expected result: "TradeSummary"

I have created a table rename rule to override this, but I thought I would problem here.

**Comment by sjh37** [comment]
Hi. Yes, the pluralisation is a bit funny sometimes. Microsoft wrote the pluralisation library so, I can't fix it.
I give two examples in comments, which don't pluralise correctly either:
```c#
new CustomPluralizationEntry("Course", "Courses");
new CustomPluralizationEntry("Status", "Status"); // Use same value to prevent pluralisation
```
