### ISSUE TITLE
EntityFrameWork

### ISSUE THREAD

**Issue by sarada123** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#258]
Hi i am a biggener for Entity FrameWork ReversePoco generator,but i want to know how to add it to my solution.for which i am using visual studio 2013.Please help me regarding to generate database without generation edmx file how to create tt files

**Comment by sjh37** [comment]
Welcome.
Please read this: https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/blob/master/README.md#to-install-and-use-this-project


* Download VSIX installer from https://marketplace.visualstudio.com/items?itemName=SimonHughes.EntityFrameworkReversePOCOGenerator
* Watch the in-depth course at pluralsight https://app.pluralsight.com/library/courses/code-first-entity-framework-legacy-databases/table-of-contents I cover everything this generator can do, and show you step-by-step how to reverse engineer your database properly.


Any other problems, write a comment here and I will pick it up here.
