### ISSUE TITLE
Tip for improved RevEng of stored procs

### ISSUE THREAD

**Issue by ErikEJ** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#260]
http://sqlblog.com/blogs/greg_low/archive/2017/04/11/avoiding-invalid-object-name-errors-with-temporary-tables-for-biztalk-reporting-services-and-apps-using-set-fmtonly.aspx 

(Just FYI)

**Comment by sjh37** [comment]
Thanks Erik, sorry for my slowness in getting this sorted.

**Comment by ErikEJ** [comment]
No worries, just FYI
