### ISSUE TITLE
Partial Class Option

### ISSUE THREAD

**Issue by jmprado** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#263]
'<#if(MakeClassesPartial) {#>            <#=DbContextName#>StaticPartial(); // Create the following method in your partial class: private static void <#=DbContextName#>StaticPartial() { }
<#}#>'

The code above add in "EF.Reverse.POCO.ttinclude" to [DbContextName]Context.cs initializer a line that prevents the code to compile.

I'm using partial classes to use data annotations using metadata.

My question is:

Is this necessary? My code works Ok without it.

Thank you

**Comment by sjh37** [comment]
This causes a lot of people to question this, so I may actually remove it.

**Comment by AndyCadley** [comment]
You can "fix" this by declaring a partial stub in your class such as:

static partial void DbContextStaticPartial();

Which is neater than putting an empty method and should guarantee the compiler eliminates the call entirely. I'm not sure I fully understand the implications of just getting the generator to put the partial stub in the generated part and allow you to override it when needed (which is the way I'd usually expect it to work).

On the whole I'd be in favour of removing it if it can't be fixed, as it gives the impression that turning on partial classes (which sort of feel like they should be the default behaviour for code generation) causes the system to generate broken code.

**Comment by sjh37** [comment]
@AndyCadley that worked, but then I started to think about its uses, and what you can actually do within the static constructor. Setting of the static DefaultConnectionFactory is now obsolete, and there is very little else to do, so I've removed it.
