### ISSUE TITLE
If Used IncludeComments = CommentsStyle.None; it doesn't declare the Collection of T

### ISSUE THREAD

**Issue by hoquem1** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#264]
If I use the IncludeComments = CommentsStyle.None; it doesn't generate the follwing lines of code for relation. The constructor shows the error that 

Severity	Code	Description	Project	File	Line	Column	Suppression State
Error	CS0103	The name 'EntityMapTypes' does not exist in the current context	Reversepoco	D:\Sandbox\Reversepoco\Reversepoco\Models\Entity.cs	32	13	Active

That line should have not affected the Collection Declaration.  Do you have a fix for this? 

/// <summary>
        /// Child EntityMapTypes where [EntityMapType].[EntityId] point to this entity (FK_EntityMapType_Entity)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<EntityMapType> EntityMapTypes { get; set; } // EntityMapType.FK_EntityMapType_Entity

**Comment by andygjp** [comment]
Hi,

It seems that its caused by the change made to support #246. If you revert that commit (b136f85d36dfac598889c2511a77ce3a56df0662) then the members are put back.

Cheers,
Andy
