### ISSUE TITLE
new csproj format and GenerateSeparateFiles=true causes VS2017 to freeze

### ISSUE THREAD

**Issue by andygjp** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#266]
Hi,

If you use the new csproj format and you set GenerateSeparateFiles=true, VS2017 will freeze when you generate code. You eventually have to kill off VS. However, when you restart VS, you discover the code, including separate code files for each class, has been generated correctly. Setting GenerateSeparateFiles=false works and does not freeze VS2017, so it would seem trying to add the code files to the project is causing the problem.

Cheers,
Andy

**Comment by sjh37** [comment]
Are there a lot of files to be added?
VS is not very fast at adding files to the csproj.

**Comment by andygjp** [comment]
22 files. I'll double check is fine using the old csproj format.

Cheers,
Andy

**Comment by andygjp** [comment]
The same db, using the old csproj format, takes about 5s to create 22 files.

**Comment by sjh37** [comment]
Thanks Andy. I wonder if there is something we can do to make adding files in VS2017 with the new csproj format work as it does for the old project format. If you have any ideas, or able to help in someway, It would be much appreciated.

**Comment by sjh37** [comment]
I suspect this is a bug with VS2017, which will hopefully get fixed in the next update.

**Comment by andygjp** [comment]
Hi,

I've managed to create a spike that solves the issue, but its a bit of a hack.

Its all because of VsEntityFrameworkTemplateFileManager thats included in EF6.Utility.CS.ttinclude (https://github.com/aspnet/EntityFramework6/blob/master/src/EFTools/EntityDesign/TextTemplates/Includes/EF6.Utility.CS.ttinclude). Remove the Process method override and it works.

I still need a way to workout the csproj version, but once I've done that, I should be able to use either the original VsEntityFrameworkTemplateFileManager, for old csproj formats, or my Vs20017EntityFrameworkTemplateFileManager.

The reason why its a hack is because I copied/pasted EntityFrameworkTemplateFileManager and VsEntityFrameworkTemplateFileManager from EF6.Utility.CS.ttinclude into EF.Reverse.POCO.Core.ttinclude. I tried to subclass EntityFrameworkTemplateFileManager but it has a private constructor. Its probably cleaner to include a modified version of EF6.Utility.CS.ttinclude as part of your VS extension.

What do you think?

Cheers,
Andy

**Comment by sjh37** [comment]
I would say include a modified version of the EF6.Utility.CS.ttinclude as part of this VS extension.
Thanks for your great work on this.
Much appreciated.

**Comment by ErikEJ** [comment]
@divega @bricelam FYI!

**Comment by divega** [comment]
@sjh37 @ErikEJ @andygjp we generally don't support the new csproj file format with either EF tools, nuget package or migrations commands. 

I have updated the list of problems we would need to fix to support the new csproj format in the issue that @ErikEJ filed some time ago at https://github.com/aspnet/EntityFramework6/issues/231.

**Comment by divega** [comment]
That said, I agree from the symptoms that this could be a bug in the project system. @davkean does this ring a bell?

**Comment by davkean** [comment]
If this is the legacy project system and you are adding files one at a time, and not pausing design-time builds - then this is going to kick off a blocking UI [design-time build](https://github.com/dotnet/project-system/blob/master/docs/design-time-builds.md) for every add. To avoid that do the work in a batched block:

``` C#
            IVsHierarchy hierarchy = ...

            try
            {

                if (hierarchy is IVsProjectBuildSystem build)
                {
                    build.BeginBatchEdit();  // Pause design-time builds
                }

                // Do modifications to the project
            }
            finally
            {
                if (hierarchy is IVsProjectBuildSystem build)
                {
                    build.EndBatchEdit();  // Kick off design-time build with all the changes
                }
            }
```

**Comment by davkean** [comment]
Here's an example from NuGet: http://sourcebrowser.io/Browse/Haacked/NuGet.git/src/VisualStudio/VsProjectManager.cs#25.

**Comment by sjh37** [comment]
Hi @davkean @divega,

@andygjp has come up with a fix. See https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/pull/278/commits/c9d0273531f79ef8363f7c4e60c4da74548bb169

That is a one of the commits from the pull request #278 which modifies `EF6.Utility.CS.ttinclude`. Is this something you guys control, and could fix?

**Comment by divega** [comment]
@sjh37 yes, that is one of the .ttinclude files that ships with EF6 Tools (maintained at https://github.com/aspnet/EntityFramework6/). 

Does this issue only affect projects with the new csproj format as the title suggests? In general none of the EF6 tooling currently supports the new csproj format but if we decided to fix https://github.com/aspnet/EntityFramework6/issues/231 in the future we could take a similar fix for this. It would probably apply to all our ttinclude files.

**Comment by sjh37** [comment]
@divega Yes, it only affect projects with the new csproj.

**Comment by divega** [comment]
@sjh37 in that case it probably make sense to keep your own fork of the code in the ttinclude file until we fix this problem in the one we ship (presumably it will affect our templates as well).

@davkean from what I am getting here this is not an issue with the legacy project system but with the new one.

**Comment by dialedin2014** [comment]
I am having other issues with EF6.Utility.CS.ttinclude and will post a separate issue for it.  It would be great to get that dependency out of the ttinclude and into a .cs file.

**Comment by Miggleness** [comment]
Also freezes in VS2019 with SDK type project

**Comment by sjh37** [comment]
Apparently, this is now fixed https://developercommunity.visualstudio.com/content/problem/563360/visual-studio-freezes-when-processing-t4-template.html

**Comment by sjh37** [comment]
Tracking the issue here: https://developercommunity.visualstudio.com/content/problem/563360/visual-studio-freezes-when-processing-t4-template.html

**Comment by sjh37** [comment]
Closing this as it is now fixed in v3 as I'm using my own custom file writer when using
```c#
Settings.FileManagerType = FileManagerType.Custom;
```

Thanks to @0xced for letting me know.

**Comment by daiplusplus** [comment]
I'm confused - is there a fix for users of the v2 T4 files?

Or is the "fix" to revert my `*.csproj` back to the old-style?

**Comment by sjh37** [comment]
Hi @Jehoel 

If you're using v2, then you need to use the old-style `*.csproj` as `EF6.Utility.CS.ttinclude` is only compatible with that.

**What v2 & v3 use to write files**
- v2 uses `EF6.Utility.CS.ttinclude` to add/delete files from Visual Studio.
- v3 uses `EF6.Utility.CS.ttinclude` to add/delete files from Visual Studio when `Settings.FileManagerType = FileManagerType.VisualStudio`, and it's own file writer (CustomFileManager) when `Settings.FileManagerType = FileManagerType.Custom`.

The `CustomFileManager` is designed for .net core projects and therefore does not communicate with VisualStudio to add/remove files. Using the filemanager built into `EF6.Utility.CS.ttinclude` for .net core projects causes VisualStudio to hang. The `CustomFileManager` simply writes the files directly to the file system, and leaves VisualStudio to automatically detect new files, which is does an excellent job of. I've a separate case #536 to delete any filtered out files when the CustomFileManager writes out files.

**Comment by daiplusplus** [comment]
What I did in my case was create a separate old-style `*.csproj` that exists only to hold the `Model.tt` file and run the TextTransformation custom-tool - while my new-style `*.csproj` (the real project) references includes the same files but does not run the custom-tool. It's okay for now, even if it does mean having a separate project entry in Solution Explorer.

Alternatively, can we run the T4 script from the command-line at all? How can that work with EnvDTE?
