### ISSUE TITLE
Column Level Attributes instead of Table

### ISSUE THREAD

**Issue by bakes82** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#27]
Can you create another way to add attributes but at the "Column" level, currently its setup for a table object.

I'm trying to rename columns from <Table>Id to just "Id" and I need an attribute called [Column("TableId")]  but would also be useful to but in required if not null, or max lengths etc.

**Comment by sjh37** [comment]
That is done via the callback

``` c#
Func<Column, string> WritePocoColumn = c => c.Entity;
```

For example:

``` c#
Func<Column, string> WritePocoColumn = c =>
{
    if(c.IsPrimaryKey)
        return "[System.ComponentModel.DataAnnotations.Key] " + c.Entity;
    return c.Entity;
}
```

**Comment by bakes82** [comment]
Thanks, must of over looked it, was looking for another attribute one.
