### ISSUE TITLE
dots in a stored procedure or views return model

### ISSUE THREAD

**Issue by lt4mosin** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#270]
I may be missing something and this may already be easy to do in the RPOCO generator and I just don't understand it. However, in SQL it is perfectly acceptable to name the return fields something like columns table.field and is in fact common. If I am reverse engineering a database that I do not have objects to map these return columns to then the generated return model properties will be made with the same name for example:  Assessment.Name which isn't valid C# syntax see below. The fix is of course to substitute the . with another legal character like _. If these were tables then it would be easy to correct but again I apologize if I missed this but, there doesn't seem to be a callback that would let me do this type of fixup for a stored procedure field?

  [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
        public class ResultSetModel2
        {
             public System.Guid Id { get; set; }
             public System.String Assessment.Name { get; set; }

**Comment by sjh37** [comment]
Unfortunately the EF stored procedure call requires the **exact** unaltered name of the return columns from stored procedures. Anything that does not match exactly gets ignored.
And as Assessment.Name is not legal C# syntax, we can't use it.

There are two solutions:

1. Change your stored procedure to return valid c# field names.
1. Create another stored procedure to call the one above, and change the column names being returned to valid c# field names

**Comment by lt4mosin** [comment]
Thank you for the quick response! Well I am glad it wasn't just something that I was missing. I can't change the existing SPs but your suggestion about making a pass through procedure might work.

**Comment by sjh37** [comment]
I'll close this as its something I can't fix. Thanks for being vigilant and trying to make the generator better!
