### ISSUE TITLE
How can I disable certain validation attributes?

### ISSUE THREAD

**Issue by jaxidian** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#273]
Howdy,

I love having Data Annotations turned on for some rudimentary validations (string length, etc.) but some of the more advanced validations (EmailAddressAttribute, PhoneAttribute) are causing me some problems. Is there a way to disable, from the configuration, these advanced validations? I'm specifically wanting to disable the ones where assumptions are made based on the name of the column.

My use case is a table called CustomFieldLabels with varchar columns like `Email`, `Phone`, etc. and I'm sure you can see the problem. I know changing the names of my columns is one way to do it but I'm working with some third-party software here as well and that's not easily done. I'd really like to control this from the config file.

Is this possible or would this require modification?

I can confirm commenting out the following section in EF.Reverse.POCO.Core.ttinclude accomplishes what I want for Emails but I don't want to have to maintain forked code (that's what I'm doing until I have a better option) and I'm unable to perform the due diligence to submit a useful PR at this point.

                if (NameHumanCase.Equals("Email", StringComparison.InvariantCultureIgnoreCase) ||
                    NameHumanCase.Equals("EmailAddress", StringComparison.InvariantCultureIgnoreCase))
                {
                    DataAnnotations.Add("EmailAddress");
                }

Thanks!!

**Comment by sjh37** [comment]
Nothing as yet, I'd need some sort of array listing you can set for the column names vs what data annotation to set for it.

I'll mark this as an enhancement so I can get round to adding this.

**Comment by sjh37** [comment]
All done. This will be in the next release.

**Comment by jaxidian** [comment]
A quick review (as a consumer, not a real code-review) of that commit looks great! Thank you very much! :-)
