### ISSUE TITLE
Settings to control context file header comment block

### ISSUE THREAD

**Issue by rhvarona** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#275]
I would like more control over the context comment block.  One option is flag that turns the whole block off.  Another option is to be able to turn off the connections string and database edition comments.  It can be a security risk to leak internal server names and database names in the comments checked into a shared code repository.

**Example of current generated comment block:**
// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.com/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Do not make changes directly to this file - edit the template instead.
//
// The following connection settings were used to generate this file:
//     Configuration file:     "<SomeConfFile>"
//     Connection String Name: "<SomeConnStringName>"
//     Connection String:      "<SomeConnString>"
// ------------------------------------------------------------------------------------------------
// Database Edition       : <Some DB Edition>
// Database Engine Edition: <Some DB Engine Edition>

**Proposed flag**
IncludeConnectionSettingComments = false; // Add comments describing connection settings used to generate file

**Comment by sjh37** [comment]
Good idea

**Comment by ErikEJ** [comment]
I propose that all settings could be ignored, to minimize the number of changed files with a refresh based on db schema changes

**Comment by sjh37** [comment]
Done. This will be in the next release.
