### ISSUE TITLE
When sproc return model property contains name like static' or 'readonly', it can rename it to @static or @readonly

### ISSUE THREAD

**Issue by rocker8942** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#279]
Hi, 

I have a DB sproc which use 'static' or 'readonly' as a return data column. In this case, when generated POCO, the returnModel fails due to the property name is reserved in C#. 

It can be easily worked around by placing '@' prefix, but could you please have this as a function this is tool? so that it can be automatically done. 

Regards
Joe

**Comment by sjh37** [comment]
Thanks. This will be in the next release.
