### ISSUE TITLE
Navigation for views

### ISSUE THREAD

**Issue by Filipowicz251** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#280]
Hi.

Am i missing something or navigations are not added to the views? Of course views does not have foreign keys (so it is somehow obvious, that there are no navigations) but of course this can be done in a different manner. So my question is: "Is there any possibility to discover navigations for the views?"

Best regards
Piotr

**Comment by sjh37** [comment]
Hi.
A view is nothing more than a predefined SQL select statement, which returns a queryable interface to allow other views/functions/queries/procs to incorporate the query plan into their existing query. Resulting in an optimal query plan to execute against the database.

So if a view is nothing more than a query plan, you can't add a foreign key to it.
