### ISSUE TITLE
Default values must be escaped on entity classes

### ISSUE THREAD

**Issue by elincognito** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#281]
Columns with default values such as 
`[Obs]                 NVARCHAR (MAX) CONSTRAINT [DF__PlanStudies_Obs] DEFAULT ('[{"k":"en","v":""},{"k":"pt","v":""}]') NULL, `

Don't ~~~Get~~~ escaped in the Generated Model entity as :

`Obs = "[{"k":"en","v":""},{"k":"pt","v":""}]";`
It should be 

`Obs = "[{\"k\":\"en\",\"v\":\"\"},{\"k\":\"pt\",\"v\":\"\"}]";`

**Comment by sjh37** [comment]
Fixed. Thanks, this will be in the next release.
