### ISSUE TITLE
float default generates invalid c# code

### ISSUE THREAD

**Issue by mellamokb** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#283]
If the type is interpreted as a float, the default generator needs to include a 'f' at the end.

public float MyVar { get; set; }

MyVar = 0.08;  // generates compiler error

The correct code would be "MyVar = 0.08f".  Or I guess more generically it could be casted so the code doesn't have to memorize the literal suffixes: "MyVar = (float)0.08".

**Comment by sjh37** [comment]
Thanks. This will be in the next release.

**Comment by sjh37** [comment]
Released.
