### ISSUE TITLE
default double with period at end generates c# compiler error

### ISSUE THREAD

**Issue by mellamokb** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#284]
If the default value has a period (.) at the end, it generates invalid c# code.  I was able to work around in our code-base by recreating the default with a .0 at the end so it's valid.

ALTER TABLE [MyTable] ADD CONSTRAINT [DF_MyTable_MyColumn] DEFAULT ((999.)) FOR [MyColumn]

Generates the following invalid C# code

MyColumn = 999.;   // C# compiler error

If the Default validation is validating the value by trying to parse it, maybe it could be ToString()'d after that to avoid issues like this.

**Comment by sjh37** [comment]
Fixed. This will be in the next release.

**Comment by sjh37** [comment]
Released.
