### ISSUE TITLE
Primary key generation using default value from database by treating it as computed(?)

### ISSUE THREAD

**Issue by Rodbourn** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#289]
I've been trying to find a way to get the primary keys to be generated from the default value at the database upon insert for uniqueidentifier primary keys.  In particular, I would like the default value "newsequentialid()" to be used.

Would having a primary key optionally treated as a computed column be a solution?

**Comment by sjh37** [comment]
Great question. I actually think I should ignore the default in the constructor and set the primary key to null, so it gets set by sql server.

**Comment by Rodbourn** [comment]
That would be great!  Any chance to also get the new id (SCOPE_IDENTITY) back?  Let me know if I can help :)

**Comment by sjh37** [comment]
Just tested this with

```sql
CREATE TABLE Token 
(
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT (newsequentialid()) ROWGUIDCOL,
    Enabled bit NOT NULL 
)
```

poco:
```c#
public class Token
{
    public System.Guid Id { get; set; } // Id (Primary key)
    public bool Enabled { get; set; } // Enabled

    public Token()
    {
        Id = System.Guid.NewGuid();
    }
}
```

test:
```c#
using (var db = new FredDb())
{
    var token = new Token { Enabled = false };
    var before = token.Id;
    db.Tokens.Add(token);

    db.SaveChanges();
    var after = token.Id;
}
```

before = {869917bf-edab-4eef-a7da-51006f2732da}
after = {e914724f-ec45-e711-a8fc-d481d72ab183}

What's in SQL Server
E914724F-EC45-E711-A8FC-D481D72AB183

So the default value assigned in the constructor of the poco Token is ignored, and the guid is generated from the default newsequentialid(). So all works as is.
Are you using the `ROWGUIDCOL` setting on the primary key?

**Comment by Rodbourn** [comment]
Well, I feel dumb.  It's behaving exactly as I wanted it to.

The SQL that was generated:

```
exec sp_executesql N'DECLARE @generated_keys table([Id] uniqueidentifier)
INSERT [dbo].[Test]([Name], [UserId], [CreatedAt], [ModifiedAt])
OUTPUT inserted.[Id] INTO @generated_keys
VALUES (@0, @1, @2, @3)
SELECT t.[Id]
FROM @generated_keys AS g JOIN [dbo].[Test] AS t ON g.[Id] = t.[Id]
WHERE @@ROWCOUNT > 0',N'@0 nvarchar(50),@1 uniqueidentifier,@2 datetime2(7),@3 datetime2(7)',@0=N'Id insert test',@1='00000000-0000-0000-0000-000000000000',@2='2017-05-31 11:02:06.7563919',@3='2017-05-31 11:02:06.7568924'
```

The Id pre-save/insert:
2efe5272-2e0b-4bb2-aafa-c58a31eaccbc

and after:
7ecf9f95-f045-e711-8c80-d05099472025

and in sql:
7ECF9F95-F045-E711-8C80-D05099472025

**Comment by Rodbourn** [comment]
Thank you @sjh37
