### ISSUE TITLE
Store procedure generate incorrectly marking out parameters

### ISSUE THREAD

**Issue by medmondson** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#291]
I have two databases which I believe are identical which contain a proc named `GetCustomerAccountDetails`

I've also got two copies of my code, one pointing to each.

However the POCO generator produces a difference in the interface file:

```csharp
       // Stored Procedures
        System.Collections.Generic.List<GetCustomerAccountDetailsReturnModel> GetCustomerAccountDetails(string statusFlags);
        System.Collections.Generic.List<GetCustomerAccountDetailsReturnModel> GetCustomerAccountDetails(string statusFlags, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<GetCustomerAccountDetailsReturnModel>> GetCustomerAccountDetailsAsync(string statusFlags);
```
vs
```csharp
        // Stored Procedures
        int GetCustomerAccountDetails(string statusFlags);
        // GetCustomerAccountDetailsAsync cannot be created due to having out parameters, or is relying on the procedure result (int)

```
I dug out the proc sql code and ran it on both databases:

|SPECIFIC_SCHEMA                                                                                                                  |SPECIFIC_NAME                                                                                                                    |ROUTINE_TYPE         |ORDINAL_POSITION |PARAMETER_MODE |PARAMETER_NAME                                                                                                                   |DATA_TYPE                                                                                                                        |CHARACTER_MAXIMUM_LENGTH |NUMERIC_PRECISION |NUMERIC_SCALE |DATETIME_PRECISION |USER_DEFINED_TYPE
|-------------------------------------------------------------------------------------------------------------------------------- |-------------------------------------------------------------------------------------------------------------------------------- |-------------------- |---------------- |-------------- |-------------------------------------------------------------------------------------------------------------------------------- |-------------------------------------------------------------------------------------------------------------------------------- |------------------------ |----------------- |------------- |------------------ |----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|dbo                                                                                                                              |GetCustomerAccountDetails                                                                                                        |PROCEDURE            |1                |IN             |@statusFlags                                                                                                                     |varchar                                                                                                                          |512                      |0                 |0             |0                  |NULL

|SPECIFIC_SCHEMA                                                                                                                  |SPECIFIC_NAME                                                                                                                    |ROUTINE_TYPE         |ORDINAL_POSITION |PARAMETER_MODE |PARAMETER_NAME                                                                                                                   |DATA_TYPE                                                                                                                        |CHARACTER_MAXIMUM_LENGTH |NUMERIC_PRECISION |NUMERIC_SCALE |DATETIME_PRECISION |USER_DEFINED_TYPE
|-------------------------------------------------------------------------------------------------------------------------------- |-------------------------------------------------------------------------------------------------------------------------------- |-------------------- |---------------- |-------------- |-------------------------------------------------------------------------------------------------------------------------------- |-------------------------------------------------------------------------------------------------------------------------------- |------------------------ |----------------- |------------- |------------------ |----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|dbo                                                                                                                              |GetCustomerAccountDetails                                                                                                        |PROCEDURE            |1                |IN             |@statusFlags                                                                                                                     |varchar                                                                                                                          |512                      |0                 |0             |0                  |NULL

I think you'll agree they're identical with no permissions type issues getting in the way.  In particular the parameter mode being IN for both yet the second example incorrectly labeling it as an OUT.

Let me know if you need anything else to investigate this.

**Comment by ErikEJ** [comment]
The code of the two sprocs?

**Comment by medmondson** [comment]
@ErikEJ - thanks for the quick reply, below is the code from the identical procs.

```sql
REMOVED

**Comment by sjh37** [comment]
Can you try setting the following at the top of the procedure
```sql
SET NOCOUNT ON;
```
It may not make a difference, but that could be a settings difference between the two sql server databases.

**Comment by medmondson** [comment]
I tried to do so but got this:

> Cannot alter the procedure 'GetCustomerAccountDetails', because it does not exist or you do not have permission.

I imagine this could be affecting the POCO gen?

**Comment by sjh37** [comment]
Aha, security....
The generator calls the proc with null parameters and set fmtonly on, to obtain the return model. If this fails due to security privs, it could be why.

**Comment by medmondson** [comment]
@sjh37 - As suspected security was the cause.  Once I got myself added to the correct AD group all was good.

Have you thought about a way of making such issues more visible to the user? There was no indication of a problem in VS. Can we add something to the Error List?

**Comment by sjh37** [comment]
Thanks for letting me know.

**Comment by sjh37** [comment]
Raised case #292

**Comment by ghandlin** [comment]
I'm seeing something similar. I have one that generating a return of int and plenty of others that correctly return a List<T>.  I'm not sure what to look at.

One thing I notice is that the one that is creating an issue is using a couple temporary tables.

But another odd thing is that it worked on my previous machine. This is a new machine from my client. Now using VS2017 and SQL Express 2014

**Comment by ghandlin** [comment]
The temp tables were the problem. Switched them to table variables and it generated correctly. Is this a known result?

**Comment by sjh37** [comment]
Thanks @ghandlin I'll investigate using temp variables instead.

**Comment by ghandlin** [comment]
To be clear, the switch was in my stored procedure, not the generator. The proc was originally using temp tables, I switched it to use table variables and the generator correctly created a return variable of List<T> rather than int.

**Comment by sjh37** [comment]
Thanks for the clarification

**Comment by ghandlin** [comment]
Still not sure why the change alters what gets generated. Any ideas?

**Comment by sjh37** [comment]
It's sql server that reports back what will be returned. Hard to say what will and what won't work in all scenarios. Try the Microsoft forums or SO.
