### ISSUE TITLE
set GenerateSeparateFiles = true; and generator creates "orphan" #endregion directive on line 84 of  IMyDbContext.cs with error CS1028 - Unexpected preprocessor directive on line 84

### ISSUE THREAD

**Issue by foodmap** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#294]
It's been awhile since I've used the Reverse POCO Generator ( RPG ) so I installed v2.31.0 and am working through the Pluralsight course again.

When I used RPG + Pluralsight course about 6 months ago I was able to complete the course with zero errors.

I just started the course chapter where we use RPG to break the code down into 4 folders, Interfaces, Entities, Content, and Configuration.

Once I've completed the work for all 4 folders everything works as expected except for one minor error - it's a PITA more than anything else - and probably my fault.

--

In the Interfaces folder, in the file IDbContext.cs, I'm getting an unmatched region error because RPC generated the ending ( #endregion ) directive but not the beginning directive (  #region Unit of work ).

When reviewing the changes to v2.31.0 it seems Issue #269 may have fix to an unrelated issue, but the fix was somewhat similar to what I'm experiencing.

--

If I set the flag ( GenerateSeparateFiles = false; ) the problem goes away and the code in all 4 folders compiles and runs with no errors.

If I leave the flag set to (  GenerateSeparateFiles = true; ) and simply delete the "extra", "unmatched", or "orphan" #endregion directive the project compiles and runs with no errors.

--

Bottom line, I can complete the entire course section where we break the code into 4 folders, however, RPC isn't generating the line (  #region Unit of work ) into the IDbContext.cs file when RPC is set to GenerateSeparateFiles = true;

Setting the flag to false and the generated code works perfectly because RPG generated the code ( #region Unit of work ) and ( #endregion ) so it must be something very simple that I'm missing.

--

Does anyone have any suggestions about what flags I may try changing ( or what I should check in my SQL Server 2016 database schema - plain stuff - no gimmicks - 20 tables or so ) or how I can go about troubleshooting this a little more so I can bring back additional information to the group ?

Unfortunately, I know zero about T4 programming, but if it has a good step-through debugger and someone can point me to a tutorial page I'd be happy to track this down as far as I can.

--

The easiest way to recreate the issue is to follow the Pluralsight course ( chapter Generating Code First Types from an Existing Database ) using these steps ( follow the course ):

1) create the 4 folders mentioned Configuration, Context, Entities, Interfaces

2) move the Database1.tt file from the root folder to the Interfaces folder

3) modify the Database1.tt lines at the top and bottom to point at the T4 templates (?)

<#@ include file="..\\EF.Reverse.POCO.Core.ttinclude" #>
<#@ include file="..\\EF.Reverse.POCO.ttinclude" #>

4) verify this flag = GenerateSeparateFiles = false;

5) program should run perfectly

6) verify this flag = GenerateSeparateFiles = true;

7) program should fail to compile on file = IMyDbContext.cs with error CS1028 - Unexpected preprocessor directive on line 84

[Documents.zip](https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/files/1056830/Documents.zip)
[Documents.zip](https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/files/1056831/Documents.zip)

8) delete line 84

9) compile and program should run perfectly

Thanks everyone !

Attached is:

1) sql script that creates the SQL Server 2016 database

2) a database seed file from which you should be able to follow the RPG Pluralsight course as instructed above through the section that breaks the script into 4 folders ( you should be able to reproduce the error )

3) the IMyDbContext.cs file that RPG creates that contains the "orphan" #endregion directive

**Comment by sjh37** [comment]
Hi. This has already been fixed in #290 , but not yet released. I'll create a release for this today so you can continue on.

**Comment by sjh37** [comment]
Released.

**Comment by sjh37** [comment]
Any problems, please let me know.

**Comment by foodmap** [comment]
After upgrading to today's release v2.31.1 everything seems to be working perfectly now!

Thanks for the super fast response!
