### ISSUE TITLE
IncludeViews=true and UsePascalCase=false not working

### ISSUE THREAD

**Issue by holy22** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#296]
My views are named like "vMyView". I would like to keep this name also as class.
When I turn UsePascalCase=true, so my class has name VMyView. This is right.
But when I turn UsePascalCase=false, so no classes and no files are being generated :(

**Comment by holy22** [comment]
It seems there is problem also with tables. For example my table with name "DMS" is not generated with UserPascalCase=false.

**Comment by sjh37** [comment]
Thanks. I'll take a look.

**Comment by sjh37** [comment]
It works for me ok with both Northwind, a horrible test database, and my companies database.

**Comment by holy22** [comment]
Thank you for your quick response and I am sorry!
After I downloaded last version is this all right.
(but my previous post about many-to-many relations still not working)

**Comment by sjh37** [comment]
Did you upgrade the generator from a previous version? If so, can you compare the ttinclude files with the current version if you added the generator into a new folder?

I'll close this for now as it appears to be working normally. I can always re-open if you are still having issues.

**Comment by ErikEJ** [comment]
Would it be possible to add a check to ensure all three template components are the same version?

**Comment by sjh37** [comment]
@ErikEJ Hmmm. Not a bad idea.
