### ISSUE TITLE
How do I use the ColumnFilterExclude?

### ISSUE THREAD

**Issue by rosdi** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#299]
I am trying to exclude Id column (because we have base entity that already has that property).

I tried:  `ColumnFilterExclude = new Regex("^Id$")` or even `ColumnFilterExclude = new Regex("*Id*")` but nothing works..

**Comment by sjh37** [comment]
That's not the right way to do it.
You have to set the column Hidden property to true.

There is an example in the `<database>.tt` file. see the `UpdateColumn` callback.

```c#
UpdateColumn = (Column column, Table table) =>
{
    // Remove column from poco class as it will be inherited from a base class
    if (column.IsPrimaryKey && table.NameHumanCase.Equals("SomeTable", StringComparison.InvariantCultureIgnoreCase))
        column.Hidden = true;
}
```
