### ISSUE TITLE
":" in the field name

### ISSUE THREAD

**Issue by farshid3003** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#3]
in my stored procedures there are some chars like ":" which generator does not replace it and project does not build

 public partial class SpXmlFeedForFacebookReturnModel
    {
        public System.Int32 id { get; set; }
        public System.Int32 modelid { get; set; }
        public System.String title { get; set; }
        public System.String description { get; set; }
        public System.String g:condition { get; set; }
        public System.String g:price { get; set; }
        public System.String g:sale_price { get; set; }
        public System.String g:product_type { get; set; }
        public System.String link { get; set; }
        public System.String g:image_link { get; set; }
        public System.String g:availability { get; set; }
        public System.String g:brand { get; set; }
        public System.String g:color { get; set; }
        public System.String g:size { get; set; }
        public System.String g:mpn { get; set; }
        public System.String g:gender { get; set; }
        public System.String g:google_product_category { get; set; }
        public System.String g:adwords_grouping { get; set; }
        public System.String g:custom_label_0 { get; set; }
        public System.Int64? rn { get; set; }
    }

**Comment by sjh37** [comment]
You can't change the return models as they have to match exactly. Sorry, but my hands are tied.

However, there is something you can do.
I your case what you have to do is to exclude any stored procedures (A) with invalid return field names, and create a new stored procedure (B) which calls the stored procedure (A) and remaps the columns to valid names.

For example

``` sql
create proc SpXmlFeedForFacebook
AS
BEGIN
  SET NOCOUNT ON;
  SET XACT_ABORT ON;
  select id, g:condition, g:price from facebook
END;
GO

create proc SpXmlFeedForFacebookV2
AS
BEGIN
  SET NOCOUNT ON;
  SET XACT_ABORT ON;
  CREATE TABLE #Result
  (
    id int, g:condition varchar(500), g:price varchar(50)
  )
INSERT #Result EXEC SpXmlFeedForFacebook
SELECT id, g:condition as condition, g:price as price  FROM #Result
DROP TABLE #Result
END;
GO
```

So you call the v2 version within your code, and exclude the SpXmlFeedForFacebook sp by using the SchemaFilterExclude regex. Something like (just make sure it matches your name. as I can't see that. Perhaps it will `^sp_xml_feed_for_facebook$`

``` c#
SchemaFilterExclude = new Regex("^SpXmlFeedForFacebook$");
```

**Comment by farshid3003** [comment]
you are right thank you
