### ISSUE TITLE
Objects are getting an appended 1

### ISSUE THREAD

**Issue by dyardyGIT** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#30]
I have a database with many tables in different schemas.
I have 2 tables named workflow in 2 different schemas.

The generated code while using     SchemaFilterInclude = new Regex("sre");; (not specifically naming the tables) I get objects that are Workflow1 instead of Workflow.

I also tried specifying specific schema and while naming the table via TableFilterInclude - the resultant code still creates the object as Workflow1 insead of Workflow

**Comment by dyardyGIT** [comment]
Right now, my work around is to exclude the schema for the other like named table 'Workflow'

**Comment by sjh37** [comment]
You could rename the table using the callback. Something like this may work:

``` c#
TableRename = (name, schema) =>
{
    if (schema == "sre" && name == "workflow")
        name = schema + "_" + name;
    return name;
};
```

Let me know if this helps.

There is a todo item for me, and thats to add an option to allow schemas to be used as namespaces. Such as Sre.Workflow, and Dbo.WorkFlow so that they don't clash.

**Comment by dyardyGIT** [comment]
That would work but i think the issue is larger.  I specified to only use sre schema tables/objects.  The tt file however was comparing sre.workflow with dbo.workflow and so if i was using both schemas that would be ok, but i specifically said just look at sre schema and so within sre schema there are no table duplicates so the problem would not exist.

I am assuming SchemaFilterInclude = new Regex("sre"); says..only look at sre schema.  Is this correct? (if that is, then it shouldnt see the dbo.workflow table and so no duplicate would exist?)

thoughts-dave

**Comment by sjh37** [comment]
Definitely a bug. I'll take a look over the next few days and get a fix out.
Thanks for finding this bug.

**Comment by sjh37** [comment]
To test, I created two tables

``` sql
CREATE TABLE Alpha.workflow (
   [Id] int NOT NULL IDENTITY(1,1) PRIMARY KEY, [Description] VARCHAR(10) NULL )
CREATE TABLE Beta.workflow  ( 
   [Id] int NOT NULL IDENTITY(1,1) PRIMARY KEY, [Description] VARCHAR(10) NULL )
```

This was generated

``` c#
System.Data.Entity.DbSet<Alpha_Workflow> Alpha_Workflows { get; set; } // workflow
System.Data.Entity.DbSet<Beta_Workflow> Beta_Workflows { get; set; } // workflow
```

All looks ok so far.

Adding a filter:

``` c#
SchemaFilterInclude = new Regex("Alpha");
```

Just gives me the following:

``` c#
System.Data.Entity.DbSet<Alpha_Workflow> Alpha_Workflows { get; set; } // workflow
```

Again, this looks ok too.
Perhaps I've already fixed this in a previous release?
I'm working with the latest code in github. I'll create a release today anyway, in case it's in the stuff I have, and not public.

Please let me know if I'm looking in the wrong place, or got something wrong with my testing and I'll revisit.

**Comment by sjh37** [comment]
Please check with the code in the latest release v2.19.2 and let me know how it goes.

**Comment by sjh37** [comment]
Let me know if you need to re open this issue.

**Comment by dyardyGIT** [comment]
I am using 2.19.3 just now and I had to explicitly exclude the other schemas otherwise generated classes would have 1 appended.

i.e. 
    SchemaFilterExclude = new Regex("tele|sre|sdue");
    SchemaFilterInclude = new Regex("chc");;

I have a table called tele.UserRoles, sre.UserRoles, sdue.UserRoles and chc.UserRoles

If i used the following
    //SchemaFilterExclude = new Regex("tele|sre|sdue");
    SchemaFilterExclude = null;
    SchemaFilterInclude = new Regex("chc");;
    TableFilterExclude = null;    

I get class names UserRole1.cs (likewise User1.cs)

**Comment by sjh37** [comment]
I've recently made some changes, and I suspect its fixed this too. Would you be able to pull the latest code changes and try them out.

**Comment by sjh37** [comment]
This should now be fixed in latest release. Can you please retest and let me know.
