### ISSUE TITLE
Visual Studio 2017

### ISSUE THREAD

**Issue by jcpMJones** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#304]
Can I install the templates into VS2017?  The vsix installer only sees my VS2015 instance.

**Comment by sjh37** [comment]
Odd, I installs into vs2017 ok.

The manifest for VS2017 is:
```xml
<Edition>Enterprise</Edition>
<Edition>Community</Edition>
<Edition>Pro</Edition>
<Edition>VSWinExpress</Edition>
<Edition>VSWinDesktopExpress</Edition>
<Edition>VWDExpress</Edition>
```

What version do you have?

**Comment by ErikEJ** [comment]
@jcpMJones Are you running the "correct" VSIX installer - must be the 2017 one...

**Comment by jcpMJones** [comment]
I keep relearning the same lesson.  I can successfully install into a class library, but not into an asp.net core web project.

**Comment by sjh37** [comment]
ASP.NET Core is on the todo list.
