### ISSUE TITLE
TT filename conflicting with output file.

### ISSUE THREAD

**Issue by ltippmann** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#305]
I've been going a little nuts over this but I think I have it figured out.

Lets say I've added a new reverse poco TT called TestDb.tt to my project.  If I configure the TT to generate multiple files and I set the name of my generated context to be "TestDb", I'm going to end up with a TestDb.cs that only has the header and footer with no TestDb class inside it.  This is because at the end of processing the template, the tooling is going to write whatever is in the GenerationEnvironment to whatever file the template is set to output to, which by default is the name of the template + .cs (so, TestDb.cs in this example case).  There does not seem to be any way to stop this from happening.

I can see two work arounds for this.  One is to go into the .csproj file and manually change the <LastGenOutput> element value under the .tt's <Content> element to something else. I have tested this and it does solve my problem.

I like a more general solution though and I think that's possible with a modification to the base template.  If right before the call to include EF.Reverse.POCO.ttinclude, we could check to see if GenerateSeparateFiles == true, and if so remove any file with the name template.cs (where "template.tt" is the name of the T4 document we're inside) from the Files collection.  The EF6.Utilities.CS.ttinclude file that takes care of turning the Files collection into a bunch of code removes the text that it puts into the individual files when split == true from the GenerationEnvironment StringBuilder as it generates the files.  Whatever is left in that StringBuilder is what goes into the final .cs file the template produces.  As it is now, that should be only the common header and footer all the files share and this is how you end up with a namespace with nothing in it where there should be your context if your context has the same name as your template.  If we just skip removing that file's text from the GenerationEnvironment, its contents should end up being exactly what we want to be written to that file and all will be well.

Ideally this solution would be aware of the name of the file that VS is configured to output for the .tt and work against that.  I can't seem to figure out how to get to that though.  If we were to put this check in place and then I went into the .csproj file and changed the output to something that doesn't share the name of our template, we'd end up not generating a file that we need.

I think I can get most of this worked out and submit a pull request.  Any insight on pulling project info out of VS from inside the TT would be helpful though.

**Comment by sjh37** [comment]
Hi.
I've tried and failed in the past to get it to stop generating an empty <context>.cs file. Drove me crazy for a few hours and I had to give up.
If you can manage it, definately create a pull request. I will gladly accept it!!
You get a gold star if you manage to crack it.

**Comment by ltippmann** [comment]
The bit of research I've done indicates you need to implement your own ITextTemplatingEngineHost implementation and then get Visual Studio to use it to avoid generating an output file with the same name as your .tt with whatever extension you set in the output directive.  That seems like quite a lot more work than I have the time for right now.  Even more so given the minimal payoff of not having some vestigial file left over.

My problem isn't that the empty file is there so much as that it shouldn't be empty.  I like my .tt to have the same name as the DbContext.  This is fine when you're not generating separate files.  At work they like the separate files for source control reasons, which is fine, but suddenly my DbContext class vanishes from the namespace when I turn it on.  Lo and behold, when I open its .cs file, it's just some usings and namespace declaration.  That was an intriguing one to debug.

Anyway, the goal of my patch will be to detect the situation where this happens and avoid it by simply skipping the part where it tries to pop the text of that file out of monolithic block of text the template produced and into its own file.  After the text of every other file has been popped from the original monolithic block, the only thing that should be left is exactly the text that I want in that one file.  I'll just let the templating host do what it normally does and write that stuff out to the file with the same name as the .tt.

I doubt I'll get to this before next week.

**Comment by sjh37** [comment]
Instead of avoiding the empty.cs file, at the end of generating the files, how about you tell visual studio to remove the empty.cs file and delete the file if generate separate files = true?

**Comment by sjh37** [comment]
Related to https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/issues/23

**Comment by ltippmann** [comment]
I tried something dumb and it completely solved the problem.  I changed the last line of the main .tt file to something like this:

    <# if(GenerateSeparateFiles) GenerationEnvironment.Clear(); } #>

(I don't have the code in front of me right now so that's my best approximation off the top of my head).  It seems like if the StringBuilder has zero length, it's not overwriting the file it already wrote with anything.  I didn't get the chance to test if that will completely prevent it from writing an empty file.  Also, I'm not sure what's responsible for installing the EF6 utility.tt (I forget the actual name of the file), but there could be changes in behavior if that file is versioned.  Definitely worth investigating before calling this fixed.

I'll try to throw a patch together this weekend.

**Comment by sjh37** [comment]
Hi @lukeatron I've implemented 
```cs
<# if(GenerateSeparateFiles) GenerationEnvironment.Clear(); } #>
```
I'll close this case for now as it looks to have solved an empty namespace. Ideally it would not generate the file at all, but I think that may be impossible to solve.
Thanks so much for your help!

**Comment by sjh37** [comment]
v2.33.0 Released.
