### ISSUE TITLE
Get error: sequence contains no matching element

### ISSUE THREAD

**Issue by melnac** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#308]
Hi, i use the 2.32 version.
When i generating the POCOs i have no errors but when i use the dbcontext i always get this error.
I leave all the configuration to the default sets.

Can i help me ?
Thanks in advance.

**Comment by sjh37** [comment]
What error is that?

**Comment by melnac** [comment]
Hi Simon,
using the generator with a very huge database, many schema and for each many many tables, when i try to do a linq query i always get ths error indicated.

For example, i try this simple query:

var objs = from x in ctx.TABLENAME select x;

This query return the error " sequence contains no matching element".

During my test i discover that if i split the database for schema, and use a different .tt for each schema, the error not happen.

I use v.2.28 generator.

Do you have any idea ?

Regards, Giuseppe.




----Messaggio originale----

Da: "Simon Hughes" <notifications@github.com>

Data: 12/07/2017 10.20

A: "sjh37/EntityFramework-Reverse-POCO-Code-First-Generator"<EntityFramework-Reverse-POCO-Code-First-Generator@noreply.github.com>

Cc: "melnac"<melnac@libero.it>, "Author"<author@noreply.github.com>

Ogg: Re: [sjh37/EntityFramework-Reverse-POCO-Code-First-Generator] Get error: sequence contains no matching element (#308)




What error is that?

**Comment by sjh37** [comment]
Is it similar to this error: https://stackoverflow.com/a/14433202/5884

Are you using `.First()` or `.Single()` ?

**Comment by melnac** [comment]
HI Simon,
none of these.

i do this query:

 var objs = from x in ctx.TABLENAME select x;

and after do this:

    objs.ToList();

But the error happens directly on the query, not on the materializing.

Is it possible that by the huge number of tables the context was not build in the correct way ?


Regards, Giuseppe.





----Messaggio originale----

Da: "Simon Hughes" <notifications@github.com>

Data: 12/07/2017 18.54

A: "sjh37/EntityFramework-Reverse-POCO-Code-First-Generator"<EntityFramework-Reverse-POCO-Code-First-Generator@noreply.github.com>

Cc: "melnac"<melnac@libero.it>, "Author"<author@noreply.github.com>

Ogg: Re: [sjh37/EntityFramework-Reverse-POCO-Code-First-Generator] Get error: sequence contains no matching element (#308)




Is it similar to this error: https://stackoverflow.com/a/14433202/5884

Are you using .First() or .Single() ?

**Comment by sjh37** [comment]
Its a possiblity. Can you check the generated code for any errors and let me know what you find.

**Comment by melnac** [comment]
Hi Simon,
i try to use the 2.17.1 version that works on others databases and for this huge db i have the same error.

When i splt the db the error not happens. So i think that the problem is really bout the number of tables in the db.

By the way, i get a strange error on tables that have relations.

For example in a table that have 1:many relations, the generator produce this:

// Foreign keys
//HasOptional(a => a.Giochi).WithMany(b => b.Giochi2).HasForeignKey(c => new { c.IdGioco2, c.IdGioco, c.IdGioco });

The error happens on the third parameter c.IdGioco: An anonymous type cannot have multiple properties with the same name.

For how the tables are desinged, the third key is wrong and not to be added. 
The correct relation is:
//HasOptional(a => a.Giochi).WithMany(b => b.Giochi2).HasForeignKey(c => new { c.IdGioco2, c.IdGioco });

It seems that thee is abug that duplicate the key in the relation.

Regards, Giuseppe.

**Comment by sjh37** [comment]
That was fixed on 10/08/2016 and first appeard in v2.23.0

Please update to the latest version.
