### ISSUE TITLE
Special characters in property names from stored procedure results causes invalid C# code

### ISSUE THREAD

**Issue by ErikEJ** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#31]
I have noticed: - (hyphen) and / (forward slash) - not sure if this also would affect other object types (table names for example)

**Comment by sjh37** [comment]
I have a CleanUp function in `EF.Reverse.POCO.Core.ttinclude` that removes non alphanumeric characters. Line 151
So it should work ok. Let me check...

**Comment by sjh37** [comment]
I created a table

``` sql
CREATE TABLE BringTheAction
(
    [$] INT NOT null PRIMARY KEY,
    [%] INT null,
    [£] INT null,
    [&fred$] INT null,
    [abc/\] INT null,
    [joe.bloggs] INT null,
    [simon-hughes] INT null,
    [description] varchar(20) NOT NULL DEFAULT (space((0))),
    someDate DATETIME2(7) NOT NULL DEFAULT (GETDATE())
);
```

and it created

``` c#
public class BringTheAction
{
    public int C36 { get; set; } // $ (Primary key)
    public int? C37 { get; set; } // %
    public int? C163 { get; set; } // £
    public int? C38Fred36 { get; set; } // &fred$
    public int? Abc4792 { get; set; } // abc/\
    public int? Joe46Bloggs { get; set; } // joe.bloggs
    public int? Simon45Hughes { get; set; } // simon-hughes
    public string Description { get; set; } // description (length: 20)
    public System.DateTime SomeDate { get; set; } // someDate
}
```

I found a fault with the configuration
Property(x => x.Abc4792).HasColumnName("abc/\").IsOptional().HasColumnType("int");

the \ needs to be escaped.

**Comment by ErikEJ** [comment]
@sjh37 It is the properties from stored procedure ReturnModel classes, sorry about the confusion

**Comment by sjh37** [comment]
Now then. The stored procedure return columns, they have to be as-is, otherwise they don't map. Could be tricky that one. The only option would be to exclude those return columns so you don't get a compiler error.

**Comment by sjh37** [comment]
For tables, I have made a slight [modification](https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/commit/79739051ce88155e491d1e6d119e1e0e7c9bbc6f)

**Comment by ErikEJ** [comment]
I am not hit by this in production, so closing for now
