### ISSUE TITLE
Rename stored procedure column names

### ISSUE THREAD

**Issue by mrbillo** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#310]
I can't seem to find a way to rename the columns from a stored procedure return model without modifying a .ttinclude file. What's the best way to do this ?

**Comment by sjh37** [comment]
You can't. It's a limitation of EF.
If you did, the data would not get mapped back into the column. It's a shame as I think EF should allow this.

See https://stackoverflow.com/a/9987939/5884
