### ISSUE TITLE
Pascal Case for Return Model for SP and TVF

### ISSUE THREAD

**Issue by Chris3773** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#311]
The UsePascalCase = true; option is not being applied to Stored Procedure and Table Valued Function return models.

**Comment by sjh37** [comment]
Hi Chris,

It's a limitation of EntityFramework.
It's impossible for me to apply this to stored procedure and TVF return models as you would get no data in your return models. The return models have to match precisely.

**Comment by Chris3773** [comment]
I don't think the models to need match precisely by casing at least for TVF, as I have changed the casing of my return models without problems.

Example of whats generated:
```
public class GetFooBooReturnModel
    {
        public System.Int32 id { get; set; }
        public System.Byte booStatusFK { get; set; }
        public System.String fooFK { get; set; }
        public System.Int32 booFK { get; set; }
    }
```
Changed to:
```
public class GetFooBooReturnModel
    {
        public System.Int32 Id { get; set; }
        public System.Byte BooStatusFk { get; set; }
        public System.String FooFk { get; set; }
        public System.Int32 BooFk { get; set; }
    }
```

Both will match, at least in my testing.
