### ISSUE TITLE
Table Extended Property Comments 

### ISSUE THREAD

**Issue by emdadgar2** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#313]
Hi,
Make Table Extended Property Comments in DbContext and DbContext Interface and POCO Class can make life easier for developers!

Thanks for your great product

**Comment by sjh37** [comment]
Comments are already added to the interface, db context and poco classes.
However extended property comments are only added to poco classes as these relate to a specific field.

I will make an exhancement to add an extended property comment at the TABLE level.

**Comment by sjh37** [comment]
Done. This will be in the next release.

**Comment by sjh37** [comment]
v2.33.0 Released.
