### ISSUE TITLE
Syntax Highlighting for .tt configuration file ?

### ISSUE THREAD

**Issue by underwater** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#314]
Just starting with this library and the accompanying pluralsight course... and was just wondering if I need to add any .tt specific software to visualize the .tt config file with syntax highlighting the way it appears in the video course ?  On my PC using VS 2015 (and 2017) it appears without any syntax highlighting.... Although this doesn't seem to impact the code generation, it would make it easier to work with the file if there were syntax highlighting.

**Comment by sjh37** [comment]
I  mention this on the front page under editing T4 files: https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator#editing-tt-t4-files
