### ISSUE TITLE
SQL2016 and medium size DB with separate files throwing lot of errors

### ISSUE THREAD

**Issue by ydlkrishna** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#317]
I am trying to reverse engineer one of my DBs which has a bit more number of tables and SPs that are in my local SQL2016 DB server. The tt file works with single file but taking very long time and throwing errors when I configure to create separate files. PFA file for the error details. I was very confident about this and waiting till last min. of my deliverable and I got stuck, now. Please help. 

[Errors.txt](https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/files/1202118/Errors.txt)

**Comment by sjh37** [comment]
Use filtering to reduce the context size. Just filter to the tables you need. That way it's fast when you are using the small db context. A large db context can take up to a minute to spin up.

**Comment by sjh37** [comment]
@ydlkrishna Any update?
