### ISSUE TITLE
Code generating incorrect OptionalNavigationPropertyConfiguration.WithOptional

### ISSUE THREAD

**Issue by ghost** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#318]
Nugett'd in EF6 and am getting an issue with a mismatch between the use of  **WithOptional** and 
_OptionalNavigationPropertyConfiguration_

**WithOptional** is a member of _RequiredNavigationPropertyConfiguration_ 

But the code getting generated is using _OptionalNavigationPropertyConfiguration_ 

Strangely the column b.EPortfolioPracticeHour is not navigateable.. and the comment for this line is _FK_EPortfolioPracticeHours_EPortfolioHours1_
```c#
HasOptional(a => a.EPortfolioHour).WithOptional(b => b.EPortfolioPracticeHour).WillCascadeOnDelete(fa
HasOptional(a => a.RefEPortfolioPracticeScope).WithMany(b => b.EPortfolioPracticeHours).HasForeignKey
HasOptional(a => a.RefEPortfolioWorkSetting).WithMany(b => b.EPortfolioPracticeHours).HasForeignKey(c
HasRequired(a => a.QualificationRegisterGroup).WithMany(b => b.EPortfolioPracticeHours).HasForeignKey
HasRequired(a => a.RefEPortfolioHoursType).WithMany(b => b.EPortfolioPracticeHours).HasForeignKey(c =
```

```xml
<packages>
  <package id="EntityFramework" version="6.1.3" targetFramework="net461" />
</packages>
```

Has anyone any ideas why this column would be HasOptional with a WithOptional() ??

**Comment by sjh37** [comment]
There is no way to check why its doing that without looking at your SQL for **all the tables involved.**
Could you please post your SQL here so I can look at it?

**Comment by ghost** [comment]
[[EPortfolioPracticeHours].txt](https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/files/1215532/EPortfolioPracticeHours.txt)

![eportfoliopracticehours](https://user-images.githubusercontent.com/2591162/29179823-a847efc6-7ded-11e7-8093-db41a2bd4d87.PNG)

[my.database.tt.txt](https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/files/1215548/my.database.tt.txt)

**Comment by sjh37** [comment]
You forgot to give me the related table SQL. Therefore all I get is:

```c#
blic EPortfolioPracticeHourConfiguration(string schema)
{
    ToTable("EPortfolioPracticeHours", schema);
    HasKey(x => x.Id);

    Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
    Property(x => x.MemberId).HasColumnName(@"MemberId").HasColumnType("int").IsRequired();
    Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime2").IsRequired();
    Property(x => x.WorkSettingId).HasColumnName(@"WorkSettingId").HasColumnType("int").IsOptional();
    Property(x => x.ScopeId).HasColumnName(@"ScopeId").HasColumnType("int").IsOptional();
    Property(x => x.QualificationRegisterGroupId).HasColumnName(@"QualificationRegisterGroupId").HasColumnType("int").IsRequired();
    Property(x => x.EPortfolioHoursTypeId).HasColumnName(@"EPortfolioHoursTypeId").HasColumnType("int").IsRequired();
}
```

**Comment by sjh37** [comment]
Just spotted one of your constrains is turned off with NOCHECK

```sql
ALTER TABLE [dbo].[EPortfolioPracticeHours] NOCHECK CONSTRAINT [FK_EPortfolioPracticeHours_EPortfolioHours1]
```

Try turning it back on with
```sql
ALTER TABLE [dbo].[EPortfolioPracticeHours] CHECK CONSTRAINT [FK_EPortfolioPracticeHours_EPortfolioHours1]
```
