### ISSUE TITLE
Add multiple namespaces

### ISSUE THREAD

**Issue by gilesrpa** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#319]
I am using EF6 and have an issue with the .tt file. To start I have separated the different elements into different folders and have a need to insert multiple namespaces. I have played with the PocoNamespace variable and it works for one namespace, but I cannot get it to accept multiples. I have tried using spaces, commas, vertical lines, semi colons between the namespaces, but nothing works.

Is this currently possible, if so can someone please help.

Some more information.

What I am trying to do is add an abstract interface to the class, as in

    public class myObject : IObjectInterface

Where IObjectInterface sits in a different namespace. So it is this namespace that I need to add a using for.

**Comment by sjh37** [comment]
I show how to do this in the pluralsight course. Have you watched it?
There are special namespace variables in the tt file just near elements to generate variable.

**Comment by gilesrpa** [comment]
Ah yes, I did see this. Unfortunately this was not what I was looking at. What I was thinking was more along the lines of inheriting from a class, so that the code generates something like this.

`
[System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
public class MyTableName : Entity
{
}`

The **Entity** is in the following namespace Core.Infrastructure. 

So at the moment I am having to reference using the fully qualified namespace i.e. 

`
[System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
public class MyTableName : Core.Infrastructure.Entity 
{
}`

This is not a problem, but I was wondering it it is possible to add the reference with a normal using Core.Infrastructure; statement?

I have my ttinclude file to generate separate elements in different folders.

**Comment by sjh37** [comment]
You should be able to do that with the additional namespace variable.

**Comment by gilesrpa** [comment]
Sorry for the delay, I have now managed to fix my issue.

Found the additional namespaces field and added that.

Also, I don't think I was very descriptive, but the question was how to add an "inherited" class.

Modifying the WritePocoBaseClasses function enables me to complete this task.
