### ISSUE TITLE
some stored procedures are not generated

### ISSUE THREAD

**Issue by android8** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#32]
I am using version 2.14.3 and SQL2014.  When I save the .tt file, only some stored procedures are generated even I used the following regex.
StoredProcedureFilterExclude = null;
StoredProcedureFilterInclude = new Regex("usp_.*");

The following sp are generated
App.usp_CCNT_PatientLetterUpdate
App.usp_ChoiceLetterUpdate
App.usp_ColonoscopyRegReminderUpdate
App.usp_ColonoscopyRegReminderUpdate_r2

There are a lot more store procedures are not generated. For example,
App.usp_CMTUserFSRUpdate
App.usp_setUserPreference

I wonder if there something specific in the body of the sp causes the generator to ignore these sp.

Thanks.

**Comment by sjh37** [comment]
can you email me one of the stored procedures that is not generated. simon@hicrest.net

**Comment by android8** [comment]
Here is the stored procedure (usp_CMTUserFSRUpdate) that I really need.  I could and prefer to update the entities in my repository method.  However, our DBA instituted an access restriction on the service account that is used by web applications to only use stored procedure.  I also reviewed the stored procedures that are generated.  They are all plan POCO without method.  The following ColonoscopyRegReminderUpdate and App_UspColonoscopyRegReminderUpdateReturnModel show the SQL statement and class generated.  If this is the class generate for all stored procedures, how am I going to pass parameters to the procedure and obtain the returned object (be it simple data or complex dataset)?

--sotred procedure that is NOT picked up by the Reverse POCO Generator
--=============================================
ALTER PROCEDURE [App].[usp_CMTUserFSRUpdate]
@userId int,
@fsrId int,
@ufsrId int out
AS
SET NOCOUNT ON

set @appId = 2

```
    insert [UserProfile].[UserFacilityServiceRole]
    select @userId, @appId, @fsrid

    select @ufsrId = @@IDENTITY
```

--original stored procedure that is picked up by the Reverse POCO Generator --===============================================
ALTER PROCEDURE [App].[usp_ColonoscopyRegReminderUpdate] 

AS
BEGIN
    SET NOCOUNT ON;

```
    SELECT a.*
    FROM [Registry].[ColonoscopyRegReport] a
        join [App].[vPermissions] b
            on a.Sta3n = b.Sta3n
        left join [App].[vColonoscopyRegFD] c
            on a.PatientSID = c.PatientSID
    WHERE b.ADAccount = 'someaccount'
    AND a.Reminder = 'No'
    AND a.LabResultLabel = '> 30 no lab result'
    AND c.PatientSID is null


    UPDATE [Registry].[ColonoscopyRegReport]
    SET [Reminder] = 'Yes',
    [ReminderUserID] = 'soemeaccount',
    [ReminderDate] = GETDATE()      
    FROM [Registry].[ColonoscopyRegReport] a
        left join [App].[vColonoscopyRegFD] c
            on a.PatientSID = c.PatientSID
    WHERE a.Reminder = 'No'
    AND a.LabResultLabel = '> 30 no lab result'
    AND c.PatientSID is null
```

END

--Generated POCO for above stored proc======================
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Linq.Expressions;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data;
using System.Data.SqlClient;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using System.Threading.Tasks;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace PanelManagement
{
    public partial class App_UspColonoscopyRegReminderUpdateReturnModel
    {
        public Int32 pkeyColonID { get; set; }
        public Int32 PatientSID { get; set; }
        public String PatientName { get; set; }
        public String PatientLastName { get; set; }
        public String PatientFirstName { get; set; }
        public Int32? Sta3n { get; set; }
        public String Age { get; set; }
        public DateTime? DateofDeath { get; set; }
        public String EWL { get; set; }
        public String PCP { get; set; }
        public String SignatureBlockName { get; set; }
        public String SignatureBlockTitle { get; set; }
        public String StreetAddress1 { get; set; }
        public String City { get; set; }
        public String State { get; set; }
        public String Zip { get; set; }
        public String ScreenConsultIEN { get; set; }
        public String ScreenConsult { get; set; }
        public String ScreenStatus { get; set; }
        public String ScreenStatusLabel { get; set; }
        public DateTime? ScreenDate { get; set; }
        public String MonthName { get; set; }
        public Int32? MonthOrder { get; set; }
        public String Contacted { get; set; }
        public String ContactedLabel { get; set; }
        public DateTime? ContactedDate { get; set; }
        public String Reminder { get; set; }
        public String ReminderUserID { get; set; }
        public DateTime? ReminderDate { get; set; }
        public String Order { get; set; }
        public String OrderLabel { get; set; }
        public String OrderStatus { get; set; }
        public String OrderStatusLabel { get; set; }
        public DateTime? OrderDate { get; set; }
        public String Lab { get; set; }
        public String LabLabel { get; set; }
        public String LabResult { get; set; }
        public String LabResultLabel { get; set; }
        public DateTime? LabDate { get; set; }
        public String HighRiskConsultIEN { get; set; }
        public String HighRiskConsult { get; set; }
        public String HighRiskStatus { get; set; }
        public String HighRiskStatusLabel { get; set; }
        public DateTime? HighRiskDate { get; set; }
        public String Reviewed { get; set; }
        public String ReviewedBy { get; set; }
        public String ReviewedByAlias { get; set; }
        public String ReviewedByLabel { get; set; }
        public DateTime? ReviewedDate { get; set; }
        public DateTime ReportDate { get; set; }
        public String FDReviewed { get; set; }
        public String FDReviewedBy { get; set; }
        public String FDReviewedByAlias { get; set; }
        public String FDReviewedByLabel { get; set; }
        public DateTime? FDReviewedDate { get; set; }
    }

}

**Comment by sjh37** [comment]
Two things to try:
1. Remove the filter `StoredProcedureFilterInclude = new Regex("usp_.*");` by setting it to null. See if those appear.
2. Upgrade the generator to the latest version.

Using your `[App].[usp_CMTUserFSRUpdate]` stored procedure, with the latest version of the generator, I get the following generated:

``` c#
public int App_UspCmtUserFsrUpdate(int? userId, int? fsrId, out int? ufsrId)
{
    var userIdParam = new System.Data.SqlClient.SqlParameter { ParameterName = "@userId", SqlDbType = System.Data.SqlDbType.Int, Direction = System.Data.ParameterDirection.Input, Value = userId.GetValueOrDefault(), Precision = 10, Scale = 0 };
    if (!userId.HasValue)
        userIdParam.Value = System.DBNull.Value;

    var fsrIdParam = new System.Data.SqlClient.SqlParameter { ParameterName = "@fsrId", SqlDbType = System.Data.SqlDbType.Int, Direction = System.Data.ParameterDirection.Input, Value = fsrId.GetValueOrDefault(), Precision = 10, Scale = 0 };
    if (!fsrId.HasValue)
        fsrIdParam.Value = System.DBNull.Value;

    var ufsrIdParam = new System.Data.SqlClient.SqlParameter { ParameterName = "@ufsrId", SqlDbType = System.Data.SqlDbType.Int, Direction = System.Data.ParameterDirection.Output, Precision = 10, Scale = 0 };
    var procResultParam = new System.Data.SqlClient.SqlParameter { ParameterName = "@procResult", SqlDbType = System.Data.SqlDbType.Int, Direction = System.Data.ParameterDirection.Output };

    Database.ExecuteSqlCommand("EXEC @procResult = [App].[usp_CMTUserFSRUpdate] @userId, @fsrId, @ufsrId OUTPUT", userIdParam, fsrIdParam, ufsrIdParam, procResultParam);
    if (IsSqlParameterNull(ufsrIdParam))
        ufsrId = null;
    else
        ufsrId = (int) ufsrIdParam.Value;

    return (int) procResultParam.Value;
}
```

**Comment by android8** [comment]
Thank you.  I upgrade to the latest version of POCO Generator.  It picked up the missing stored procedures.  I noticed that if the stored procedure returns recordset, then the generated class will be in a file nested under the .tt.  If the stored return simple data, then POCO Generator generates a method under the Context.cs.  It might have generated the method all along, I just never looked inside the Context.cs.

**Comment by android8** [comment]
I installed the lasted POCO Generator.  Now the stored procedures that return simple data type are generated in the context.cs.  However, those that return recordset are still not generated by POCO Generator.

**Comment by sjh37** [comment]
Try doing a search for the name of the stored procedure, as the return model would be a separate class.
