### ISSUE TITLE
Method 'SaveChangesAsync' in type '' from assembly '' does not have an implementation.

### ISSUE THREAD

**Issue by MADCookie** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#323]
This is very similar to https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/issues/191 where I am running the Web app and receiving that error. 

- I'm using v2.32.0
- My project properties show target .NET 4.5.2
- In the TT file, I didn't see a variable `TargetFrameworkVersion`, so I edited `.Core.ttinclude` and hard coded the setting of the variable `_targetFrameworkVersion = 4.0f;`
- When hard coded, the IContext*.cs file does not generate the two lines for `SaveChangesAsync` and my web site runs without errors.
- My solution is using EntityFramework 6.1.3

Can you help me see what I've misconfigured, please?

**Comment by sjh37** [comment]
Thanks. I'm on holiday at the moment and will look at this when I get back.

**Comment by MADCookie** [comment]
You can close this. I screwed up. My web project didn't have a reference to Entity Framework !!!!
