### ISSUE TITLE
Getting error when attempting to delete parent row

### ISSUE THREAD

**Issue by NaomiN** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#324]
Hi Simon,

In our database we have sec_role table and sec_mbrs and sec_rght tables that have role_no column from sec_role table as FK and have on delete cascade set. I found this thread on stackoverflow for the error message I am getting

https://stackoverflow.com/questions/19325473/ef6-0-the-relationship-could-not-be-changed-because-one-or-more-of-the-foreign

in one of the suggestions I see that we need to have .WillCascadeOnDelete(true); when defining our entity. I searched our project and it doesn't have this portion. We're not on the very latest version of your  generator, do you know if this is part of your generator or not? Is there any other simple way to solve my problem?

**Comment by sjh37** [comment]
Try changing
```c#
cascadeOnDelete ? string.Empty: ".WillCascadeOnDelete(false)");
```
to
```c#
cascadeOnDelete ? ".WillCascadeOnDelete(true)" : ".WillCascadeOnDelete(false)");
```
Please let me know if this fixes your problem

**Comment by NaomiN** [comment]
Hi Simon,

I am sorry, I resolved the problem the other way by always just using Remove in the repository instead of the code we had originally there. It seemed to solve the issue and I didn't dig deeper.

**Comment by sjh37** [comment]
ok thanks
