### ISSUE TITLE
How easy is it to create interfaces for the generated Poco classes

### ISSUE THREAD

**Issue by gilesrpa** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#325]
Hi,

How easy is it to create interfaces for the generated Poco classes?

It is just a thought, but for testing in Moq or JustMock, is there a way of auto generating interfaces from the base Poco object dynamically?

**Comment by sjh37** [comment]
Very easy. Just modify the WritePocoBaseClasses function in your tt file.
