### ISSUE TITLE
CLS compliance

### ISSUE THREAD

**Issue by feldrim** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#328]
Public (or protected if in a public class) properties starting with underscore is CLS-incompliant. Hence,

`public System.Data.Entity.Infrastructure.DbChangeTracker _changeTracker;`

`public System.Data.Entity.Infrastructure.DbContextConfiguration _configuration;`

`public System.Data.Entity.Database _database;`

lines in the `EF.Reverse.POCO.ttinclude` should be private, not public. Even because they have their own public readonly properties, it may not break anything at all.

**Comment by sjh37** [comment]
Thanks. This will be in the next release.

**Comment by sjh37** [comment]
v2.33.0 Released.

**Comment by StevenBonePgh** [comment]
FYI, as a result of this change, you may encounter compiler warning CS0649: 

> Field 'xyz' is never assigned to, and will always have its default value null

 for xyz equaling _changeTracker, _configuration, and _database in the generated Fake*Context.  

To resolve the warnings, you will need to add (or edit) your non-generated FakeContext class implementation of `partial void InitializePartial()` and set them explicitly (even if setting them to null) to remove the warning.

This is not a knock on the fix, but could be a useful note for someone searching issues trying to figure out why there was a new warning or three popping up after upgrading to 2.33.0 or higher.

**Comment by TimSirmovics** [comment]
Should we `#prgama` disable this warning?
