### ISSUE TITLE
Using column.SummaryComments in config to modify column

### ISSUE THREAD

**Issue by elistia** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#332]
I was hoping to be able to use the SQL server column description to modify the way in which columns are processed by the Reverse-POCO-Generator. Specifically, I would like to be able to 'hide' columns by putting 'HIDE' in the description.

For example, in the database.tt

```c#
UpdateColumn = (Column column, Table table) =>
    {
           if(column.SummaryComments == "HIDE")
			  column.Hidden = true;
    }
```

Unfortunately when this code is reached, the SummaryComments property is always null. The description is being read at some point, as the generated code includes the comment as below:

```c#
///<summary>
/// HIDE
///</summary>
public short Outcome { get; set; } // outcome
```

Any idea if this is possible?

**Comment by sjh37** [comment]
Firstly, you should be checking
```c#
if (column.ExtendedProperty == "HIDE")
     column.Hidden = true;
```

The problem is the column extended properties are not read in at that time.
To fix this, I have changed it round so they are read in before the UpdateColumn function is called.

**Comment by elistia** [comment]
That's fantastic Simon, very many thanks :-)

(I have sent you an email)

**Comment by sjh37** [comment]
v2.33.0 Released.
