### ISSUE TITLE
Consider Verifying Database Connection Before Starting Rewrite

### ISSUE THREAD

**Issue by Eric-Hanson** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#335]
One potential enhancement is to perform a quick check verifying database availability before destroying the generated data classes. This change would allow continued development even when disconnected. 

Currently, a developer accidentally saving the configuration file can lose the ability to compile and run tests. It would be nice if disconnected state or logon failure did not result in catastrophic build failure with all data dependencies breaking.

**Comment by sjh37** [comment]
I'm not so sure this is a good idea as it could lead to you assuming that the latest db changes were reverse engineered ok.
You could always roll back using Git/Mercurial.

**Comment by Eric-Hanson** [comment]
We use TFS but the concept is the same - works great to revert if you're connected. Only an issue when disconnected. You're right, making this change can lead to other issues. Either leave it unchanged or maybe leave the generated classes unchanged except for adding a throw exception and comments describing the update failure and cause so the developer has to deal with that before moving forward.
