### ISSUE TITLE
Views do not map.

### ISSUE THREAD

**Issue by plmcguir** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#337]
I have an issue with some of my views.  the POCO's get generated for all views, but the mapping does not - only for some of them.  is there some kind of logging that happens when you 'save' the .tt file to see what the issue may be?
I even created an entire new project (VS2015 sp2).  same problem - same views that do not map.  simple queries - nothing special about them that I can see, and they all open just fine in ssms.
any ideas?

**Comment by sjh37** [comment]
Each table/view in EF must have a primary key, this generator is able to use tables/views that do not have a primary key by using all the NOT NULL columns as a primary key.
However, if your table/view only has NULLable columns, then unfortunately, it cannot be used by Entity framework.

**Comment by sjh37** [comment]
If you change your views to return a primary key column, or a column that is NOT NULLable, they will be included. Let me know if this does not solve your problem and I can re-open this case.

**Comment by techie55** [comment]
Hi, 
I have a Sql Server View which is created by using a CTE (Common Table Expression). Since the view is created by a CTE, all columns are NULLABLE. Is there a way you can change the generator to create this in EF?

**Comment by NaomiN** [comment]
I think there is a trick to make it non-nullable by using COALESCE (or ISNULL) function for the column and providing default expression.

**Comment by NaomiN** [comment]
I think that was my solution for similar problems. If you want, I can provide more details - it was a while ago and I think I researched this issue then.

**Comment by techie55** [comment]
Thanks @NaomiN. Would appreciate if you could provide more details as to how this can be done in Sql Server

**Comment by NaomiN** [comment]
I reviewed a couple of views, I don't remember, unfortunately, which one presented the original problem. Here is one of the samples (the last one will be not nullable column):
select o.op_code as OpCode
     , c.FirstName
     , c.LastName
     , o.role_no as RoleNo
     , o.Hidden
	 , ISNULL(em.EMAddress,'') as EMail
  from dbo.operator o left join dbo.Contacts c on o.ContactId = c.ContactId
  left join dbo.EmailAddresses em ON c.PrefEmId = em.EmId;

----------------------------------------------------------------------
I tried to quickly find the thread either in MSDN or in issues, but was unable to even though I remember posting something.

**Comment by NaomiN** [comment]
Found this https://social.msdn.microsoft.com/Forums/en-US/ea0bf748-bc97-439d-99b0-76180b2161bb/entity-framework-issues-with-views-and-possibly-tables-as-well?forum=adodotnetentityframework which may be somehow related. Need to run now, will search later tonight if that's not enough.

**Comment by NaomiN** [comment]
After many searches I think I found one good thread and found also that my problem most likely was opposite of yours 
https://social.msdn.microsoft.com/Forums/expression/en-US/4a5c1b25-c04c-4913-88e7-3ecfe49aaf4f/what-are-some-best-practices-for-creating-columns-in-a-view-that-are-the-result-of-an-arithmatic?forum=transactsql

**Comment by techie55** [comment]
Hi @NaomiN Thanks a lot for your help. However, my issue is that since I am using a recursive CTE to create my view, Sql Server creates all columns as Nullable. I do not think there is anything I can do on the Sql Server side. The generator needs to be able to generate Classes for views even if all columns are null

**Comment by sjh37** [comment]
Entity Framework has a restriction in that it will only work with tables that have a primary column.
In a view you don't have primary columns as its a select/cte statement returning data that may or may not include primary keys. Primary keys cannot contain NULLable columns. What I do is to include all NOT NULLable columns in as the primary key, even though you will never update the data.

Not sure how feasible it is to artificially create (within the generator) an extra column which will act as a fake primary key. This would allow me to include all views, regardless if they have all nullable columns or not.

**Comment by techie55** [comment]
@sjh37 I was able to fix the Views to have not null columns by specifying a ISNULL condition for my columns while creating the view. Now the generator is able to generate classes for the views. Thanks a lot.
