### ISSUE TITLE
Correct usage of GeneratedCode attribute

### ISSUE THREAD

**Issue by ErikEJ** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#34]
It looks like the guidelines are not followed for partial classes:
https://blogs.msdn.microsoft.com/codeanalysis/2007/04/27/correct-usage-of-the-compilergeneratedattribute-and-the-generatedcodeattribute/

**Comment by sjh37** [comment]
Thanks Erik, learn something new everyday.
So the attribute has to go against everything inside the class for partial, and not at the class level, which would cover the user editable side of the partial class.

**Comment by ErikEJ** [comment]
Yes, that seems to be the recommended approach (it was also new to me, I was just doing some research)

**Comment by andygjp** [comment]
Well thats annoying :(

In my project, I have many custom configurations. When ever I add a new one, I always forget to add to the model which results in a broken system.

You can't just add all configurations to the model as it'll blow up if you add a duplicate configuration file.

I started to keep my custom configurations in a different namespace and I had a function which  automatically added configurations in that namespace to the model, but I'd often forget to place configurations within that namespace - boom.

So in the end changed the function to add EntityTypeConfiguration<T> sub types to the model, but only if they are not decorated with the GeneratedCode attribute. (It was me that made the change to add the attribute.)

I'd like to work with you to come up with a better solution.

Suppose, firstly, should really find out of this a problem for anyone else. (I suspect its not.) Do you, or anyone else for that matter, use custom configurations? Is this a problem for anyone else? How do you add custom configurations to the model?

One option I thought of was to maintain a list of the generated configurations, I can then simply work out which configurations I need to add.

Another could be to move the "get all configurations and add them to the model" code to this repo and then we can make it an option to automatically add all configurations using reflection.

What do you think?

Cheers,
Andy

**Comment by sjh37** [comment]
Hi Andy,
To make sure there is no misunderstanding on my part, I'd need to see some code examples to fully understand what you are talking about.

I personally don't use custom configurations, and I suspect the majority of others won't either.

**Comment by andygjp** [comment]
Hi Simon,

I've copied and pasted some code from my application into a sample console app and turned it into a [Gist](https://gist.github.com/andygjp/bf2701cd85a81e85a1d190e1341e3334). It won't run, but it compiles and it'll help to demonstrate.

The sample comprises of a helper class which identifies all EntityTypeConfiguration<'> sub types that are not decorated with the GeneratedCode attribute. It then enumerates the types and instantiates each one and adds it to DbModelBuilder.Configurations.

A consumer could choose to either use the current method of adding generated configurations, which writes code to the context.cs file that looks like this:

```
protected override void OnModelCreating(System.Data.Entity.DbModelBuilder modelBuilder)
{
    base.OnModelCreating(modelBuilder);

    modelBuilder.Configurations.Add(new MyTable1Configuration());
    modelBuilder.Configurations.Add(new MyTable2Configuration());

    OnModelCreatingPartial(modelBuilder);
}
```

Or another method which calls ConfigurationHelper.AddCustomConfiguration, except without the "ignore generated configuration files" bit.

However, having just said all that, I've just thought of a better method which would avoid adding all this terrible code. Perhaps we could add a "add configuration to model filter". It could work in a similar way to the other lambda based filters in the .tt file. That way, I could modify the filter such that it excludes all configurations and then I can use my terrible code to add all configurations for me automatically.

If you like I can try and turn the above suggestion into a pull request. What do you think?

Cheers,
Andy

**Comment by andygjp** [comment]
@sjh37 I created a pull request: https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/pull/69

Please take a look and see if this is a suitable fix. (Still need to add some comments, but I thought I would be useful to see some code.)

Cheers,
Andy

**Comment by andygjp** [comment]
@sjh37 I meant to add, if this gets accepted I can modify my terrible "add human-generated configurations" code and complete this issue for you too (as a separate pull request).

**Comment by sjh37** [comment]
Thanks @andygjp .
Your code is not terrible! lol. It's actually top notch.

For performance a lot of people use multiple small contexts, say one for orders, and one for finance, all within the project.data library assembly. If we go with an automatic way of detecting the configurations, what's to stop it picking up finance configurations and adding it to the orders model builder?

I guess you would end up with:

``` c#
public class MyContextName : DbContext
{
    ...
    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        modelBuilder.Configurations.AddFromAssembly(typeof(MyContextName).Assembly);
        base.OnModelCreating(modelBuilder);
    }
}
```

or

``` c#
protected override void OnModelCreating(DbModelBuilder modelBuilder)
{
    modelBuilder.AddConfigurations(typeof(MyContextName).Assembly);
    base.OnModelCreating(modelBuilder);
}
```

or

``` c#
public abstract class ByBoxDbContext : DbContext
{
    protected ByBoxDbContext() { }
    protected ByBoxDbContext(string connectionString) : base(connectionString) { }

    private IEnumerable<Type> GetTypes()
    {
        var type = typeof(EntityTypeConfiguration<>);
        return GetType()
            .GetProperties(BindingFlags.Instance | BindingFlags.Public)
            .Where(p => p.PropertyType.IsGenericType &&
                        p.PropertyType.GetGenericTypeDefinition() == typeof(IDbSet<>))
            .Select(p => type.MakeGenericType(p.PropertyType.GetGenericArguments().First()))
            .ToArray();
    }

    private static void LoadAllEntityConfigurationsFromAllAssemblies(DbModelBuilder modelBuilder, IEnumerable<Type> types, string assemblyFilter, IEnumerable<string> namePartFilters)
    {
        var path = Assembly.GetExecutingAssembly().GetDirectoryName();
        new DirectoryCatalog(path, assemblyFilter)
            .LoadedFiles
            .Where(x =>
            {
                var fileNameWithoutExtension = Path.GetFileNameWithoutExtension(x.ToLower());
                if (fileNameWithoutExtension != null)
                {
                    var parts = fileNameWithoutExtension.Split(".".ToCharArray());
                    return parts.Any(part => namePartFilters.Any(namePartFilter => part == namePartFilter.ToLower()));
                }
                return false;
            })
            .Select(Assembly.LoadFrom)
            .ToList()
            .ForEach(assembly => assembly.GetTypes()
                                     .Where(t => types.Contains(t.BaseType))
                                     .Select(Activator.CreateInstance)
                                     .ToList<dynamic>()
                                     .ForEach(instance => modelBuilder.Configurations.Add(instance)));
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        var typesToLoad = GetTypes();
        LoadAllEntityConfigurationsFromAllAssemblies(modelBuilder, typesToLoad, "ByBox*.dll", new[] { "Data", "Domain", "Poco" });
    }
}
```

These all work if we have a single db context, however I worry if we have two are more in the same assembly, which I know a lot of people will have.

**Comment by sjh37** [comment]
Whoops, pressed the wrong button

**Comment by andygjp** [comment]
@sjh37 

I think your last example is spot on - using the generic type of the IDbSet<'> properties of the context to work out the configuration types is a great idea! I'm going to pinch your idea and add it to my system now :smile: - I can get rid of the "only add human-generated configurations" bit.

I don't think they'll be a problem with multiple contexts. (Note, this is just a hypothesis, I've not tested it yet.) If two contexts happen to share an entity and configuration it shouldn't be an issue because they are separate contexts with their own model builder (assuming a context gets its own model builder and there isn't just one per process). Adding a the same configuration to different context shouldn't be an issue, but adding the same configuration to the same context would throw an exception. Was this what you were thinking might cause an issue or are there other possibilities that I'm missing? (Apologies if I've got the wrong end of the stick.)

With your example in place, would we scrap pull request https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/pull/69?

Cheers,
Andy

**Comment by andygjp** [comment]
@sjh37 

I've modified my code. Now it automatically adds configurations if it decorated with a custom attribute. Plus I have an unit test to help identify when I've missed a configuration. Meaning I can correctly implement GeneratedCode attribute if you like.

Cheers,
Andy
