### ISSUE TITLE
Extended Properties in Summary Block

### ISSUE THREAD

**Issue by ThDoor** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#342]
When there are line breaks in extended properties text, the summary block does not add triple / on new lines to signal comment.

How can i get multi line support in extended properties and summary block?

Br,
Thomas

**Comment by ErikEJ** [comment]
I think you need to improve the implementation here: https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/blob/master/EntityFramework.Reverse.POCO.Generator/EF.Reverse.POCO.Core.ttinclude#L2459

**Comment by ThDoor** [comment]
or in the tt where there's an action for tables (and function for columns):
  Action<Table> WritePocoClassExtendedComments = t =>
    {
        if (IncludeExtendedPropertyComments != CommentsStyle.None && !string.IsNullOrEmpty(t.ExtendedProperty))
        {
            WriteLine("    ///<summary>");
            WriteLine("    /// {0}", System.Security.SecurityElement.Escape(t.ExtendedProperty));
            WriteLine("    ///</summary>");
        }
    };

where you could do a replace - from newline to '///' + newline. This will give you the same line breaks in summary as in extended props - or some regex searching for both \r\n or \n.

Something like that :-)

br,
Thomas

**Comment by sjh37** [comment]
This will be in the next release.

**Comment by sjh37** [comment]
Released in v2.34.0
