### ISSUE TITLE
ColumnUpdate can't filter out anymore

### ISSUE THREAD

**Issue by phofman** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#348]
In previous versions (example: v2.31), it was possible to filter out column, while performing update by simply returning null to the caller of ColumnUpdate(). In current version v2.33 this functionality is broken and the column still stays in table definition.

Scenario: I have a column 'LastUpdated', which is automatically populated (have triggers and default value etc.) and I want it to be removed from all tables (models) except ones that belong to 'dbo' schema and few other named directly tables.

**Comment by sjh37** [comment]
Set the column to hidden

**Comment by phofman** [comment]
It did the job.

Thanks a lot!
