### ISSUE TITLE
AdditionalContextInterfaceItems on FakeDBContext

### ISSUE THREAD

**Issue by jondavis9898** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#349]
When the setting "AdditionalContextInterfaceItems" contains items, the generated FakeDBContext generates an implementation for each one with a "throw new System.NotImplementedException()".

The challenge with this approach is that there is no way to implement any logic in the generated method without directly modifying the generated FakeDBContext file since the method isn't marked virtual (to allow for a derived implementation).

AdditionalContextInterfaceItems are not generated in the "real" DBContext and I think the same approach should be applied to the FakeDBContext.  This would allow MakeClassesPartial to be set to true and an implementation for the items to be created in a partial FakeDBContext class.

Depending on your thoughts on this, I'm happy to make the change and submit a PR.

Thank you!

**Comment by sjh37** [comment]
Like the idea. Pull the latest code and make a PR. Thanks.

**Comment by jondavis9898** [comment]
PR submitted, thank you!

**Comment by sjh37** [comment]
Thanks, this will be in the next release

**Comment by sjh37** [comment]
Released in v2.34.0
