### ISSUE TITLE
sys.extended_properties

### ISSUE THREAD

**Issue by mwoffenden** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#35]
I need to be able to create a POCO class that maps to sys.extended_properties.  Can the generator currently support this?

**Comment by sjh37** [comment]
Not directly, but I do already include extended properties.

I use the following sql

``` sql
SELECT  s.name AS [schema],
        t.name AS [table],
        c.name AS [column],
        value AS [property]
FROM    sys.extended_properties AS ep
        INNER JOIN sys.tables AS t
            ON ep.major_id = t.object_id
        INNER JOIN sys.schemas AS s
            ON s.schema_id = t.schema_id
        INNER JOIN sys.columns AS c
            ON ep.major_id = c.object_id
               AND ep.minor_id = c.column_id
WHERE   class = 1
ORDER BY t.name
```

and set the Column ExtendedProperty as follows

``` c#
string extendedProperty = rdr["property"].ToString().Trim();
col.ExtendedProperty = extendedProperty.Replace("\n", " ").Replace("\r", " ");
```

If you want/need to capture more data from `sys.extended_properties` then alter the ExtendedPropertySQL in `EF.Reverse.POCO.Core.ttinclude` and change the function ReadExtendedProperties() how you need it.
