### ISSUE TITLE
Adding new Item - Reverse POCO

### ISSUE THREAD

**Issue by mestricDev** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#350]
Hi, 
Upon adding a new item POCO to the project I get the following warning (textbox):
The reference "System" could not be added to the project.

When the code gets generated, I always have to manually add the:
using System.Data.Entity;
The generated code looks like this:
 public class TestDbContext : DbContext
    {
        public System.Data.Entity.DbSet<GhCustomInvoice> GhCustomInvoices { get; set; } 
   ....
etc.
Your examples are without the System.Data.Entity, just public DbSet<> and i can't figure out why mine aren't. I also had to add the System.DataEntity in References.

The project is ASP.Net Core 2.0, - VS2017 Community 15.4.4

Any help appreciated.

**Comment by Chris3773** [comment]
I tried on a new ASP.Net Core 2.0 project and didn't have any problems with generating.

So you don't need to add manually every time, you can add the reference to the "AdditionalNamespaces" under the generator options.
