### ISSUE TITLE
Missing using in configuration files

### ISSUE THREAD

**Issue by hossein-abdn** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#353]
Hi.
When [ElementsToGenerate = Elements.PocoConfiguration] and [UseDataAnnotations = true] in configuration files, [System.ComponentModel.DataAnnotations.Schema] not generated and <The name 'DatabaseGeneratedOption' does not exist in the current context> is appeared because of this line:

`Property(x => x.Id).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);`

**Comment by sjh37** [comment]
Is `UseDataAnnotationsSchema = true;` ?

**Comment by hossein-abdn** [comment]
No. UseDataAnnotationsSchema = false;

**Comment by sjh37** [comment]
Try setting it to true.

**Comment by sjh37** [comment]
Thanks for reporting this. Fixed. This will be in the next release.

**Comment by sjh37** [comment]
Released in v2.34.0
