### ISSUE TITLE
EF.Reverse.POCO.Core.ttinclude error

### ISSUE THREAD

**Issue by bbieb** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#354]
I started using the latest version today 2.34.0 and am getting the following error.  Any hints on how to correct?
brian

![image](https://user-images.githubusercontent.com/13998759/33398490-c53e7784-d514-11e7-802d-cb34b4de822b.png)

**Comment by yongding422** [comment]
I had the same issue, it works in VS2017, but it doesn't work in VS2015, I think it is because the version of T4 generation tool are different.

**Comment by bbieb** [comment]
I am using VS2015 so that might explain it.  I ended up copying an older version of the generator into my project and it is working as expected.

**Comment by sjh37** [comment]
Thanks guys, I'll investigate the VS2015 issue. Unless you can beat me to the fix 👍

**Comment by ErikEJ** [comment]
Using C# 7 features by mistake?

**Comment by sjh37** [comment]
Released v2.34.1

**Comment by donamk** [comment]
This bug come out in my VS 2013 with .NET 4.5.2 console project and Reverse POCO Generator 2.35.0

**Comment by sjh37** [comment]
@donamk pull the latest code from github, and copy the ttinclude files to your project. Can you let me know if fixes it for you as I made further changes yesterday.
