### ISSUE TITLE
FR: possibility to set where (what directory) are POCO and mapping files generated and/or generate them into 2 diff. projects

### ISSUE THREAD

**Issue by hidegh** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#358]

**Comment by sjh37** [comment]
I show how to do this on the pluralsight course. Please watch "Organising The Generated Code" https://app.pluralsight.com/player?course=code-first-entity-framework-legacy-databases&author=simon-hughes&name=code-first-entity-framework-legacy-databases-m4&clip=0&mode=live

Basically create a copy of the generator in the folder you want the pocos generated and set the EntitiesTo Gnerate = poco.
