### ISSUE TITLE
A namespace cannot directly contain members such as fields or methods

### ISSUE THREAD

**Issue by YakupIpek** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#36]
I am having exception "A namespace cannot directly contain members such as fields or methods".
https://gyazo.com/7d4c0d1ffae9bfafad2bc7b294928fcc

I tested it on Visual Studio 2015 update 2 with latest Template on new project but i am always getting this error after adding and generator failing to generate poco classes.

**Comment by sjh37** [comment]
Install Entity Framework 6 Tools available [here ](https://www.microsoft.com/en-us/download/details.aspx?id=40762) This installs the required EF6.Utility.CS.ttinclude which is used for pluralisation You only need to do this once.

I thought VS2015 already included EF6.Utility.CS.ttinclude as part of the install. Have a search for the file to see if it is on your hard drive.

**Comment by PatrickMcDonald** [comment]
This [discussion](http://entityframework.codeplex.com/discussions/401836) on CodePlex is relevant to Visual Studio 2012, but may apply to 2015 also.

They suggest modifying the Visual Studio installation to include **Microsoft Web Developer Tools** or **Microsoft SQL Server Data Tools** to get `EF6.Utility.CS.ttinclude` onto your machine.

On my machine (Visual Studio 2015 Update 1), this file is located in 

> `C:\Program Files\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Entity Framework Tools\Templates\Includes`

**Comment by sjh37** [comment]
I am going to close this issue as the solution is to install one or all of the below to obtain the `EF6.Utility.CS.ttinclude` file.
- Install Entity Framework 6 Tools
- Install Microsoft Web Developer Tools
- Install Microsoft SQL Server Data Tools
