### ISSUE TITLE
string configFilePath as input parameter to pass in external config file directory

### ISSUE THREAD

**Issue by ellentan17** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#361]
we have multiple entity framework projects sharing 1 single web config. The web config file at a share folder outside the projects.
Can the poco pass the configFilePath as input parameter when get the connection string?

**Comment by sjh37** [comment]
No quite sure what you mean. The poco's are generated, and are therefore not passing configFilePath elements anywhere, nor are they generated to pass config file paths around either. They are completely ignorant of anything database related as that is all handled by the dbcontext.

If you mean, "can the generator pass the configFilePath as input parameter when get the connection string?". Then the answer is no. The generator outputs comments to say what the connection string was, such as:
```c#
// The following connection settings were used to generate this file:
//     Configuration file:     "EntityFramework.Reverse.POCO.Generator\App.config"
//     Connection String Name: "MyDbContext"
//     Connection String:      "Data Source=(local);Initial Catalog=some_database;Integrated Security=True;Application Name=EntityFramework Reverse POCO Generator"
```

How you spin up your database context is up to you, although I would strongly recommend you configure your connection string and use a IOC/DI container such as CastleWindsor/Autofac/etc.
