### ISSUE TITLE
Question about entity generation

### ISSUE THREAD

**Issue by MarcusBananus** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#362]
Hello, is there a way to generate the entities in another project?
or have two tt file that will do the trick....

So I would have : 
myproject.data for the dbContext and configurations
myproject.entities for the entities so I can reuse them

thanks!

**Comment by sjh37** [comment]
Hi Marcus.
Use 2 tt files, and specify the relevant things you want generated in that folder, such as poco, or db context. etc.
I show how to do this in the pluralsight course if you want to see it done step by step.

**Comment by MarcusBananus** [comment]
Thank you very much for your quick response!
