### ISSUE TITLE
Validation Error with non-nullable Foreign Keys

### ISSUE THREAD

**Issue by andy-timetrak** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#363]
I am running into the following error when trying to run a web portal project that includes a reference to my model library:

Multiplicity conflicts with the referential constraint in Role 'LayoutPageContent_LayoutPage_Target' in relationship 'LayoutPageContent_LayoutPage'. Because all of the properties in the Dependent Role are non-nullable, multiplicity of the Principal Role must be '1'.

This problem seems to happen anywhere I havea Foreign Key column set to NOT NULL in SQL Server. Any tables where I have the foreign key nullable appear to work correctly. For example:

Primary Key Table (LayoutPages)
```sql
CREATE TABLE [dbo].[LayoutPages](
	[LayoutPageId] [uniqueidentifier] NOT NULL,
	[Name] [varchar](50) NULL,
	[Label] [varchar](75) NULL,
	[Description] [varchar](200) NULL,
	[PageMode] [tinyint] NULL,
 CONSTRAINT [PK_LayoutPages] PRIMARY KEY CLUSTERED 
(
	[LayoutPageId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[LayoutPages] ADD  CONSTRAINT [DF_LayoutPages_LayoutPageId]  DEFAULT (newid()) FOR [LayoutPageId]
GO
```
Foreign Key Table (LayoutPageContent) 
```sql
CREATE TABLE [dbo].[LayoutPageContent](
	[LayoutPageContentId] [uniqueidentifier] NOT NULL,
	[Name] [varchar](50) NULL,
	[Label] [varchar](75) NULL,
	[Description] [varchar](200) NULL,
	[ContentDefinition] [varchar](max) NULL,
	[LayoutPageId] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_LayoutPageContent] PRIMARY KEY CLUSTERED 
(
	[LayoutPageContentId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[LayoutPageContent] ADD  CONSTRAINT [DF_LayoutPageContent_LayoutPageContentId]  DEFAULT (newid()) FOR [LayoutPageContentId]
GO

ALTER TABLE [dbo].[LayoutPageContent]  WITH NOCHECK ADD  CONSTRAINT [FK_LayoutPageContent_LayoutPages] FOREIGN KEY([LayoutPageId])
REFERENCES [dbo].[LayoutPages] ([LayoutPageId])
NOT FOR REPLICATION 
GO

ALTER TABLE [dbo].[LayoutPageContent] NOCHECK CONSTRAINT [FK_LayoutPageContent_LayoutPages]
GO
```
I would prefer to have the columns marked not null since the record should not exist without that column populated, but, I can work around this for now. I'm hoping there is just an option I've missed somewhere, but wanted to check and make sure.

**Comment by andy-timetrak** [comment]
Additional data - I was looking at the generated code, and I think the only issue is that "HasOptional" is being used instead of "HasRequired". In the code below, I tried commenting out the generated line and replacing it with HasRequired, and the validation error goes away.
```
// Foreign keys
//HasOptional(a => a.LayoutPage).WithMany(b => b.LayoutPageContents).HasForeignKey(c => c.LayoutPageId).WillCascadeOnDelete(false); // FK_LayoutPageContent_LayoutPages
HasRequired(a => a.LayoutPage).WithMany(b => b.LayoutPageContents).HasForeignKey(c => c.LayoutPageId).WillCascadeOnDelete(false);
```
I also should have mentioned I am using version 2.34.1. Let me know if there is anything else that would help.

Thanks!

**Comment by sjh37** [comment]
before I look into this I spotted your PK's are a guid, and the default value is not using a sequential guid, but rather a newid which is random. The clustered key forces the data in the table to be sorted physically in that order, hence why they are so fast. Therefore clustered keys should be append only. Given NewID() is random, your table will be resorted on every insert, really hurting performance. I suggest you change your default to NEWSEQUENTIALID() instead, which is sequential and the table will not need resorting upon insert.

**Comment by andy-timetrak** [comment]
There is a lot of information out there on sequential vs non sequential IDs, so it is not easy to come up with a good sense of what approach makes the most sense. Your comment actually does make sense, and I don't remember seeing it explained that way before. I will check into that again - thanks for the feedback. 

Also, I came across a table where HasRequired was applied correctly to a NOT NULL foreign key column. That table has the foreign key defined the following way:
```
ALTER TABLE [dbo].[GOInstances]  WITH CHECK ADD  CONSTRAINT [FK_GoInstances_CustomerId] FOREIGN KEY([CustomerId])
REFERENCES [dbo].[GOCustomers] ([GOCustomerId])
```
So is the decision based on the CHECK / NOCHECK option instead of NULL / NOT NULL?

**Comment by sjh37** [comment]
This is done via:

```c#

// HasOptional
// HasRequired
// HasMany
private static string GetHasMethod(Relationship relationship, Column fkCol, Column pkCol, bool isNotEnforced)
{
    bool withMany = false;
    switch (relationship)
    {
        case Relationship.ManyToOne:
        case Relationship.ManyToMany:
            withMany = true;
            break;
    }

    if (withMany || pkCol.IsPrimaryKey)
        return fkCol.IsNullable || isNotEnforced ? "Optional" : "Required";

    return "Many";
}
```

**Comment by sjh37** [comment]
The sql to obtain the FK's is

```sql
SELECT  FK.name AS FK_Table,
        FkCol.name AS FK_Column,
        PK.name AS PK_Table,
        PkCol.name AS PK_Column,
        OBJECT_NAME(f.object_id) AS Constraint_Name,
        SCHEMA_NAME(FK.schema_id) AS fkSchema,
        SCHEMA_NAME(PK.schema_id) AS pkSchema,
        PkCol.name AS primarykey,
        k.constraint_column_id AS ORDINAL_POSITION,
        CASE WHEN f.delete_referential_action = 1 THEN 1 ELSE 0 END as CascadeOnDelete,
        f.is_disabled AS IsNotEnforced
FROM    sys.objects AS PK
        INNER JOIN sys.foreign_keys AS f
            INNER JOIN sys.foreign_key_columns AS k
                ON k.constraint_object_id = f.object_id
            INNER JOIN sys.indexes AS i
                ON f.referenced_object_id = i.object_id
                   AND f.key_index_id = i.index_id
            ON PK.object_id = f.referenced_object_id
        INNER JOIN sys.objects AS FK
            ON f.parent_object_id = FK.object_id
        INNER JOIN sys.columns AS PkCol
            ON f.referenced_object_id = PkCol.object_id
               AND k.referenced_column_id = PkCol.column_id
        INNER JOIN sys.columns AS FkCol
            ON f.parent_object_id = FkCol.object_id
               AND k.parent_column_id = FkCol.column_id
```

**Comment by andy-timetrak** [comment]
I will investigate a little further with the query you provided and see if I can identify anything. Everything makes sense, but I'm obviously getting an odd result for some reason.

**Comment by andy-timetrak** [comment]
For the benefit of other developers, the bulk of my problems were being caused by the relationships using NOCHECK, so this caused the query shown above to indicate that relationship was not being enforced. Reviewed all of my databases relationships to make sure they were correctly setup and this seems to have cleared up the described issue. Have been running the app for about five or six weeks now using the EF model generated with this tool, and haven't run into this issue.

**Comment by NaomiN** [comment]
Hi Andy,

I read this discussion (quite interesting) and here is an extra link supporting earlier statement by Simon:
http://blogs.lessthandot.com/index.php/datamgmt/dbprogramming/best-practice-don-t-not-cluster-on-uniqu/

**Comment by andy-timetrak** [comment]
Appreciate the link. I have read a lot of discussion on both sides of the argument, and I still have to figure out how we're going to handle the GUIDs being generated from our applications and not from our database. So, this is a bigger deal to us than just changing the default value in the database primary keys.

**Comment by NaomiN** [comment]
If you're using .NET, I think there is a way to create sequential guid from C#. You need to google on this topic.

**Comment by andy-timetrak** [comment]
That is the plan once I have time to actually research it and come up with a solution that will address everything we will be using.

**Comment by sjh37** [comment]
@andy-timetrak You always have the option of changing the primary key to be not clustered.

**Comment by 0xced** [comment]
I also stumbled on this issue. I noticed that some contraints are added `WITH NOCHECK`. Since I don't have the rights to modify the database structure, I worked around by modifying the `ForeignKeyProcessing` setting like this, using reflection since `IsNotEnforced` is private set 😕:
```c#
Settings.ForeignKeyProcessing = (foreignKeys, fkTable, pkTable, anyNullableColumnInForeignKey) =>
{
    var foreignKey = foreignKeys.First();
    foreignKey.GetType().GetProperty("IsNotEnforced").SetValue(foreignKey, false);
    return foreignKey;
};
```
After doing this, the model becomes valid for Entity Framework and the *Multiplicity conflicts with the referential constraint in Role* exceptions disappear.

**Comment by sjh37** [comment]
@0xced I have allowed the ForeignKey.IsNotForced to be changed. This will be in the next release. For now, you can update your code to remove the `private` from that property.
See changeset https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/commit/1038416ef0867be78e674463de626b34fdd38ea5

**Comment by 0xced** [comment]
Shouldn't we completely drop the `IsNotEnforced` setting and use only the nullable information? If a foreign key constraint is not enforced, the generator produces a model which is not valid for Entity Framework and throws. It can even generate code that does not even compile with a combination of `HasOptional` + `WithOptional`.

**Comment by sjh37** [comment]
@0xced I'll investigate

**Comment by sjh37** [comment]
@0xced I have managed to replicate the issue with the following sql
```sql
CREATE TABLE ForeignKeyIsNotEnforced     ( id int NOT NULL IDENTITY(1,1) PRIMARY KEY, null_value INT NULL, not_null_value INT NOT NULL );
CREATE TABLE ForeignKeyIsNotEnforcedItem ( id int NOT NULL IDENTITY(1,1) PRIMARY KEY, null_value INT NULL, not_null_value INT NOT NULL );
ALTER TABLE ForeignKeyIsNotEnforced ADD CONSTRAINT [UQ_ForeignKeyIsNotEnforced_null_value] UNIQUE NONCLUSTERED (null_value);
ALTER TABLE ForeignKeyIsNotEnforced ADD CONSTRAINT [UQ_ForeignKeyIsNotEnforced_not_null_value] UNIQUE NONCLUSTERED (not_null_value);
ALTER TABLE ForeignKeyIsNotEnforcedItem ADD CONSTRAINT [UQ_ForeignKeyIsNotEnforcedItem_null_value] UNIQUE NONCLUSTERED (null_value);
ALTER TABLE ForeignKeyIsNotEnforcedItem ADD CONSTRAINT [UQ_ForeignKeyIsNotEnforcedItem_not_null_value] UNIQUE NONCLUSTERED (not_null_value);
GO
ALTER TABLE ForeignKeyIsNotEnforcedItem WITH NOCHECK ADD CONSTRAINT [FK_ForeignKeyIsNotEnforcedItem_null_null] FOREIGN KEY(null_value) REFERENCES ForeignKeyIsNotEnforced (null_value);
ALTER TABLE ForeignKeyIsNotEnforcedItem WITH NOCHECK ADD CONSTRAINT [FK_ForeignKeyIsNotEnforcedItem_null_notnull] FOREIGN KEY(null_value) REFERENCES ForeignKeyIsNotEnforced (not_null_value);
ALTER TABLE ForeignKeyIsNotEnforcedItem WITH NOCHECK ADD CONSTRAINT [FK_ForeignKeyIsNotEnforcedItem_notnull_null] FOREIGN KEY(not_null_value) REFERENCES ForeignKeyIsNotEnforced (null_value);
ALTER TABLE ForeignKeyIsNotEnforcedItem WITH NOCHECK ADD CONSTRAINT [FK_ForeignKeyIsNotEnforcedItem_notnull_notnull] FOREIGN KEY(not_null_value) REFERENCES ForeignKeyIsNotEnforced (not_null_value);
```

**Comment by sjh37** [comment]
This is now fixed, and was a very simple fix in the end. This will be in the next release.

**Comment by 0xced** [comment]
I guess you meant *this* changeset: 003fdda987bc8f0d7202a231e637c8b0f68223aa. Anyway, thanks for solving this issue.
