### ISSUE TITLE
generate entities to another project/namespace, ok, but why say 'folder'?

### ISSUE THREAD

**Issue by kimballjohnson** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#372]
In the following example, you describe how to generate pieces of the output into different 'places'. 
You seem to say the tool will not generate to another assembly, which is a reasonable exclusion.
but what exactly are you suggesting with the word 'folder' and 'add the "EntityFramework Reverse POCO Code First Generator" into each of these folders'? 
Thanks,
Kimball Johnson

actually, in re-reading this, I've got some other specific questions;
1. multiple 'projects'? do you mean a VS project producing an assembly?
2. 'where the elements now live'? 'where it lives' usually means 'where it resides', 'where it can be found'. Is that what you mean? 
3. 'does not create the files... it only adds a using statement' - where is that added? in a namespace? the files aren't created at all?
4. 'into these folders' - this is the first time you mention folders - what folders?
You seem to be presuming some shared understanding that I am missing
 // Elements to generate ***************************************************************************************************************
    // Add the elements that should be generated when the template is executed.
    // Multiple projects can now be used that separate the different concerns.
    Settings.ElementsToGenerate = Elements.Poco | Elements.Context | Elements.UnitOfWork | Elements.PocoConfiguration;

    // Use these namespaces to specify where the different elements now live. These may even be in different assemblies.
    // Please note this does not create the files in these locations, it only adds a using statement to say where they are.
    // The way to do this is to add the "EntityFramework Reverse POCO Code First Generator" into each of these folders.
    // Then set the .tt to only generate the relevant section you need by setting
    //      ElementsToGenerate = Elements.Poco; in your Entity folder,
    //      ElementsToGenerate = Elements.Context | Elements.UnitOfWork; in your Context folder,
    //      ElementsToGenerate = Elements.PocoConfiguration; in your Maps folder.
    //      PocoNamespace = "YourProject.Entities";
    //      ContextNamespace = "YourProject.Context";
    //      UnitOfWorkNamespace = "YourProject.Context";
    //      PocoConfigurationNamespace = "YourProject.Maps";
    // You also need to set the following to the namespace where they now live:
    Settings.PocoNamespace = "webapibk.Entity";
    Settings.ContextNamespace = "";
    Settings.UnitOfWorkNamespace = "";
    Settings.PocoConfigurationNamespace = "";

**Comment by sjh37** [comment]
1. Multiple projects - A single solution, with multiple cs projects.
2. Lives - Which namespace the elements reside in.
3. If the following variables contain a namespace, then these are added to the generated code. If the poco's are generated in namespace `abc`, and the context is generated in namespace 'def', you would setup the following:
```c#
Settings.PocoNamespace = "abc";
Settings.ContextNamespace = "def";
Settings.UnitOfWorkNamespace = "";
Settings.PocoConfigurationNamespace = "";
```
4. You can generate code in sub-folders within a single project, OR generate code in separate projects.

**Please watch the Pluralsight course**. I explain all this in chapter 4 [Organising the generated code](https://app.pluralsight.com/player?course=code-first-entity-framework-legacy-databases&author=simon-hughes&name=code-first-entity-framework-legacy-databases-m4&clip=0&mode=live)
