### ISSUE TITLE
Feature Request: Please add a way to manually set which columns are the primary key of a view

### ISSUE THREAD

**Issue by tpancoast** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#375]
As discussed in other issues, Reverse POCO must infer the primary key of a view based on which columns are not NULLABLE. This is sometimes the correct solution, but it doesn't always work. There are multiple workarounds, but it would be much easier to maintain if there was a way to set which columns of a view to treat as a the primary key.

**Comment by hidegh** [comment]
I'd go for a regex (conventions) to define primary key candidates for views.

**Comment by sjh37** [comment]
Hi, This was implemented as part of #432

**Comment by tpancoast** [comment]
Yay! Thanks for the update.
