### ISSUE TITLE
V2.35 Visual Studio 2015

### ISSUE THREAD

**Issue by mshauny** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#376]
Hi there,

Version V2.35 does not seem to be compatible with Visual Studio 2015, I think this could be due to the usage of the new C# syntax and features not supported. 
![image](https://user-images.githubusercontent.com/3635959/35607901-544b567e-065f-11e8-8641-735c2c8ab501.png)

**Comment by sjh37** [comment]
This should be fixed. Try pulling in the latest code from GitHub and copy the .ttinclude files to your project and let me know how you get on.

**Comment by sjh37** [comment]
Released in v2.36.0.
