### ISSUE TITLE
Extracting SETTINGS into a separate file and referencing it in the template

### ISSUE THREAD

**Issue by hidegh** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#378]
i'd like to keep settings on changes but would consider use new T4 templates. it's a hard work of 30 mins to set up everything correctly, then another 15 mins to fine-tune it...

**Comment by sjh37** [comment]
how about creating a separate settings file and reference that including it at the bottom of the database.tt file.
```c#
    // bottom of file
#>
<#@ include file="hidegh.ttinclude" #>                    // <- ***************
<#@ include file="EF.Reverse.POCO.ttinclude" #>
<#  }
    if(Settings.GenerateSeparateFiles)
        GenerationEnvironment.Clear();#>
```

This settings file would over-ride any defaults.

**Comment by hidegh** [comment]
hints on how it was done, here: https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/issues/470
