### ISSUE TITLE
Cannot have readonly primary key field

### ISSUE THREAD

**Issue by SoulFireMage** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#382]
This is quite peculiar. I was getting a problem Add objects to a table via table.Add(new object) method. However, despite not including the primary key, it was not behaving at all.

![image](https://user-images.githubusercontent.com/2396080/36494725-d954f9d4-172a-11e8-8b2c-c24d0fcc31ae.png)

So in my wisdom decided to try and make the primary key field in this table readonly only to get this:

![image](https://user-images.githubusercontent.com/2396080/36494780-077f918e-172b-11e8-9396-44dfe93edee7.png)

I've googled a fair bit, but cannot see a straight answer. The tables do have correct primary keys.

I'm still assuming EF6 needs to be told that the Primary key field is actually readonly somehow?

Thanks for any help or advice. 

Thank you

**Comment by SoulFireMage** [comment]
I found a way round it in the end, needed separate contexts - I usually hide this work in separate layers but the project is too small to need that.

**Comment by sjh37** [comment]
Glad you got it sorted Richard. Sorry I didn't reply earlier. Just landed back in the UK after a holiday with the Family. 




Regards,


Simon Hughes







On Thu, Feb 22, 2018 at 2:00 PM +0000, "Richard Griffiths" <notifications@github.com> wrote:












I found a way round it in the end, needed separate contexts - I usually hide this work in separate layers but the project is too small to need that.
