### ISSUE TITLE
without saving, reverse poco run

### ISSUE THREAD

**Issue by superbmilkyway** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#383]
I think how can I prevent this behavior.

I  followed your pluralsight course, I create 3 separate tt (Entities, Context, Configuration).

When I change tt file and did not save yet and move to entity file to look at something,
reverse poco run regenerated file even if I did not save tt file yet.

In my humble opinion, it should run only I save tt file.  

VS 2017 15.5.6+ Reverse Poco  2.36.0

**Comment by sjh37** [comment]
Hi.
I can't prevent Visual Studio from running an unsaved TT file when you look at another file. I don't know why it does it, but I too find it annoying.
