### ISSUE TITLE
Return models for stored procedures with fake data contracts

### ISSUE THREAD

**Issue by prashantadepu** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#387]
We have quite a few stored procedures with temporary tables and we used fake data contracts (something like one answered [here](https://stackoverflow.com/a/16594665/5884) ) for EF to recognize result sets. The generator generates return models if I use Set FMTONLY OFF for these but not if I use fake data contracts. Any way generator automatically generates return models for SP's with fake data contracts or am I missing something? 

I am working with latest version(2.36.1) of generator in VS 2017.

**Comment by sjh37** [comment]
This is a common problem with Sql Server. It's actually SQL Server that tells me what will be returned.
To obtain the result set I use:
```sql
SET FMTONLY OFF;
SET FMTONLY ON;
exec [proc_schema].[proc_name] @parameter1, @parameter2, @etc
SET FMTONLY OFF;
SET FMTONLY OFF;
```

And I save what columns are returned in a C# result set.
If you use temporary tables, it seems to confuse SQL Server. Have a play around and see what works for you. There is nothing I can do in this project. I could try calling the stored proc in a different way to see if that helps. I'm sure there is already a case raised for this in GitHub, so will close this one.
