### ISSUE TITLE
Setting MakeClassesInternal to true makes the constuctors internal as well

### ISSUE THREAD

**Issue by ltippmann** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#392]
When setting the MakeClassesInternal flag to true, the access modifier of the DbContext constructors is changed to internal as well.  This change is not necessary as the scope of a public constructor on an internal class is effectively internal anyway.  

There is an instance where this is causing me a problem.  I have an abstract base class that encapsulates my a DbContext.  I want to take the type of DbContext to be wrapped as a generic parameter with the constraints `where TDbContext: DbContext, new()`. For the `new()` constraint to work, the class must have a public parameterless constructor.  An internal parameterless constructor isn't good enough to make the compiler happy.

I have been changing EF.Reverse.POCO.ttinclude file locally to make it work for my uses but I figured I might as well push this upstream.  There is no other impact I can think of to making the default constructor public instead of internal unless some one is using reflection with the internal binding flag or some other backwards way of getting to the default constructor.

I have a pull request ready to go that only changes the default constructor to always be public, regardless of the MakeClassesInternal flag.

**Comment by sjh37** [comment]
Thanks. This will be in the next release.

**Comment by sjh37** [comment]
Released in v2.37.0
