### ISSUE TITLE
Resharper detects hundreds of errors in .TT files

### ISSUE THREAD

**Issue by ClassyCircuit** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#394]
I have setup 17 large databases with this generator, however, Resharper complains about many errors in your T4 templates:

That's from .TT files:
![image](https://user-images.githubusercontent.com/6424248/37523610-28b87ade-2930-11e8-9348-e98518348675.png)

And .ttinclude files have even more issues:
![image](https://user-images.githubusercontent.com/6424248/37523736-8230f4b0-2930-11e8-882b-36cca3d72c11.png)
![image](https://user-images.githubusercontent.com/6424248/37523873-e3cef118-2930-11e8-89ad-e68c840f7f1e.png)

Am I missing some dependencies?

**Comment by sjh37** [comment]
It sounds like you have moved your database.tt file to a sub folder, but either haven't moved `EF.Reverse.POCO.Core.ttinclude` to the same folder, or changed the path in the database.tt
<#@ include file="<relative path to>\EF.Reverse.POCO.Core.ttinclude" #>

**Comment by ClassyCircuit** [comment]
Yes, I have changed the path in all my database.tt files.
I have moved the .ttinclude files to a different directory and have them being referenced by all the db.tt files.
Also POCOs are generating just fine when I save the file. It's just that those errors keep appearing so I am forced to exclude all .tt files from resharper analysis, which in turn disables syntax highlighting for those files, so it's much more difficult editing them.

The directories are layed out liked this:
`Project\Common\ReverseGenerator\EF.Reverse.POCO.Core.ttinclude`
`Project\Common\ReverseGenerator\EF.Reverse.POCO.ttinclude`
And database.tt files are here:
`Project\System\DbName1\database.tt`
`Project\System\DbName2\database.tt`
`Project\System\DbName3\database.tt`

And references inside those files:
`<#@ include file="..\\..\\Common\\ReverseGenerator\\EF.Reverse.POCO.Core.ttinclude" #>`
`<#@ include file="..\\..\\Common\\ReverseGenerator\\EF.Reverse.POCO.ttinclude" #>`

Not everything in the template is marked as an error, only some parts, for example this:
![image](https://user-images.githubusercontent.com/6424248/37532651-44d2598e-2948-11e8-9fa8-495ffd201d50.png)

**Comment by TimSirmovics** [comment]
Just to add, I have the same errors as above and all of my files are located within the same folder.

**Comment by ClassyCircuit** [comment]
@sjh37 could it be related to EF6 Tools version? I am using VS 2017 and EF6 tools are installed automatically as one of the VS components.
Or do you have another idea, what could be wrong?

Thanks!

**Comment by sjh37** [comment]
OK that's odd. I too use reshaper and don't get the errors  I shall investigate tomorrow if I can. I'm in meetings all day today.

**Comment by mdentremont** [comment]
I am also seeing these issues - it almost seems like the System namespace has been included twice and the IDE isn't able to decide which System to use.

I am on the following versions:
- Reverse POCO generator extension v2.36.1
- Visual Studio 2015 (Version 14.0.25431.01 Update 3)
- Resharper 2017.3.5
- ForTea 1.11.0

**Comment by sjh37** [comment]
For reference, I am on:
* Visual Studio Enterprise 2017 (15.6.5)
* Resharper 2017.2.2
* ForTea 1.10.0

**Comment by sjh37** [comment]
I see them now, they are part of R# solution wide analysis, not part of Visual Studio's Error output.

**Comment by sjh37** [comment]
Does right clicking on the file, and saying "Ignore Errors" help?
![image](https://user-images.githubusercontent.com/4190514/38506723-936a3670-3c12-11e8-9da6-cb827ef7eeab.png)

**Comment by mdentremont** [comment]
@sjh37 - I have solution wide analysis turned off and they still appear - I tried enabling it and ignoring the errors, but that didn't resolve the issue.

Most of the checking is helpful, except for the false positives I'm getting on the lambdas/Action/Func:
![image](https://user-images.githubusercontent.com/1106324/38508460-a6d14c84-3bf5-11e8-9414-86ed7b55cce4.png)

**Comment by sjh37** [comment]
Looking at @janissimsons code, he is using double back slashes:
```
<#@ include file="..\\..\\Common\\ReverseGenerator\\EF.Reverse.POCO.Core.ttinclude" #>
<#@ include file="..\\..\\Common\\ReverseGenerator\\EF.Reverse.POCO.ttinclude" #>
```

In my code I use single back slashes:
```
<#@ include file="..\EntityFramework.Reverse.POCO.Generator\EF.Reverse.POCO.Core.ttinclude" #>
```

@mdentremont I wonder if that could be the difference?

**Comment by TimSirmovics** [comment]
My code doesn't use any slashes, the .ttinclude files are in the same folder as the context tt file but I still get the errors.

The issue seems to be the definitions in the Core.ttinclude file.

![errors](https://user-images.githubusercontent.com/10243286/38649795-e5897f1c-3e3b-11e8-88bc-025876e93bb7.png)

When you try to navigate to definition R# seems to think both assemblies are the same one, and navigating to both options for mscorlib goes to the exact same file so i'm not sure why it is complaining.

**Comment by sjh37** [comment]
I know what R# is doing now. It's treating the .ttinclude files on their own right, rather than an include file. However, like you said, marking the *.ttinclude in R# to ignore also turns off syntax highlighting.

I am going to make lots of changes for .Net Core and plan on possibly getting rid of one of the files. But I will keep the R# errors in mind for the .ttinclude file. Perhaps using empty partial classes so R# no longer complains about things.

**Comment by CWuertz** [comment]
Has there been any update on this issue? I'm using Visual Studio 2017 and .NET 4.6 and I'm getting lots of TT file errors. Many of them are complaints about code that is commented out??

![2018-11-06_10h32_23](https://user-images.githubusercontent.com/44811299/48074658-713ab780-e1af-11e8-8b17-f65965e1b7cc.png)

 and

![2018-11-06_09h38_41](https://user-images.githubusercontent.com/44811299/48074675-78fa5c00-e1af-11e8-93b7-3713299f8005.png)

The tool is also failing to recognize table changes now. I have not changed my paths for over a year. This just started in the last week. And disabling R# does not resolve it....

Thoughts??

**Comment by sjh37** [comment]
Try turning off R# solution wide analysis, see if that helps.

**Comment by CWuertz** [comment]
It was already turned off. What I eventually had to do was disable R#, uninstall the Reverse Poco generator, reboot, reinstall and then delete my Poco objects and recreate them. Not sure why that exact voodoo worked, but it did. 

⁣Sent from TypeApp ​
