### ISSUE TITLE
Test database(s) missing in Source Control

### ISSUE THREAD

**Issue by dialedin2014** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#396]
The is a TestDatabase.sql, but this updates EfrpgTest which is not present.  Some general setup instructions for unit testing would be helpful too.  I'll do it!

**Comment by sjh37** [comment]
The creation of the database is at the top of the TestDatabase.sql file, just commented out.

**Comment by dialedin2014** [comment]
Got it, thanks
