### ISSUE TITLE
How to overwrite an computed Guid PRIMARY KEY to Identity

### ISSUE THREAD

**Issue by yyjdelete** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#4]
I Create an table like this,

``` sql
CREATE TABLE Token (
Token uniqueidentifier NOT NULL DEFAULT (newsequentialid()) ROWGUIDCOL,
Enabled bit NOT NULL 
)
ALTER TABLE Token ADD PRIMARY KEY (Token)
```

And get some code like that.

``` C#
public UserTokenConfiguration(string schema)
{
    ToTable(schema + ".Token");
    HasKey(x => x.Token);

    Property(x => x.Token).HasColumnName("Token").IsRequired().HasColumnType("uniqueidentifier").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Computed);
    Property(x => x.Enabled).HasColumnName("Enabled").IsRequired().HasColumnType("bit");
}
```

I get an Exception `System.Data.Entity.Core.UpdateException ---> System.NotSupportedException`,
and can't update any row in the table for that it has an **Computed** PRIMARY KEY. I know that I won't modify the column, and want to change it to **Identity**.

Is there any way for me to manually modify it to DatabaseGeneratedOption.Identity.
Or generally, is it OK to auto modify all **Computed** PK to **Identity**, for that **Computed** PK is NOT supported to modify, and modify is the only difference between them.

**Comment by sjh37** [comment]
I'll get this fixed asap and update the code

**Comment by sjh37** [comment]
All done. This will be in the next release.
See this [changeset ](https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/commit/7e0e45a0a6004a612802e69d8e9e2cb04fa1f747)to get the changes immediately.
