### ISSUE TITLE
Many-to-many does not use proper naming

### ISSUE THREAD

**Issue by revbones** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#40]
It appears that in a many to many relationship, the first navigational property should be the plural without the foreign key and without "1" appended but in version 2.19 this does not happen. 

For instance, we have the following tables:
Roles (RoleId)
Permission (PermissionId)
RolePermission (RoleId, PermissionId)

In the generated Role class, instead of a "Permissions" property in the reverse navigation , we get a property for "Permissions_PermissionId" and another for "Permissions1".

Similarly, in the generated Permission class we get properties "Roles_RoleId" and "Roles1". 

It seems like the intention was to have a result where the Role class would have a property named "Permissions" and a second one named either "Permissions1" or "Permissions_PermissionId" - which would be fine if that was the result.

It appears that the error is in the POCO.Core.ttinclude with the conditional:

``` c#
if (!ReverseNavigationUniquePropNameClashes.Contains(tableNameHumanCase) &&
    !ReverseNavigationUniquePropName.Contains(tableNameHumanCase))
{
    ReverseNavigationUniquePropName.Add(tableNameHumanCase);
    return tableNameHumanCase;
}
```

Which sees the name clash so the normal and probably intended naming doesn't happen on the first instance.

**Comment by sjh37** [comment]
Would you be able to give me the schema for the above tables so I can test it. It would save me some time. Thanks. simon@hicrest.net

**Comment by revbones** [comment]
Digging further yesterday we discovered that it may be caused by a legacy table we have named tblPermissionAssignment that is also a mapping table between Role and Permission.  Here is the sql for the 4 tables:

USE [TITAN]
GO

/*****\* Object:  Table [dbo].[Permission]    Script Date: 5/10/2016 9:30:30 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Permission]([Id] [int] IDENTITY%281,1%29 NOT NULL,
    [Name] [varchar]%2850%29 NOT NULL,
    [Code] [varchar]%2830%29 NOT NULL,
    [PermissionLevel] [tinyint] NOT NULL,
    [Description] [varchar]%28100%29 NOT NULL,
    [LastModifiedBy] [int] NOT NULL,
    [LastModified] [datetime] NOT NULL,
    [Assignable] [bit] NOT NULL,
 CONSTRAINT [PK_Permission] PRIMARY KEY CLUSTERED 
%28
    [Id] ASC
%29WITH %28PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON%29 ON [PRIMARY]) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[Permission] ADD  DEFAULT ('None') FOR [Name]
GO

ALTER TABLE [dbo].[Permission] ADD  DEFAULT ('None') FOR [Code]
GO

ALTER TABLE [dbo].[Permission] ADD  DEFAULT ((0)) FOR [Assignable]
GO

**Comment by sjh37** [comment]
Any more SQL available?

**Comment by revbones** [comment]
Oops - sorry, looks like I pasted the sql but it does something to it when I post it with the GO statements.  Here you go:

CREATE TABLE [dbo].[Role]

(
    [Id] [int] IDENTITY(1,1) NOT NULL,
    [Name] [varchar](50) NOT NULL,
    [Code] [varchar](50) NULL,
    [Description] [varchar](250) NULL,
    [LastModified] [datetime] NOT NULL,
    [LastModifiedBy] [int] NOT NULL,
    [Enabled] [bit] NOT NULL,
    [SystemRole] [bit] NOT NULL,
 CONSTRAINT [PK_Role] PRIMARY KEY CLUSTERED 
(
    [Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[Role] ADD  DEFAULT ((0)) FOR [SystemRole]

CREATE TABLE [dbo].[Permission]([Id] [int] IDENTITY%281,1%29 NOT NULL,
    [Name] [varchar]%2850%29 NOT NULL,
    [Code] [varchar]%2830%29 NOT NULL,
    [PermissionLevel] [tinyint] NOT NULL,
    [Description] [varchar]%28100%29 NOT NULL,
    [LastModifiedBy] [int] NOT NULL,
    [LastModified] [datetime] NOT NULL,
    [Assignable] [bit] NOT NULL,
 CONSTRAINT [PK_Permission] PRIMARY KEY CLUSTERED 
%28
    [Id] ASC
%29WITH %28PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON%29 ON [PRIMARY]) ON [PRIMARY]

ALTER TABLE [dbo].[Permission] ADD  DEFAULT ('None') FOR [Name]

ALTER TABLE [dbo].[Permission] ADD  DEFAULT ('None') FOR [Code]

ALTER TABLE [dbo].[Permission] ADD  DEFAULT ((0)) FOR [Assignable]

CREATE TABLE [dbo].[RolePermission]([RoleId] [int] NOT NULL,
    [PermissionId] [int] NOT NULL,
 CONSTRAINT [PK_RolePermission] PRIMARY KEY CLUSTERED 
%28
    [RoleId] ASC,
    [PermissionId] ASC
%29WITH %28PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON%29 ON [PRIMARY]) ON [PRIMARY]

ALTER TABLE [dbo].[RolePermission]  WITH CHECK ADD  CONSTRAINT [FK_RolePermission_Permission] FOREIGN KEY([PermissionId])
REFERENCES [dbo].[Permission]([Id])

ALTER TABLE [dbo].[RolePermission] CHECK CONSTRAINT [FK_RolePermission_Permission]

ALTER TABLE [dbo].[RolePermission]  WITH CHECK ADD  CONSTRAINT [FK_RolePermission_Role] FOREIGN KEY([RoleId])
REFERENCES [dbo].[Role]([Id])

ALTER TABLE [dbo].[RolePermission] CHECK CONSTRAINT [FK_RolePermission_Role]

CREATE TABLE [dbo].[tblPermissionAssignment]([PermissionId] [int] NOT NULL,
    [RoleId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
%28
    [PermissionId] ASC,
    [RoleId] ASC
%29WITH %28PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON%29 ON [PRIMARY]) ON [PRIMARY]

ALTER TABLE [dbo].[tblPermissionAssignment]  WITH CHECK ADD  CONSTRAINT [FK_tblPermissionAssignment_Permission] FOREIGN KEY([PermissionId])
REFERENCES [dbo].[Permission]([Id])

ALTER TABLE [dbo].[tblPermissionAssignment] CHECK CONSTRAINT [FK_tblPermissionAssignment_Permission]

ALTER TABLE [dbo].[tblPermissionAssignment]  WITH CHECK ADD  CONSTRAINT [FK_tblPermissionAssignment_Role] FOREIGN KEY([RoleId])
REFERENCES [dbo].[Role]([Id])

ALTER TABLE [dbo].[tblPermissionAssignment] CHECK CONSTRAINT [FK_tblPermissionAssignment_Role]

**Comment by sjh37** [comment]
The following tables have no columns

CREATE TABLE [dbo].Permission
CREATE TABLE [dbo].RolePermission 
CREATE TABLE [dbo].tblPermissionAssignment

**Comment by revbones** [comment]
Sorry - if I edit the post all the table defintions are there, but previewing or saving hides them for some reason.  I'm guessing it's some sql injection prevention stuff or something similar.  

I added the sql to a text file and attached that.  Hopefully that gets around the issue.

[PermissionsCreateSQL.txt](https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/files/259682/PermissionsCreateSQL.txt)

**Comment by sjh37** [comment]
Got it thanks :+1:

**Comment by sjh37** [comment]
It's because you have two mappings table for the same exact thing.

You have both **RolePermission** and **tblPermissionAssignment** mapping tables which both map exactly the same fields: [RoleId] and [PermissionId].

One will not be faster than the other as they are using a clustered index covering both fields.
So drop table tblPermissionAssignment as you don't need it. The added benefit will be that RolePermission and tblPermissionAssignment will never get out of sync, as there will only be one mapping table.

**Comment by sjh37** [comment]
If you want to keep two mapping tables, you could remove the EF mapping tables and instead use them as plain tables, and simply use joins in your LinqToSql by setting:

``` c#
UseMappingTables = false;
```
