### ISSUE TITLE
Error in EF6.Utility.CS.ttinclude

### ISSUE THREAD

**Issue by dialedin2014** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#400]
I am working with the RPOCO source code and am running into an error with the T4 compiler not being able to find an EF dependency.

Error	 Compiling transformation: The name 'ArgumentNotNull' does not exist in the current context	Miscellaneous Files	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\Entity Framework Tools\Templates\Includes\EF6.Utility.CS.ttinclude	Line 1497	

See the linked screenshot [https://imgur.com/n82VzOU](url)

**Comment by sjh37** [comment]
Hi. That url takes me to http://lyrics.url.com/ front page.
External to the generator, looks like other people have had the same issue: https://stackoverflow.com/q/47537785
Even if you told me what versions of the generator and visual studio version and edition, I'd unfortunately still be unable to help. Perhaps @ErikEJ could help?

**Comment by dialedin2014** [comment]
Weird.  Just copy and paste the link into the address bar to see the screenshot.  I downloaded the source code about a week ago.  It's Visual Studio 2017.

**Comment by sjh37** [comment]
Tried viewing the screenshot again, and its working now. I'm still at a loss as to why that is. Do you have EntityFramework nuget package installed in your project?

**Comment by dialedin2014** [comment]
Yes, the latest from NuGet

**Comment by sjh37** [comment]
Do you get the same error on another developer machine?

**Comment by dialedin2014** [comment]
Hi Simon.  I have not had the chance to try it on another machine, but that sounds like a good troubleshooting step thx.
