### ISSUE TITLE
Ability to ignore a determined column from a determined table

### ISSUE THREAD

**Issue by retorres** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#41]
Hello , I suggest you have this ability , as in some projects we have need to ignore a particular column by name and table name too.

**Comment by sjh37** [comment]
It already does this.

See the `<database>.tt` settings file for the section on either:
- ColumnFilterExclude. Set the regex to skip columns you don't want, or for more control use
- UpdateColumn. Set column.Hidden = true; and it will not appear.
