### ISSUE TITLE
Building EF Core Branch

### ISSUE THREAD

**Issue by ccampbellclearesult** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#414]
Hello, I love this tool. It's seriously the bomb - thanks so much.

I've tried pulling and building the ef core branch - yet no avail. I tried registering the .pfx/key but it needed a password. Is the EF core version accessible? May I get some tips on getting started?

Cheers

**Comment by sjh37** [comment]
It's not ready yet. You can follow along on https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/issues/5
The pfx key is private, which means another person could not change this extension and release it to the world, perhaps with a virus/worm in it, or as simple as a bug, on my behalf.
I'll close this issue as it's tracked by #5
