### ISSUE TITLE
Add DataAnnotations.Add() in the EF.Reverse.POCO.Core.ttinclude file

### ISSUE THREAD

**Issue by fulton** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#416]
Hi, everyone. 
In the EF.Reverse.POCO.Core.ttinclude file I modified SetupConfig() method, like below:
```c#
DataAnnotations.Add(string.Format("Required(ErrorMessage = \"请输入{0}!\")", DisplayName));
```
in the code DisplayName's value is "成绩名称", but output 
"Required(ErrorMessage = \"������成绩名称!\")", how modify this error, 
Thanks

**Comment by sjh37** [comment]
Can you try
```c#
const string note = "请输入";
DataAnnotations.Add(
   string.Format("Required(ErrorMessage = \"{0}{1}!\")", note, DisplayName));
```

**Comment by fulton** [comment]
thanks for @sjh37 help, I tried it but not worked.

**Comment by sjh37** [comment]
Try add an @ symbol to the note string.
```c#
const string note = @"请输入";
DataAnnotations.Add(
   string.Format("Required(ErrorMessage = \"{0}{1}!\")", note, DisplayName));
```

**Comment by sjh37** [comment]
If this does not fix it, you will have to try another way. I will close this case.
