### ISSUE TITLE
GetSqlDbType missing case numeric

### ISSUE THREAD

**Issue by krisnatm** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#419]
Add numeric type to private static string GetSqlDbType(string sqlType, int scale, int precision)

I believe it should be this:
		
case "decimal":
case "numeric":
     sysType = "Decimal";
     break;

Currently sysType is returning as VarChar when numeric is passed as sqlType

**Comment by sjh37** [comment]
Thanks. This will be in the next release.

**Comment by sjh37** [comment]
Released in v2.37.0
