### ISSUE TITLE
order of settings in database.tt

### ISSUE THREAD

**Issue by ErikEJ** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#42]
Watching your pluralsigt course: would it be helpful to move the single required setting to the top?

**Comment by sjh37** [comment]
Hi Erik. Which setting (s) are you talking about?

**Comment by sjh37** [comment]
ah. the connection string name. Good point.

**Comment by ErikEJ** [comment]
Yes, the connection string name!
