### ISSUE TITLE
Compiler Warning CS0649

### ISSUE THREAD

**Issue by TimSirmovics** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#420]
This is a follow up to the issue raised in #328.

After this change, I get 3 compiler warnings per generated Fake context about CS0649. For example:

`FakeContext._changeTracker' is never assigned to, and will always have its default value null
 FakeContext._configuration' is never assigned to, and will always have its default value null
 FakeContext._database' is never assigned to, and will always have its default value null`

The suggestion by @StevenBonePgh in #328 was to edit `InitializePartial()` to explicitly set the values to `null`. Another option is to add a `#pragma` along with the list of other disabled warnings.

Should we go ahead and implement one of these approaches, or can the problem be resolved in another way?

**Comment by TimSirmovics** [comment]
No response.. Should I just submit a PR with the additional pragma statement?

**Comment by sjh37** [comment]
Sorry I missing this Tim, I was away all last week.
The #pragma would effect all future variables, so I would suggest setting these to null would be the best choice here.
I'll make the modification

**Comment by sjh37** [comment]
Thanks for the prod Tim.

**Comment by sjh37** [comment]
Released in v2.37.0
