### ISSUE TITLE
Roslyn

### ISSUE THREAD

**Issue by sjh37** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#421]
From the [Q&A](https://marketplace.visualstudio.com/items?itemName=SimonHughes.EntityFrameworkReversePOCOGenerator#qna) marketplace tab.

Quote from K. L. Carter
> Microsoft seems to no longer be actively supporting T4, but Roslyn instead.  Would you recommend Roslyn (Scripty seems dead) instead of T4 for those of use who still write T4 templates?

I personally have not heard anything, but will investigate after EF.Core and support for multiple databases has been completed. Although I suspect T4 will be supported and used for many years to come.

Here is a note I made about [Scripty](https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/wiki/Could-this-project-be-run-by-a-script---build-process-such-as-scripty%3F).

**Comment by dyardyGIT** [comment]
I have been using t4 for years.  What have you seen that brings you to this conclusion?  Have you seen samples of code generation via Roslyn?
Ty

**Comment by sjh37** [comment]
No, not at all. I copy and pasted the comments from the Q&A board here https://marketplace.visualstudio.com/items?itemName=SimonHughes.EntityFrameworkReversePOCOGenerator#qna

I will edit it so it looks correct as it's not from me.

**Comment by dyardyGIT** [comment]
Correct - ok i have not seen anywhere the lack of support or deprecation of t4.  This would be big change for our current work processes.  Will let you know if i see/find any evidence of this.  We are looking to continue usage with ef core releases.

**Comment by bbakermmc** [comment]
T4s arent supported under .net core.  So in order to run a t4, you need to make a non core/non standard project, then copy the generated files over to your .net core project.

**Comment by inforithmics** [comment]
I use T4 Templates without Problems in .NET Standard projects, about .net core I don't know but I don't see any problem using it there (it's an Visual Studio Feature not dependant on the Project type).

**Comment by sjh37** [comment]
No longer valid. T4 is supported in .NET Core.
