### ISSUE TITLE
[Question]: Renaming Columns - sproc and view

### ISSUE THREAD

**Issue by RafaelJovel** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#422]
Hi,

I am trying to rename columns coming back from a SPROC in a legacy database.
The column names correspond to periods (-1 for opening etc)[-1,0,1,2,3,4,5].
Is there a way to do this? The column rename seems to be only for tables. Or am I wrong on this?

Thanks

**Comment by sjh37** [comment]
You can't rename columns back from a sproc because the data returned won't map. The columns have to match **exactly**, even the case has to be the same.
The best you can do is wrap a call to this stored proc within another one to change the returned column names.
