### ISSUE TITLE
Include Northwind.mdf or include generation script or provide link to download it

### ISSUE THREAD

**Issue by daiplusplus** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#429]
I see the project uses the Northwind sample database for testing and other purposes (e.g. the default `Database.tt`/`Database.cs` is generated from Northwind). I see the project does include the SQL-CE version, in the `App_Data` directory but not the full-fat SQL Server version.

Microsoft no-longer offers a working copy of Northwind for download. The only download from their site is an MSI installer for SQL Server 2000 that does not extract or install the database with my locally installed SQL Server 2017 install: https://www.microsoft.com/en-us/download/confirmation.aspx?id=23654

Other sites have their own copies of Northwind.mdb to download, however their schema or version is different than the one @sjh37 uses (e.g. the copy I downloaded from  http://businessimpactinc.com/blog/install-northwind-database/ contains new objects like table `Contacts` and views `Customer and Suppliers by City` so my `Database.cs` is different from the original in the Git repo, adding noise and making it harder to see if my changes are correct or not.

Another issue with trying to provide our own copy of the Northwind database is the potential for getting an adulterated version with malicious code inside a sproc, for example.

I see 3 options:

- Include a link to a known good copy of Northwind.mdf or an equivalent SQL Server backup file in the Solution README.md file.
- Include a zipped archive containing a known good copy of Northwind.mdf or an equivalent SQL Server backup file directly in the repo.
- Include a SQL Server database project in the Solution that regenerates the schema and reinserts the data verbatim. This is my preferred option because then it can use the built-in version of SQL Server used by SSDT, so we could use POCOGenerator against it without needing to install SQL Server at all.

**Comment by sjh37** [comment]
Thanks jehoel. Merged.
