### ISSUE TITLE
Option to generate Entity Configuration with Fluent API, but still add validation attributes

### ISSUE THREAD

**Issue by daiplusplus** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#434]
The EF Fluent API and Data Annotations API cover different subsets of EF's functionality. Unfortunately neither of them entirely encompass the other.

[According to this thread](https://stackoverflow.com/questions/5354900/code-first-are-data-annotations-or-the-fluent-api-better) (from 2012... so my information may be out of date by now) the Fluent API offers more control over things like table/class inheritance, while the Annotations API includes annotations that can be used by other, non-EF components (e.g. `[Required]`, `[StringLength]` etc which is especially useful for performing business-layer validation or even (erk!) using Entity classes as ViewModels in frameworks like ASP.NET MVC.

So it'd be nice if there was an option that enabled the Fluent API for Entity Configuration but also added the multi-purpose validation and data-type annotations as well.

**Comment by sjh37** [comment]
Yes, I've always thought the same. I'll take a look at the pull request. Thanks again Dai.

**Comment by daiplusplus** [comment]
My PR's been merged, thanks!
