### ISSUE TITLE
EF6.Utility.CS.ttinclude	missing

### ISSUE THREAD

**Issue by Dairtech** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#440]
Severity	Code	Description	Project	File	Line	Suppression State
Error		\EF6.Utility.CS.ttinclude	ConsoleApp2	ConsoleApp2\Database1.tt
Installed EntityFramework and Reverse Poco Generator

**Comment by sjh37** [comment]
Have a look at #427 and #36

**Comment by Charlygrind** [comment]
again in vs2022 V17.6.2.
This solved the problem 
https://developercommunity.visualstudio.com/t/Create-or-recreate-a-Model-does-not-work/10318478?page=59&pageSize=15&sort=active&openOnly=false&closedOnly=false&topics=C++
