### ISSUE TITLE
problem with case sensitive database

### ISSUE THREAD

**Issue by mhwlng** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#452]
EF.Reverse.POCO.Core.ttinclude

WHERE
    C.TABLE_NAME NOT IN ('EdmMetadata', '__MigrationHistory', '__RefactorLog', 'sysdiagrams')

should be

WHERE
    c.TABLE_NAME NOT IN ('EdmMetadata', '__MigrationHistory', '__RefactorLog', 'sysdiagrams')

otherwise doesn't work with case sensitive database

**Comment by sjh37** [comment]
Thanks. This will be in the next release.

**Comment by sjh37** [comment]
Released v2.37.2
