### ISSUE TITLE
Support Async Stored Procedure Calls

### ISSUE THREAD

**Issue by paulirwin** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#46]
The stored procedure call generation code that exists is fantastic. Unfortunately I can't really use it because it is synchronous and the rest of our Web API code is async. It would be great if for a given stored procedure Foo, it would also generate a FooAsync() method that returns Task<T>.

**Comment by sjh37** [comment]
Hi Paul, I'm always short on time. Would you be able to code one of the calls to be Async, paste it in here, then I'll alter the generator to create it so it looks the same/similar.

**Comment by paulirwin** [comment]
Absolutely. So this is a simple case, and I know there's other possibilities for how sprocs are executed, but here is the original code that is generated by the T4 template:

``` C#
        public System.Collections.Generic.List<GetConversationsForUserReturnModel> GetConversationsForUser(System.Guid? userId)
        {
            int procResult;
            return GetConversationsForUser(userId, out procResult);
        }

        public System.Collections.Generic.List<GetConversationsForUserReturnModel> GetConversationsForUser(System.Guid? userId, out int procResult)
        {
            var userIdParam = new System.Data.SqlClient.SqlParameter { ParameterName = "@userId", SqlDbType = System.Data.SqlDbType.UniqueIdentifier, Direction = System.Data.ParameterDirection.Input, Value = userId.GetValueOrDefault() };
            if (!userId.HasValue)
                userIdParam.Value = System.DBNull.Value;

            var procResultParam = new System.Data.SqlClient.SqlParameter { ParameterName = "@procResult", SqlDbType = System.Data.SqlDbType.Int, Direction = System.Data.ParameterDirection.Output };
            var procResultData = Database.SqlQuery<GetConversationsForUserReturnModel>("EXEC @procResult = [dbo].[GetConversationsForUser] @userId", userIdParam, procResultParam).ToList();

            procResult = (int) procResultParam.Value;
            return procResultData;
        }
```

Now, with async methods you can't have `out` parameters, so only the first version can have an async alternative. Here's what it might look like, using the same code style as the other synchronous ones:

``` C#
        public async System.Threading.Tasks.Task<System.Collections.Generic.List<GetConversationsForUserReturnModel>> GetConversationsForUserAsync(System.Guid? userId)
        {
            var userIdParam = new System.Data.SqlClient.SqlParameter { ParameterName = "@userId", SqlDbType = System.Data.SqlDbType.UniqueIdentifier, Direction = System.Data.ParameterDirection.Input, Value = userId.GetValueOrDefault() };
            if (!userId.HasValue)
                userIdParam.Value = System.DBNull.Value;

            var procResultData = await Database.SqlQuery<GetConversationsForUserReturnModel>("EXEC [dbo].[GetConversationsForUser] @userId", userIdParam).ToListAsync();

            return procResultData;
        }
```

Note the following:
- The method name ends in Async, following the common convention
- The return type is `Task<List<T>>`. It might be worth considering returning `Task<IList<T>>` instead.
- The assignment of the return value of the sproc has been removed from the SQL EXEC string
- Here we're calling .ToListAsync() instead of .ToList()

**Comment by sjh37** [comment]
Thats great Paul. I'll see what I can do :-)

**Comment by sjh37** [comment]
Under development, should have something by tomorrow

**Comment by sjh37** [comment]
Hi @paulirwin 

Try the attached and let me know if this works for you.
I've tested it ok, but would be good to get another devs feedback.

[async EntityFramework.Reverse.POCO.Generator.zip](https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/files/281842/async.EntityFramework.Reverse.POCO.Generator.zip)

**Comment by dhenderson12** [comment]
Has this issue been resolved in the latest version?
