### ISSUE TITLE
Error with EF6.Utility.CS.ttinclude

### ISSUE THREAD

**Issue by siddzie** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#462]
I am receiving the following error every time I am trying to generate files from EF reverse POCO generator t4 template.
Loading the include file EF6.Utility.CS.ttinclude returned a null or empty string. The transformation will not be run.

I am able to temporarily avoid the issue by adding the EF6 tticlude file in the same directory where reverse POCO t4 template resides, but it is not an ideal solution. I am running VS 2017 Enterprise.

Any advice would be great.

Thanks!

**Comment by sjh37** [comment]
Please have a look at #427 and #36
