### ISSUE TITLE
Separate namespaces for different schemas

### ISSUE THREAD

**Issue by FaizulHussain** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#471]
Is it possible to emit the generated classes into separate namespaces based on the name of the schema the SQL object is in? For instance, if I had table or procedure in a schema called "Admin", all generated classes should be inside a "Admin" suffix namespace. Thanks

**Comment by sjh37** [comment]
This is a duplicate of #293 and will therefore close this case.
There is the option
```c#
Settings.PrependSchemaName = true;   // Control if the schema name is prepended to the table name
```
However, the schema is not added as a namespace. It's still on the todo list.
