### ISSUE TITLE
EF.Reverse.POCO.Core.ttinclude:Line 390 outputWindow.ActivePane System.NullReferenceException

### ISSUE THREAD

**Issue by qgxcry** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#472]
try
		{
			outputWindow.ActivePane.Activate();
		}
		catch
		{
			var pane1 = outputWindow.OutputWindowPanes.Add("Pane1");
			pane1.Activate();
		}

**Comment by sjh37** [comment]
Thanks.

**Comment by sjh37** [comment]
Fixed. This will be in the next release.

**Comment by sjh37** [comment]
This has now been released in v2.37.3
