### ISSUE TITLE
Any way to declare a varchar column set by an after insert trigger as an identity?

### ISSUE THREAD

**Issue by ckelley7** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#475]
I have a Sql Server table non-primary key, varchar column whose value is generated by an after insert trigger.   I use the trigger because the generated value is derived by by fetching data from a foreign key table.   I'd like EF to real this varchar column like an identity and do nothing to it on update, but expect an insert to modify it.  Is there any way to generate the necessary .HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity) property on this column when it is not marked as an identity in the database?

**Comment by sjh37** [comment]
In the `UpdateColumn` function in your tt file.
Add something like:
```c#
if (table.NameHumanCase.Equals("AlphabeticalListOfProduct", StringComparison.InvariantCultureIgnoreCase) &&
    column.NameHumanCase.Equals("QuantityPerUnit", StringComparison.InvariantCultureIgnoreCase))
{
    column.IsComputed = true;
}
```

**Comment by sjh37** [comment]
Let me know if this works for you and close the case if it does. Thanks.

**Comment by ckelley7** [comment]
You have created something truly useful

I’m amazed your generator can do this as well

— Carl Kelley

On Nov 23, 2018, at 2:04 AM, Simon Hughes <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #475<https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/issues/475>.

**Comment by ckelley7** [comment]
Unfortunately, the modification you suggested caused the generator to fail and produce no output classes.  I used to remember where to find the log when the generator throws an exception but it eludes me now.  Here's what I added to the UpdateColumn function:

```
        if (table.Name.Equals("Quote", StringComparison.InvariantCultureIgnoreCase) &&
            column.Name.Equals("Quote_Number", StringComparison.InvariantCultureIgnoreCase))
        {
            column.IsComputed = true;
        }
```

**Comment by sjh37** [comment]
Hi @ckelley7 That's odd, it worked for me. Did you put the code snippet within the `Settings.UpdateColumn = (Column column, Table table) => { .. }` function ?

The output should be visible in the output window Ctrl+Alt+O and select the show output from: 'EF Reverse POCO Generator'

**Comment by ckelley7** [comment]
Hey, Simon,

Nothing appears in the output window from EF Reverse POCO Generator v2.36.1 running inside Visual Studio Community 2017 Version 15.7.4.  The [Show Output from:] drop down does not include a reference to same.  After I remove the new code from the Settings.UpdateColumn = (Column column, Table table) => { .. } function, it works perfectly once again.

**Comment by ckelley7** [comment]
Simon,

I upgraded to VS 15.9.2 and your EF.Reverse POCO v2.37.2 and got a little bit further.  After saving the tt file with the suggested IsComputed = true override, I got the following error:

Compiling transformation: 'GeneratedTextTransformation.Column.IsComputed()' is inaccessible due to its protection level	WinMetrics.IQ.DAL

I then modified my EF.Reverse.POCO.Core.ttinclude to make IsComputed public and got this error:

Compiling transformation: Cannot assign to 'IsComputed' because it is a 'method group'	WinMetrics.IQ.DAL	D:\DotNet\IQAdmin\WinMetrics.IQ.DAL\IQ.tt

IsComputed is defined as the following method in ttinclude:

```
        public bool IsComputed()
        {
            return IsStoreGenerated && !IsIdentity;
        }
```
So, then I tried the following UpdateColumn extension and it worked:

```
        if (table.Name.Equals("Quote", StringComparison.InvariantCultureIgnoreCase)
            && column.Name.Equals("Quote_Number", StringComparison.InvariantCultureIgnoreCase))
        {
            column.IsStoreGenerated = true;
        }
```

This case is closed.
