### ISSUE TITLE
Is there new EntityFrameworkWithHierarchyId lib which match ef 6.2?

### ISSUE THREAD

**Issue by sPhinX-LHJ** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#476]
I want use Generator in a abp based project, but the new abp template reference ef 6.2, when I doing some scaffolding, there is a "Exception has been thrown by the target of an invocation".
I believe the root cause is the EntityFrameworkWithHierarchyId's version lower then ef's version, is where new version?

**Comment by sjh37** [comment]
There is a some info [here](https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/wiki/HierarchyId) in the wiki.
Until the `EntityFrameworkWithHierarchyId` catches up, you could:

1. Use version v6.1.3 of entity framework to match the NuGet package `EntityFrameworkWithHierarchyId`
2. Filter out any tables that use the SQL `HIERARCHYID` type.
3. Filter out the just the column(s) that use the SQL `HIERARCHYID` type. You can filter out the columns by marking them has `hidden=true` in the `Settings.UpdateColumn` function in your tt file.

I would say use either option 1 or 3.

**Comment by sPhinX-LHJ** [comment]
There is a good news and a bad one, which one first? HAHAHA

The good news is EF6 master support HierarchyId already, see here:https://github.com/aspnet/EntityFramework6/blob/master/src/EntityFramework/Hierarchy/HierarchyId.cs

The bad one is not ready for nuget.

so I compile source then everything ok.

**Comment by sjh37** [comment]
Ah, I didn't know EF6 will support HierarchyId. That is awesome. Thanks @sPhinX-LHJ for letting me, and others know about it :-)

**Comment by sjh37** [comment]
I have updated the [wiki](https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/wiki/HierarchyId) article with the good news. Thanks for the heads up.

**Comment by sPhinX-LHJ** [comment]
I recommend the [Entity Framework 6 Nightly Builds](https://github.com/aspnet/EntityFramework6/wiki/Nightly-Builds) after some testing, The Nightly Builds can support MVC scaffolding that Single dll doesn't.
