### ISSUE TITLE
*.tt file doesn't auto generate model upon saving

### ISSUE THREAD

**Issue by brillious** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#484]
I have no idea why, but all of a sudden, my *.tt file won't auto generate model upon saving. Nothing happens and no *.cs file is generated.

**Comment by brillious** [comment]
What I notice too though, is that if I exclude it from my project, then drag it back in, it does then save and generate the resultant model.

It's a workaround, but a bit annoying. Something in my development environment not configured correctly?

**Comment by sjh37** [comment]
Can you click on the tt file, and press F4 to take a look at the properties. Mine are as follows:
![image](https://user-images.githubusercontent.com/4190514/51377112-f6bcdb00-1b01-11e9-9b40-8eec87afb264.png)

Failing that, what I would do is take a copy of the project when it does not work, fix it, then compare the folders with araxis merge or beyond compare to see what's changed. I bet it's a simple property in the .csproj file with regard to the .tt file.

**Comment by brillious** [comment]
No idea how, but it started working again. Thanks for the quick response though.
