### ISSUE TITLE
Generate Only One table from existing database contains n number of tables

### ISSUE THREAD

**Issue by ravi-ku** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#492]
Hi,

Can we generate Only One table from existing database contains n number of tables?

Can we modify/add/remove some column in a particular existing table?

**Comment by sjh37** [comment]
Yes and Yes.

To include only the tables you specify, use:
```c#
Settings.TableFilterInclude = new Regex("^table_name1$|^table_name2$|etc");
```

To rename, or exclude columns, edit the UpdateColumn() function in your settings:
```c#
Settings.UpdateColumn = (Column column, Table table) =>
{
    // Rename column
    if (column.IsPrimaryKey && column.NameHumanCase == "PkId")
        column.NameHumanCase = "Id";

    // To remove a column, set it to hidden
    if (column.IsPrimaryKey && table.NameHumanCase.Equals("SomeTable", StringComparison.InvariantCultureIgnoreCase))
        column.Hidden = true;
};

**Comment by ravi-ku** [comment]
You mean I have to update source code then it will work?

Is it not possible to we have UI in which we show all tables with check boxes to allow user to select/un-selected the tables & columns?

![image](https://user-images.githubusercontent.com/11146609/53684559-0b150a00-3d35-11e9-9b3a-cc4312ba8681.png)

**Comment by sjh37** [comment]
The `database.tt` file is a settings file. The settings file is designed for you to modify to tweak the generator to do exactly what you want. By default, the generator will reverse enginner every table and every stored procedure for you. If you don't want all the tables in your dbcontext, then add a filter and press save.
Watch the course I give on this generator, which is available [here](https://www.pluralsight.com/courses/code-first-entity-framework-legacy-databases).
