### ISSUE TITLE
Support for VS2019

### ISSUE THREAD

**Issue by GutierrezDev** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#495]
Hi. Is there a planned upgrade for VS2019?

**Comment by ClassyCircuit** [comment]
@sjh37 Can you please push an update for VS 2019 ?

**Comment by sjh37** [comment]
Just sorting it out now

**Comment by sjh37** [comment]
Done. v2.37.4 released. Should be available in about 15 mins.
