### ISSUE TITLE
EF 6 project: name 'fileManager' does not exist in the current context

### ISSUE THREAD

**Issue by BurstX** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#500]
Hi! I've added [the extension](https://marketplace.visualstudio.com/items?itemName=SimonHughes.EntityFrameworkReversePOCOGenerator) to VS2017 Prof. Added "new item" to the project where EF 6 is added via NuGet.

_TCMDB.tt_ file contains
```
<#@ include file="EF.Reverse.POCO.Core.ttinclude" #>
```
but I need EF 6, so I replaced the first line with
```
<#@ include file="EF.Reverse.POCO.ttinclude" #>
```
Then I executed _TCMDB.tt_  and got errors:
![image](https://user-images.githubusercontent.com/3790231/55875991-31815d00-5b9f-11e9-84a7-7b763203a796.png)

I guess the problem is that the first line of executable code refers to an object which is not declared:
![image](https://user-images.githubusercontent.com/3790231/55876055-5f66a180-5b9f-11e9-9fd1-fc12d786b061.png)

Or do I miss something?

**Comment by sjh37** [comment]
<#@ include file="EF.Reverse.POCO.Core.ttinclude" #>
That is NOT .net core code, but the 'core' code of the EF6 template. The whole project is EF6, and I have not yet released the .NET Core version (v3) yet. You need to put that back.
I'll make sure v3 (which will support both EF6 and .Net core is more explicit with its file name :-) ).

**Comment by sjh37** [comment]
Also watch the Pluralsight course I created for this project, available [https://www.pluralsight.com/courses/code-first-entity-framework-legacy-databases](https://www.pluralsight.com/courses/code-first-entity-framework-legacy-databases)
