### ISSUE TITLE
Get table name for entity?

### ISSUE THREAD

**Issue by mwoffenden** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#503]
How do we get the underlying table name (schema name) for an entity?

**Comment by sjh37** [comment]
Hi @mwoffenden 
That should be the `Table.Name` and `Table.Schema` properties.

**Comment by sjh37** [comment]
I'll close this for now. Let me know if you still need help.

**Comment by mwoffenden** [comment]
Do you have a simple example of how to access the table name from a .NET application in C#?

**Comment by sjh37** [comment]
Ahh. Do you need it as part of the code generation, or part of using it via entity framework?

**Comment by sjh37** [comment]
Table.Name and Table.Schema properties is part of the code generation process.

**Comment by mwoffenden** [comment]
Via EF.

**Comment by sjh37** [comment]
Take a look at [https://romiller.com/2014/04/08/ef6-1-mapping-between-types-tables/](https://romiller.com/2014/04/08/ef6-1-mapping-between-types-tables/)

**Comment by mwoffenden** [comment]
Great, I will take a look at that.

**Comment by mwoffenden** [comment]
Simon - I tried his code and it does not work.  Do you have any other ideas or sample code?  Since this information is readily available to the T4 templates, shouldn't it also be available via EF?

**Comment by mwoffenden** [comment]
I'm also wondering if the table name could somehow (during class generation) be baked into the class as an easily accessible property?

**Comment by sjh37** [comment]
Actually, that's not a bad idea :-)

**Comment by mwoffenden** [comment]
That sounds encouraging.  Doable?  I really need this for a project I'm working on.  No pressure!

**Comment by mwoffenden** [comment]
Managed to get romiller's code working after some adjustments.  But would love to see this feature...

**Comment by sjh37** [comment]
Just checked the code, it's actually already doable.

In your <database>.tt file, change WritePocoBaseClassBody to be
```c#
Action<Table> WritePocoBaseClassBody = t =>
{
    WriteLine("        public static readonly string TableName=\"" + t.Name + "\";");
};
```

**Comment by mwoffenden** [comment]
How could this be accessed from EF?

**Comment by sjh37** [comment]
It's a static property, so the for the table called `OrderDetails`, it would be `OrderDetails.TableName`
