### ISSUE TITLE
HasColumnType seems to break usage of Sqlite

### ISSUE THREAD

**Issue by adaxer** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#505]
In our project we recently upgraded the generator from version 2.13.1 to 2.37.2.
For the configuration classes it now emits some .HasColumnType(xy) fluent calls for Properties, which the older version did not emit.
While this works fine with SqlServer, when using System.Data.SQLite (v1.0.110.0), we get the error  
System.InvalidOperationException: The store type 'bigint' could not be found in the SQLite provider manifest (the topmost stacktrace entry being: System.Data.Entity.Utilities.DbProviderManifestExtensions.GetStoreTypeFromName(DbProviderManifest providerManifest, String name))
If we remove all occurrences of .HasColumnType('bigint'), then the same error is there for eg. 'numeric'

So - is there a way to fallback to the old behavior where the .HasColumnType is not emitted, or do we miss anything else?

By the way: Using the connectionstring via ado and querying any table via DbCommand works just fine, so the file is found and opened). We also have the sections in app.config as was for earlier versions of System.Data.SQLite

**Comment by sjh37** [comment]
Hi @adaxer 
I've never used or tested it against SqlLite, so you are the first that I know of.
You could alter the code that emits `.HasColumnType(xy)` that is on line 1131 in `EF.Reverse.POCO.Core.ttinclude` file:
```c#
sb.AppendFormat(".HasColumnName(@\"{0}\").HasColumnType(\"{1}\")", Name, SqlPropertyType);
```
See if that gets SqlLite going again :-)

**Comment by adaxer** [comment]
Hi Simon,

indeed, that did the trick. Thanks very much for the quick help.
(Actually, the SqlServer connection also runs fine without the configuration classes containing the .HasColumnType calls...)
