### ISSUE TITLE
Create all MappingTables/dependent tables in TableFilterInclude list table regex

### ISSUE THREAD

**Issue by pvrajesh** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#506]
Hi,

Using Entity framework v6.0.0.0 and POCO generator v2.37.4

I want to generate all dependent objects for TableFilterInclude list of tables.

Currently: If I mention TableFilterInclude = new Regex("^Book$"); only for this table POCO class is generating, but it has mapping table which is "Type" db table for this its not generating any class.

I have tried with https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/issues/243 answer also ,but no luck.

Can any one suggest me on this.

**Comment by sjh37** [comment]
Hi @pvrajesh Could you post your code for the BookConfiguration here so I can see what you are getting. Thanks.

**Comment by pvrajesh** [comment]
```c#
public BookConfiguration(string schema)
{
    ToTable("Book", schema);
    HasKey(x => x.ID);
    Property(x => x.ID).HasColumnName(@"Id").HasColumnType("bigint").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
    Property(x => x.CreatedDate).HasColumnName(@"created_date").HasColumnType("datetime").IsRequired();
    Property(x => x.EndedDate).HasColumnName(@"ended_date").HasColumnType("datetime").IsRequired();
    Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar").IsRequired().HasMaxLength(255);
    Property(x => x.Subject).HasColumnName(@"Subject").HasColumnType("nvarchar(max)").IsOptional();
    Property(x => x.Revision).HasColumnName(@"Revision").HasColumnType("timestamp").IsOptional();
}
```
Above BookConfiguration class was generated without adding "Type" table in  TableFilterInclude.

If I add "Type" db table in TableFilterInclude list then its generating FK_Type in Book poco class. 

Is that necessary to place all the list of relational/dependency tables in TableFilterInclude to generate right POCO class?

**Comment by sjh37** [comment]
Ok, I think I now understand what you are tying to achive.
You want to list 1 table, and have all the dependant tables automatically included. Yes?

If yes, then no, you can't do that. You have to manually specify the list of tables you want the generator to include for you.

**Comment by pvrajesh** [comment]
Thanks @sjh37 

Yes, I am looking for list 1 table and it has to generate all dependent tables classes. 

can you prefer any code change in ttinclude file to achieve this?

**Comment by sjh37** [comment]
In `EF.Reverse.POCO.Core.ttinclude`, in function `public override Tables ReadSchema()` line 2780, you would have to remove
```c#
if(IsFilterExcluded(Settings.TableFilterExclude, Settings.TableFilterInclude, tableName))
    continue;
```
and line 2806
```c#
if (IsFilterExcluded(Settings.TableFilterExclude, null, tableName)) // Retest exclusion filter after table rename
    continue;
```

That change would include all the tables.

Then in the function `public override void ProcessForeignKeys(List<ForeignKey> fkList, Tables tables, bool checkForFkNameClashes)`  approx at line 3244, you would need to find all the tables where they would be kept and add those to a temporary list. At the top of the function add:
```c#
var delete = new List<string>();
var keep = tables
    .Where(tbl => !IsFilterExcluded(Settings.TableFilterExclude, Settings.TableFilterInclude, tbl.Name) &&
                  !IsFilterExcluded(Settings.TableFilterExclude, Settings.TableFilterInclude, tbl.NameHumanCase))
    .Select(x => x)
    .ToList();
```

Then at line 3267, just before `var fkCols = foreignKeys.Select(x => new` add the following:
```c#
if (!keep.Contains(pkTable.NameHumanCase) && !keep.Contains(fkTable.NameHumanCase))
{
    delete.Add(pkTable.NameHumanCase);
    delete.Add(fkTable.NameHumanCase);
}
```

At the very bottom of that function, line 3400, add the following
```c#
tables.RemoveAll(t => delete.Contains(t.NameHumanCase));
```

Good luck, I've not tested it, and can't help any further. It would be easier for you to work out which tables to include in the first place.

**Comment by pvrajesh** [comment]
Thank you very much @sjh37.
