### ISSUE TITLE
Does support for Teradata exist?

### ISSUE THREAD

**Issue by ClassyCircuit** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#507]
Is it possible to generate entities from Teradata database?
When I try to run the generator on Teradata I get the following errors:

`Running transformation: Failed to read database schema in LoadTables(). [500] Could not execute the specified command: [Teradata Database] [3706] Syntax error: expected something between '(' and the string 'Edition'.`

`Running transformation: Failed to read database schema for stored procedures. [500] Could not execute the specified command: [Teradata Database] [3706] Syntax error: Data Type "CHARACTER_MAXIMUM_LENGTH" does not match a Defined Type name.`

**Comment by ClassyCircuit** [comment]
@sjh37 would it take a lot of effort to add support for Teradata?

**Comment by sjh37** [comment]
Hi Janis. Never used it before, but seeing as it's a sql database, you'd have to modify the sql in `EF.Reverse.POCO.Core.ttinclude` in the class `SqlServerSchemaReader`.
As long as the columns returned are the same name (you can use aliases if they are not) and type, you should be ok. You can ignore the synonym sql as long as you have that `Settings.IncludeSynonyms = false;` turned off.

Modify the following variables:

- Anything starting with **Synonym** Ignore.
- Anything ending in **SQLCE** or **Azure** ignore.
- **TableSQL** Modify this.
- **ForeignKeySQL** Modify this
- **ExtendedPropertySQL** set to ""
- **StoredProcedureSQL** Modify this.
- **IndexSQL** Modify this

Modify the function `ReadDatabaseEdition()` and delete the inside of it as it won't work for Teradata. Replace it with the following content:
```c#
_sqlDatabaseEdition = "Teradata";
_sqlDatabaseEngineEdition = "";
_sqlDatabaseProductVersion = "";
_sqlDatabaseProductMajorVersion = "";
```

**Comment by sjh37** [comment]
Googling around, see what the following gives you back
```sql
SELECT ColumnName
FROM DBC.Columns
WHERE DatabaseName='DatabaseName goes here'
```

**Comment by sjh37** [comment]
BTW, if you get it working, please let me have the Teradata SQL and I'll add it to the new v3 generator. As a thank you, I'd like to give you a two year free licence for it, just as soon as it's launched.

**Comment by ClassyCircuit** [comment]
> 
> 
> Googling around, see what the following gives you back
> 
> ```sql
> SELECT ColumnName
> FROM DBC.Columns
> WHERE DatabaseName='DatabaseName goes here'
> ```

This query returned 2810 rows with the column names for my DB.

**Comment by ClassyCircuit** [comment]
I read and experimented more with Teradata and EF, and it turns out that Teradata .NET Data Provider only supports EF v5.0, which is unbelievable..
@sjh37 Does your generator support EF 5 ? There are a lot of differences how entities should be generated for the older EF, I am not sure that this is a quick fix anymore.

**Comment by sjh37** [comment]
It generates code for EF 6.
A few tweaks:

```c#
// In settings
Settings.AddUnitTestingDbContext = false;

// In EF.Reverse.POCO.Core.ttinclude
public static Func<string,bool> IsSupportedFrameworkVersion = (string frameworkVersion) => { return false; };
```

Once generated:
Delete
```c#
public MyDbContext(System.Data.Entity.Core.Objects.ObjectContext objectContext, bool dbContextOwnsObjectContext)
        : base(objectContext, dbContextOwnsObjectContext)
    {
    }
```

And voila. Works with EF 5.

**Comment by sjh37** [comment]
Closing this case due to Terradata not supporting EF6/EFCore
