### ISSUE TITLE
Error while calling SQL function,  'Entities.POCOTestFunction' cannot be resolved into a valid type or function. Near member access expression, line 1, column 11.

### ISSUE THREAD

**Issue by chandan1001** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#509]
There is simple SQL Table Valued Function like -

```sql
create function POCOTestFunction
(
    -- Add the parameters for the function here
    @StartValue int
  , @EndValue int
)
returns @returnTable table
(
    Incremental int
  , Decremental int
)
as
begin
    -- code
end 
```

Call to function is working properly if used in a new fresh project, but when I call any SQL function in my existing project it throws error.

`'Entities.POCOTestFunction' cannot be resolved into a valid type or function. Near member access expression, line 1, column 11.`

**Comment by sjh37** [comment]
Hi.

If the following setting is true:
```c#
Settings.IncludeTableValuedFunctions = true;
```
You must install the "EntityFramework.CodeFirstStoreFunctions" Nuget Package.

If you have already done that, then check which version of `entityframework` NuGet package you have installed between the new fresh project and the existing project.

Also check if there are any differences in the function code between the two. Use araxis merger, or beyond compare so you don't accidentally miss anything.

**Comment by chandan1001** [comment]
Thanks for the response, the problem seems to be something different. 
I could reproduce it in my "fresh project"

My db context name is `Entities`, when I use an instance of that everything goes well.
If I create a subclass of this `Entities` (say `SubclassOfEntities`)  and use instance of that subclass to execute a TVF, it throws error.

here is the related code -

`return ((System.Data.Entity.Infrastructure.IObjectContextAdapter)this).ObjectContext.CreateQuery<PocoTestFunctionReturnModel>("[Entities].[POCOTestFunction]()", new System.Data.Entity.Core.Objects.ObjectParameter[] { });`

If I change `"[Entities].[POCOTestFunction]()"` with `"[SubclassOfEntities].[POCOTestFunction]()"` this works.

**Comment by sjh37** [comment]
Hi.
Not sure why that is if I'm honest. I wonder if it's a bug in the `EntityFramework.CodeFirstStoreFunctions` Nuget Package?

**Comment by sjh37** [comment]
Closing this case. Please let me know if this happens again with v3.
