### ISSUE TITLE
Column order fix

### ISSUE THREAD

**Issue by darko1979** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#510]
I'm currently using latest v2.37.4 and I'm having column order issues with generated POCO classes.
Although I did not change column order in my database, after running T4 script some POCO classes are generated with different order. 
I looked through EF.Reverse.POCO.Core.ttinclude script and found that ORDINAL_POSITION of a column is referenced multiple times but it appears, if I'm not mistaken, it's not used to sort results when reading database schema.
I manually appended "ORDER BY c.TABLE_SCHEMA, c.TABLE_NAME, c.ORDINAL_POSITION" at the end of TableSQL constant and after that it seems to generate columns in correct order.

It would be nice if this could be included in future releases.

**Comment by sjh37** [comment]
That is strange as the order of the columns is done within `EF.Reverse.POCO.ttinclude` template file. Line 1024 when writing the columns out:

```c#
<# foreach(Column col in tbl.Columns.OrderBy(x => x.Ordinal).Where(x => !x.Hidden))
{
#>
<#= WritePocoColumn(col) #>
<# } #>
```

Can you check your file to make sure that `OrderBy` clause is there.

**Comment by sjh37** [comment]
If it is like that, and you still have problems, can you let me know if changing the line to the following solves the problem:

```c#
<# foreach(Column col in tbl.Columns.Where(x => !x.Hidden).OrderBy(x => x.Ordinal))
```

**Comment by darko1979** [comment]
Well, this is embarrassing, I removed order by clause I added into query and now it generates columns in the correct order. Now I'm not sure what happened, but yesterday I double checked and the column that was second in place was created last in the generated POCO class.
If it happens again I'll try to reverse Where and OrderBy in that LINQ query.
Sorry to bother you.

Best regards,
Darko Matesic

**Comment by sjh37** [comment]
Thanks for letting me know
