### ISSUE TITLE
Update model 

### ISSUE THREAD

**Issue by fzan** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#512]
Hi,

I was wondering if it's possible to refresh the model from the database, without the effort to do it manually.

The use case is:

1) generate the EF POCOs and Context from an existing SQL database
2) modify the POCOS, like adding decorations or other things (IE : [JsonIgnore], or fake properties)
3) modify the SQL database, adding/removing fields
4) safe update the context and POCOs.

Anyone knows if this case is supported, or only the 1-3-4 steps are correct?
And how?

Thanks

**Comment by sjh37** [comment]
Hi Fabio. Everytime you press save on the `<database>.tt` file, it will always overwrite the POCOs. There is no way to detect what code modifications you made, and what modifications were made by the generator and merge them back. The best you can hope for in this scenario is to press save on the generator, and check the changes in your GIT/HG commit, and only tick the lines that have changed in the commit due to database changes, and revert everything else.

**Comment by sjh37** [comment]
I'll close this issue as this is something I can't fix.

**Comment by fzan** [comment]
Thanks for your quick reply Simon :-) 

Although i disagree, because in my experience database modifications are not so infrequents.

if i can, i suggest to take into consideration that the scaffold could generate also 1 extension class per entity/context, via flag. 

so we could have
Context class + updatable context extension
Entity1 + updatable Entity extension
Entity2 + updatable Entity extension

In this way we could handle specific ad hoc modification on the extension class that hopefully not will be overwritten by a subsequent update (you could skip those files when updating)
It is possible? 🥇

**Comment by sjh37** [comment]
Hi, that is possible now. Set
```c#
Settings.EntityClassesModifiers = "public partial";
```

All POCO's will be created with "public partial", you can now create your own separate public partial class with the same name as the POCO.

**Comment by fzan** [comment]
@sjh37 thanks again for your kind answer :-) you hare very handsome 👍 

> All POCO's will be created with "public partial", you can now create your own separate public partial class with the same name as the POCO.

however i found that the partial is applied only to the class definition.
Foreign keys have the 

`public virtual`

 accessor, therefore they cannot be modified without rewriting the original POCO, or extending it. Again, that's not comfortable.

IMHO, the correct solution could be the one i suggested above, i don't think i'm the only one with the need of updating the custom schema without some sort of hackish git trick :-D
