### ISSUE TITLE
SP interface does not work is SP has a Temp table

### ISSUE THREAD

**Issue by CycoPH** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#513]
Here is a sample stored proc.  The system does not recognise that some data is returned

--------------
CREATE PROCEDURE sp_GetSomething
AS
SET NOCOUNT ON;
SELECT CAST([key] as INT) as idx, CAST([value] as INT) as Id INTO #TempIds FROM OPENJSON('[400,350,5,4,3,2,1,2,3,4,5,200,300,400]')
-- do some processing
select idx,id from #TempIds
return 0
--------------

But if you rewrite the temp table as a 'with' clause then the return model is found?  Why?

------------
CREATE PROCEDURE sp_GetSomething
AS
SET NOCOUNT ON;

WITH TempIds as (
	SELECT CAST([key] as INT) as idx, CAST([value] as INT) as Id FROM OPENJSON('[400,350,5,4,3,2,1,2,3,4,5,200,300,400]')
)
-- do some processing
select idx,id from TempIds
return 0

**Comment by sjh37** [comment]
Hi Peter,
It's all down to what SQL Server thinks will be returned. I honestly have no control over what SQL Server tells me will be returned. I call the stored procedure with NULLS and `SET FMTONLY ON` and it returns back the data structure it thinks I will get back when it gets called for real.
Sorry, but I'd love to fix this for you, but I have to close the case as it's completely out of my hands.
The best you can do is to alter the stored proc so it works for you, or simply write your own wrapper for it.

**Comment by NaomiN** [comment]
I hope sp_ is not really your SP name.

**Comment by sjh37** [comment]
Yes, calling your procs starting with `sp_` will cause SQL Server to search the master database first, then your database last for the stored procedure.

Have a read of [http://www.sqlnuggets.com/blog/do-not-prefix-stored-procedures-with-sp_/](http://www.sqlnuggets.com/blog/do-not-prefix-stored-procedures-with-sp_/)

**Comment by CycoPH** [comment]
I did not know that.  Thank you for pointing that out
