### ISSUE TITLE
Cannot see EF option when I right click

### ISSUE THREAD

**Issue by kad1r** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#514]
Hi, I did a clean install for VS2019 and I installed this and my other extensions.
But whatever I do I cannot see EntityFramework option when I right click to class project.
Am I doing something wrong or do you have any idea maybe other extensions block it?
Thanks.

![image](https://user-images.githubusercontent.com/2114669/60423068-00408800-9bf6-11e9-86d7-4b5eefd3fc64.png)

![image](https://user-images.githubusercontent.com/2114669/60421674-fb2e0980-9bf2-11e9-9366-3628ce8ffce9.png)

**Comment by sjh37** [comment]
Right-click -> Add -> New Item.
![image](https://user-images.githubusercontent.com/4190514/60424744-e8163c00-9be8-11e9-9076-28ef79931f27.png)
