### ISSUE TITLE
Error when working with IdentityDbContext

### ISSUE THREAD

**Issue by arbh89** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#518]
Hi Simon, there is an error when DBContext inherits from Microsoft IdentityDbContext, there is a constructor that is not supported by IdentityDbContext

```c#
public MyDbContext(System.Data.Entity.Core.Objects.ObjectContext objectContext, bool dbContextOwnsObjectContext)
            : base(objectContext, dbContextOwnsObjectContext)
        {
            InitializePartial();
        }
```
The error is as follow.

Error	CS1503	Argument 1: cannot convert from 'System.Data.Entity.Core.Objects.ObjectContext' to 'string'

I made a hot fix to exclude this constructor when DBContext inherits from IdentityDbContext.

I modified EF.Reverse.POCO file on line 273.

Code nows looks like this.

```c#
<#if(!Settings.DbContextBaseClass.Contains("IdentityDbContext")) {#>
        public <#=Settings.DbContextName#>(System.Data.Entity.Core.Objects.ObjectContext objectContext, bool dbContextOwnsObjectContext)
            : base(objectContext, dbContextOwnsObjectContext)
        {
<#if(Settings.DbContextClassIsPartial()) {#>            InitializePartial();
<#}#>
        }
		<#}#>

```

**Comment by sjh37** [comment]
Thanks @arbh89 .
As a thank you, send me an email, and I'll give you a 1 year free licence for v3 generator :-)
Simon.
