### ISSUE TITLE
Installed - but not found

### ISSUE THREAD

**Issue by Michael-Eber** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#521]
I was pointed at your code for building my edmx.  I downloaded it and installed it.  But there is no sign of it in anything.  Context menu?  Nada.  Nuget solution manager? Nada.  How am I supposed to use this???

**Comment by sjh37** [comment]
Hi Michael,
This is a code-first generator, and has nothing at all to do with edmx.
Right click on your project, add, new item, choose Entity framework reverse poco generator.

![image](https://user-images.githubusercontent.com/4190514/63127482-5b61ea80-bfaa-11e9-8bde-614fac90d071.png)

Choose a suitable name for the file, and modify the settings to suit. Pressing save on the .tt file causes it to run and generate your code for you.

Alternatively, please watch the training course I created showing you how to use it. https://www.pluralsight.com/courses/code-first-entity-framework-legacy-databases
