### ISSUE TITLE
Renaming column before Humanize/casing is applied

### ISSUE THREAD

**Issue by kostii** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#522]
Is there a way to do the column rename before the casing is applied to the column name?

I have a legacy ERP database which I want to generate poco's for that is littered with abbreviated uppercase columns with underscores.

TableRename works in this way where I can do a rename before the Humanize is generated i.e. ```name = name.Replace("STK_", "STOCK_");``` will change the table name to have the word ```Stock```.

The rename for columns applies after the Humanize has been done. Ideally I would like to do the rename before the underscores are stripped out.

For example, the database contains column names like ```SALES_VALUE_LYR```. If I want the output to be ```SalesValueLastYear``` I can do a rename on the Humanized column of ```Lyr``` to ```LastYear``` but then there are columns which contain ```LLYR``` which would get renamed to ```LLastYear```.
 
I would like to do the rename of ```_LYR``` to ```_LAST_YEAR``` and ```_LLYR``` to ```_PREVIOUS_LAST_YEAR``` before the Humanize.

Another example is that there are columns with ```_PER_``` which I want to rename to ```_PERIOD_``` to avoid having to do it after the Humanize so it doesn't rename columns like ```_PERSON_```,

**Comment by sjh37** [comment]
Hi @kostii 

No problem.

Search for
```c#
col.NameHumanCase = rxClean.Replace(col.NameHumanCase, "_$1");
```
in the file `EF.Reverse.POCO.Core.ttinclude`. It should be approximately line 3544

Under that line, you can either add this line
```c#
Settings.UpdateColumn(col, col.ParentTable);
```
or instead of calling `UpdateColumn` simply add your own code in to do your string replacements for `_LLYR`, `_LYR`, etc.

Any problems let me know, and I'll re-open the case.

**Comment by sjh37** [comment]
Other related case is #254
