### ISSUE TITLE
Can't generate FK relationship when fk is mapped to unique index

### ISSUE THREAD

**Issue by Pearseak** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#524]

**Comment by sjh37** [comment]
Duplicate of #364 
- EF6: Foreign key against a unique index is _not_ allowed. Only FK's against primary keys are allowed in EF6
- EFCore: Foreign key against a unique index is allowed.

The soon to be released v3 of the generator will support both EF6, EFCore2, EFCore3.
Foreign key against a unique index is allowed and code generated for both EFCore2, EFCore3.
Take a look at #364
