### ISSUE TITLE
Poco Naming Issue

### ISSUE THREAD

**Issue by Bitfiddler** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#53]
First, great work on this.  Totally love the flexibility and output of the tool.  One small issue:

I am working with a legacy database that has it's table names pluralized.  When the generator creates entities for tables with names that end in 'ies' it capitalizes the second-last letter of the word, which it should not.

Example:
Currencies (table) -- becomes --> CurrenCy.cs

![pocogeneratorissue](https://cloud.githubusercontent.com/assets/1213557/15941255/84141b40-2e3c-11e6-9b7d-ed4b2d9ff460.jpg)

I have been trying to debug the template myself to propose a fix, but debugging t4 templates has proved more complex than I have time for at the moment (when my second vs2015 instance launches to debug, it cannot find the pdb file of the t4 template and adding the debug attribute to the t4 template causes an error in the template itself).

**Comment by Bitfiddler** [comment]
I also tried doing a tableRename callback, but it seems that there is something about words ending in 'y' that causes mahem:

![pocogeneratorissue2](https://cloud.githubusercontent.com/assets/1213557/15948195/9eb6a81c-2e5c-11e6-9524-577317ed8fdd.jpg)

**Comment by Bitfiddler** [comment]
I think I have figured it out.  Whatever part of the code 'depluralizes' the table name probably replaces the 'ies' with a lower case 'y'.

So:
CURRENCIES (table) -- becomes --> CURRENCy

Then when the part of the code that does camel casing runs, it probably interprets the lowercase 'y' at the end as a new word so:
CURRENCy -- becomes --> CurrenCyMapping

The following callback fixes this:
![pocogeneratorissue3](https://cloud.githubusercontent.com/assets/1213557/15948489/46aff072-2e5e-11e6-9c59-f583818932b3.jpg)

**Comment by sjh37** [comment]
Definitely a strange bug I've not seen before.
I must admin I've never tested against a database with all CAPS for its table names, so will give it a go and report back...

**Comment by Bitfiddler** [comment]
Totally understandable, table names in all caps are weird but such is the database I'm working with.  I think it was, at one point, a straight import of text files who's file names were all CAPS.  The table names were never updated and so here I am ;-)  Any tips for debugging t4 templates?  

I have tried adding:
System.Diagnostics.Debugger.Launch();

To a spot in the template that I wanted to debug but got a "pdb not found" in the debugger instance.

So I tried adding to the template:
<@#template debug="true" #>

But then I get an error:
Error Compiling transformation: The name 'Host' does not exist in the current context       

Am I missing something?  Do you debug this in some other fashion?

**Comment by Bitfiddler** [comment]
Figured it out, the debug attribute needed to be added to the existing template tag in EF.Reverse.POCO.Core.ttinclude:
<#@ template  debug="true" hostspecific="true" language="C#" #>

**Comment by sjh37** [comment]
OMG, I've never debugged a T4 template before. This is amazing :-)

For debug, I now use
1. Set a breakpoint in the .tt file
2. Right-click the .tt file in the solution explorer
3. Select "Debug T4 Template"
4. Done!

No attaching a second instance of Visual Studio needed.

**Comment by sjh37** [comment]
``` sql
CREATE TABLE BitFiddlerCATEGORIES ([Id] int NOT NULL IDENTITY(1,1) PRIMARY KEY)
CREATE TABLE BitFiddlerCURRENCIES ([Id] int NOT NULL IDENTITY(1,1) PRIMARY KEY)
```

created

``` c#
DbSet<BitFiddlerCategoRy> BitFiddlerCategoRies { get; set; } // BitFiddlerCATEGORIES
DbSet<BitFiddlerCurrenCy> BitFiddlerCurrenCies { get; set; } // BitFiddlerCURRENCIES
```

Quite amazed at the pluralisation. service doing this.
Definitely bug of the year. Great find!!

**Comment by sjh37** [comment]
Getting close, not quite there yet.
I'll continue over the weekend at some point as its late

**Comment by sjh37** [comment]
Sorted. See the latest code changes. This will be in the next release.

**Comment by Bitfiddler** [comment]
Thanks so much!  I had it on my todo list to sort this out during the week but I certainly appreciate the fix!
