### ISSUE TITLE
cant access .GetTable and  Mapping.GetTable

### ISSUE THREAD

**Issue by smarteez17** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#532]
Hi 

I found the code on the net 
https://blog.csainty.com/2008/04/linq-to-sql-generic-primary-key.html

I want to create a generic get method that takes in Table and Pk and returns First Object 

I having issues with the following lines cant access .GetTable and  Mapping.GetTable

var table = context.GetTable<T>();
 var mapping = context.Mapping.GetTable(typeof(T));

**Comment by sjh37** [comment]
EntityFramework already provides the `Find` function which searches by the primary key. 

DbSet.Find accepts the primary keys and returns an entity. Calling Find can improve the performance, because it looks up cache before querying the database.

```c#
using (AdventureWorks adventureWorks = new AdventureWorks())
{
    Product[] products = adventureWorks.Products
        .Where(product => product.Name.StartsWith("Road"))
        .ToArray(); // SELECT
	
    Product fromDatabaseAndThrowAway = adventureWorks.Products
        .Where(product => product.Id == 4) // <-- I see this all the time in users code!
        .FirstOrDefault(); // SELECT to get data from db, and then throw it away.

    Product fromCache = adventureWorks.Products
        .Find(4); // No database query. #YES

    Trace.WriteLine(products.Contains(fromCache)); // True
}
```
