### ISSUE TITLE
Generating template for multiple database providers

### ISSUE THREAD

**Issue by statler** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#535]
I have a model that is shared across 2 different database providers - SQL and CE. The problem I face is that my template works fine for SQL, but the same template will not work for CE. In my case the issue is types - notably nvarchar(max) which needs to be ntext in CE, and money=> numeric.

Can you suggest any options whereby I could relatively easily develop a template that would work for both? I figure I would been to just base it on (say) the SQL template, and use conditionals to create something like;

```c#
string moneyType = isSQL?"money":"numeric";
Property(x => x.ItemOrder)
    .HasColumnName(@"ItemOrder")
    .HasColumnType(moneyType )
    .IsOptional()
    .HasPrecision(19,4);
```

Any recommendations about the easiest way to achieve this - any suggestions appreciated as I expect this may not be the best way to do this.

**Comment by sjh37** [comment]
Try it without defining the HasColumnType at all. In `EF.Reverse.POCO.Core.ttinclude`, change line
```c#
sb.AppendFormat(".HasColumnName(@\"{0}\").HasColumnType(\"{1}\")", Name, SqlPropertyType);
```
to
```c#
sb.AppendFormat(".HasColumnName(@\"{0}\")", Name);
```

**Comment by statler** [comment]
Only problem is that I have some non-standard mappings - otherwise I think that would work. 

In the end, it looks like the EF properties are stored using a hash on the name of the property, and repeating the property definition overwrites any existing definition.

This means I can do it with partials. I just set the configuration classes as partial, and where necessary create another partial class with the partial method on InitializePartial.

Seems to work OK

```

    public partial class NcrConfiguration
    {
        partial void InitializePartial()
        {
            if (!cpContext_Approval.IsSqlCe) return;
            Property(x => x.ApprovalDetails).HasColumnName(@"ApprovalDetails").HasColumnType("ntext").IsOptional();
            Property(x => x.NcrCost).HasColumnName(@"NCRCost").HasColumnType("numeric").IsOptional().HasPrecision(19, 4);
        }
    }
```

**Comment by sjh37** [comment]
@statler Nice idea. Good simple solution.
