### ISSUE TITLE
Table-valued parameter support in TVF/sproc?

### ISSUE THREAD

**Issue by daiplusplus** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#537]
I have some table-valued functions that accept a table-valued parameter, however they don't seem to be imported by the T4 scirpt.

Curiously, when I added a stored-procedure that has identical parameters, but wraps the TVF, then the T4 script imports it fine - albeit using a `DataTable` for the table-valued parameter instead of respecting the original UDT.

I couldn't find anything in the documentation or other issues regarding table-valued functions that accept table-valued parameters.

**Comment by sjh37** [comment]
Hi Dai, Send me an email, As a thank you for your past contributions to v2 I'd like to give you a free licence to v3 when it comes out. simon@hicrest.net

**Comment by sjh37** [comment]
Could you have a test with the new v3 generator? It'll probably be the same, but worth a try.
Here is a [DropBox](https://www.dropbox.com/s/huxxlel9irlgjp2/ReversePoco.7z?dl=0) link to the latest v3 code.

**Comment by daiplusplus** [comment]
@sjh37  Thanks - I'll try it out shortly.

I have a PR I'd like to submit immediately to add suport for tabbed indentation (by setting `Indent = -1`), where can I submit it? :)

**Comment by sjh37** [comment]
Hi @Jehoel Email me the code, and I'll use Araxis to compare it with my source and pull in the changes.
Thanks.

**Comment by sjh37** [comment]
If v3 has a problem with this, let me know and I'll re-open.

**Comment by daiplusplus** [comment]
Ooof, sorry - I let this slip in my TODO lists.

Thank you for the email with the v3 info - I should be able to try it out next week as I'm busy for the rest of this week with non-work-related things.

**Comment by Altri** [comment]
Hello. Any updates on this? I have the same problem and I am using v2. Would upgrading to v3 resolve the issue?

**Comment by sjh37** [comment]
Hi @Altri Download a trial license which will give you a restricted number of tables and stored procedures (I plan to increase that on the next release) and see if it works for you.
