### ISSUE TITLE
Steps to Upgrade version 

### ISSUE THREAD

**Issue by smarteez17** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#546]
Hi There 

I currently using version  v2.37.4

I would like to upgrade to the new version which includes Scalar Value Functions. Please can you advise steps on how to upgrade so that I don't loose any of my current setting.

Also last we chatted The new version doesn't include data annotation , can it be included as this help a lot with creating the entries  and When I need to create my Domain/Application classes I can just copy the setting from the entries  classes.

When bring in Scalar Value Functions do I still need to include Stored Procs? As this new system upgrade I working on is replacing all Store procs with EF Methods  

Editing TT (T4) Files
To have full syntax highlighting and intellisense when editing TT files, I use the Resharper plugin ForTea. I can't imagine editing TT files without it.

Can you suggest any other editors as Many people I know including me  dont have Resharper 

https://www.dropbox.com/s/huxxlel9irlgjp2/ReversePoco.7z?dl=0

Is this file a trial version ? when the new version coming out 

Settings.ConnectionStringName    = "RiskDataContext"; // ConnectionString key as specified in your app.config/web.config/appsettings.json
    Settings.DbContextName           = "RiskDataContext"; // Class name for the DbContext to be generated. Note: If generating separate files, please give the db context a different name from this tt filename.
    //Settings.DbContextInterfaceName= "IMyDbContext"; // Defaults to "I" + DbContextName or set string empty to not implement any interface.
    Settings.GenerateSeparateFiles   = true;

here my setting i updated from your files but no classes and file are being created and In my document folder I did put the  ReversePOCO file

**Comment by sjh37** [comment]
I have written up documentation: [here](https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/wiki/Upgrading-from-v2-to-v3)

**Comment by smarteez17** [comment]
Hi What about my Other questions 

Editing TT (T4) Files
To have full syntax highlighting and intellisense when editing TT files, I use the Resharper plugin ForTea. I can't imagine editing TT files without it.

Also last we chatted The new version doesn't include data annotation , can it be included as this help a lot with creating the entries and When I need to create my Domain/Application classes I can just copy the setting from the entries classes.

When bring in Scalar Value Functions do I still need to include Stored Procs? As this new system upgrade I working on is replacing all Store procs with EF Methods

**Comment by sjh37** [comment]
Hi,

## Data annotations

You can manually add data annotations using the column.Attributes list within UpdateColumn.

Example:

```c#
Settings.UpdateColumn = delegate(Column column, Table table, List<EnumDefinition> enumDefinitions)
{
    // Adding custom data annotations (include your extra namespaces in Settings.AdditionalNamespaces above)
    column.Attributes.Add($"[Display(Name = \"{column.DisplayName}\")]");
    if (column.IsPrimaryKey)
        column.Attributes.Add("[Key]");
}
```

##  Scalar Value Functions
Inside `FilterSettings.CheckSettings()` function, I force `IncludeStoredProcedures = true` if TVF or SVF are required.

```c#
public static class FilterSettings
{
    public static void CheckSettings()
    {
        if (IncludeTableValuedFunctions || IncludeScalarValuedFunctions)
            IncludeStoredProcedures = true; // Must be set if table/scalar functions are wanted
    }
}
```

`FilterSettings.CheckSettings()` is called from your `<database>.tt` settings file, very near the bottom.

**Comment by smarteez17** [comment]
thank you will try the upgrade today and let you know the outcomes 

Editing TT (T4) Files
To have full syntax highlighting and intellisense when editing TT files, I use the Resharper plugin ForTea. I can't imagine editing TT files without it.

Can you suggest any other editors as Many people I know including me dont have Resharper

**Comment by sjh37** [comment]
Hi @smarteez17 
I've not looked any further to be honest, as R# + ForTea works for me.

**Comment by smarteez17** [comment]
Hi I have done some testing and found one issues V3 only works if I have this file in my documents folder ( I got yhis file from you when we were test) . I check the file and it saying Trial version . can I get the new file 
[ReversePOCO.txt](https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/files/3868701/ReversePOCO.txt)


I also try running EntityFramework.Reverse.POCO.Generator.v3.0.8 

![image](https://user-images.githubusercontent.com/35128168/69231452-c4e92a80-0b91-11ea-9ce4-8c91bf9181a6.png)

I am using vs 2019 and dont see the option 

Are Scalar value function going to be in the context . Can you give me a small example how can i call it ?

**Comment by sjh37** [comment]
@smarteez17 Get a licence from www.reversepoco.co.uk

**Comment by smarteez17** [comment]
@sjh37  does this mean that Poco is no long freeware ?

**Comment by sjh37** [comment]
Hi @smarteez17 

It's free for non-commercial / classroom learning / academic (student, etc) purposes only.
You will need a paid license for commercial use.
