### ISSUE TITLE
Commercial licensing model

### ISSUE THREAD

**Issue by harigutta** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#548]
For an organization, is one commercial license sufficient or do we need to buy a license for every developer?
https://www.reversepoco.co.uk/Pricing

**Comment by sjh37** [comment]
Hi @harigutta 

Thanks for checking. You can do either. If you have a team of 6 developers, you can either buy:
- A single license with Qty = 6, with the license name set to the name of your team/group.
- Or buy 6 individual licenses with each name set to the name of each developer.
