### ISSUE TITLE
Current and Old versions 

### ISSUE THREAD

**Issue by smarteez17** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#549]
Hi @sjh37 

With the New version (Version 3) needs a licence for used. Currently in my company with I work for they using version 2 and it didn't need a licence. They have used your plural sight and used it in a number of projects (https://www.pluralsight.com/courses/code-first-entity-framework-legacy-databases) 

**Questions** 
1. Whats does it mean for version 2 will it stop working without a licence key ?
2. Will version 2 be discontinued and all current system stop working ?
3. Is the version 3 the only version we can use ? can we still use the old version

**Comment by sjh37** [comment]
Version 2 will continue to work in your project, forever, and won't ever need a license key.

You can continue to use version 2 for as long as you like. However it won't ever be upgraded beyond what it can do now. If you need .Net Core support, you will need version 3.

**Comment by smarteez17** [comment]
Thank for that information How do I used version 2 on new projects as when I tried to do a test project only version 3 comes up

**Comment by sjh37** [comment]
You have to uninstall version 3, and install version 2 which is available from 
`https://reversepocostorage.blob.core.windows.net/public-file-share/EntityFramework Reverse POCO Generator v2.37.5.vsix`

**Comment by smarteez17** [comment]
thank you

**Comment by irfnkprc** [comment]
thank you Simon for sharing the version 2 installer
