### ISSUE TITLE
TableFilterInclude applied against original and renamed table name

### ISSUE THREAD

**Issue by TimSirmovics** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#55]
I am using the TableFilterInclude to control which tables/views are generated.

I found that for objects that are renamed, I have to include two entries in the Regex - one for the original name and one for the renamed version. This is not made clear in the comments (I had to debug the tt to work it out), and means I have to double up the entries in my Regex to account for both names:

`TableFilterInclude = new Regex("PurchaseOrder.*|Purchase Order.*|WebOrder.*|Web Order.*|vwClientSupplier|Vw Client Supplier|vwOrders|Vw Orders");`

Is this the intended behaviour?
I understand for exclusions it makes sense to apply it to both names to give the user the option of using either, but for inclusions it introduces extra work to account for both combinations.
Could you provide an option to only apply filters to either the original, or renamed names?

**Comment by sjh37** [comment]
No this is definitely not the intended behaviour.
I recently changed the filter code to do a better job. Can you use version 2.20.1 and let me know if this is still a problem. If so, I'll look at this asap.

**Comment by TimSirmovics** [comment]
Hi Simon,

I've only just started using the generator today after watching your Pluralsight course, and i'm using v2.20.1.

**Comment by sjh37** [comment]
ok, i'll look into it asap. Perhaps I introduced a bug.

**Comment by sjh37** [comment]
I have replicated the problem and will get a fix out shortly.

**Comment by sjh37** [comment]
In `EF.Reverse.POCO.Core.ttinclude` change line 1680 from

``` c#
if (IsFilterExcluded(tableFilterExclude, tableFilterInclude, tableName)) // Retest after table rename
```

to

``` c#
if (IsFilterExcluded(tableFilterExclude, null, tableName)) // Retest after table rename
```

Can you please let me know if this works ok for you

**Comment by suitcasenuke** [comment]
I was hitting the same issue. Changing the line in EF.Reverse.POCO.Core.ttinclude fixed the issue for me.

**Comment by TimSirmovics** [comment]
This fix works.

**Comment by sjh37** [comment]
Great. Thanks for checking. This will be in the next release.
