### ISSUE TITLE
AddParameterlessConstructor setting is ignored in EFCore templates

### ISSUE THREAD

**Issue by 0xced** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#551]
Hi Simon,

I have found another small bug. You should add this in EF.Reverse.POCO.v3.ttinclude v3.0.8 (line 16283):
```
{{#if AddParameterlessConstructorToDbContext}}
```
and `{{/if}}` on line 16291.

**Comment by sjh37** [comment]
Thanks.

**Comment by sjh37** [comment]
Hi @0xced 

Taking a look at the code, this setting is for EF 6 only as you can't just pass in the connection string to the base class. However, there is an OnConfiguration() function, which I've just enhanced.

I've added a new Enum to control how the connection strings are used.
See case #553 and [Settings.OnConfiguration](https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/wiki/Settings.OnConfiguration) documentation.

I'd like to add a comment to `Settings.AddParameterlessConstructorToDbContext` to say
`// EF 6 only. If true...`

Let me know what you think.

**Comment by sjh37** [comment]
I've added a comment to the code about it. I'll close this for now as I don't think it belongs in EF Core.
