### ISSUE TITLE
Connection string in Generated Code

### ISSUE THREAD

**Issue by agentKnipe** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#553]
I have found that the connection string listed in the config file is being placed in the generated code.  This results in committed code having usernames and passwords in them.  

![image](https://user-images.githubusercontent.com/7571082/70093021-87eb5200-15ed-11ea-8e75-769010cfccb6.png)

A possible solution would be to updated the the include file as follows:
![image](https://user-images.githubusercontent.com/7571082/70093066-a0f40300-15ed-11ea-946d-62a02a4cf6ad.png)

I needed to add the connection string name to the ContextModel class.  Additionally I added a reference to IConfiguration in my base class, and added :
using.Add("Microsoft.Extensions.Configuration");

to the include where the dbcontext is created.  I have not completed testing, nor do I know much about T4 templates, but this appears ( at first glance) to generate the appropriate OnConfiguring method.

![image](https://user-images.githubusercontent.com/7571082/70093319-1eb80e80-15ee-11ea-8db5-2c23230c3c83.png)

**Comment by sjh37** [comment]
Hi

Normally the connection string is passed via Startup.ConfigureServices and IMyDbContext is dependency injected into your controllers using:
```c#
services.AddDbContext<MyDbContext>(options =>
    options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
```

or by manually choosing a connection string with:

```c#
var optionsBuilder = new DbContextOptionsBuilder<MyDbContext>();
optionsBuilder.UseSqlServer("Data Source=(local);Initial Catalog=Northwind;Integrated Security=True");
_db = new MyDbContext(optionsBuilder.Options);
```

or by passing in an IConfiguration to a new ctor of the dbcontext:

```c#
private readonly IConfiguration _configuration;

public MyDbContext(IConfiguration configuration)
{
    _configuration = configuration;
}

protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
{
    if (!optionsBuilder.IsConfigured && _configuration != null)
    {
        optionsBuilder.UseSqlServer(_configuration.GetConnectionString("MyDbContext"));
    }
}
```

The `OnConfiguring` is used if there as a fall-back if no optionsBuilder passed in. Normally not a problem if you are using a "Integrated Security=true" style connection string as it doesn't contain a username/password, but is a problem if you do and don't want this in the code.

Now the real question, which option do I provide to the general public?
The best answer may be to provide this as a configuration option in the <database>.tt file. You select what you'd like generated. 

I'll add a new configuration enum called OnConfiguration:

### OnConfiguration.Omit
You may always be using DI, and have the connection string configured there, in which case you do not need an `OnConfiguring` function at all.

### OnConfiguration.ConnectionString
Place the Settings.ConnectionString into the code as is being done now.
```c#
optionsBuilder.UseSqlServer(@"Data Source=(local);Initial Catalog=Northwind;Integrated Security=True");
```

### OnConfiguration.Configuration
Uses
```c#
optionsBuilder.UseSqlServer(_configuration.GetConnectionString("MyDbContext"));
```

**Comment by agentKnipe** [comment]
Thank you for the response.  Personally, I would think most people would want the `optionsBuilder.UseSqlServer(_configuration.GetConnectionString("MyDbContext"));` style OnConfiguration as the default; even in an environment where integrated security if feasible.  If your db server changes (end of life hardware, hardware failure etc), I cant imagine anyone would want to redeploy code instead of updating a connection string in a config file.  We recently moved to azure, and updating config files was trivial compared to updating 100+ applications, and then redeploying them.  

Thank you again, Im looking forward to the update.

**Comment by sjh37** [comment]
Done. This will be in the next release.
