### ISSUE TITLE
Question - Do I need everything in the database.tt file?

### ISSUE THREAD

**Issue by agentKnipe** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#554]
This is kind of a silly question, but do I need everything in the database.tt file? I am in the process of figuring out the best way to make this work all of our applications such that the developers need to make minimal changes to the database.tt file.  Ideally Id come up with the settings we want to use and dump out everything else, so that other developers only need to set the connection string info, and they are off and running.  

Would this work?  is there some set of other things in the tt files that are needed in order to make the generation run correctly (besides the includes at the top obviously)?

**Comment by sjh37** [comment]
Defaults are already provided in the Settings class, at the top of the `EF.Reverse.POCO.v3.ttinclude` file. So you can strip down the database.tt quite dramatically.

The minimum you need are:
```c#
Settings.DatabaseType            = DatabaseType.SqlServer; 
Settings.TemplateType            = TemplateType.EfCore3; 
Settings.GeneratorType           = GeneratorType.EfCore;
Settings.UseMappingTables        = false; 
Settings.FileManagerType         = FileManagerType.Custom; 
Settings.ConnectionString        = "Data Source=(local);Initial Catalog=Northwind;Integrated Security=True";
Settings.ConnectionStringName    = "MyDbContext";
Settings.DbContextName           = "MyDbContext"; 
Settings.OnConfiguration         = OnConfiguration.Configuration;
Settings.GenerateSeparateFiles   = false;
Settings.Namespace               = DefaultNamespace; 

FilterSettings.Reset();
FilterSettings.AddDefaults();

Inflector.PluralisationService = new EnglishPluralizationService();
var outer = (GeneratedTextTransformation) this;
var fileManagement = new FileManagementService(outer);
var generator = GeneratorFactory.Create(fileManagement, FileManagerFactory.GetFileManagerType());
if (generator.InitialisationOk)
{
    generator.ReadDatabase();
    generator.GenerateCode();
}
fileManagement.Process(true);#>
```

**Comment by sjh37** [comment]
In fact it used to look like that all through efcore development, and I had to add in all the settings before it went live so people could easily set something without having to think too hard.

**Comment by agentKnipe** [comment]
excellent, thank you!
