### ISSUE TITLE
Bypassing pluralization

### ISSUE THREAD

**Issue by statler** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#558]
I prefer to have my entities without plural. Similarly with my reverse navigation properties.

How can I bypass the pluralization?

**Comment by statler** [comment]
Same as previous version - sorry. Missed a //


    Inflector.PluralisationService = null;

**Comment by sjh37** [comment]
Hi, yes that is exactly correct. Set it to null.
I'll add a comment to the code to make sure others know how to turn it off too.

**Comment by sjh37** [comment]
Released in v3.1.1
