### ISSUE TITLE
.Net Core 3.1 error

### ISSUE THREAD

**Issue by LarryWMSN** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#559]
I'm getting the below error on startup using .Net Core 3.1 with version 3.1.0 of the templates. Is there anything I need to set that I am missing or do you need more information?

>System.AggregateException: 'Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Database.MyContext Lifetime: Scoped ImplementationType: Database.MyContext': Unable to activate type 'Database.VendorBridgeContext'. The following constructors are ambiguous:
Void .ctor(Microsoft.EntityFrameworkCore.DbContextOptions`1[Database.MyContext])
Void .ctor(Microsoft.Extensions.Configuration.IConfiguration))'

The constructors look like this in Database.cs:

```cs
public MyContext() {}

public MyContext(DbContextOptions<VendorBridgeContext> options) : base(options) {}

public VendorBridgeContext(IConfiguration configuration)
{
    _configuration = configuration;
}
```
And startup.cs has this in ConfigureServices: 
```cs
services.AddDbContext<MyContext>();
```

**Comment by sjh37** [comment]
Hi Larry,

in startup.cs change it to be
```c#
services.AddDbContext<MyContext>(options =>
    options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
```

**Comment by LarryWMSN** [comment]
That works great when I run it on my dev machine, but when I deploy it to the server I need to be able to have the code use appsettings.json. I would also prefer to use user secrets on my dev machine if that's possible too.

**Comment by sjh37** [comment]
In program.cs you should have
```c#
 var environment = Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT")
                              ?? EnvironmentName.Development;
var configuration = new ConfigurationBuilder()
                .AddJsonFile("appsettings.json", false, true)
                .AddJsonFile($"appsettings.{environment}.json", true, true)
                .AddEnvironmentVariables()
                .Build();
```

**Comment by LarryWMSN** [comment]
Thanks,

I used the above code as my starting point and I can see that the files are getting read. However when I attach a remote debugger to the process I see that optionsBuilder.IsConfigured is always false in OnConfiguring in the database.cs file, so it tries to use to connection string from the tt file.

**Comment by LarryWMSN** [comment]
After many attempts I think the only change needed was in startup.cs --> ConfigureServices

```cs
services.AddDbContext<MyContext>(options =>
    options.UseSqlServer(Configuration["ConnectionStrings:MyConnectionString"]));
```

**Comment by sjh37** [comment]
Great news. Thanks for letting me know. I'll close this case.
