### ISSUE TITLE
FakeDbContext isnt implementing methods in the Settings.DbContextInterfaceBaseClasses

### ISSUE THREAD

**Issue by agentKnipe** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#560]
The fake DB context doesnt appear to be implementing the methods laid out in the Settings.DbContextInterfaceBaseClasses.  It is entirely possible to im using this feature incorrectly, or miss interpreting what should be generated.

For example, I have a interface that I am referencing in that setting which provides an additional SaveChanges method that takes a UserID as a parameter

```
public interface IMyDbContext : IDisposable {
        int SaveChanges(int maintUserID);
    }
```

However, when the fake db context is generated, this method is not generated.  This method is also no generated with the normal db context, but I am handling that with my base class.

![image](https://user-images.githubusercontent.com/7571082/70655841-f308da00-1c26-11ea-835a-15b72bb47668.png)

Should I be implementing this method in a fake db context base class? if so is there a way to identify that base class in the settings similar to 
`Settings.DbContextBaseClass                     = "DbContext"; // Specify what the base class is for your DbContext. For ASP.NET Identity use "IdentityDbContext<ApplicationUser>";`

note* im not worried about the first error, im tacking that onto elsewhere, and understand why that one is not there.  its the 2nd one im concerned with IWorkflowContext extends from my interface example above.

**Comment by sjh37** [comment]
Hi.

First off, set
```c#
Settings.AdditionalContextInterfaceItems = new List<string> { "int SaveChanges(int maintUserID);" };
Settings.DbContextClassModifiers     = "public partial";
Settings.DbContextInterfaceModifiers = "public partial";
```

Create two partial classes
```c#
public partial class MyDbContext
{
    public int SaveChanges(int maintUserID)
    {
        // todo
    }
}

public partial class FakeMyDbContext
{
    public int SaveChanges(int maintUserID)
    {
        // todo
    }
}
```

As you are using a base class to do the work for the `MyDbContext` you can omit that partial class.

**Comment by agentKnipe** [comment]
ok so I would have to implement the save changes in a separate partial class. not a problem thank you.
