### ISSUE TITLE
Remove type from DbContextOptions arg

### ISSUE THREAD

**Issue by statler** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#561]
The code generates a constructor like below. 

        public cpContext_base(DbContextOptions<cpContext_base> options)
            : base(options)
        {
        }

I use the generated context as a baseclass for my public context, so this causes issues. What I need is;

        public cpContext_base(DbContextOptions options)
            : base(options)
        {
        }

so that from my parent class I can call;

    public class cpContext : cpContext_base
        {
            public cpContext(DbContextOptions<cpContext> options, IHttpContextAccessor httpContextAccessor) : base(options)
            {
                _httpContextAccessor = httpContextAccessor;
            }
        }

Is there anything that I could do in the config? Or do I need to edit the template?

**Comment by sjh37** [comment]
You need to edit the template to do that.
Approximately line 16481
change
```
public {{DbContextName}}(DbContextOptions<{{DbContextName}}> options){{#newline}}
```
to
```
public {{DbContextName}}(DbContextOptions options){{#newline}}
```

**Comment by sjh37** [comment]
Any problems, let me know and I can re-open this case.
