### ISSUE TITLE
Log of substitutions

### ISSUE THREAD

**Issue by statler** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#566]
What would be the easiest way to generate a log of all substitutions made on account of rules in the template? E.g. I have several case-based substitutions (e.g. Fsid=> FsId) and some FK substitutions. To check for case issues on my client, it would be handy to know what was subbed.

**Comment by sjh37** [comment]
In `<database>.tt` in the `UpdateColomn` function add the following:

```c#
if(column.NameHumanCase != column.DbName)
{
    var sub = string.Format("{0}.{1} = {2}.{3}{4}",
        table.DbName, column.DbName, table.NameHumanCase, column.NameHumanCase, Environment.NewLine);
    File.AppendAllText("c:\\temp\\Substitutions.txt", sub);
}
```

You will want to delete that file every time the generator is run, so near the bottom of `<database>.tt`, just before `FilterSettings.CheckSettings();` add the following

```c#
File.Delete("c:\\temp\\Substitutions.txt");
```
