### ISSUE TITLE
Support Rider IDE

### ISSUE THREAD

**Issue by sjh37** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#567]
See if it's possible to include support for an IntelliJ plugin.

**Comment by mtanneryd** [comment]
I recently started using the Rider IDE instead of VS2019. The only thing missing right now is support for your "EntityFramework-Reverse-POCO-Code-First-Generator". I tried the hackish way of getting it to work described by bbakermmc in another thread but could not get it to work properly.

**Comment by sjh37** [comment]
I would love to be able to support Rider. Not sure if its even possible. Any Rider experts out there would could help with this?

**Comment by sjh37** [comment]
As of December 2019 Rider supports T4 templates
https://blog.jetbrains.com/dotnet/2019/12/17/introducing-t4-text-template-support/

I have contacted Matthias Koch @matkoch87 to see if he can help.

**Comment by sjh37** [comment]
Duplicate of #412

**Comment by sjh37** [comment]
Closing this case as it's a duplicate of #412. Any updates for Rider support will be added in #412.
