### ISSUE TITLE
System.Linq.IQueryable

### ISSUE THREAD

**Issue by TimSirmovics** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#57]
When IncludeTableValuedFunctions is set to true, tvf's are generated with IQueryable return values.

Unlike the other members of the context which are generated with full namespaces, IQueryable is generated with no namespace and causes a compiler error as the System.Linq namespace needs to be imported.

I know that additional namespaces can be manually added in the config, but can the IQueryable be generated like all other items with the fully qualified name?

**Comment by sjh37** [comment]
Released in 2.20.2
