### ISSUE TITLE
DbContext constructors are ambiguous

### ISSUE THREAD

**Issue by mmisnerms** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#572]
I use the following to add my dbcontext to my webapp.

services.AddDbContext<IMyDbContext, MyDbContext>(options => options.UseSqlServer(Configuration.GetConnectionString("MyDb")));

I am getting the following exception from the services DI:

The following constructors are ambiguous:
Void .ctor(Microsoft.EntityFrameworkCore.DbContextOptions`1[MasterSpa.My.Domain.Entity.MyDbContext])
Void .ctor(Microsoft.Extensions.Configuration.IConfiguration)

The dbcontext constructors are as follows

    public MyDbContext()
    {
    }

    public MyDbContext(DbContextOptions<FinishedGoodsScanDbContext> options)
        : base(options)
    {
    }

    public MyDbContext(IConfiguration configuration)
    {
      _configuration = configuration;
    }

If I comment out the DbContextOptions constructor it works.

**Comment by sjh37** [comment]
Set
```c#
Settings.OnConfiguration = OnConfiguration.ConnectionString;
```

**Comment by sjh37** [comment]
To prevent this, I have changed the default to be:
```c#
Settings.OnConfiguration = OnConfiguration.ConnectionString;
```
which is how it used to be.
This will be in the next release
