### ISSUE TITLE
Sample CustomPluralizationEntry's enabled by default

### ISSUE THREAD

**Issue by TimSirmovics** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#58]
When adding a new Reverse Poco tt file, the Pluralization section contains entries for LiveQuizzes, Course, CustomerStatus and EmployeeStatus which were used as samples in your pluralsight course.

I think you may have left these uncommented unintentionally as all other examples are commented out.

**Comment by sjh37** [comment]
updated.
