### ISSUE TITLE
Examples with t.Schema.Name

### ISSUE THREAD

**Issue by TimSirmovics** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#583]
Some of the examples for filtering in `EF.Reverse.POCO.v3.ttinclude` have comments referencing `t.Schema.Name` where `Name` does not exist any more and should probably be `DbName` or `NameHumanCase`.

**Comment by sjh37** [comment]
Well spotted. Thanks @TimSirmovics.

**Comment by sjh37** [comment]
Now released as part of v3.2.0
