### ISSUE TITLE
Duplicate DbSets generated in the FakeContext

### ISSUE THREAD

**Issue by pmcivor-accesso** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#584]
Hello, I have a situation where the FakeDbContext is generating duplicate DbSets for an entity I have mapped 2 different stored procedures to.  For example in the .tt file:

`Settings.StoredProcedureReturnTypes.Add("getProductionsById", "Production"); 
	Settings.StoredProcedureReturnTypes.Add("getProductionsSomeOtherWay", "Production"); `

The FakeDbSet is creating two DbSet properties named "Production" like
`public DbSet<Production> Production { get; set; }`

Is there a good way to prevent this from happening? thanks!

**Comment by sjh37** [comment]
That should be fixed now. Grab the latest `EF.Reverse.POCO.v3.ttinclude` file from github and replace yours in your project.
Any problems, let me know.

**Comment by pmcivor-accesso** [comment]
all good, thanks!
