### ISSUE TITLE
ObjectParameter null string values

### ISSUE THREAD

**Issue by TimSirmovics** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#59]
Object Parameters are generated for functions using the (string name, object value) constructor:

`var exampleParam = new System.Data.Entity.Core.Objects.ObjectParameter("ExampleParam", exampleParamValue);`

When an optional string parameter is null, this throws an exception in the constructor of ObjectParameter even though it is legal and neccesary to have a null value for this parameter.

[This StackOverflow answer](http://stackoverflow.com/a/4815554/395416) suggests using the alternative constructor, and setting the Value parameter after construction:

`var exampleParam = new System.Data.Entity.Core.Objects.ObjectParameter("ExampleParam", typeof(string))  { Value = exampleParamValue }`

Could this be incorporated into the generator?

**Comment by sjh37** [comment]
I have modified WriteTableValuedFunctionDeclareSqlParameter.
Can you pull the latest code and check this ok

**Comment by TimSirmovics** [comment]
Perfect.

**Comment by sjh37** [comment]
Great. Thanks for your help. This will be in the next release.
