### ISSUE TITLE
Custom Classes

### ISSUE THREAD

**Issue by acgentry** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#592]
Hi Simon,

Any mechanism we can leverage to generate home brew classes next to the POCO classes?

I have inherited a large database that was created from ETL tools, think hundreds of CSV files of various dimensions, that I would like to move to EF. What I need is to generate a method that will mimic the poco configuration class but would stand on its own to iterate through the columns and expect a list of string values and cast them to the correct DB type.

If this doesn't already exist it would be great to inject a custom classes into your framework.

Thanks,
ACG

**Comment by sjh37** [comment]
Hi ACG,

Interesting.

I initially thought that using either the multi-context generator (where it reads the tables and columns you want to generate from a separate database) or a multi-context plug-in (you specify it the tables and columns in an array, see `MultiContextSettingsPluginNorthwind` in the `Generator.Tests.Unit` project). However, they also read the db schema and match the two up and only output what you need.

It's kind of in the right direction, but will ultimately fail. "I've a solution further on."

Firstly, leave your `EF.Reverse.POCO.v3.ttinclude` file alone, and clone this GIT repository (the `EF.Reverse.POCO.v3.ttinclude` file is auto-generated by running `BuildTT` project).

This means you can code and test with a real C# project, and not the `EF.Reverse.POCO.v3.ttinclude`. The `generator` project is the code to play with.

Take a look at `Generator.LoadTables()` and change the following:
```c#
var rawTables      = DatabaseReader.ReadTables(includeSynonyms);
var rawIndexes     = DatabaseReader.ReadIndexes();
var rawForeignKeys = DatabaseReader.ReadForeignKeys(includeSynonyms);
```
to
```c#
var rawTables      = new List<RawTable>();
var rawIndexes     = new List<RawIndex>();
var rawForeignKeys = new List<RawForeignKey>();
// Todo - fill in rawTables from your CSV files here
```

You will need to write code to read your csv files and fill in in the rawTables before the call to `AddTablesToFilters(rawTables);`

Once you are happy with the code, run the BuildTT project it will generate the `EF.Reverse.POCO.v3.ttinclude` file to use in your project. You could name this `EF.Reverse.POCO.custom.ttinclude` and reference this specific file from a `customCSV.tt` file.

**Comment by acgentry** [comment]
Thank you for the detailed notes and how to jerry rig this. I created a quick and dirty T4 template that reads in the poco classes you generate and it got me 95% there.

Don't know if you would keep this open as an enhancement, but it would be a great feature to inject our own templates. In a previous life I used a similar product and that was a great benefit.

All the best, stay well!

ACG

**Comment by sjh37** [comment]
If I get more requests for this feature, I'll re-open and implement something :-)
