### ISSUE TITLE
Override Language Conversion

### ISSUE THREAD

**Issue by MarkLFT** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#594]
I can see the SQLServer to C# conversion class, but is it posisble to override this in the tt file?  What I am trying to do is map the sql server sql_variant to a .Net object.  By default it maps to a string.

We are working with a legacy database, so by choice we would not have used sql_variant, but it is used, and in a number of places thougout the database.

**Comment by sjh37** [comment]
Hi Mark,
You can either edit the SqlServerToCSharp class, or change it in your `.tt` file by modifying `Settings.UpdateColumn` and adding something like:

```c#
if (column.SqlPropertyType.ToLowerInvariant() == "sql_variant")
    column.PropertyType = "MyVariantType";
```

**Comment by MarkLFT** [comment]
I spent hours trying to work that out, now I feel very stupid.  Thanks for the help.
