### ISSUE TITLE
Is there way of implementing a new generic column in (all) the created classes ?

### ISSUE THREAD

**Issue by tss56** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#596]
Hi! I'm new here but I really need some help, sorry if I write weirdly, English ain't my native language.
I'm actually looking at the reverse POCO solution for a project that we want to change to EF soon, 
And so I had an interrogation, is there a way to automatically add in the generated Pocos a Date property? (it would be useful for tracking the data lifetime or such) 
I know I could do that in my db for each table but if I can use Reverse to auto implement this and then migrate my updated classes into my tables, that would be useful or so I think

**Comment by sjh37** [comment]
Hi. Yes you can :-)

In your <database>.tt file update the function `Settings.UpdateTable` to be:

```c#
Settings.UpdateTable = delegate(Table table)
{
    var date = new Column
    {
        // Database
        SqlPropertyType = "datetime",
        DbName          = "Date",
        IsNullable      = false

        // C#
        NameHumanCase   = "Date",
        PropertyType    = "DateTime",
        Default         = "DateTime.Now"
    };
    table.Columns.Add(date);
};
```

**Comment by tss56** [comment]
Thank you for your reply :-) But I have some troubles with the Configuration of my classes when I add this in my .tt file, it adds the Date property but with "IsUnicode(false)" at the end and thus my code doesn't compile (error CS1061)

**Comment by sjh37** [comment]
Hi. Also set the property `IsUnicode = true`

**Comment by tss56** [comment]
Ah, yes, maybe I should have tried that too, it works all right :) thank you a lot ^^'

**Comment by sjh37** [comment]
You're welcome
