### ISSUE TITLE
Configuration generator uses Settings.EntityClassModifiers

### ISSUE THREAD

**Issue by MarkLFT** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#598]
I tried to make my Configuration clasess partial, but simply changing Settings.ConfigurationClassesModifers to public partial does not work.  You have to set Settings.EntityClassesModifiers to public particial.

I believe this is caused by a type in the EF.Reverse.POCO.v3.ttinclude file.  On line 3240 Class Modifier is getting its value from EnityClassModifiers.

**Comment by sjh37** [comment]
Well spotted. Thanks.

**Comment by sjh37** [comment]
This will be in the next release.

**Comment by sjh37** [comment]
Now released as part of v3.2.0
