### ISSUE TITLE
Using statements

### ISSUE THREAD

**Issue by dyardyGIT** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#6]
Where in the tt files do the using statements get inserted? i.e. using System.Data.Entity or using System.Linq ?

thx

**Comment by sjh37** [comment]
If you need to specify your own usings, add them to the `AdditionalNamespaces`array in the <database>.tt settings file.

If you are just talking about `System.Linq` for instance, that is inserted by the file `EF.Reverse.POCO.ttinclude` near the top. See line 50 which does `usingsContext.Add("System.Linq");`

**Comment by sjh37** [comment]
Let me know if you need any further help / info.
