### ISSUE TITLE
How to automagically add [Required] annotation on non-nullable fields?

### ISSUE THREAD

**Issue by rosdi** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#60]
I am using the generated classes as the model for my forms...

How can I add the [Required] annotation automatically to all non-nullable fields? I guess I could mess up with the `.tt` files to have this functionality?

**Comment by sjh37** [comment]
``` c#

Func<Column, string> WritePocoColumn = c =>
{
    if (!c.IsNullable)
        return "[System.ComponentModel.DataAnnotations.Required] " + c.Entity;
    return c.Entity;
};
```

**Comment by rosdi** [comment]
Thanks... didn't know this exist since it is way down below... looks like it is far more extensible than I originally thought.

**Comment by cody1024d** [comment]
For some reason I'm not seeing this work for navigation properties.  Further, it seems to be duplicating the [Required] attribute for all non-Navigation Property fields.
