### ISSUE TITLE
Updating POCO does not include file in the project and it must be manually included.

### ISSUE THREAD

**Issue by statler** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#600]
I have my configuration set up and working - no problems there, every time I update after adding a new table, I have to manually add the class file to the project.

**Comment by sjh37** [comment]
## .NET Framework project
If your project is a .NET Framework, then in your `<database>.tt` file, set
```c#
Settings.FileManagerType = FileManagerType.VisualStudio;
```
This will automatically add new files to your project.

## .NET Core project
If you are using .Net Core, set
```c#
Settings.FileManagerType = FileManagerType.Custom;
```
Visual studio will detect the new files and automatically add them to the project.

**Comment by sjh37** [comment]
Hi @statler 
Did that solve your problem?

**Comment by statler** [comment]
Havent had to update my schema recently - but i expect that is it

**Comment by sjh37** [comment]
Thanks, will close for now.
