### ISSUE TITLE
table's float attribute updated as double in the poco 

### ISSUE THREAD

**Issue by tss56** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#601]
I wonder if it's supposed to be so, my float attributes aren't any more float when they're generated with the tt. generator

**Comment by sjh37** [comment]
Hi @tss56 

Yes, we usually map a SQL table float to a C# double.
Read about it here [stackoverflow](https://stackoverflow.com/a/122536/5884) and here [microsoftcrosoft](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqldbtype?redirectedfrom=MSDN&view=netframework-4.8#Mtps_DropDownFilterText)

If you want to change this to a float you can do that by modifying the class `SqlServerToCSharp` in `EF.Reverse.POCO.v3.ttinclude` However, I suggest you leave it alone as it is correct!
