### ISSUE TITLE
Table filtering

### ISSUE THREAD

**Issue by tss56** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#602]
Hi, I was wondering if there was a way to indicate in the .tt file the tables we want to keep, for example, 8 tables out of 26? (another way than RegexExclude), I tried RegexInclude but it does nothing actually  
Thanks

**Comment by tss56** [comment]
I found a way to include the table I want
to filter the table to include use RegexIncludeFilter("^tablename1$|^tablename2$")

**Comment by sjh37** [comment]
Yes exactly :-)
Use a single RegexIncludeFilter :-)
