### ISSUE TITLE
Generate configuration for hidden columns

### ISSUE THREAD

**Issue by statler** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#603]
Nearly every entity in my model inherits from an entity which contains my tracking columns - or others which control locking. To handle this I do the following;
```c#
Settings.UpdateTable = delegate(Table table)
{        
    if (table.Columns.Any(x=>x.NameHumanCase == "ModifiedBy"))
    {
        table.BaseClasses =" : TrackableEntity";
    }
    else if (table.Columns.Any(x=>x.NameHumanCase == "UniqueId"))
    {
        table.BaseClasses =" : ReplicableEntity";
    }
    else if (table.Columns.Any(x=>x.NameHumanCase == "OptimisticLockField"))
    {
        table.BaseClasses =" : LockableEntity";
    }
};    

Settings.UpdateColumn = delegate(Column column, Table table, List<EnumDefinition> enumDefinitions)
{
    List<string> lstTrackable  = new List<string>() { "createdby", "createdon", "modifiedby", "modifiedon" };
    List<string> lstReplicable = new List<string>() { "uniqueid", "hrid"};
    List<string> lstLockable   = new List<string>() { "optimisticlockfield" };
    // Remove column from poco class as it will be inherited from a base class
    if (lstTrackable .Contains(column.NameHumanCase.ToLower()) ||
        lstReplicable.Contains(column.NameHumanCase.ToLower()) ||
        lstLockable  .Contains(column.NameHumanCase.ToLower()))
    {
        column.Hidden = true;
    }
}
```
The problem is of course, that this prevents the columns being added to the configuration files. So, first question is - is this the best way to handle the inheritance situation I have. Secondly, how can I get the configuration for the hidden columns written for each table?

**Comment by sjh37** [comment]
Hi @statler 
Instead of setting `column.Hidden = true;` set `column.ExistsInBaseClass = true;`
This is a new feature that is not released yet, so you will have to grab the latest [EF.Reverse.POCO.v3.ttinclude](https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/blob/master/EntityFramework.Reverse.POCO.Generator/EF.Reverse.POCO.v3.ttinclude) from GitHub and overwrite your own `EF.Reverse.POCO.v3.ttinclude`  file

**Comment by statler** [comment]
Cool. Thanks for that.
