### ISSUE TITLE
Trouble with Sql Queries

### ISSUE THREAD

**Issue by tss56** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#606]
Hi,
I'm trying to use SQL queries in my project and I always get the same issue, that 
"A member of the type, 'columnName', does not have the corresponding column in the data reader with the same name."
The column is my PK
I did rename my columns with the help of the .tt file but is it that the mapping with my DB is not anymore working because of this?
example: var result = myContext.CRegisters.SqlQuery("select * from tbRegister where iIDName=1500");
(iIDName ain't the PK here)

**Comment by sjh37** [comment]
Hi @tss56 . 
For direct SQL, you need to match the names of the columns so they can be bound by EF.
```c#
var result = myContext.CRegisters.SqlQuery("select id as 'ID', some_thing as 'SomeThing' from tbRegister where iIDName=1500");
```

Instead of querying via sql, you should use `.Find` on entity framework. This finds entities via primary keys. If the record is already in memory, then EF doesn't even have to query the database.
```c#
myContext.CRegisters.Find(1500);
```

**Comment by sjh37** [comment]
Any problems, let me know and I can reopen if something is in error.

**Comment by tss56** [comment]
Ok thank you, I can't try it now but when I will, I will tell the outcome ;)
