### ISSUE TITLE
Use #Region

### ISSUE THREAD

**Issue by sjh37** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#61]
Would be nice to have all of the stored proc in one region, all of the POCOs in an other, etc.

**Comment by sjh37** [comment]
Done. This will be in the next release.

**Comment by ErikEJ** [comment]
Regions is an anti pattern

**Comment by mhwlng** [comment]
This v2.21.0 change adds  an #endregion to the .cs file without a corresponding #region :

![untitled](https://cloud.githubusercontent.com/assets/1388886/16371459/fe9768be-3c46-11e6-8391-9523fa39cd25.png)

**Comment by sjh37** [comment]
I will get this fixed.
For now, set `AddUnitTestingDbContext = true`

**Comment by sjh37** [comment]
Pull the latest code for the fix. I will make a bug-fix release in a couple of hours

**Comment by mhwlng** [comment]
ok, that got rid of the error, thanks...

**Comment by sjh37** [comment]
Released
