### ISSUE TITLE
Add setting to remove R# comments

### ISSUE THREAD

**Issue by sjh37** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#615]
Some people don't use Resharper.
Add a boolean setting that can be set to in the .tt file so we don't have all that noise for Resharper at the top of each file generated.

**Comment by nealculiner** [comment]
@sjh37 I also suggest having a setting to not write the registered license info at the top of each file. I really don't need that noise in every generated file either.

**Comment by sjh37** [comment]
@nealculiner I'll add an option for that too :-)

**Comment by sjh37** [comment]
That has been done, and will be in the next release.

**Comment by sjh37** [comment]
Now released as part of v3.2.0
