### ISSUE TITLE
Leave no trace of connection strings in generated files

### ISSUE THREAD

**Issue by nealculiner** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#616]
Having the connectionstring in every generated poco in the OnConfiguring is a red flag to me. While many do use obfuscators there is too much risk in sensitive data being leaked in class libraries in shipped applications. Remember all uses cases, not all apps are server based, it could be client desktop apps, mobile apps, etc. I personally don't obfuscate (yet) my mobile apps. Regardless, I'm very uncomfortable with the v3 way of using the full connectionString and including it in so many files including the top of each file in comments which can be turned off as thankfully there is a setting and I suggest this be false by default which has already been changed.

I reviewed https://docs.microsoft.com/en-us/ef/core/miscellaneous/configuring-dbcontext#using-dbcontext-with-dependency-injection and am learning .NET Core / EF Core as I'm migrating some API's to asp.net core now. I'm trying to determine how this can be handled properly without spreading sensitive data even if it's developer machine credentials vs. production which is still wrong in my opinion. If in fact the OnConfiguring does not need a connectionstring as the context can carry it then why include it? Again, I'm not sure on the architecture and requirements but this needs careful review for security and keeping sensitive data out of any generated file to the max extent possible.

**Comment by nealculiner** [comment]
I write this only because I'm learning this, I'm no expert on EF/.NET Core. I read this article https://www.learnentityframeworkcore.com/connection-strings and it raises a concern:

> If you choose to set the connection string in the OnConfiguring method, this will override any other configuration.

If this is true then setting a connectionstring in the startup is not going to override this? Then in the scenario you mentioned @sjh37 of using a dev machine then changing to production in the startup wouldn't work? Something is just very concerning to me with connectionstrings as of 3.1.3, again remember my ignorance!!!

**Comment by sjh37** [comment]
Hi Neal,
If a local connection string is specified in the DbContext, for instance:

```c#
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
{
    if (!optionsBuilder.IsConfigured)
    {
        optionsBuilder.UseSqlServer(@"Data Source=(local);Initial Catalog=Northwind;Integrated Security=True;MultipleActiveResultSets=True");
    }

```

Notice `if (!optionsBuilder.IsConfigured)` protects against always using your local connection string.

There are two constructors
```c#
public MyDbContext()
{
}

public MyDbContext(DbContextOptions<MyDbContext> options)
    : base(options)
{
}
```

One that takes nothing, and one that takes options.
If you are using a website, you would have code that looks like in this in your `Startup.cs` `ConfigureServices` function:
```c#
services.AddDbContext<MyDbContext>(options =>
    options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
```

So whenever you have a something that requires the database, such as a controller, or a service:
```c#
public class CartService : ICartService
{
    private readonly IApplicationDbContext _db;

    public CartService(IApplicationDbContext db)
    {
        _db = db;
    }
```

The database is passed in, using the dependency injection setup previously in `Startup.cs`.
```c#
services.AddDbContext<MyDbContext>(options =>
    options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
```
The database context constructor that is used is the one with options `MyDbContext(DbContextOptions<MyDbContext> options)`, and therefore will use the connection string from `Configuration.GetConnectionString("DefaultConnection")`

You can of course change how the the connection string is written out by specifying one of:
```c#
Settings.OnConfiguration = OnConfiguration.Configuration;
Settings.OnConfiguration = OnConfiguration.ConnectionString;
Settings.OnConfiguration = OnConfiguration.Omit;
```

Please read [Settings.OnConfiguration](https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/wiki/Settings.OnConfiguration) documentation.

**Comment by nealculiner** [comment]
Thanks @sjh37 - my other question was whether I was to pass in the IDbContext to the constructor or the DbContext as a sample I'm referencing does not use an Interface but instead the DbContext. Learning....thanks.

**Comment by sjh37** [comment]
Always pass interfaces. This allows you to pass in a FakeDbContext to test your code.

**Comment by sjh37** [comment]
In fact, all your code should use interfaces, it's part of SOLID. Again, handy for unit testing and passing in test services to simulate whatever the real thing does.
Take a look at the [strategy pattern](https://en.wikipedia.org/wiki/Strategy_pattern)

**Comment by nealculiner** [comment]
Will do, enjoying some nice coding patterns I'm learning in this process of moving to .NET Core. It seems to really be better with learning/enforcing better patterns. First experience with DI, etc.

**Comment by nealculiner** [comment]
@sjh37 it appears if I'm going to pass the Interface as the constructor I have to use the AddScoped per below. I'm new to this, does this sound right? If I don't then I'm getting an error in my postman unit tests failing to resolve the DI:

```
services.AddScoped<IMyDbContext, MyDbContext>();

            services.AddDbContext<MyDbContext>(opt =>
               opt.UseSqlServer(Configuration.GetConnectionString("MyConnString"), opt => opt.UseNetTopologySuite())
                  .EnableSensitiveDataLogging()
               );
```

**Comment by sjh37** [comment]
**Scoped** is exactly what you need for a database context. You get back the same database object within a request.

 - **Transient** objects are always different; a new instance is provided to every controller and every service.
 - **Scoped** objects are the same within a request, but different across different requests.
 - **Singleton** objects are the same for every object and every request.

**Comment by nealculiner** [comment]
Realize there are EF Core newbies like me, consider your samples to include these code requirements and it may save others grief. Very steep learning curve for me the past few weeks but loving it! Just about done with my conversions to .NET Core, ASP.NET Core, EF Core
