### ISSUE TITLE
New column Default string value

### ISSUE THREAD

**Issue by tss56** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#618]
Hi, while trying to add a new property through the Settings.UpdateTable, I have trouble setting the default value of a string property, I did this in my tt file:
```c#
var tableNotification = new Column
{
	// Database
	SqlPropertyType = "char",
	DbName          = "sTableName",
	IsNullable      = false,
	IsUnicode = true,


	// C#
	NameHumanCase   = "sTableName",
	PropertyType    = "string",
	Default         = "tb" + table.NameHumanCase.Remove(0,1)
};
```
but I don't get a string, it's the name but there are no quotation marks, what did I do wrong? 
What I'm doing here is just adding a property with the name of the table in it, because I need it to add the use of SQLDependency later

**Comment by sjh37** [comment]
The `Default` can be used for integers too, so
```c#
Default = "123"
```
Would result in
colname = 123;

You have to include quotes for strings in your defaults:

```c#
Default = "\"tb" + table.NameHumanCase.Remove(0,1) + "\""
```
