### ISSUE TITLE
Generator thinks stored procedure is using multiple results sets

### ISSUE THREAD

**Issue by nealculiner** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#620]
Using version 3.1.3 in EF Core and it's not creating stored procedures for this as it thinks this procedure code returns multiple result sets when in fact it's returning a scalar value, a datetime. The code is generated in the Fake DbContext but not the production side.

```
CREATEPROCEDURE [dbo].[Subscriptions_GetExpiresUtc]
    @AccountID INT ,
    @PlanType INT ,
    @IncludeFreeTrial BIT = 1
AS
    BEGIN
        SET NOCOUNT ON;
        IF @IncludeFreeTrial = 0
            BEGIN
                SELECT TOP 1
                        ExpiresUtc
                FROM    dbo.Subscriptions
                WHERE   AccountID = @AccountID
                        AND PlanType = @PlanType
                        AND IsActive = 1
                        AND IsVerified = 1
						AND IsFreeTrial = 0
						AND IsCanceled = 0
                ORDER BY ExpiresUtc DESC;
            END;
        ELSE
            BEGIN	
                SELECT TOP 1
                        ExpiresUtc
                FROM    dbo.Subscriptions
                WHERE   AccountID = @AccountID
                        AND PlanType = @PlanType
                        AND IsActive = 1
                        AND IsVerified = 1
						AND IsCanceled = 0
                ORDER BY ExpiresUtc DESC;
            END;	
    END;
```

**Comment by sjh37** [comment]
Hi. It's the IF statement that makes it look like two result sets. Even if they are the same. I've another case to check for identical result sets and merge them if specified in settings

**Comment by nealculiner** [comment]
@sjh37 some ideas:

If it's too hard or risky to parse sprocs for this, don't block it but generate the code for it and let the developer figure it out. Maybe just put a pragma warning on it if you think it needs developer attention. The other thing is tomorrow some update could come out with EF that allows MARS. I wasn't aware it didn't support it so that's good but I'm not sure I'm even using it even though my connectionstring allows it which I have since removed. If the connectionstring would require the MARS element then maybe flag that to the developer as unsupported instead? Just a few ideas but I'd rather have the code stubbed out instead of my current situation of rewriting my sprocs in LINQ.

**Comment by sjh37** [comment]
Select the data into a variable within each select statement.
```sql
AS
BEGIN
	SET NOCOUNT ON;
	SET XACT_ABORT ON;

	DECLARE @ExpiresUtc DATETIME 

	IF @IncludeFreeTrial = 0
	BEGIN
		SELECT @ExpiresUtc = GETDATE(); -- Use your SQL
	END
	ELSE
	BEGIN
		SELECT @ExpiresUtc = GETDATE() + 100;  -- Use your SQL
	END
	SELECT @ExpiresUtc AS ExpiresUtc; -- Return a single result set
END
```

That will return a single result set back.

**Comment by nealculiner** [comment]
Thank you. Certainly various ways to code sprocs. My sprocs with output variables are also not plumbed, as you know. Oh well, will make do with what I have and consider refactoring some of the sprocs as needed per your suggestion.
