### ISSUE TITLE
Stored procedures not getting Async methods generated that should

### ISSUE THREAD

**Issue by nealculiner** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#621]
From the Q&A area...but I'm getting a lot of stored procedures whether like the one below that is a fire and forget or ones that return single values (scalars) that the generator is commenting out as it thinks it has output params, multiple result sets, etc. Consider pragma warnings if it's a feature EF core doesn't support at the time the generator code was written, etc. Leave it to the developer to test and decide? It just seems like the generator is not able to properly evaluate the sprocs as to whether EF Core can handle this async or not.

Another sproc I can't get an async method for:

```sql
ALTER PROCEDURE [dbo].[DeleteOldestBinary]
    @UserId INT, @ItemType INT
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @OldestBinaryId INT;

    SELECT @OldestBinaryId =
    (
        SELECT TOP (1) BinaryId
        FROM dbo.Binaries
        WHERE UserId = @UserId AND ItemType = @ItemType
        ORDER BY CreatedUtc
    );

    EXEC dbo.DeleteItemById @BinaryId = @OldestBinaryId; -- int
END;
```

// DeleteOldestBinaryAsync() cannot be created due to having out parameters, or is relying on the procedure result (int)

Not sure why this can't be executed async as it's essentially a fire and forget sproc

**Comment by sjh37** [comment]
As an experiment, in `EF.Reverse.POCO.v3.ttinclude` search for

```c#
DatabaseReader.ReadStoredProcReturnObjects(storedProcs);
```

Underneath that line add:

```c#
// Force generation of Async stored procs
foreach (var sp in storedProcs.Where(x => !x.IsTableValuedFunction && !x.ReturnModels.Any()))
{
    sp.ReturnModels.Add(new List<DataColumn>{new DataColumn("result", typeof(int))});
}
```

It might work, it might not, as I've not tested it. Please let me know how you get on.

**Comment by sjh37** [comment]
This will be in the next release
