### ISSUE TITLE
Support for .NET Core with EF6 and Reverse POCO Generator 2.37.4?

### ISSUE THREAD

**Issue by udlose** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#622]
I am rewriting an app from .NET Framework 4.5 to .NET Core 3.1 that will be using EntityFramework 6 (EF Core is not an option).  I have an older version of the POCO Generator (v2.37.4).  

I am using the existing .tt file from the 4.5 version of my application to generate the POCOs and StoredProcs.  However, I am not seeing any `async` methods generated.  All other POCOs and synchronous StoredProcs are generated fine.

1. are there settings I'm missing that need to change from .NET Framework to .NET Core 3.1
OR
2. Does the v2 POCO Generator not support generating the `async` methods with .NET Core and EF6?

Note that I **do not** have any of these messages so the async methods should be there:
_Async cannot be created due to having out parameters, or is relying on the procedure result_

Do I need to set the `SupportedFrameworkVersion` somewhere?
TIA

**Comment by sjh37** [comment]
Search for
```c#
if (Settings.TargetFrameworkVersion < 1.0f)
{
    var project = GetCurrentProject();
    var targetFrameworkMoniker = project.Properties.Item("TargetFrameworkMoniker").Value.ToString();
    var targetFramework = new System.Runtime.Versioning.FrameworkName(targetFrameworkMoniker).Version;
    Settings.TargetFrameworkVersion = targetFramework.Major + (targetFramework.Minor * 0.1f);
}
```

and replace it with
```c#
Settings.TargetFrameworkVersion = 4.5f;
```

That should give you back your Async functions

**Comment by udlose** [comment]
I ended up upgrading to Reverse POCO Generator v3 and everything is now correctly generated.  Thank you for your prompt response :)
