### ISSUE TITLE
Add FluentMigration PocoConfiguration for Unique Indexes

### ISSUE THREAD

**Issue by kcadduk** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#628]
v3.1.3 - EF Core 3.1 - MSSQL 2017

Create a Table in SQL as per below 
```sql
CREATE TABLE [dbo].[RoleTypes](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CreatedDate] [datetime2](7) NOT NULL,
	[UpdatedDate] [datetime2](7) NOT NULL,
	[UUID] [varbinary](16) NOT NULL,
	[RoleName] [varchar](20) NOT NULL,
	[RoleEnumID] [int] NOT NULL,
 CONSTRAINT [PK_RoleTypes] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX [NonClusteredIndex-20200703-134635] ON [dbo].[RoleTypes]
(
	[RoleEnumID] ASC
)
```

Reverse engineer PocoConfiguration, find that the FluentMigration does not specify IsUnique

```c#
builder.HasIndex(x => x.RoleEnumID).HasName("NonClusteredIndex-20200703-134635");
```

Should be 

```c#
builder.HasIndex(x => x.RoleEnumID).HasName("NonClusteredIndex-20200703-134635").IsUnique();
```

**Comment by ghost** [comment]
Yepp, same here. Would be nice if that could be fixed.

**Comment by sjh37** [comment]
Already fixed and will be in the next release:

```c#
// RoleTypes
public class RoleType
{
    public int Id { get; set; } // ID (Primary key)
    public DateTime CreatedDate { get; set; } // CreatedDate
    public DateTime UpdatedDate { get; set; } // UpdatedDate
    public byte[] Uuid { get; set; } // UUID (length: 16)
    public string RoleName { get; set; } // RoleName (length: 20)
    public int RoleEnumId { get; set; } // RoleEnumID
}

// RoleTypes
public class RoleTypeConfiguration : IEntityTypeConfiguration<RoleType>
{
    public void Configure(EntityTypeBuilder<RoleType> builder)
    {
        builder.ToTable("RoleTypes", "dbo");
        builder.HasKey(x => x.Id).HasName("PK_RoleTypes").IsClustered();

        builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
        builder.Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime2").IsRequired();
        builder.Property(x => x.UpdatedDate).HasColumnName(@"UpdatedDate").HasColumnType("datetime2").IsRequired();
        builder.Property(x => x.Uuid).HasColumnName(@"UUID").HasColumnType("varbinary(16)").IsRequired().HasMaxLength(16);
        builder.Property(x => x.RoleName).HasColumnName(@"RoleName").HasColumnType("varchar(20)").IsRequired().IsUnicode(false).HasMaxLength(20);
        builder.Property(x => x.RoleEnumId).HasColumnName(@"RoleEnumID").HasColumnType("int").IsRequired();

        builder.HasIndex(x => x.RoleEnumId).HasName("NonClusteredIndex-20200703-134635").IsUnique();
    }
}
```

**Comment by sjh37** [comment]
If you want, you can grab the latest code now, directly from this repo and copy the latest .ttinclude file into your project.

**Comment by ZigabooGroove** [comment]
Thanks Simon

Kind regards
Viele Grüße aus Wesel
Frank Seidel
System development
KOMDAT® Gesellschaft für externes
Vertriebsmanagement mbH
Fair Management Services
Südring 5
D-46483 Wesel
Phone: +49 (0)281/33930-17
Fax: +49 (0)281/33930-99
Mobile +49 (0)170/7362319
e-mail: fs@komdatgroup.com<mailto:fs@komdatgroup.com>
Internet: http://www.komdatgroup.com
<http://www.komdatgroup.com/>______________________________________________________________________________________
Vertriebsbüro Berlin, Kreuzbergstrasse 25, D-10965 Berlin, Tel. +49 (0) 30-788966-50, Fax +49 (0) 30-788966-52
UstID: DE121007986, Handelsregister-Nr.: HRB 10871, Amtsgericht Duisburg, Geschäftsführer: Matthias Hillenbach

Von: Simon Hughes [mailto:notifications@github.com]
Gesendet: Samstag, 1. August 2020 18:55
An: sjh37/EntityFramework-Reverse-POCO-Code-First-Generator
Cc: Frank Seidel; Comment
Betreff: Re: [sjh37/EntityFramework-Reverse-POCO-Code-First-Generator] Add FluentMigration PocoConfiguration for Unique Indexes (#628)


If you want, you can grab the latest code now, directly from this repo and copy the latest .ttinclude file into your project.

**Comment by ghost** [comment]
Thanks Simon
