### ISSUE TITLE
version 3 

### ISSUE THREAD

**Issue by smarteez17** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#629]
Hi 
would like to say thank you for version 2 it help me alot. We version 3 being paid version I need to demo it to my company and how the options work. they have request the demo to show 2 or more tables and views and 1 or stored proc and 1 of each function ( table and scalar ) . I can see the trial version only allows 1 Stored proc or function can that be change allow more please 
and with pricing I have a team of 4 to 5 people do we need a licence for each person ?

**Comment by sjh37** [comment]
Order a trial version, let me know the order number, and i will change it to an academic version for you so you can re-download the new license from your order page.
Academic version will give you 16 tables and 4 stored procedures.

**Comment by smarteez17** [comment]
thank you my order number is 716

**Comment by sjh37** [comment]
@smarteez17 done. View [your order]( https://www.reversepoco.co.uk/Orders/Details/716) and re-download your license by clicking on the blue download icon.

**Comment by sjh37** [comment]
You need a license for each developer who will save the `<database>.tt` file to run the generator.
Any other developer can freely use the generated code in the project.
