### ISSUE TITLE
Callback function to determine whether to include object

### ISSUE THREAD

**Issue by TimSirmovics** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#63]
It would be useful to have a callback function that accepts the Schema Name and Table Name for tables / views, and returns a bool indicating whether the object is to be included. This would be an alternative to the Regex exclusions/inclusions.

I have situations with Legacy databases where for example:
Schema One has 15 objects, we want to include them all.
Schema Two has 400 objects, we only want 1.

In this case I can't filter by Schema, so I need to add in all 16 objects to the inclusion filters.

We could use 2 seperate contexts, however this duplicates the number of contexts and we can't perform queries including both contexts.

If this was to be implemented it would be good to have the same functionality for Tables, Views and Stored Procedures / TVF's, either the same callback with an object type parameter, or seperate callbacks.

**Comment by sjh37** [comment]
Nice idea, this function can be used with or without the regex filters.

There is also a simple UI for the generator is available at [https://efreversepocoui.codeplex.com/](efreversepocoui.codeplex.com/) which helps you to create a regex to filter your tables.

**Comment by ErikEJ** [comment]
+1 for this, I also had a complex selection of Schemas/Tables, where this would be very useful, and easier on the eye!

**Comment by sjh37** [comment]
Added. This will be in the next version.
See the new callback function `TableFilter`
