### ISSUE TITLE
Changing setting after files have been created  bug 

### ISSUE THREAD

**Issue by smarteez17** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#631]
Hi there 
I not sure if this is a bug or not I first set this to true and also had this setting on as well 

  FilterSettings.IncludeViews                 = true;
    FilterSettings.IncludeSynonyms              = false;
    FilterSettings.IncludeStoredProcedures      = true;
    FilterSettings.IncludeTableValuedFunctions  = true; // If true, for EF6 install the "EntityFramework.CodeFirstStoreFunctions" NuGet Package.
    FilterSettings.IncludeScalarValuedFunctions = true;

then I wanted Settings.GenerateSeparateFiles  set it to false and nothing happen ( the reason I did this is to move the items into folder example all the entries in one folder )

**Comment by smarteez17** [comment]
I just tested also section and found the same problem Settings.AddUnitTestingDbContext = true; I now change to false . I version 2 anytime some setting was change all the current file would be deleted and remove and readd again this is not happening in version 3

**Comment by sjh37** [comment]
@smarteez17 If you are using EF6 please use `Settings.FileManagerType = FileManagerType.VisualStudio`
If you are using EF.Core, then use `Settings.FileManagerType = FileManagerType.Custom`

More information [here](https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/wiki/Common-Settings.*Types-explained#settingsfilemanagertype).

**Comment by TimSirmovics** [comment]
@sjh37 just for clarity, the comment for `Settings.FileManagerType` says: `.NET project = VisualStudio; .NET Core project = Custom; No output (testing only) = Null`.

We have projects which are .NET Framework, using EF.Core.
What value should we use in this case?

**Comment by smarteez17** [comment]
I am using .net core and  here all my setting 

```c#
Settings.DatabaseType            = DatabaseType.SqlServer; // SqlServer, SqlCe. Coming next: PostgreSQL, MySql, Oracle
    Settings.TemplateType            = TemplateType.EfCore3; // Ef6, EfCore2, EfCore3, FileBasedCore2, FileBasedCore3. FileBased specify folder using Settings.TemplateFolder
    Settings.GeneratorType           = GeneratorType.EfCore; // Ef6, EfCore, Custom. Custom edit GeneratorCustom class to provide your own implementation
    Settings.UseMappingTables        = false; // Set to false for EfCore. EFCore will add support for this in v3 at some point, so please set this to false. If true, mapping will be used and no mapping tables will be generated. If false, all tables will be generated.
    Settings.FileManagerType         = FileManagerType.Custom; // .NET project = VisualStudio; .NET Core project = Custom; No output (testing only) = Null
    Settings.ConnectionString        = "Data Source=COL2875\\SQLEXPRESS;Database=HRM;Trusted_Connection=True;MultipleActiveResultSets=true"; // This is used by the generator to reverse engineer your database
    Settings.ConnectionStringName    = "MyDbContext"; // ConnectionString key as specified in your app.config/web.config/appsettings.json. Not used by the generator, but is placed into the generated DbContext constructor.
    Settings.DbContextName           = "MyDbContext"; // Class name for the DbContext to be generated. Note: If generating separate files, please give the db context a different name from this tt filename.
    //Settings.DbContextInterfaceName= "IMyDbContext"; // Defaults to "I" + DbContextName or set string empty to not implement any interface.
    Settings.GenerateSeparateFiles   = true;
    Settings.Namespace               = DefaultNamespace; // Override the default namespace here. Please use double quotes, example: "Accounts.Billing"
    Settings.TemplateFolder          = Path.Combine(Settings.Root, "Templates"); // Only used if Settings.TemplateType = TemplateType.FileBased. Specify folder name where the mustache folders can be found. Please read https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/wiki/Custom-file-based-templates
    Settings.AddUnitTestingDbContext = true;

```
as you can see  Settings.FileManagerType         = FileManagerType.Custom;  

I try it again the old files are not getting remove and replace with updates ones see images 

![image](https://user-images.githubusercontent.com/35128168/89156072-58208f80-d56a-11ea-8736-adb752b2798b.png)

when I set it to false and save nothing happens 

![image](https://user-images.githubusercontent.com/35128168/89156155-7f775c80-d56a-11ea-9fbe-660f7bcfc19e.png)

**Comment by sjh37** [comment]
@TimSirmovics It all boils down to how you want the generator to interact with Visual Studio.

### Settings.FileManagerType = FileManagerType.VisualStudio
It will make use of the `EF6.Utility.CS.ttinclude` to add/remove files from the Visual Studio project. This is how version 2 of the generator worked. It instructs Visual Studio which files to add/remove from the project. _Visual Studio does not like this if you are using a .NET Core project as the files are not listed in the `.csproj` file._
For example, the .csproj file could contain:
```xml
<ItemGroup>
  <Compile Include="AssemblyHelper.cs" />
  <Compile Include="EfrpgVersion.cs" />
  <Compile Include="FileManagement\VisualStudioFileManager.cs" />
  ...
```

### Settings.FileManagerType = FileManagerType.Custom
Use this for .NET Core projects. It will write the files directly to the file system, and not control Visual Studio at all. `EF6.Utility.CS.ttinclude` is not used either. Visual Studio will automatically detect new files being present in the folder and include them in the project. The projects `.csproj` does not include the files in the project. Visual Studio is basically working on a folder with a collection of files and sub-folders in it.
For example, the .csproj file would not list all the files in your project. It may list a few sub-folders, but not list any of the files in those either.

### Which to use...
Use notepad and take a look at the `.csproj` file. If it **does not** list all the files in your project, then use `FileManagerType.Custom`, if it **does** then use `FileManagerType.VisualStudio`.

Using `FileManagerType.VisualStudio` on a project in Visual Studio where the project type does not list any files (.NET Core projects) confuses Visual Studio. The generator is telling Visual Studio to add/remove files from its project file, and no files are listed in the project file in the first place. In early versions of Visual Studio 2017/2019 this used to be a problem, however this is no longer the case and now works ok.

**Comment by sjh37** [comment]
@smarteez17 Ahh, toggling the `Settings.GenerateSeparateFiles` from `true` to `false` will not delete your files. You have to manually delete them.

**Comment by sjh37** [comment]
I will close this issue, as moving from `Settings.GenerateSeparateFiles` from `true` to `false` will not delete your files. I don't want the generator to delete files either if `Settings.GenerateSeparateFiles = false` because there could be scenarios where the user has file names that match the names of classes within the generated `<database>.cs` file, and I don't want to accidentally delete those.
