### ISSUE TITLE
Support to generate OrmLite POCO classes

### ISSUE THREAD

**Issue by adrianwright109** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#634]
Has anyone tried to customise the templates so that it generates OrmLite specific code rather than EFCore?

I see that ServiceStack OrmLite have T4 templates in their source code:
[https://github.com/ServiceStack/ServiceStack.OrmLite/tree/master/src/ServiceStack.OrmLite.T4](https://github.com/ServiceStack/ServiceStack.OrmLite/tree/master/src/ServiceStack.OrmLite.T4)

Has anyone tried to integrate these ServiceStack OrmLite templates into the Reverse POCO generator?

**Comment by sjh37** [comment]
Not that I know of.
Given the data is separated from the template, it could conceivably generate anything given the right template.

**Comment by sjh37** [comment]
I'll close this issue as the name of the product is specific to entity framework. I have thought about generating none EF code, but I would have to place it into a separate product.
