### ISSUE TITLE
EnumDefinitions for mapping tables

### ISSUE THREAD

**Issue by mtanneryd** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#636]
Hi!

Assume that we have the following tables and an enum.
```c#
enum DealCategories
{
 Category1 = 1,
 Category2 = 2,
 Category3 = 3
}
```
Deal
-----
Id
Name,
Date,
Buyer,
Seller,
Price,
Volume

DealCategory (This should be mapped to the DealCategories enum)
---------------
Id
Name

DealCategoryMap
--------------------
DealId
DealCategoryId

I would like for the Deal class to get a collection of the enum DealCategories.

**Comment by sjh37** [comment]
I have a wiki article explaining how to do it at https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/wiki/Enum-generation-from-table-data

Let me know how you get on and if you need more help.
