### ISSUE TITLE
views and the expection of id's being present

### ISSUE THREAD

**Issue by dyardyGIT** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#64]
The {view}Respository.cs file that is generated for a view is assuming that we have a id field.

What is the best way to tell t4 that we are working with a view without a primary id field (or that the view does not participate in add/modify operations?)

i.e.this code does not apply with a view

```
    public void InsertOrUpdate(VwPayItemsBase obj)
    {
        if (obj.VwPayItemsBaseId == default(int))
        {
            this.UnitOfWork.Context.Set<VwPayItemsBase>().Add(obj);
        }
        else
        {
            this.UnitOfWork.Context.Entry(obj).State = System.Data.Entity.EntityState.Modified;
        }
    }
```

thx

**Comment by sjh37** [comment]
Hi,
I know that views cannot participate in add/modify operations. They are basically a select statement.
I don't believe my generator created that code above.
