### ISSUE TITLE
Premium option: settings for DTO's Controllers and Views

### ISSUE THREAD

**Issue by papyr** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#642]
Hello, we find this is to be a lot more productive _over_ the flaky and buggy _RAD tools or ASP Net Zer0 over priced $2000USD_

This could be very beneficial both ways to the developers and @sjh37 , if we could build on this tool and allow users to generate the Basic` CRUD Controllers `and `Views` in Razor - Many of the templates are here on Github, it would be a matter of invoking them in the tool chain.

Next allow developers to contribute` plug-ins to your tool`, essentially building off your base and community. For example my boss has no issues reallocating a portion of the RAD tool into your tool if it can give us features, its longer path surely, but you can start and get there. I am sure there will be nay-sayers, but once the usage shows up... it would on board many developers. Please consider it.

thanks and great work Simon!

**Comment by clooge** [comment]
Do you know how much would it be? 
The other scaffolds could be included as partial classes, how about 100$ for this option?

**Comment by sjh37** [comment]
Like the idea of plug-ins and user contributions. This would only really work for .NET Core projects as I have control over which sub-folder the files get generated in.

**Comment by papyr** [comment]
So let me explain: the current scaffolding tool is not a POCO first model, so the tool chain doesn't really work easily POCO. 

While, your tool works off the POCO objects directly, which is really what many of the developers want. This was something we discussed at developers at a couple event extensively. 

For a start, you can leverage/hook your POCO's into [this](https://github.com/dotnet/Scaffolding/tree/master/src/VS.Web.CG.Templating).  Since, its got the base class which can be extended, so you don't have to work on the generation of the controllers or views. The advantage is that you already iterate over the models to create the POCO's and if we had an simple start partial class or option to add the CRUD controllers/Views

In our case here our value is to re/run your tool to gen the upper layers as we make changes to the POCO's, based off our settings.

This can be moved to a plug-in component.

I also wanted to add Datatables and Daniels Worfklow as a Plugin

**Comment by papyr** [comment]
Hey you should checkout the ASP core generator and just tie into that!
