### ISSUE TITLE
.NET 5 / EFCore 5 issues

### ISSUE THREAD

**Issue by nealculiner** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#646]
Hi Simon, after updating to .NET 5 / EF Core 5 a few issues you're probably aware of.

1. I had to add a new using: using Microsoft.EntityFrameworkCore.Query;
2. warning CS0618: 'RelationalIndexBuilderExtensions.HasName<TEntity>(IndexBuilder<TEntity>, string)' is obsolete: 'Use HasDatabaseName() instead.'

**Comment by omeszar** [comment]
I had already added "Microsoft.AspNetCore.Identity.EntityFrameworkCore" to the active project I'm working on so I was good with that.

However, if I add the Unit Testing Db Context (setting the flag to true) then I get the message below. We don't use the Fake DB b/c of the bug I reported back on June 12th but I wanted to try it out.

CS0246	The type or namespace name 'IAsyncQueryProvider' could not be found (are you missing a using directive or an assembly reference?)

In addition, of course, it will be nice to get the tool updated to EF Core 5 and be able to generate the many-to-many relationships that was finally added to EF Core. You can always add the relationships yourself after you run the tool. I tried that in a test DB and it works fine. But that defeats the purpose of the tool somewhat if you happen to have as many many-to-many as one of our DB has.

**Comment by sjh37** [comment]
Note to self.
Use `[Keyless]` attribute on stored procedure return models. Keyless entities have most of the mapping capabilities as normal entities, but they are not tracked for changes in the DbContext. It also means that we won’t be able to perform insert, update, or delete on such entity.
More info: https://www.michalbialecki.com/2020/09/03/select-data-with-a-stored-procedure-with-entity-framework-core-5/

**Comment by sjh37** [comment]
Released in v3.3.0
