### ISSUE TITLE
How to share settings between multiple generators

### ISSUE THREAD

**Issue by ClassyCircuit** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#647]
I have copied the same generator in 3 different places, so I can generate entities, interfaces, dbcontext in separate projects.
The downside to this - I have to keep all 3 generator files up to date, if I change a small thing in entities generator, I also have to change it in interfaces and dbcontext generator. 
How do I manage this duplicated configuration code?

**Comment by sjh37** [comment]
Other uses pull out all the common settings into a `common.tt` file, just leaving the elements to generate in the `database.tt`.
Each of the `database.tt` files include the `common.tt` file.

**Comment by sjh37** [comment]
Similar to #389 and #104

**Comment by sjh37** [comment]
I'll close this as you've managed to solve this as part of #597 which is a great solution
