### ISSUE TITLE
[NET 5] Problem with understanding Settings.OnConfiguration

### ISSUE THREAD

**Issue by nielshenriksen** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#648]
I am working on a project for a customer where I have a problem with understanding the generator:

When I am using Settings.OnConfiguration                        = OnConfiguration.Omit; I want to add my own connectionstring in appsettings. 

In my ConfigureServices in Startup.cs I have
services.AddDbContext<MyDbContext>(options => options.UseSqlServer(Configuration.GetConnectionString("connectionstring")));

But when I run it I get this error
System.InvalidOperationException: No database provider has been configured for this DbContext. A provider can be configured by overriding the 'DbContext.OnConfiguring' method or by using 'AddDbContext' on the application service provider. If 'AddDbContext' is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.

I dont know what I am doing wrong - and I dont want to recompile every time i need to change database.

**Comment by sjh37** [comment]
I've a wiki page on this at [Settings.OnConfiguration](https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/wiki/Settings.OnConfiguration)

Have a read and see if it helps you. The important bit is at the bottom, which I've included here:

### Settings.OnConfiguration = OnConfiguration.Omit
This completely removes the `OnConfiguring` function altogether. This assumes IMyDbContext is dependency injected into your controllers / services / classes, and that you have setup your connection using:
```c#
services.AddDbContext<MyDbContext>(options =>
    options.UseSqlServer(Configuration.GetConnectionString("MyDbContext")));

...

// Scoped is usually what you need for a database context.
// You get back the same database object within a request.
services.AddScoped<IMyDbContext, MyDbContext>();
```

**Comment by sjh37** [comment]
Let me know if this is still an issue and I can re-open.
