### ISSUE TITLE
How to use Identity 3

### ISSUE THREAD

**Issue by javadinasab** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#649]
I want to use this tool in Identity, please  help me

**Comment by sjh37** [comment]
It is best to exclude the ASP.Net identity tables as they are already built into the ASP.Net framework you will use. Therefore, no need for the generator to duplicate them as you shouldn't be reading those tables directly. For ASP.NET Identity you should go through the provided functions instead. This keeps your identity code database agnostic.

The default installation of `database.tt` file at line 58 already excludes the ASP.NET identity tables as follows:
```c#
FilterSettings.TableFilters.Add(new RegexExcludeFilter("AspNet.*")); // This excludes all tables starting with 'AspNet'
FilterSettings.TableFilters.Add(new RegexExcludeFilter("__EFMigrationsHistory")); // This excludes a table called '__EFMigrationsHistory'
```

**Comment by javadinasab** [comment]
thank you very much
