### ISSUE TITLE
Rename properties in sproc return models?

### ISSUE THREAD

**Issue by jsmarsch** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#650]
I've had great success with the 'generator for years!

Today, I'm working with a legacy-ish database, that still has a large number of sprocs.  I would like to be able to rename the properties in the sproc return models -- is there a hook for that?  can you point me to where I might look?  

I used to have a fair amount of familiarity with the v2 generator.  This is my first time working with v3.

**Comment by sjh37** [comment]
Hi @jsmarsch 

Glad to hear you've enjoyed the generator for a few years :-)

You can't rename the properties in the sproc return models. Unfortunately stored procedure return models must match exactly the return column names returned, and therefore cannot be renamed. If they were renamed, Entity Framework would not map the column data back.

A workaround for this is to wrap this stored procedure by another stored procedure which calls it, and returns the column names with the exact name you want, and exclude the original stored procedure.
