### ISSUE TITLE
New Item menu doe not list the ReversePoco item

### ISSUE THREAD

**Issue by manu191357** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#655]
I installed the extension (VS 2019, latest version), followed the instructions given in your video, right-clicked on the project, selected new item ... but the ReversePoco item is not listed.
Please help.
Regards, Manu

**Comment by sjh37** [comment]
Hi,
In which case try an online search.

1. Right click on project, and select "Add -> new item"
2. Select online in the left hand side
3. Search for "reverse poco" in the top right search box.

![image](https://user-images.githubusercontent.com/4190514/105020712-92f68100-5a3f-11eb-8fbf-421077eecb70.png)

**Comment by manu191357** [comment]
Hello,
thank you for the help. Now I got it!
Regards, Manu

**Comment by manu191357** [comment]
Hello,
I tested the generator and it seems to fit my needs. Due to the limitations of the free version, I could not see whether idenity classes are also managed correctly. My database has all the standard identity tables (AspNetUser, AspNetUserRoles, ...); The AspNetUser table has a few additional custom fields, including a foreign key to another table.  I also have a lot of views in the database but only need a few ones to be mapped to the project.

Before buying a licence I have below questions:
1. Can the generator handle the described scenario
2. Is it possible to include only selected views?

Regards, Manu

**Comment by sjh37** [comment]
Yes and Yes.

**ASP.NET Identity**
It's best to exclude the ASP.NET Identity tables as those are already included in the ASP.NET DbContext. Microsoft recommend you only go via the ASP.NET commands to add/lookup/whatever users and not access its data directly via the database.
The `AspNetUser` table has additional custom fields, those will be provided for you by the user lookup using the ASP.NET commands.

**Filtering**
The core to this generator has always been about filtering. Often developers have to use a database with 1200+ tables and 500+ stored procedures. The generator can handle this no problem, however a large db context is really bad for performance. If your service only needs 10 tables and few views, then filter it to just those for your service. A small db context will be excellent in terms of performance.
Use the table filtering for `Views`.
Have a read of https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/wiki/Filtering

**Comment by manu191357** [comment]
Hello,
thank you again. Sounds good, I will buy a licence today.
Regards, Manu
