### ISSUE TITLE
If the .tt file has the same name as the context, the context is not generated

### ISSUE THREAD

**Issue by statler** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#660]
OK, so here is 2 hours of my life I want back.

If the .tt file has the same name as the context, despite the fact that they have different extensions, the process fails silently, and does not report an error. 

No error, couldn't even debug it. Just fails silently.

EDIT: This is actually annotated in the config file, but I feel this is not enough as there is a lot of comments in there, and in this case I had set up the tt file already, and afterwards renamed the file in the solution explorer, so did not even note the comment. Having not edited the config, this became difficult to track.

Correct behaviour should be to check if the names are the same, and throw an error.

**Comment by sjh37** [comment]
Sorry @statler 
I'll get that fixed.
Let me know your order number and I'll extend your license by 3 months as an apology.

**Comment by sjh37** [comment]
Was first reported in #23, and again in #334
Comment added to the code in https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/commit/3f263a25dfee2201cce65c2d1f21d97deb5410d2 to warn developers

**Comment by statler** [comment]
Fair enough. Have updated my reported bug to reflect.

Thanks

**Comment by statler** [comment]
In case you missed the edit:

This is actually annotated in the config file, but I feel this is not enough as there is a lot of comments in there, and in this case I had set up the tt file already, and afterwards renamed the file in the solution explorer, so did not even note the comment. Having not edited the config, this became difficult to track.

Correct behaviour should be to check if the names are the same, and throw an error.

**Comment by sjh37** [comment]
@statler This is now solved, and will be in the next release.
Sorry for any inconvenience it caused!

**Comment by sjh37** [comment]
This has now been released in v3.4.0
