### ISSUE TITLE
Multi-statement table-valued function

### ISSUE THREAD

**Issue by FotisSig** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#662]
Hello, I need help with multi-statement table-valued function. I have created a multi-statement table-valued function and this error appears:

**The type or namespace name 'GetTranslationsReturnModel' could not be found (are you missing a using directive or an assembly.**

My steps:

1) Add EntityFramework.CodeFirstStoreFunctions NuGet package version 1.2.0
2) Set FilterSettings.IncludeTableValuedFunctions  = true; 

This error appears with multi-statement table-valued function but with inline table functions works great.
I attached two screenshots. The first one is the multi-statement table-valued function with the error. The second one is a test table function which **works**.

Screenshot 1.
![image](https://user-images.githubusercontent.com/78492035/106769003-2f767100-6645-11eb-9fef-33de2b359b0c.png)

Screenshot 2.
![image](https://user-images.githubusercontent.com/78492035/106770695-e3c4c700-6646-11eb-9c6c-7863de443ff2.png)

I found this issue https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/issues/356 and I tried your code but it didnt work either.

_Poco generation version **v3.3.0**
    Settings.DatabaseType      = DatabaseType.SqlServer;
    Settings.TemplateType    = TemplateType.Ef6;
    Settings.GeneratorType   = GeneratorType.Ef6;_

**Comment by sjh37** [comment]
Not sure why SQL Server is not returning the model to the generator for the multi-statement version.

In the function `GetTranslations`, two things to try out:

1. Change the function to just perform a SELECT statement and nothing else.  Do not insert into @LanguageTable.

2. Another thing to try is to leave the function as it was, and after the `INSERT INTO @LanguageTable SELECT...` add a last select statement
    ```sql
    SELECT  Id, Title, Subtitle from @LanguageTable;
    ```

3. Also try changing it to a single select statement
   ```sql
   ALTER FUNCTION dbo.GetTranslations ( @lang NVARCHAR(100) )
   RETURNS TABLE AS
   RETURN
      SELECT g.Id, Title as 'Gender, gtr.Description as Subtitle
      FROM LK_Genders G
      ...
      ORDER BY g.Position;
   ```

**Comment by cubidobusinesssolutions** [comment]
For me, this problem was solved by downgrading localdb from SQL Server 2019 (installed manually) to SQL Server 2016 (installed with Visual Studio 2019).

**Comment by sjh37** [comment]
Thanks for the update
