### ISSUE TITLE
Only generates maximum 10 POCO classes.

### ISSUE THREAD

**Issue by Tanmay2711** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#664]
Hi Team,

I used net core 3 version, and it generates maximum 10 poco classes, I want to generate poco classes for all the tables but it generates for 10 tables that too with descending order of table names.

**Comment by aloene** [comment]
I have also just tried the product and I understand this is a licensing limitation. You need to buy it to get more than 10 tables/POCO.

**Comment by sjh37** [comment]
Hi. That is by design. You need a licence to derestrict it to unlimited tables.
If you have an educational or university email address you can have it for free.
For commercial use you will need a licence. Please buy a license from https://reversepoco.co.uk/.

**Comment by Tanmay2711** [comment]
Thank you @sjh37 and @aloene, I realize it later on.

**Comment by kaisoun** [comment]
Hi, the limit of 10 classes is for one project it is all what we can test?

**Comment by sjh37** [comment]
Hi @kaisoun, You can try this on as many projects and databases as you wish. Each reverse engineering will give you 10 tables/views and 10 stored procedures/functions. This is so you can check whether you like using the product and what it creates for you.
