### ISSUE TITLE
 [Question] Is this product capable of generating C# mapping code from EF6 EDMX ?

### ISSUE THREAD

**Issue by aloene** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#665]
Hi,

I have just tried the generator and I understand it can be used and customized to generate POCO/DbContext and **mapping** code from Database.
But can it generate the same code from existing EF6 **EDMX** (especially **mapping code**) ?
If not, is there any product someone is aware of that suits this need ?

Thank you.

**Comment by sjh37** [comment]
Hi. Yes, you can customise the generated code. The defaults are pretty good, but there are a lot of settings you can play with.
Throw edmx away, its truly horrible, and point the generator at your database. It will generate your code first database conext.

**Comment by sjh37** [comment]
If you need any other help,  just ask.

**Comment by aloene** [comment]
I precisely want to throw the giant EDMX away for this old big app but I do not want to loose all the custom (names) mappings in it (> 500 entities) when doing it so I am looking for a tool that could help me to translate this EDMX into mapping code before I can delete the EDMX file and begin to separate things.

**Comment by StevenBonePgh** [comment]
I doubt you are going to find anything like that. Best bet is to write a bit of code to parse the legacy EDMX XML and generate the necessary renames that can be pasted into the template. It would be a pain, but also a one-time thing. And something that I'm sure you could share back to the community.

For me, the absolute best thing about this generator is you can use the extended properties which will then add XML documentation to the POCOs. Oh yeah, and the Fake context generation, and so on. I'm on a way old version, at least until .NET 5+ migration starts in earnest.
