### ISSUE TITLE
Error with TPH, nugets out of date

### ISSUE THREAD

**Issue by weedkiller** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#666]
Hello, I was trying this with 

- [ ] Table per hierarchy - this still alludes me since I want a clear reflection of the inheritance startegy in the DB
- [ ] also server nugets are quite old and not updated

![image](https://user-images.githubusercontent.com/21086190/107125546-a6478000-6878-11eb-9db1-9ce210381cab.png)

**Comment by sjh37** [comment]
Table per hierarchy is not automatically reverse engineered for you. The generator reverse engineers on a type per table basis. TPH could be calculated by matching the same columns in the base table, but could also be problematic if this was incorrectly calculated. I.e. if the base had id, description. And another table had id, description, value. Is the second table inherited from the first or not. Impossible to know.

The generator should be nuget independent.  What problem with Nuget are you seeing?

**Comment by weedkiller** [comment]
Thanks appreciate it.

When I downloaded the project and tried to build, the targets are old and the dependency nugets are also old, not updated
