### ISSUE TITLE
Poblem using DatabaseType.PostgreSQL

### ISSUE THREAD

**Issue by powerqubit** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#669]
Selecting DatabaseType.PostgreSQL to reverse from, I get the following
// WARNING: Failed to load provider "Npgsql" - Unable to find the requested .Net Framework Data Provider.  It may not be installed.
// Allowed providers:
//    "System.Data.Odbc"
//    "System.Data.OleDb"
//    "System.Data.OracleClient"
//    "System.Data.SqlClient"
//    "System.Data.SqlServerCe.4.0"
//    "Microsoft.SqlServerCe.Client.4.0"

The package is installed and present in the project file:

PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="6.0.0-preview1"

The project is targeting net5.0 but other versions combination Yielded same results.

**Comment by sjh37** [comment]
Have a read of https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/wiki/PostgreSQL

**Comment by powerqubit** [comment]
Yes you were right. After installing the .msi it worked.
(anyone looking for the .msi installer check versions prior to v4.1.4 as top version assets only hold the sources) 
Thks!
