### ISSUE TITLE
Computed columns cannot be queried in ODATA when the setter is private if using a $select filter.

### ISSUE THREAD

**Issue by rsmaloney** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#67]
I set the private property generated for a computed column by using the InitializePartial() method for my entity but the odata $select filter choked on a exception because of this.  Because I want to use the $select filter instead of returning a full entity I had to make the property public.  

Is this a good reason to make computed columns have public setters or to at least have a config option for this?

**Comment by andygjp** [comment]
Hi @rsmaloney, I had a similar problem with RowVersion columns - the tool generates a byte array property with a private setter.

In my case I modified the `WritePocoColumn` lambda in the .tt file to this:

```
    Func<Column, string> WritePocoColumn = c =>
    {
        // Example of adding a [Required] data annotation attribute to all non-null fields
        //if (!c.IsNullable)
        //    return "[System.ComponentModel.DataAnnotations.Required] " + c.Entity;

        if (c.IsRowVersion)
        {
            var s = c.Entity.Replace("private", "");
            return s;
        }

        return c.Entity;
    };
```

My addition checks if the column `IsRowVersion` and removes the `private` keyword. Not very elegant, but it gets the job done.

You could do the same, but instead you check if the column `IsComputed`.

I'd call this a workaround, however, I too would like to make this configurable.

Cheers,
Andy

**Comment by sjh37** [comment]
I think its probably best to remove the private from the set altogether, and not bother with making it configurable.

**Comment by sjh37** [comment]
Actually, i am going to make it configurable

**Comment by sjh37** [comment]
It's now configurable.
This will be in the next release.

Thanks guys!

**Comment by ghost** [comment]
@sjh37 thanks.

**Comment by rsmaloney** [comment]
thanks
