### ISSUE TITLE
How to filter table in OnModelCreating ?

### ISSUE THREAD

**Issue by vahidjavadinasab** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#671]

**Comment by vahidjavadinasab** [comment]
Filter column in  IEntityTypeConfiguration?
 please help

**Comment by sjh37** [comment]
Take a look at filtering
https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/wiki/Filtering#table-filtering
If you need any more help, just let me know.
