### ISSUE TITLE
EFCore support for UseMappingTables missing

### ISSUE THREAD

**Issue by ms162223** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#672]
It appears support is missing for UseMappingTables  in EFCore.  I am looking for ManyToMany relationships to be created as a simple Collection property on the entity.  
**Scenario:**
Table "Persons" with a primary key of PersonID
Table "Roles" with a primary key of RoleID
Table "PersonRoles" as an ManyToMany XREF table that holds the relationship PersonID, RoleID 

In EF6 using UseMappingTables the above scenario resulted in a Person entity with a property called Roles that was a collection of Role entities.

In EFCore, no matter what you set "UseMappingTables" to, I get a Person entity with a property called PersonRoles that is of type ICollection<PersonRole>.  You get an entity called PersonRole that has a property called Role of type Role.

Is there another way that I should be doing this for EFCore or is this a bug / missing feature?

Details:
If I set the generator up with the following settings:
```c#
    Settings.TemplateType  = TemplateType.Ef6;
    Settings.GeneratorType = GeneratorType.Ef6;
    Settings.UseMappingTables  = true;
```
Then point it at a set of tables like this:
```sql
USE [ReversePOCOTesting]
GO
/****** Object:  Table [dbo].[PersonRoles]    Script Date: 3/14/2021 11:18:57 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PersonRoles](
	[PersonID] [int] NOT NULL,
	[RoleID] [int] NOT NULL,
 CONSTRAINT [PK_PersonRoles] PRIMARY KEY CLUSTERED 
(
	[PersonID] ASC,
	[RoleID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Persons]    Script Date: 3/14/2021 11:18:57 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Persons](
	[PersonID] [int] IDENTITY(1,1) NOT NULL,
	[NameFull] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Persons] PRIMARY KEY CLUSTERED 
(
	[PersonID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Roles]    Script Date: 3/14/2021 11:18:57 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Roles](
	[RoleID] [int] IDENTITY(1,1) NOT NULL,
	[Label] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Roles] PRIMARY KEY CLUSTERED 
(
	[RoleID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PersonRoles]  WITH CHECK ADD  CONSTRAINT [FK_PersonRoles_Persons] FOREIGN KEY([PersonID])
REFERENCES [dbo].[Persons] ([PersonID])
GO
ALTER TABLE [dbo].[PersonRoles] CHECK CONSTRAINT [FK_PersonRoles_Persons]
GO
ALTER TABLE [dbo].[PersonRoles]  WITH CHECK ADD  CONSTRAINT [FK_PersonRoles_Roles] FOREIGN KEY([RoleID])
REFERENCES [dbo].[Roles] ([RoleID])
GO
ALTER TABLE [dbo].[PersonRoles] CHECK CONSTRAINT [FK_PersonRoles_Roles]
GO

```

For EF6 I get a set of Entities that look like this:

```c#
    #region POCO classes

    // Persons
    public class Person
    {
        public int PersonId { get; set; } // PersonID (Primary key)
        public string NameFull { get; set; } // NameFull (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child Roles (Many-to-Many) mapped by table [PersonRoles]
        /// </summary>
        public virtual ICollection<Role> Roles { get; set; } // Many to many mapping

        public Person()
        {
            Roles = new List<Role>();
        }
    }

    // Roles
    public class Role
    {
        public int RoleId { get; set; } // RoleID (Primary key)
        public string Label { get; set; } // Label (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child People (Many-to-Many) mapped by table [PersonRoles]
        /// </summary>
        public virtual ICollection<Person> People { get; set; } // Many to many mapping

        public Role()
        {
            People = new List<Person>();
        }
    }

    #endregion

```

If I set the generator up with the following settings:
```c#
    Settings.TemplateType  = TemplateType.EfCore5;
    Settings.GeneratorType = GeneratorType.EfCore;
    Settings.UseMappingTables  = true;
OR
    Settings.UseMappingTables  = false;
```

I get classes that look like this, no matter what I set the UseMappingTables setting to:

```c#
    #region POCO classes

    // Persons
    public class Person
    {
        public int PersonId { get; set; } // PersonID (Primary key)
        public string NameFull { get; set; } // NameFull (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child PersonRoles where [PersonRoles].[PersonID] point to this entity (FK_PersonRoles_Persons)
        /// </summary>
        public virtual ICollection<PersonRole> PersonRoles { get; set; } // PersonRoles.FK_PersonRoles_Persons

        public Person()
        {
            PersonRoles = new List<PersonRole>();
        }
    }

    // PersonRoles
    public class PersonRole
    {
        public int PersonId { get; set; } // PersonID (Primary key)
        public int RoleId { get; set; } // RoleID (Primary key)

        // Foreign keys

        /// <summary>
        /// Parent Person pointed by [PersonRoles].([PersonId]) (FK_PersonRoles_Persons)
        /// </summary>
        public virtual Person Person { get; set; } // FK_PersonRoles_Persons

        /// <summary>
        /// Parent Role pointed by [PersonRoles].([RoleId]) (FK_PersonRoles_Roles)
        /// </summary>
        public virtual Role Role { get; set; } // FK_PersonRoles_Roles
    }

    // Roles
    public class Role
    {
        public int RoleId { get; set; } // RoleID (Primary key)
        public string Label { get; set; } // Label (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child PersonRoles where [PersonRoles].[RoleID] point to this entity (FK_PersonRoles_Roles)
        /// </summary>
        public virtual ICollection<PersonRole> PersonRoles { get; set; } // PersonRoles.FK_PersonRoles_Roles

        public Role()
        {
            PersonRoles = new List<PersonRole>();
        }
    }


    #endregion

```

**Comment by sjh37** [comment]
EF Core 2 & 3 has never supported many to many relationships, and Microsoft have stated they never will.

EF Core 5 has that support, but was strange initially and didn’t make any sense as you still had to declare the mapping table? Hence it was left it out. It looks like they have fixed this now.
So at the moment all version of EF Core don't make use of mapping tables in the generator, however I will now add this feature for EF Core 5.

**Comment by ms162223** [comment]
I am using EF5 so that is a ton of help, thank you!

**Comment by sjh37** [comment]
I've just checked, and yep they still need you to declare all 3 tables, left, right, and link. and join them up with the `UsingEntity` keyword. Seems crazy when you can simply declare all 3 tables and configure them all as a 1-to-many.

Here is an example:
```c#
builder.HasMany(t => t.Territories).WithMany(t => t.Employees).UsingEntity<EmployeeTerritories>(
    j => j
        .HasOne(m => m.EmployeeTerritories)
        .WithMany()
        .HasForeignKey(m => m.TerritoryID),
    j => j
        .HasOne(m => m.EmployeeTerritories)
        .WithMany()
        .HasForeignKey(m => m.EmployeeID),
    j =>
    {
        j.HasKey(t => new { t.EmployeeID, t.TerritoryID });
    });
```

I have raised an issue with the EF Core team here: https://github.com/dotnet/efcore/issues/24576

**Comment by ArminShoeibi** [comment]
You don't need to create a join table just for naming.

modelBuilder.Entity<YourEntity>()
    .HasMany(left => left.Entity)
    .WithMany(right => right.Entity)
    .UsingEntity(join => join.ToTable("TheDesiredName"));

**Comment by sjh37** [comment]
Thanks @ArminShoeibi Didn't know I could do that.

**Comment by xammob** [comment]
The ToTable with the table name didn't work for us. We're moving from EF6 and have a many-many table linking a role table and a user table. EF6 automatically created a RoleUsers table for us but put underscores in the fields (Role_Id and User_Id). It seems the default behaviour is to assume the fields don't have underscores in them. I managed to get it working using the following syntax


        modelBuilder.Entity<Role>()
                        .HasMany<User>(r => r.Users)
                        .WithMany(u => u.Roles)
                        .UsingEntity<Dictionary<string, object>>(
                            "RoleUsers",
                            j => j
                                .HasOne<User>()
                                .WithMany()
                                .HasForeignKey("User_Id"),

                            j => j
                                .HasOne<Role>()
                                .WithMany()
                                .HasForeignKey("Role_Id"));


this compares with the old EF6 syntax

      modelBuilder.Entity<Role>()
                        .HasMany<User>(r => r.Users)
                        .WithMany(u => u.Roles)
                        .Map(cs =>
                        {
                            cs.MapLeftKey("Role_Id");
                            cs.MapRightKey("User_Id");
                            cs.ToTable("RoleUsers");
                        });

Not entirely sure the new method is an improvement (unless I'm doing something wrong)

**Comment by ms162223** [comment]
I stumbled across this article which describes how it works in EF Core 5.  I hope this helps someone.
https://www.thereformedprogrammer.net/updating-many-to-many-relationships-in-ef-core-5-and-above/

**Comment by sjh37** [comment]
Could you please check the latest code works for you before I release it.
[EF.Reverse.POCO.v3.ttinclude](https://raw.githubusercontent.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/2eb7f2be32ac2df5cacbf6c6f7442cd5028f37e8/EntityFramework.Reverse.POCO.Generator/EF.Reverse.POCO.v3.ttinclude)

I've tested it against many databases and only found one issue, and that was with a mapping table that used a `SMALLINT` primary key type. The mapping table column types cannot be specified in the `.UsingEntity` and so it looks like it defaults to using an `INT` internally. If anyone has a problem, I can easily exclude tables from being a mapping table if the mapping types are not `INT`s. However mapping tables should be able to contain any data type.

**Comment by sjh37** [comment]
This has now been released in v3.4.0

**Comment by ms162223** [comment]
Hi Simon,
Sorry your emails got marked as spam and ended  up in my Junk mail.  I just found them.
I will test this out this week and let you know.  I am not sure I quite followed though.  Are you saying I should use tinyint or avoid using them?

Brandon Brown

**Comment by sjh37** [comment]
@ms162223 Just use it as-is. It should work out of the box.
