### ISSUE TITLE
Minor issue with namespaces when generating only Enums 

### ISSUE THREAD

**Issue by slee-accesso** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#678]
If you have ```Settings.IncludeCodeGeneratedAttribute    = true;``` and ```Settings.ElementsToGenerate = Elements.Enum;```
then the generator will not include the namespace necessary for annotations (System.CodeDom.Compiler).

The work-around for now is simply to set ```Settings.IncludeCodeGeneratedAttribute    = false;``` and things will work. But - this might be something you'd like to tweak? Or, perhaps I missed a setting somewhere else...

Thanks, Simon : )

**Comment by sjh37** [comment]
Thanks, I'll look into it.

**Comment by sjh37** [comment]
This has now been fixed and will be in the next release.
Thanks for spotting it.

**Comment by sjh37** [comment]
This has now been released in v3.4.0
