### ISSUE TITLE
Support for Synonyms

### ISSUE THREAD

**Issue by TimSirmovics** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#68]
Would it be possible to import Synonyms as if they were tables and views in the target database?

**Comment by sjh37** [comment]
I have added support for synonyms.
Pull the latest code, and see if this works for you.

**Comment by TimSirmovics** [comment]
Hi Simon,

Didn't work for me, I probably should have mentioned that these synonyms point to objects in another database (on the same server), not the database I am connecting to.

The problem is that sys.synonyms.base_object_name is a 3 part name pointing to the secondary database so OBJECT_ID(base_object_name) is returning the object id in the secondary database, causing the next join to sys.columns in the current database to fail.

I see also that base_object_name can take a 4 part name if the server is specified.

I guess a solution could be to pre-select all synonyms, parse the names and then generate seperate queries for each using the server and database name. Not sure if there is an easier way.

**Comment by sjh37** [comment]
Would you have time to look at the SQL? I really must crack on with company work right now.

**Comment by sjh37** [comment]
Ok, I'll add what I have for now, then take a look at a later time.

**Comment by TimSirmovics** [comment]
Hi Simon, sorry for the delay -I haven't actually used Git before so I spent some time this week playing around with it and have just started to look at implementing this. Hopefully I will be making my first pull request soon.

**Comment by sjh37** [comment]
Thanks Tim.

**Comment by sjh37** [comment]
@TimSirmovics This has now been completed by @EricSmall.
Pull the latest code and give it a go.

I will close this case and this enhancement will be in the next release.
