### ISSUE TITLE
Problems with "Setting.GenerateSeparateFiles"

### ISSUE THREAD

**Issue by abrahamm7** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#680]
Hi, i have a little problem with a setting in reverse poco generator ver 3.0.0.
After set the setting: **Setting.GenerateSeparateFiles = true** and build the project, I can't see the generated files on visual studio after build project.
![image](https://user-images.githubusercontent.com/40126895/115973652-b50f0c00-a524-11eb-975d-e04e2e1ddc57.png)
![image](https://user-images.githubusercontent.com/40126895/115974127-8b57e400-a528-11eb-923d-8d197a1f2ee8.png)
However at the project location i can see the files generated.
![image](https://user-images.githubusercontent.com/40126895/115973649-aaed0d80-a524-11eb-99c9-2e72296334b8.png)
But i can't use in another files in my project because, these files are not generated in my project solution.
![image](https://user-images.githubusercontent.com/40126895/115974097-606d9000-a528-11eb-9a5d-1985916c742c.png)

Section in my csproj to generate the .tt files 
![image](https://user-images.githubusercontent.com/40126895/115974178-f6091f80-a528-11eb-915a-80108f60a8d9.png)

How can i solve this?

**Comment by sjh37** [comment]
Files **should not** be generated during a build. They should only be generated when you save the `.TT` file.
Open each `.tt` file you have and press `ctrl-s` to save each one. That will make the generator run and create your files.

Once all the files are generated, then you can do a build.

On each `.tt` file properties (F4 to view them) they should be set to:
![image](https://user-images.githubusercontent.com/4190514/116206251-82d4f880-a736-11eb-90a1-904111ec6e3c.png)

**Comment by abrahamm7** [comment]
All right, thanks for the support Mr Simon.


Regards

Abraham Morillo
