### ISSUE TITLE
poco generator do not generate method for stored procedure in Academic  licence

### ISSUE THREAD

**Issue by abbas-asgharzadeh85** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#682]
hi a get academic licence and user Northwind database for my classroom learning.
when a user with this licence method for stored procedure not generate.
but if i use Trial licence   method for stored procedure generate.

**Comment by sjh37** [comment]
I have tested the academic license and it does generate stored procedures ok.
Have you placed the license file in your Documents folder?
`%userprofile%\documents\ReversePOCO.txt`

**Comment by abbas-asgharzadeh85** [comment]
yes i placed the license file in my Documents folder. (in this path : %userprofile%\documents\ReversePOCO.txt)
when o change license file  in this folder with trial license stored procedure generate.
i have 2 license 1 trial who generate procedure and 1 academic who do not generate stored procedure

**Comment by sjh37** [comment]
Replace your `EF.Reverse.POCO.v3.ttinclude` with this file below and see if it works ok for you.

https://raw.githubusercontent.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/6930d48d2955f8c0443211a2338a4ac82c290172/EntityFramework.Reverse.POCO.Generator/EF.Reverse.POCO.v3.ttinclude

**Comment by abbas-asgharzadeh85** [comment]
thanks a lot
it s work.

**Comment by sjh37** [comment]
I will make sure this fix gets released soon
