### ISSUE TITLE
Nullable int Property with Default Value of 0 

### ISSUE THREAD

**Issue by kcadduk** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#683]
A table with a nullable int column is generated with a nullable int property on the model but then has a 0 value assigned as its default value, where the value should be null (or just not assigned)?

EF Core 3.1 - SQL 2017 - .Net Framework 4.8

```sql
TABLE Journey (ID INT PRIMARY KEY IDENTITY(1,1), JourneyType_ID INT)
```

```csharp
public class Journey {
        public int ID { get; set; } // ID (Primary key)
        public int? JourneyType_ID { get; set; } = 0; // JourneyType_ID
}
```

It should not have the `= 0` after the JourneyType_ID property. As this is nullable

Any ideas why?

Thanks
Kevin

**Comment by sjh37** [comment]
Defaults are picked up from SQL Server. Can you check your SQL Server table to check if a default value has been assigned for that column.

Run the following to see if a default of (0) is present for that column. The following SQL will only show columns with defaults set.

```sql
SELECT  TABLE_SCHEMA AS SchemaName,
        TABLE_NAME AS TableName,
        COLUMN_NAME AS ColumnName,
        CAST(CASE WHEN IS_NULLABLE = 'YES' THEN 1 ELSE 0 END AS BIT) AS IsNullable,
        DATA_TYPE AS TypeName,
        ISNULL(CHARACTER_MAXIMUM_LENGTH, 0) AS MaxLength,
        CAST(ISNULL(NUMERIC_PRECISION, 0) AS INT) AS Precision,
        ISNULL(COLUMN_DEFAULT, '') AS [Default]
FROM    INFORMATION_SCHEMA.COLUMNS
WHERE   COLUMN_DEFAULT IS NOT NULL
ORDER BY TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME;
```

**Comment by kcadduk** [comment]
Sorry Simon, you're completely right. It has a default constraint. No idea how that slipped in.

Thanks for the fast reply.
