### ISSUE TITLE
Can we generate Check Constraints

### ISSUE THREAD

**Issue by kcadduk** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#684]
Suppose I have a check constraint 

```sql
ALTER TABLE dbo.Journey WITH CHECK
ADD CONSTRAINT CK_Journey_Times
CHECK ((
        DepartureTime <= ArrivalTime
        AND   TakeOffTime >= DepartureTime
        AND   LandingTime >= TakeOffTime
        AND   LandingTime <= ArrivalTime
      ));
GO
```

This isn't replicated to C# and then to a database generated from the Code First Migrations. Should it be?

Thanks
Kevin

**Comment by sjh37** [comment]
Hi Kevin,
Check constraints can be really quite complex, and some using SQL only syntax. Some are simple, as in your case above where it could be possible, others definitely not.
What makes it impossible to predict is if the user filters out a column in EF that is required as a check constraint, such as LandingTime. The developer may have another filtered (very small and fast) context which contains arrival information columns only, and does not want to query TakeOffTime columns for instance. Again, the check constraint is impossible to code as the column simply don't exist in EF.
Check constraints could call SQL Functions, or even check data exists in a table not even brought into the EF context. Even if the EF context had that extra table, the data may not have been queried for and not present in the EF cache. So by doing this I would double up on the db hits to gather up info to check the constraints would pass. To add this feature, I would also need an accurate SQL to C# parser. In the end, all that would be saved is a database round trip, and the possibility that it's not truly 100% accurate as what happens in the database. There may be plenty of edge cases.

The best I could hope for is a very simple check constraint check in EF as in your case above, and only if the Poco contained all of those columns. The DBA later on could introduce some more complex logic into the check constraint which the generator may decide is now too complex to convert, and drop it out, which you may of been relying on in your code previously. It's actually best all round to not do it, and for you to rely on the database constraints as the net to catch any errors.

Nice idea though, and one I've thought about before.

**Comment by kcadduk** [comment]
Thanks for the feedback Simon
