### ISSUE TITLE
Adding IsDirty to each class?

### ISSUE THREAD

**Issue by nielshenriksen** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#685]
If I want to add a boolean to each class that will be fired by OnPropertyChanged where is the best place to add it? Are there a method in the settings where it can be easy added?

**Comment by nick5454** [comment]
@nielshenriksen I would think you want that in a ViewModel, but you could have all the tables extend a base class to add to the definitions. 

You could also edit poco.mustache and add custom code there too, I think. 

I've only been using this 2 days, so ...

**Comment by sjh37** [comment]
This document may help [How-to-implement-OnPropertyChanged](https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/wiki/How-to-implement-OnPropertyChanged)

Edit `EF.Reverse.POCO.v3.ttinclude` and add code to 
```c#
// Writes any boilerplate stuff inside the POCO class body
public string WriteInsideClassBody()
{
    // Example:
    return "    public bool IsDirty;" + Environment.NewLine;

    // Do nothing by default
    // return string.Empty;
}
```

**Comment by sjh37** [comment]
Let me know if this does not solve your problem and I can re-open.

**Comment by nielshenriksen** [comment]
it was perfect :)
