### ISSUE TITLE
EF 6.4 and Reveser POCO 2.37.3

### ISSUE THREAD

**Issue by EricHurt** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#688]
Hi there, I have recently had to upgrade from EF 6.2 to 6.4 and now use .NET Standard 2.1. After saving my .tt file, the async methods are no longer generated. Is this expected and an upgrade to v3 is required, or should this currently be working?

**Comment by sjh37** [comment]
That is most probably a bug in in v2. 

Edit `EF.Reverse.POCO.Core.ttinclude` and replace the following function
```c#
public static Func<string,bool> IsSupportedFrameworkVersion = (string frameworkVersion) =>
{
    var nfi = CultureInfo.InvariantCulture.NumberFormat;
    var isSupported = float.Parse(frameworkVersion, nfi);
    return isSupported <= TargetFrameworkVersion;
};
```

with this
```c#
public static Func<string,bool> IsSupportedFrameworkVersion = (string frameworkVersion) =>
{
    return true;
};
```
