### ISSUE TITLE
ignoring base class columns

### ISSUE THREAD

**Issue by nick5454** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#698]
Lets say I have a BaseEntity that all tables extend with 2 columns "CreatedAt" and "UpdatedAt".

All tables in the database have these columns.

Is there a way to say only write column names which are not equal to Any column defined in my BaseEntity.cs class?

**Comment by sjh37** [comment]
Hi @nick5454 
Yes. Mark your column as hidden. In your `<database>.tt` scroll down to find
```cs
Settings.UpdateColumn = delegate(Column column, Table table, List<EnumDefinition> enumDefinitions)
{
    if(column.NameHumanCase.Equals("CreatedAt", StringComparison.InvariantCultureIgnoreCase) ||
       column.NameHumanCase.Equals("UpdatedAt", StringComparison.InvariantCultureIgnoreCase))
    {
        column.Hidden = true; // Hidden means the generator does not generate any code for this column at all.
    }
}
```

**Comment by sjh37** [comment]
Any problems, let me know
