### ISSUE TITLE
Excluding columns contain within BaseEntity

### ISSUE THREAD

**Issue by nick5454** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#699]
We have 2 columns in every table "CreatedAt" and "UpdatedAt". I put these in BaseEntity.cs.

I don't want to create a column if my BaseEntity.cs class already contains the column.

How could I exclude these columns in all tables if they are in BaseEntity?

**Comment by sjh37** [comment]
Duplicate of #698
