### ISSUE TITLE
Reverse engineered model does not specify precision and scale

### ISSUE THREAD

**Issue by statler** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#700]
Can you please advise how I can have my reverse poco'd model correctly nominate precision and scale so that database created from the model are correct? Currently any decimal is just decimal(18,0) when my database is decimal(14,6).

Is it related to https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/issues/411 - because the referenced ticket in efcore is resolved, and I can confirm these options are now available

Assuming I have just missed a config somewhere, if not can we get this sorted ASAP please? I note that it works for EF6.

**Comment by sjh37** [comment]
Thanks for the reminder @statler I'll get that added.

**Comment by statler** [comment]
Superb mate - thanks. Let me know when it is done as I can use it right about now :)

**Comment by sjh37** [comment]
Note to self: The generator currently specifies the precision and scale within the `HasColumnType` as:
```c#
builder.Property(x => x.Adecimal)
    .HasColumnName(@"adecimal")
    .HasColumnType("decimal(19,4)")
    .IsRequired(false);
```

**Comment by sjh37** [comment]
This will be in the next release. If you want the code now, grab the updated [EF.Reverse.POCO.v3.ttinclude](https://raw.githubusercontent.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/390d2ac72d1f7bdbafb5ad7cbe6852004810b7c7/EntityFramework.Reverse.POCO.Generator/EF.Reverse.POCO.v3.ttinclude)

**Comment by sjh37** [comment]
Released in v3.4.1

**Comment by statler** [comment]
I have updated to 3.4.1, and the ttinclude was not updated in an existing project. Is this the expected behaviour? Do I need to manually update existing templates when the app updates?

**Comment by sjh37** [comment]
Hi @statler
Installing the update of the generator into Visual Studio will not update your project. You would have to delete the ttinclude file, right-click and add the generator with a `delete.tt` file. I would take a quick compare of the `delete.tt` file and your .tt file to compare to see if anything is new is in there, then delete the `delete.tt` file, leaving the new .ttinclude file.
