### ISSUE TITLE
Support for graph tables

### ISSUE THREAD

**Issue by FaizulHussain** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#701]
Currently, graph tables (tables as nodes) generates columns with hashed random names

Anyways to rename/filter these out?

Thanks

**Comment by sjh37** [comment]
You can do both. Edit your `<database>.tt` settings file, within the `Settings.UpdateColumn = delegate...` callback (approx line 274):

To rename a column:
```c#
if (column.NameHumanCase.Equals("Abc123", StringComparison.InvariantCultureIgnoreCase))
    column.NameHumanCase = "NodeId";
```

To filter out a column, mark it as hidden:
```c#
if (column.NameHumanCase.Equals("SomeColumnYouDontWant", StringComparison.InvariantCultureIgnoreCase))
    column.Hidden = true; // Hidden means the generator does not generate any code for this column at all.
```

Any problems, just let me know.
