### ISSUE TITLE
Table & Schema Filters - Filter table based on schema too?

### ISSUE THREAD

**Issue by kcadduk** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#703]
Given the following tables with schemas

```
dbo.tAsset
dbo.sPart
dbo.tModel
camo.Reg
camo.Asset
```

I want to have a context that includes everything in the camo schema, and only tables that start with "t" in the dbo schema.

Can this be done with the RegexFilters?

**Comment by sjh37** [comment]
Hi @kaddyuk 

Great question! Add a regex schema filter to just include dbo and camo. If those are your only schema's then you don't need it.
```c#
FilterSettings.SchemaFilters.Add(new RegexIncludeFilter("dbo|camo"));
```

You have to also use the TableFilter for custom filtering. Enhance the one that is already provided in the `EF.Reverse.POCO.v3.ttinclude` file, or provide your own in a `filter.ttinclude` file and include that file in your `<database>.tt` after the inclusion of the `EF.Reverse.POCO.v3.ttinclude` file.

```c#
public class TableFilter : IFilterType<Table>
{
    // Filtering of tables using a function.
    // Return true to exclude the table, return false to include it.
    public bool IsExcluded(Table t)
    {
        if(t.Schema.DbName.Equals("dbo", StringComparison.InvariantCultureIgnoreCase) &&
           !t.DbName.ToLowerInvariant().StartsWith("t"))
            return true;

        return false;
    }
}

If you provide your own `filter.ttinclude` table filter file, add that to your table filters:
```c#
FilterSettings.TableFilters.Add(new NameOfYourCustomTableFilter());
```

Any problems, let me know.

**Comment by sjh37** [comment]
Also take a look at the [wiki](https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/wiki/Filtering#using-your-own-functions-to-filter)
