### ISSUE TITLE
Support for Visual Studio 2022

### ISSUE THREAD

**Issue by elistia** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#704]
Hi Simon,

How easy would it be for you to make the extension work with the new Visual Studio 2022 preview?

Is this just a case of adding this as a supported version, or does the change to 64bit make a difference?

Very happy to test anything if that would help at all.

Cheers.

**Comment by sjh37** [comment]
Hi @elistia yes, that's all that is required. I'll make the change. If you send me your email address I can email you the vsix installer.

**Comment by elistia** [comment]
Thanks @sjh37 - have emailed you.

**Comment by sjh37** [comment]
Released in v3.4.1
