### ISSUE TITLE
Models updated without prompt when focus is moved from tab - not just when saved

### ISSUE THREAD

**Issue by statler** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#707]
After the recent update, my templates now generate models automatically if I move focus to another page - regardless of whether I save.

Previously my templates did not update unless I saved the template, and I think I was even prompted (but not sure).

Is this a change in RevPOCO, Visual Studio or some settings weirdness?

**Comment by sjh37** [comment]
Visual studio has always run the template for me whenever I navigate away from an unsaved `.tt` file. I find it annoying it does that and would love to know the VS setting to turn that off.

https://stackoverflow.com/questions/4034886/how-to-stop-t4-from-executing-every-time-i-switch-to-another-tab

**Comment by sjh37** [comment]
I'll close this issue as its something I am unable to fix/resolve.
