### ISSUE TITLE
Custom POCO property type

### ISSUE THREAD

**Issue by FaizulHussain** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#717]
Hi,

Is there a way to change the property type? I need to change the primitive type to custom strongly typed identifier for some of the classes

Thanks

**Comment by sjh37** [comment]
Hi Faizul,

Take a look inside `EF.Reverse.POCO.v3.ttinclude` and search for `public class SqlServerToCSharp`
That class is responsible for mapping sql server properties to C#

Any problems just add a note below.
