### ISSUE TITLE
Unable to Generate Stored procedure objects

### ISSUE THREAD

**Issue by sdoma** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#72]
Hi,
I am trying to generate Stored procedure objects using EF-Reverse-POCO-Code-First-Generator V2.19.3.0. I have not change any configuration by default setting for store procedure is  includestoredprocedures = true unable to see the store procedure objects.I really appreciate if you could help me on this.
Thanks,
Sri

**Comment by sjh37** [comment]
Set the connection string name in the database.tt file, press save.
That should reverse engineer everything for you.
btw there is a newer version out now :-)

**Comment by sdoma** [comment]
Thanks Simon. Connection string already mentioned and get generate tables and view objects not store procedure.
Thanks,
Sri

**Comment by sjh37** [comment]
So it reverse engineers the context, poco's, and mapping, just not stored procedures?
Might be a SQL Permission if that's the case. Might not be of course?

**Comment by sjh37** [comment]
What are these set to?

``` c#
StoredProcedureFilterExclude = null;
StoredProcedureFilterInclude = null;
```

**Comment by sdoma** [comment]
set to null only. I have not changed. Just i written stored procedure pass id as a parameter and it returns result set.I am trying to to generate resultset object using database.tt file.

**Comment by sjh37** [comment]
Try running the SQL by hand using SSMS to see if that returns back any data. This should reveal if there is any security getting in the way.
SQL is inside `EF.Reverse.POCO.Core.ttinclude`
Find `StoredProcedureSQL = @"`
and copy the select and paste it into SSMS and run it, see what you get back.

**Comment by sdoma** [comment]
I ran  in SSMS it returns results. I found in the EF.Reverse.POCO.Core.ttinclude below details. Which does not contain my storeprocedure details.
   private const string StoredProcedureSQL = @"
SELECT  R.SPECIFIC_SCHEMA,
        R.SPECIFIC_NAME,
        R.ROUTINE_TYPE,
        P.ORDINAL_POSITION,
        P.PARAMETER_MODE,
        P.PARAMETER_NAME,
        P.DATA_TYPE,
        ISNULL(P.CHARACTER_MAXIMUM_LENGTH, 0) AS CHARACTER_MAXIMUM_LENGTH,
        ISNULL(P.NUMERIC_PRECISION, 0) AS NUMERIC_PRECISION,
        ISNULL(P.NUMERIC_SCALE, 0) AS NUMERIC_SCALE,
        ISNULL(P.DATETIME_PRECISION, 0) AS DATETIME_PRECISION,
        P.USER_DEFINED_TYPE_SCHEMA + '.' + P.USER_DEFINED_TYPE_NAME AS USER_DEFINED_TYPE
FROM    INFORMATION_SCHEMA.ROUTINES R
        LEFT OUTER JOIN INFORMATION_SCHEMA.PARAMETERS P
            ON P.SPECIFIC_SCHEMA = R.SPECIFIC_SCHEMA
               AND P.SPECIFIC_NAME = R.SPECIFIC_NAME
WHERE   R.ROUTINE_TYPE = 'PROCEDURE'
        AND (
             P.IS_RESULT = 'NO'
             OR P.IS_RESULT IS NULL
            )
        AND R.SPECIFIC_SCHEMA + R.SPECIFIC_NAME IN (
            SELECT  SCHEMA_NAME(sp.schema_id) + sp.name
            FROM    sys.all_objects AS sp
                    LEFT OUTER JOIN sys.all_sql_modules AS sm
                        ON sm.object_id = sp.object_id
            WHERE   sp.type = 'P'
                    AND (CAST(CASE WHEN sp.is_ms_shipped = 1 THEN 1
                                   WHEN (
                                         SELECT major_id
                                         FROM   sys.extended_properties
                                         WHERE  major_id = sp.object_id
                                                AND minor_id = 0
                                                AND class = 1
                                                AND name = N'microsoft_database_tools_support'
                                        ) IS NOT NULL THEN 1
                                   ELSE 0
                              END AS BIT) = 0))

UNION ALL
SELECT  R.SPECIFIC_SCHEMA,
        R.SPECIFIC_NAME,
        R.ROUTINE_TYPE,
        P.ORDINAL_POSITION,
        P.PARAMETER_MODE,
        P.PARAMETER_NAME,
        P.DATA_TYPE,
        ISNULL(P.CHARACTER_MAXIMUM_LENGTH, 0) AS CHARACTER_MAXIMUM_LENGTH,
        ISNULL(P.NUMERIC_PRECISION, 0) AS NUMERIC_PRECISION,
        ISNULL(P.NUMERIC_SCALE, 0) AS NUMERIC_SCALE,
        ISNULL(P.DATETIME_PRECISION, 0) AS DATETIME_PRECISION,
        P.USER_DEFINED_TYPE_SCHEMA + '.' + P.USER_DEFINED_TYPE_NAME AS USER_DEFINED_TYPE
FROM    INFORMATION_SCHEMA.ROUTINES R
        LEFT OUTER JOIN INFORMATION_SCHEMA.PARAMETERS P
            ON P.SPECIFIC_SCHEMA = R.SPECIFIC_SCHEMA
               AND P.SPECIFIC_NAME = R.SPECIFIC_NAME
WHERE   R.ROUTINE_TYPE = 'FUNCTION'
        AND R.DATA_TYPE = 'TABLE'
ORDER BY R.SPECIFIC_SCHEMA,
        R.SPECIFIC_NAME,
        P.ORDINAL_POSITION";

**Comment by sjh37** [comment]
It returned results, which means that you have access, and that you have stored procedures. All good.
I find it odd that it is not adding in any stored procedures.

Try creating a little console application, add entityframework, add a connection string to your database, add ef reverse poco generator (the latest version), and set the app.config connection string name in the database.tt and see if it creates the stored procedures.

**Comment by sjh37** [comment]
if that fails, fire up join.me and I'll watch what you are doing and help.

**Comment by ErikEJ** [comment]
Does your sproc have if statements?

**Comment by sdoma** [comment]
No. Simple select \* from emp where id=@id like

**Comment by sdoma** [comment]
Hi Simon, I did that exercise it did not work . I want show that code. Can you please let me know how to connect through  join.me.

**Comment by sjh37** [comment]
https://www.join.me/
Then give me the code.

**Comment by sjh37** [comment]
I'm stopping work now. this will have to wait until tomorrow. 10 am GMT at the earliest.

**Comment by sdoma** [comment]
Can not install this plugin due to our  internal security reasons.

**Comment by sjh37** [comment]
Watch the course at https://app.pluralsight.com/library/courses/code-first-entity-framework-legacy-databases
This will help you

**Comment by sdoma** [comment]
I already i went through couple of times . You talk about renaming stored procedure and mapping business objects in customizing the generation code module.

Thanks,

**Comment by sjh37** [comment]
It could be down to the connection string details not having enough sql permission security access.
There is nothing more I can do sorry. The generator generates stored procedures ok for everyone else.

**Comment by daydrivencode** [comment]
// Main settings ***************************************************************************
...
IncludeStoredProcedures = true;  //Must be true to have stored procedures

**Comment by farukhsharipov** [comment]
Had similar problem, issue. Was my mistake i have VS 15 and VS 17 side by side and I had Reverse POCO installed for VS 15 but not for VS 17, and I was trying to regenerate using VS 17. SP's will show up under MyDbContext. 

Hope this helps someone.
