### ISSUE TITLE
Default values for column mapped to enum failed

### ISSUE THREAD

**Issue by DDtMM** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#78]
If a column has a default value and is mapped to an enum type via EnumsDefinitions, then the generated context will fail because where the default value is set with error _CS0226 - Cannot implicitly convert type 'type1' to 'type2'. An explicit conversion exists (are you missing a cast?)_.

In line 960 in _EF.Reverse.POCO.ttinclude_ needs to cast `col.Default`  to the enum type if the column is mapped to an enum, or `col.Default` must be the appropriate enum value.

Example to recreate the error:
**context.tt**

```
EnumsDefinitions.Add(new EnumDefinition { Schema = "dbo", Table = "MyTable", Column = "MyColumn", EnumType = "MyColumnEnum"});
```

**MyTable constructor from context.cs**

```
public MyTable()
{
    MyColumn = 1; /* ERROR CS0226! */
}
```

**MyTable constructor from context.cs should be:**

```
public MyTable()
{
    MyColumn = (MyColumnEnum)1; 
    /* or MyColumn = MyColumnEnum.One */
}
```

**Comment by sjh37** [comment]
Would you be able to create a pull request to fix the problem?

**Comment by sjh37** [comment]
Fixed. This will be in the next release.
