### ISSUE TITLE
Is it possible to remove comments at the top of file??

### ISSUE THREAD

**Issue by airomero** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#79]
At the top of each generated POCO appears this comment;

// auto-generated
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
# pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

Is there any config for not generating this comments? 

Thanks

**Comment by sjh37** [comment]
No toggle, but if you remove them from the top of EF.Reverse.POCO.ttinclude, they will be removed from your generated code.
