### ISSUE TITLE
Stored procedure with multiple optional result sets returns incorrect entities

### ISSUE THREAD

**Issue by kesh00** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#81]
Stored procedures can return result sets in any order or combination, and does not need to return all possible result sets for each call. Unfortunately, the code generated relies on all result sets being returned and all being returned in the same order.

```
procResultData.ResultSet1 = objectContext.Translate<ProcReturnModel.ResultSetModel1>(reader).ToList();
reader.NextResult();

procResultData.ResultSet2 = objectContext.Translate<ProcReturnModel.ResultSetModel2>(reader).ToList();
reader.NextResult();

procResultData.ResultSet3 = objectContext.Translate<ProcReturnModel.ResultSetModel3>(reader).ToList();
reader.NextResult();

procResultData.ResultSet4 = objectContext.Translate<ProcReturnModel.ResultSetModel4>(reader).ToList();
reader.NextResult();
```

For example, in the above generated code, if ResultSet3 is not returned by the stored procedure on a particular call, the data from ResultSet4 will be the "NextResult." The code will attempt to translate the result set to ProcReturnModel.ResultSetModel3 instead of ProcReturnModel.ResultSetModel4, even though the models may be completely different.

**Comment by ErikEJ** [comment]
What are you proposing?

**Comment by sjh37** [comment]
I have test this, and it is working fine.
I created a stored procedure to return 3 result sets.
- First set returns 1 row
- Second, returns nothing
- Third returns 3 rows

![2016-08-05_10-51-01](https://cloud.githubusercontent.com/assets/4190514/17433100/9f8fa282-5afa-11e6-8b12-1f4fd8d78878.png)

**Comment by kesh00** [comment]
The bug doesn't occur when the stored procedure returns an _empty_ result set, but when it doesn't return the result set at all.

For example, the stored procedure:

```
CREATE PROCEDURE [dbo].[Procedure]
    @param1 bit
AS
    SELECT '1' as FieldA;
    IF @param1 = 1
        SELECT 2 as FieldB;
    SELECT 3.1 as FieldC;
RETURN 0
```

Using the above stored procedure, the following code will reproduce the bug:

```
    class Program {
        static void Main(string[] args) {

            using (IMyDbContext context = new MyDbContext()) {
                Console.WriteLine("Procedure(true)");
                Console.WriteLine("\tShould be (String) 1, (Int32) 2, (Double) 3.1.");
                var result = context.Procedure(true);
                PrintResult(result);

                Console.WriteLine();
                Console.WriteLine("Procedure(false)");
                Console.WriteLine("\tShould be (String) 1, (Double) 3.1.");
                result = context.Procedure(false);
                PrintResult(result);
            }

            Console.ReadLine();
        }

        private static void PrintResult(ProcedureReturnModel result) {
            object[] items = {
                result.ResultSet1.FirstOrDefault()?.FieldA,
                result.ResultSet2.FirstOrDefault()?.FieldB,
                result.ResultSet3.FirstOrDefault()?.FieldC
            };
            string text = string.Join(", ", items.Where(i => i != null).Select(i => $"({i.GetType().Name}) {i}"));
            Console.WriteLine("\tActual values are " + text  + ".");
        }
    }
```

The console prints:

> Procedure(true)
>         Should be (String) 1, (Int32) 2, (Double) 3.1.
>         Actual values are (String) 1, (Int32) 2, (Decimal) 3.1.
> 
> Procedure(false)
>         Should be (String) 1, (Double) 3.1.
>         Actual values are (String) 1.

**Comment by sjh37** [comment]
Thanks for the example.
However, I am not sure how to fix it. Conditionals returning different result sets are always going to be problematic.
I feel the right answer is to modify the stored procedure to always return the 3 result sets if they are different, If the results sets are the same, then you can optionally return a result set or not.

What are your thoughts?

**Comment by sjh37** [comment]
I am afraid there is now way I can fix this from the generators point of view.
