### ISSUE TITLE
Add RemoveRange() in FakeDbSet class.

### ISSUE THREAD

**Issue by rajjan** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#86]
Please add RemoveRange method in generated FakeDbSet.cs file. 
 It is now throwing below exception:
System.NotImplementedException: The member 'RemoveRange' has not been implemented on type 'FakeDbSet`1' which inherits from 'DbSet`1'. Test doubles for 'DbSet`1' must provide implementations of methods and properties that are used.

I can submit a pull request if you need help.

**Comment by sjh37** [comment]
Thanks. This will be in the next release.
