### ISSUE TITLE
Duplicate ForeignKeys in multiple schemas

### ISSUE THREAD

**Issue by Harish3485** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#88]
Thank You for the answers.

I have one more case of duplicate foreign keys as below:

ALTER TABLE [OCR].[Request]  WITH CHECK ADD  CONSTRAINT [FK_RequestStatus_Request] FOREIGN KEY([RequestStatusID])
REFERENCES [OCR].[RequestStatus]([RequestStatusID])
GO

ALTER TABLE [Paradatec].[RequestStatus]  WITH CHECK ADD  CONSTRAINT [FK_RequestStatus_Request] FOREIGN KEY([RequestID])
REFERENCES [Paradatec].[Request]([RequestID])
GO

FK_RequestStatus_Request is the duplicate foreignkey name.

so when the poco map class is generated I see two mapping as below.  
.HasForeignKey(c => new { c.RequestStatusID, c.RequestID })

It iss also considering the second foreign keys column of different table i.e c.RequestID
Its not fixed with .Distinct() as previous cases had same column name. 

Can you please help me in this regard.

Thank You
Harish

**Comment by sjh37** [comment]
Fixed, and will be in next release (later today)
