### ISSUE TITLE
Disable generated table objects

### ISSUE THREAD

**Issue by MartinBodocky** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#89]
I know this is not an issue by default by in my project I want to expose just views and stored procedures to DbContext but not tables. 

Is there a way to achieve it?

Thank you

**Comment by sjh37** [comment]
In your `<database>.tt` settings file

``` c#
TableFilter = (Table t) =>
{
    return t.IsView;
};
```

**Comment by MartinBodocky** [comment]
After more deliberated search I found the way by using TableFilter!

TableFilter = (Table t) =>
    {
        return t.IsView;
    };
