### ISSUE TITLE
Add your preferred dev environment for editing .tt files to readme

### ISSUE THREAD

**Issue by blyry** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#9]
The fact that .tt still isn't first class in VS is mind boggling, and you seem to have more experience than others in editing templates -- how do you manage that much code spread across .tt files?

**Comment by sjh37** [comment]
I use the Resharper plugin called ForTea. Totally excellent. Colour syntax highlighting and intellisense. It's just as if I'm editing a C# file.
