### ISSUE TITLE
GenerateSeparateFiles=true silently overrides "custom" partial classes

### ISSUE THREAD

**Issue by ghost** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#90]
Hi,

As watched in your [pluralsight tutorial](https://app.pluralsight.com/player?course=code-first-entity-framework-legacy-databases&author=simon-hughes&name=code-first-entity-framework-legacy-databases-m2&clip=9&mode=live) I tested the "Generate Separate Files". In the previous steps custom partial classes NorthwindDbContext.cs and FakeNorthwindDbContext.cs were added from my side to proceed with the tutorial.

After setting GenerateSeparateFiles to **true**, my custom classes were silently overridden from your generator (see attached Screenshot of my solution structure):

![generateseparatefiles](https://cloud.githubusercontent.com/assets/6480047/17646983/2b699d5e-61df-11e6-8b34-f4150495eb58.png)

After investigation I made an VCS undo to that step and decided to name all my custom partial classes like NorthwindDbContext**-Partial**.cs and FakeNorthwindDbContext**-Partial**.cs. But of course not the C# classnames!

Is there a better approach or can you take care of that while code generation?

thanks,
Eric

**Comment by sjh37** [comment]
Hi Eric,
You have to be careful with partials as there's nothing worse than losing some work. Although, the second time round, the code tends to be better :-)
The way I do it is to either name the filename differently, as you have done, or have my hand-crafted partial classes in a different folder. I tend to use a sub-folder named 'partial'.

**Comment by ghost** [comment]
Hi Simon,
Thanks for your reply. I will apply your suggested way with a own "Partials" subfolder:)
