### ISSUE TITLE
NVarChar(max) parameter in stored procedure does not generate Size = -1 

### ISSUE THREAD

**Issue by fmorriso** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#92]
_\* Documenting Issue Previously Reported on Visual Studio Gallery Web Site that has a fix available *_

When a stored procedure is processed that contains a parameter declaration of nvarchar(max), the generated C# code does not include any Size = value, so when I run a test program that tries to use that parameter, it gets an error saying that Size is set to zero.

How can I code my .TT file to generate Size = -1 as part of such parameters, as seen in the following (manually altered to make it work) example:

var myOutputParam = new System.Data.SqlClient.SqlParameter
{
    ParameterName = "@myOutputParam",
    SqlDbType = System.Data.SqlDbType.NVarChar,
    Direction = System.Data.ParameterDirection.Output,
    Size = -1 // manually added to avoid run-time error
};

**Comment by sjh37** [comment]
This has been fixed and will be in the next release.
See changeset https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/commit/3bb6c9fdb438df5b0e8702c73bbf67511068fdb7
