### ISSUE TITLE
For SQL varchar(MAX) / nvarchar(MAX) is generated wrong type in POCO.cs file

### ISSUE THREAD

**Issue by TadeuszSobol** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#93]
If in DB is varchar(MAX)/nvarchar(Max) then is generated  “... .HasColumnType("**varchar**");”  but it should be  “... .HasColumnType("**varchar(MAX)**");” .
Simply, in the consequence of it, for “... .HasColumnType("varchar");” ,  EF migration creates in database varchar(8000)/nvarchar(8000) – where is required varchar(MAX)/nvarchar(MAX).

**Comment by sjh37** [comment]
Many thanks!
This is now fixed and will be in the next release.
