### ISSUE TITLE
Generated code does not compile when using Fakes and custom Interface names

### ISSUE THREAD

**Issue by jaxidian** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#96]
Repro steps:
1) Get stuff working with all defaults (i.e. add connection string)
2) DbContextName = "MyBaseDbContext";
3) DbContextInterfaceName = "IMyDbContext"; //Defaults to "I" + DbContextName
4) AddUnitTestingDbContext = true;
Generate

Notice that the generated Fake class fails to honor the custom interface name but instead tries to use IMyBaseDbContext. Simple defect in EF.Reverse.POCO.ttinclude.

**Comment by sjh37** [comment]
pull request accepted.
