### ISSUE TITLE
Namespace for SqlGeography is generated incorrectly in Stored Procedure return model

### ISSUE THREAD

**Issue by kenlefeb** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#98]
I have a stored procedure that returns a DbGeography value. The table entity is correctly generated with the System.Data.Entity.Spatial namespace, but the return model for my stored procedure is generating System.DbGeography? (nullable).

**Comment by L1tR05** [comment]
This is related to issue #132

**Comment by sjh37** [comment]
This might be also related to #213 which is also fixed, but still pending release.

**Comment by mdentremont** [comment]
I can confirm that the issue is still present on the latest build - which includes #132 and #213

**Comment by mdentremont** [comment]
NVM - I think we're OK on this front, I was running into a different issue

**Comment by sjh37** [comment]
This will be in the next release.
